### ISSUE TITLE
Session restore does not work when SumatraPDF is terminated by system shutdown

### ISSUE THREAD

**Issue by kasati** [sumatrapdfreader/sumatrapdf#1000]
Hi there, 

been using SumatraPDF for quite a while under Win7. Love it, it's sleek. Thanks guys! There's just one issue that keeps bugging me: I work with a great deal of PDF files at the same time and have them open in tabs. When I close SumatraPDF and open it again, restoring the session works just fine, and reliably so. However, when I shut down my PC and SumatraPDF is told to shut down by Windows, it seemingly doesnt save the session. At least I get this "Often used documents" tab when I start it up again. All those papers I was about to cite are simply gone, sucks.
Would appreciate a fix!
Thanks!
Version: 3.1.2

**Comment by SumatraPeter** [comment]
Sumatra saves session data only when it is properly closed (see this [related forum thread](https://forum.sumatrapdfreader.org/t/windows-update-reboots/29)). If it's forcibly terminated for any reason (say you leave it running and initiate a shutdown or power's lost and the system reboots) then you end up losing your session data. Why don't you simply close Sumatra before powering down, or hibernate instead of shutting down?

**Comment by benryanau** [comment]
I too have run into this.. system issues don't always give you the option.

**Comment by yshklarov** [comment]
This is a frustrating issue for me, too. It's not always possible to close Sumatra by hand because occasionally Sumatra crashes!

**Comment by GitHubRulesOK** [comment]
@kasati @benryanau @yshklarov 
I have suggested a **2step fix** to the code is all that's needed however as I'm not a programmer I cant prove it is enough, so have built this cmd file as proof of concept, would any (all ?) of you see if it works for you

copy and paste the following 4 lines (beware the first one is about twice as long as the others)
using notepad into a file called something like SumatraWithBackup.CMD

```
IF exist "%~dp0SumatraPDF-settings.REC" IF NOT exist "%~dp0SumatraPDF-settings.txt"  COPY "%~dp0SumatraPDF-settings.REC" "%~dp0SumatraPDF-settings.txt"
call "%~dp0SumatraPDF.exe" -appdata "%~dp0" 
find /i /c "# Settings after this line" "%~dp0SumatraPDF-settings.txt" 
if %errorlevel%==0 COPY "%~dp0SumatraPDF-settings.txt" "%~dp0SumatraPDF-settings.REC"

```
Now place the file in the SumatraPDF folder and run it rather than SumatraPDF.exe (you may need to change your current shortcuts etc

**Comment by kjk** [comment]
This should be fixed with https://github.com/sumatrapdfreader/sumatrapdf/commit/351f73d1e2b8269b3a6262987e72c3ea21727fd0
