### ISSUE TITLE
Having Sumatra installed supposedly causes Windows 10 1803 Settings app to crash

### ISSUE THREAD

**Issue by imchau** [sumatrapdfreader/sumatrapdf#1019]
Multiple reports here that uninstalling it fixes the issue:
https://www.reddit.com/r/Windows10/comments/8j4xyu/for_those_whose_set_defaults_by_app_in_settings/

I only want to inform the developers about this peculiar issue and am not implying that it's SumatraPDF's fault.

**Comment by SumatraPeter** [comment]
Apparently people who don't use Sumatra are experiencing the crashes as well, so I'm guessing MS broke something and hopefully will fix it on a forthcoming Patch Tuesday.

**Comment by asc7uni** [comment]
@GitHubRulesOK registry hot-fix didn't work for me. 
I checked that values are actually set in registry. But Settings app still crashes. 
So I completely removed them and Settings started to work. 

Almost certainly it is not Sumatra fail to crush something in "always-in-beta" Win10 but I think some kind of workaround could be implemented to Sumatra installer.

Bug was known to MS from 2018-04 and there is no guarantee it will be fixed soon.

**Comment by GitHubRulesOK** [comment]
@asc7uni 
Currently running Windows version: Windows 10 pro x64 1803 (17134.137)
Currently logged in as Standard User have not tried (as elevated yet)

Installed a fresh download of 3.12 (requires admin password to install) with options to include pdf preview and set as default handler, have not changed registry and settings crash does NOT happen
Windows ignores SumatraPDFs request to be default .pdf handler and keeps resetting .pdf handler to Edge. Manually select a pdf and told windows that SumatraPDf is to be default handler, preview is working and .pdf icon finally changes from white with blue to yellow with black **all good so far and no need for the hack** as default apps can be seen even if SumatraPDF is not listed under "set default by app"

so now its a mystery again , the installer did NOT cause a problem
is it user rights, is it latest win 10 version ?

going to test out 
1) after a reboot to standard user and
 2) test an elevated account

**Comment by GitHubRulesOK** [comment]
Confirmed on several installations of updated windows this issue seems to have gone, I thus recommend you let windows update to latest 2018-06 and uninstall / reinstall SumatraPDF if necessary (remember to use OPTIONS during install to select pdf previewer) UNFORTUNATLY windows will still insist the only way nanny allows you to open a pdf is with Edge. so you will need to use the settings>apps dialogs to tell it otherwise see https://forum.sumatrapdfreader.org/t/register-sumatra-in-windows-10/1277

![untitled](https://user-images.githubusercontent.com/12754913/42377469-54a6491c-811b-11e8-90f0-7f754542d20d.png)

@kjk for the moment this seems to suggest this has been a temporary (3 months ?) issue in windows 10 that is now fixed, and has been an issue with several apps thus I would classify as NOT a SumatraPDF issue (close ?)

**Comment by asc7uni** [comment]
@GitHubRulesOK As it turned out my Windows was not updated to latest version. Today I updated it to 17134.137 and reinstalled Sumatra. 
Good news is Settings don't crash any more for me.
Bad news is there is no Sumatra in lit of default applications but you already mentioned it. 
So I have to manually register Sumatra as .pdf viewer (and .cbr, etc.). Now it works fine.

**Comment by GitHubRulesOK** [comment]
@asc7uni 
Thanks for the feedback, confirming my observation

Others
please note IF you still have this issue, you will first need to confirm if KB4284848 was installed without failure

**Comment by GitHubRulesOK** [comment]
@kjk no sugestions over the past year that this is still an issue, I suggest it was a temporary problem with some older Win 10 builds, thus should no longer be a current issue.
