### ISSUE TITLE
Feed in the settings file as a command line argument

### ISSUE THREAD

**Issue by nimafazeli** [sumatrapdfreader/sumatrapdf#1027]
This way we could use different settings using a shortcut files or using a build system from the preferred text editor depending on the situation.

For example I compile from latex using a build system in my editor. However at nights I use a dark theme on my editor and switching between the screens with different luminosity is literally painful to my eyes. I wish I could just run something like `SumatraPDF.exe --settings="nightmode.txt"` to get my customized dark mode settings or `SumatraPDF.exe --settings="presentation.json` for my customized presentation mode.

**Comment by GitHubRulesOK** [comment]
there are several issues with what you propose since over time the settings file has been extended to include file history etc.
there were a few old cli settings that may help (see documentation on -bg-color and -set-color-range

however I guess your best bet is to use windows built-in command editor ( edlin) or a more modern script processor to find and replace those lines of the settings.txt file to your preference or run two copies ( installed and portable ?) without a common history

**Comment by GitHubRulesOK** [comment]
As a result of other forum comments this issue re: selecting a user preferred SumatraPDFsettings.txt file
was addressed per https://github.com/sumatrapdfreader/sumatrapdf/issues/69
For a recent description of how this may be used see https://forum.sumatrapdfreader.org/t/sessions-in-sumatra/1272/2
@kjk @nimafazeli I think this can be closed as achievable with current -appdata behaviour

**Comment by kjk** [comment]
Closing as per suggestion.
