### ISSUE TITLE
Commandline Printing of A2 A1 A0

### ISSUE THREAD

**Issue by boulec** [sumatrapdfreader/sumatrapdf#1045]
I’m trying to print larger format CAD drawings, like A2 A1 A0, scale 1:1 on our rolplotter. No matter what I try, I only get a part of the document (cropt to A4) printed.
Diving into the “print.cpp” source code, I only find references to A4 and A3 ISO formats.

So for the moment the bigger formats are not supported for commandline printing.

Can this be fixed?

Thanks

**Comment by GitHubRulesOK** [comment]
@boulec 
If you look at the recent code change you can see page options have been extended to A6 & A2

If you can get someone to compile the latest source code it should be easy for them to add A1 & A0
in the FOUR locations in a commit along the lines of  https://github.com/sumatrapdfreader/sumatrapdf/commit/e559279ac37f80583f0cfb2c1277ac74ceac1e40
Note the values need to be
    if (limitValue(sizeP.dx, 33.11, 33.13) == sizeP.dx && limitValue(sizeP.dy, 47.16, 47.18) == sizeP.dy) 
       return Paper_A0; 
    if (limitValue(sizeP.dx, 23.38, 23.40) == sizeP.dx && limitValue(sizeP.dy, 33.11, 33.13) == sizeP.dy) 
         return Paper_A1; 


@kjk any chance these could be added to close this issue ?

**Comment by kjk** [comment]
I don't know which windows definition from https://docs.microsoft.com/en-us/windows/desktop/api/wingdi/ns-wingdi-_devicemodea correspond to A1 and A0. There is `DMPAPER_A2` but no `DMPAPER_A1` and DMPAPER_A0`.

**Comment by GitHubRulesOK** [comment]
Ok I see the problem, (its a bit more than using given driver sheet names ? how does bin= work ?)

Whats the significance of Paper_Other in the src/SumatraProperties.h  list ?

Very large and very small format printers would need  to go beyond the fixed range by using a "custom" stored value (candidate for SumatraPDF-settings.txt?) and presumably use say 2 variable *.#mm values
e.g. for AO  CustomPrint=1189.0,841.0

then feed that to 

DUMMYUNIONNAME.DUMMYSTRUCTNAME.dmPaperLength
For printer devices only, overrides the length of the paper specified by the dmPaperSize member, either for custom paper sizes or for devices such as dot-matrix printers that can print on a page of arbitrary length. These values, along with all other values in this structure that specify a physical length, are in tenths of a millimeter. 

DUMMYUNIONNAME.DUMMYSTRUCTNAME.dmPaperWidth
For printer devices only, overrides the width of the paper specified by the dmPaperSize member.

**Comment by GitHubRulesOK** [comment]
@kjk 
It would appear A1 and A0 are/were "hidden" by
#define DMPAPER_RESERVED_48 48 /* RESERVED--DO NOT USE */ 
#define DMPAPER_RESERVED_49 49 /* RESERVED--DO NOT USE */

may be worth testing using print to windows pdf printer to check output size

if (limitValue(sizeP.dx, 33.11, 33.13) == sizeP.dx && limitValue(sizeP.dy, 46.81, 46.83) == sizeP.dy)
return Paper_RESERVED_49;
if (limitValue(sizeP.dx, 23.38, 23.40) == sizeP.dx && limitValue(sizeP.dy, 33.11, 33.13) == sizeP.dy)
return Paper_RESERVED_48;

**Comment by kjk** [comment]
My preferred way of solving such problems is: investigate what other apps do. I assume that Adobe Reader, FoxIt etc. support such functionality in some way. 

If they don't that suggests it has not been asked by many people.

If they do, Sumatra should just copy their cmd-line ux.

**Comment by GitHubRulesOK** [comment]
CAD format printer drivers have always caused issues (I should ~~know~~ remember having demo/installed/supported/used hundreds but due to the number of problems cant count all the ways I have tested) many times the old solution was to simply send via DOS a Form Feed just to poke the buffer

Bing result = 4,070,000 "Acrobat print A1 problem"
Most users want print to PDF or "Acme" plotter

Acrobat generally hid A1 and A0 sizes but PRO/CAD had very good Large Format support  and generally used a custom PostScript Plot driver
e.g support advice was along the lines of
In the paper size drop-down, select "Postscript Custom Page Size" and enter your sheet dimensions. Hit OK on all the prompts to back out to the AutoCAD Plot dialog box and save the settings as Adobe PDF.pc3 and use this to plot. 

Ayumini which is where I found "reserved values" had very good licensed CAD pdf driver, scriptable in CAD file viewers such as (Nowadays) Oracle AutoVue

Daily I still use AutoCAD or Bentley drivers again using specialist files for settings for PDF output

Many apps usually use Redmon and GS as a back-end converter to Large Format PDF, Similar to Adobe Distiller, where the page size is usually held in a config file

but that's not what's needed for this alchemists stone of turning all outputs to Golden sizes on any plotter / physical / virtual printer

I think the best answer is to add "USER" (/CUSTOM) size as it will then depend on USER HAVING a good / suitable print driver

Foxit tends to depend on default printer tray / page size and uses /t similar to Acrobat
/t <filename> <printername> <drivername> <portname>
note no page size (however respects a pre-set large format printer default)

**Comment by boulec** [comment]
I need this functionality for commandline printing.
At the commandline, I always need to specify the printername. 

As a suggestion, maybe it's a good idea to retrieve the papersizes known by the specified printer. This can be done using [DeviceCapabilities](https://docs.microsoft.com/en-us/windows/desktop/api/wingdi/nf-wingdi-devicecapabilitiesa)...

Then one can iterate through the papersizes, to find the best match (if any) to the documentsize.

I've found some code:

```
    char printerDevice[ 256 ] = "", printerDriver[ 256 ] = "", printerPort[ 256 ] = "";
    THandle printerDeviceModeHandle = 0;
    Printer( )->GetPrinter( printerDevice, printerDriver, printerPort, printerDeviceModeHandle );
    if( printerDeviceModeHandle != 0 )
    {
        DEVMODE *printerDeviceMode = ( DEVMODE * ) GlobalLock( ( void * ) printerDeviceModeHandle );
        if( printerDeviceMode != NULL )
        {     
            bool minSizeFound = false;
            WORD minWidthDifferenceSize = 0;
            try
            {
                DWORD resultPaperSize = 0, resultPapers = 0;
                resultPaperSize = DeviceCapabilities( PrinterComboBox->Text.c_str( ), printerPort, DC_PAPERSIZE, NULL, NULL );
                resultPapers = DeviceCapabilities( PrinterComboBox->Text.c_str( ), printerPort, DC_PAPERS, NULL, NULL );
                if( resultPaperSize > 0 && resultPaperSize == resultPapers )
                {
                    int bufferSize = resultPaperSize * sizeof( POINT );
                    BYTE *buffer = new BYTE[ bufferSize ];
                    resultPaperSize = DeviceCapabilities( PrinterComboBox->Text.c_str( ), printerPort, DC_PAPERSIZE, buffer, NULL );
                    WORD papers[ 9999 ];
                    resultPapers = DeviceCapabilities( PrinterComboBox->Text.c_str( ), printerPort, DC_PAPERS, ( char * ) &papers, NULL );
                    if( resultPaperSize > 0 && resultPaperSize == resultPapers )
                    {
                        double minWidthDifference = 999999;
                     for( DWORD i = 0; i < resultPaperSize; i++ )
                        {
                            POINT p;
                            Move( buffer + i * sizeof( POINT ), ( void * ) &p, sizeof( POINT ) );
                            double paperSizeWidth = p.x / 254.0508001016 * PixelsPerInch - printerOffsetX;
                            double paperSizeHeight = p.y / 254.0508001016 * PixelsPerInch - printerOffsetY;

                            double widthDifference = paperSizeWidth - bitmap->Width;
                            if( widthDifference < 0 )
                                widthDifference *= -1;
                            if( widthDifference < minWidthDifference && paperSizeHeight > bitmap->Width * 0.9 )
                            {
                                minSizeFound = true;
                                minWidthDifferenceSize = papers[ i ];
                                minWidthDifference = widthDifference;
                            }
                        }
                    }
                    delete [ ] buffer;
                }
            } catch( ... ) { }
  if( minSizeFound )
            {
                printerDeviceMode->dmFields = DM_PAPERSIZE;
                printerDeviceMode->dmPaperSize = minWidthDifferenceSize;
            }
            GlobalUnlock( ( void * ) printerDeviceModeHandle );
            Printer( )->PrinterIndex = Printer( )->PrinterIndex;
        }
    }
```

source [https://www.experts-exchange.com/questions/22478486/Set-Printer-Page-Size-API.html](https://www.experts-exchange.com/questions/22478486/Set-Printer-Page-Size-API.html)

Thanks a lot.

**Comment by GitHubRulesOK** [comment]
@boulec 

@kjk may correct me were I'm wrong but as I understand it
That is roughly the method SumatraPDF uses
The issue here is that A1 and A0 are not officially recognised paper sizes per that documentation, see my comment's re paper sizes _RESERVED_49 & 48
So paper sizes would need to be extended by any driver offered "custom" size (not many drivers have or expose that)
or 
ALL various page sizes / bins exposed by the bidirectional driver be offered to the user (thus likely a lot of work would be needed on creating and testing a custom dialog box to please all of the users all of the time!)

**Comment by GitHubRulesOK** [comment]
Closing as this was addressed nov 2020 in https://github.com/sumatrapdfreader/sumatrapdf/commit/b4db2f104f4c6790b87da03cfc7ac803e41f137d by new definitions for paper= and paperkind=
