### ISSUE TITLE
Make Ctrl-Page-Up/Ctrl-Page-Down go to previous/next tab as in many browsers

### ISSUE THREAD

**Issue by nneil** [sumatrapdfreader/sumatrapdf#1049]
My hands have learnt this combination and become confused in Sumatra.

**Comment by GitHubRulesOK** [comment]
@nneil 
Traditionally Ctrl + Page Up (BrowsePrev) and Ctrl + Page Down (BrowseNext) were used within documents for find next / find previous for which SumatraPDF uses other key combinations.

Microsoft sometimes **but not always** used the CTRL Page combo for jumping between tabs e.g. in Excel so that's probably why its used now by many modern tabbed browsers.

SumatraPDF uses the CTRL Tab and CTRL shift Tab duo to navigate Tabs
whilst it **possibly** could follow the browser convention it does already have a valid combination and others have requested totally different combinations, you cant please all of …..

If its really essential to your current personal sanity you could remap using AutoHotKey see the comments and solution in https://forum.sumatrapdfreader.org/t/custom-keyboard-commands-for-switching-tabs/459/6
so for your own usage
 you need to load the following into AutoHotKey

#IfWinActive ahk_class SUMATRA_PDF_FRAME
{
^PgUp::^+tab
^PgDn::^tab
`::^w
}

If you save the above 6 lines using notepad and save the file to autohotkeyU32.ahk alongside AutoHotkeyU32.exe it will run if you follow the **fast track instructions  here** and download AutoHotkeyU32

Background Basics first **just read parts 1a 1b 1c** of https://autohotkey.com/docs/Tutorial.htm#s11
HOWEVER for portability instead of install I usually download https://autohotkey.com/download/ahk.zip
and use "extract here" to get the files into their own folder whilst experimenting, if you use the installer and have problems go to FAQ for install https://autohotkey.com/docs/FAQ.htm#install

It realy helps to read some of the fundamentals in this page https://lexikos.github.io/v2/docs/Program.htm

**However the bottom line** is that if you have a copy of  Autohotkey???.exe renamed to whatever.exe and a script file as above called whatever.ahk then running the exe will automatically run the companion script

**Comment by AndrejIT** [comment]
In my IDE and in browser i have tens of tabs, so i have "Ctrl+Tab cycles through tabs in recently used order" option on, and i am extremely used to it.
I personally don't work with pdf that much, but you can keep in mind, that some people may really make use of "recently used order" option.

**Comment by baldandbrave** [comment]
@kjk Is this keyboard shortcut in the development plan? Really getting used to it.
I would like to contribute but I didn't find the code assigning the shortcut. I can make PR if you could point me the code location.

**Comment by GitHubRulesOK** [comment]
The shortcut key press for selecting and cycling tabs is documented in several manual pages
such as https://www.sumatrapdfreader.org/docs/Keyboard-shortcuts.html so they need to be honoured
Tabs
    Ctrl + Tab - go to next tab
    Ctrl + Shift + Tab - go to previous tab
    Alt + 1 - go to tab 1. Use 2, 3 etc. up to 8 to go to n-th tab
    Alt + 9 - go to last tab

Ctrl Page up and down are already allocated to Page Up Down actions (i.e. next and previous pages)
thus they would need to be repurposed from Adobe Acrobat natural **page** at a time behaviour or next image in a single page image viewer e.g. IrfanView to the less natural behaviour for viewers (although it may be natural for browsers to go to next tabbed **page**)

If you think changing historic use would be acceptable to the majority of users (that expect behaviour identical to Adobe Reader) you could look at swaping the tab behaviours over to page behaviours, but I think that is redefining it the wrong way round and would be adding to confusion.

**Comment by baldandbrave** [comment]
@GitHubRulesOK 
Thanks for your explanation and your dedicated contribution for this great tool!
It does makes sense to adapt to key bindings in Acrobat considering Sumatra is a doc viewer and doesn't work like web browsers.
I think we might as well look for a workaround with some process-wise key/gesture binder (or just get used to `Ctrl+Tab`)

**Comment by nneil** [comment]
I don’t think it makes sense to use the historical (old fashioned) Acrobat keystrokes. Most people use their web browser far more than they do a PDF reader. Even reading PDFs within the browser. In this case it’s natural to follow the control page up, control page down key convention.

**Comment by SumatraPeter** [comment]
> In this case it’s natural to follow the control page up, control page down key convention.

Ctrl+Tab and Shift+Ctrl+Tab have worked in every tabbed browser I recall using, so I'd argue they constitute convention as much, if not more, than Ctrl+PgUp/PgDn.

**Comment by nneil** [comment]
But Ctrl-shift-tab is three keys, which should be reserved for unusual actions. With control page up and page down you can keep your finger on the control key and step back and forwards easily. It’s a much better pair of shortcut keys.

**Comment by GitHubRulesOK** [comment]
@nneil 
For each user it will differ (and other keyboards are available) on my keyboard ctrl shift and tabs are together and usable by one my free left hand, whereas for my page up /down I need to let go of the mouse, then span my right hand fully to reach the page down key (top right of the numeric pad) for me that's slower and more painful

**Comment by SumatraPeter** [comment]
Your usage pattern matches mine exactly @GitHubRulesOK, and of course we have years of muscle memory associated with these common actions.

For the record I'm not at all opposed to kjk adding Ctrl+PgUp/PgDn as an _addition_ to Ctrl+Tab/Shift+Ctrl+Tab if he so wishes, but doing so in lieu of the latter would make the app unusable for me.

**Comment by GitHubRulesOK** [comment]
@kjk 
with custom shortcuts this issue should now be addressed ?
