### ISSUE TITLE
missing content, diff with the version online. ≤ this symbol.

### ISSUE THREAD

**Issue by jasonbu** [sumatrapdfreader/sumatrapdf#1050]
when download and read by the newest version.
found on
https://developer.apple.com/accessories/Accessory-Design-Guidelines.pdf
and page 61 
the symbol ≤  is missing
![default](https://user-images.githubusercontent.com/6532028/43460817-577f24ea-9504-11e8-9772-f4a7a3fd866a.png)
and online version
![default](https://user-images.githubusercontent.com/6532028/43460833-6472f186-9504-11e8-806e-90651fdde451.png)

**Comment by SumatraPeter** [comment]
try the latest [pre-release version](https://www.sumatrapdfreader.org/prerelease.html).

**Comment by SumatraPeter** [comment]
> Peter I tried several versions of SumatraPDF and found the problem consistent on Windows 10

I didn't advise the use of the latest pre-release version without testing it myself first. Seems to work fine here:

![image](https://user-images.githubusercontent.com/15380332/43544948-1dd8c086-95f2-11e8-9a99-d13f44e8f33f.png)

This is on a Win10 system I just finished installing (the latest 17134.191 cumulative update was in the process of getting installed when I took this screenshot). I don't know what font if any is getting substituted for "Myriad", but whatever it is clearly the MuPDF version used by 3.2.10766 is able to do what the one used by 3.1.2 can't.

**Comment by GitHubRulesOK** [comment]
Thank Peter
I did try a portable 32 bit 10766 on newer Win 10 Pro x 64 any of that could be having an affect
![image](https://user-images.githubusercontent.com/12754913/43550524-c028fbd8-95db-11e8-8c83-59895e9878d0.png)

Also I note from your about box your system font is different (italic) and your / mine locale may also be relevant

@jasonbu I know its a lot, but can you please  confirm bitness of your system / OS version and was SumatraPDF "installed" and with which version / bitness

**Comment by jasonbu** [comment]
@GitHubRulesOK I tried pre-release version, and the release version on the official website. the issue is still there.
My computer is working with Win10 x64 1803 10.0.17134
something diff maybe my main language is chinese. maybe take effect on the encoding and font.

**Comment by GitHubRulesOK** [comment]
@kjk 
I have tried several external means to change SumatraPDF behaviour in windows 10
I have NOT checked if it is a problem in Windows 8.x
The bottom line is that MuPDF works as expected but SumatraPDF does not
so we come back to, Is there a difference caused by UTF / Unicode handling on international versions ?

**Comment by GitHubRulesOK** [comment]
@kjk this issue seems to have resolved itself !
![image](https://user-images.githubusercontent.com/12754913/71736145-3c280480-2e48-11ea-90a8-e749ef3045d6.png)

I cannot find an old copy of the file above, the current linked version is from november 2019
Thus either it was a file with bad selection of font(s) and has been replaced to conform to the PDF principle of showing what author intended. (now on page 113)
Or windows updates have provided valid font alternatives.
Unless someone has an old copy for re-testing I suggest since the linked sample is NOT an issue in 3.1.2 or current build this thread can now be closed ?

**Comment by SumatraPeter** [comment]
>  Or windows updates have provided valid font alternatives.

That would be my guess too.
