### ISSUE TITLE
titlebar hard to grab when many tabs open

### ISSUE THREAD

**Issue by e4711s** [sumatrapdfreader/sumatrapdf#1053]
In tab mode the tabs reach into the titlebar, leaving only a couple of free pixels above the tabs to grab the window.

**Comment by GitHubRulesOK** [comment]
That is unusual 
you possibly know thay you can from the pull down menu use Window > Move then any arrow key will allow you to move the window.
As to cause, it may be related to screen dpi can you confirm resolution of screen AND what percent your working to, usually found by right click on desktop then select display settings ?

**Comment by SumatraPeter** [comment]
> That is unusual

@GitHubRulesOK: Here's the 'grabbable' area of Sumatra's titlebar, which admittedly is a bit narrow:

![image](https://user-images.githubusercontent.com/15380332/43733928-d4d992ee-99d3-11e8-997f-35adef46a414.png)

Perhaps the tabs could be redesigned to take up the _entire_ height of the titlebar as in the case of Firefox, but leave clear gaps on both sides to aid in grabbing and moving the window with a mouse.

![image](https://user-images.githubusercontent.com/15380332/43734051-2a3f9ea4-99d4-11e8-9bfa-13f0d7998c58.png)

Note a clever aspect of Firefox's design, in that the empty area to the left of the tabs disappears when the window is maximized (the first tab starts right at the top left of the window in that case).

Various tab-related improvements have been on my wish list ever since Sumatra started supporting tabs (see [here](http://forums.fofou.org/sumatrapdf/topic?id=3184717) and linked GitHub issues), but unfortunately there's no-one around to implement any of them. 😞

**Comment by GitHubRulesOK** [comment]
Peter whilst I agree there are many requests/improvements needed for tabs
I see the area above yours is about 14 pixels rather than the "couple" (two?) as mentioned by @e4711s hence the `That is unusual` 
I have on occasion mis-grabbed a tag and moved it rather than the whole window but I put that down to my haste or bad eye co-ordination.
Personally I think the current tabs look ok when maximised and (apart from color/logo) not that different to your Firefox example (which seems to have a space top left)  and I would rather find the tribar options button in the traditional top left menu position well away from close / resize etc at top right see my screen
![untitled1](https://user-images.githubusercontent.com/12754913/43741592-6f18ee10-99be-11e8-8e63-b3790d75c826.png)
It is difficult to meet everyone's preference for layout since the ribbon brigade want more and more buttons and the tabs brigade want to tear them away  etc I just don't know how many ways the original concept could be changed as it started out to provide a fast reading area to the max (same as MuPDF) but with more access to the basic underlying functions.

**Comment by SumatraPeter** [comment]
> rather than the "couple" (two?) as mentioned by @e4711s

I took the word "couple" to generally imply a small number and not literally to be read as "two". Even if it is 14px (I didn't count), I do find it to be rather narrow to be able to grab hold of quickly/easily. Let's also not forget that when the cursor gets too close to the top edge it changes into "resize window mode" and no longer simply grabs the titlebar as intended.

> Personally I think the current tabs look ok when maximised and (apart from color/logo) not that different to your Firefox example (which seems to have a space top left)

Yes, my FF screenshot displays the blank grabbable area at the top left since clearly the window is not maximized.

My suggestion would be three-fold. As you've pointed out in your Sumatra screenshot, the grabbable area to the right between the last tab and the minimize button is variable in width. So first of all I'd make it fixed-width like FF does, to provide a consistent area to be targeted with the mouse for grabbing.

Second, since introducing another grabbable area to the top left of the non-maximized window (like FF does) would interfere with the hamburger menu, I'd see if the square menu button itself can also be used to drag if the mouse is left-clicked and held on it. I'm pretty sure that can be managed. So left-click it once and the menu would open as usual, but left-click and drag and the menu would close and window would get dragged.

Finally, since these changes will effectively replicate FF's two grabbable areas on both sides of the tabs, when the window is non-maximized I'd make Sumatra's tabs full height to cover the titlebar, again just like FF (since that narrow horizontal strip on top is a poor target anyway and would no longer be required).

Anyway, all these are ideas that will most likely remain just that, because as Krzysztof has previously pointed out Sumatra is in an inactive state development-wise right now, and even otherwise the responsibility of all the piled up bug fixes, feature requests, engine/library updates etc. is clearly way too much for one person with a day job to handle.

**Comment by SumatraPeter** [comment]
Forum issue with more details about the bug that causes the tabs to even orverlay the min/max/close buttons sometimes: https://forum.sumatrapdfreader.org/t/feature-request-drag-space-next-to-the-minimize-maximize-title-bar-buttons/1911/3

**Comment by kjk** [comment]
Thanks to @amurzeau we now have app icon in the top left that can be used to move the window
