### ISSUE TITLE
Sumatra Portable as Windows Preview Handler

### ISSUE THREAD

**Issue by geoorgge** [sumatrapdfreader/sumatrapdf#1065]
Installation Version:
When installing, click "Options" and select "Let Windows show previews of PDF documents", details in this thread
[https://github.com/sumatrapdfreader/sumatrapdf/issues/457](url)

![image](https://user-images.githubusercontent.com/42699020/44620195-559e6100-a890-11e8-8052-07d5a406255b.png)

Portable Version
I cannot find this feature in the portable version. Is it possible to register the portable version as Windows previewer?

**Comment by GitHubRulesOK** [comment]
It is always possible BUT you need to use a context loader/unloader e.g. yap or portableapps since you want an installed feature to be only there for portable use, the whole point of a preview handler is it is by nature "registered" to be available to explorers all the time. take a look at the way the above portableizers work-around this issue

@kjk I suggest this can be closed as SumatraPDF is working as expected

**Comment by SumatraPeter** [comment]
What @GitHubRulesOK said. There's a reason why PdfPreview.dll isn't included with the portable version. If it was and you registered it as a preview handler in Windows, then the app would obviously no longer be in portable mode since you would be unable to simply move the app (and DLL) elsewhere without breaking functionality.

If you want you can install a standalone PDF preview handler (such as [this one](http://www.windows10pdf.com/pdfpreviewer.html) - not tested by me) on your systems where you want to use the portable version of Sumatra. That way you'll have the PDF preview functionality irrespective of where Sumatra portable is located and even when it is deleted from the system.

**Comment by kjk** [comment]
The purpose of portable version is to minimize permanent modifications to the OS so this is not compatible with that goal.
