### ISSUE TITLE
Default Layout Won't Change

### ISSUE THREAD

**Issue by pheonix727** [sumatrapdfreader/sumatrapdf#1067]
i'm trying to change the default layout from automatic to single page or facing in an ebook (epub), it won't change
sumatra 3.1.1
########################
before this problem happened : 
i used advanced option made this change :  EbookUI > UseFixedPageUI = True
before i did this everything was fine and the page layout was changing normally in the ebookUI
###########
i changed UseFixedPageUI back to false and now the ebook page layout is stuck to whatever FixedPageUI layout is set to be
###########
currently if i want to change the Ebook layout i have to make UseFixedPageUI = true then change the layout then revert back to UseFixedPageUI = false
###########
it is like the ebook page layout was linked to the FixedPageUI layout and it doesn't want to unlink when i set the UseFixedPageUI to false
############
removing the remember these settings for each document seems to solve the problem
############
still i have to close and reopen sumatra for the new layout to load

**Comment by GitHubRulesOK** [comment]
@pheonix727 
Whilst Settings > Advanced options is dynamic, some settings take effect straight away, some settings require all documents to be closed and some require the program to be closed before opening another file.
When you change any setting it is important to use notepads File > Save or [Ctrl]+[S] to make it "stick" equally if you then change it back it will need another "save". 
To be safe close notepad first then the SumatraPDF session so it may change other values on closing. HOWEVER a later "save" of SumatraPDF-settings.txt will overwrite to the current ones in notepad, which may or may not be what you want.

Settings such as true or false must be lower case and have a space after the  = sign like this = true
if you change UseFixedPageUI = false (and "save" ) then if the file is open in SumatraPDF you need to press [R] to reload the file. IF you did it right you can use this to switch between the two UIs without closing the .epub

As you point out the behaviour on closing and reopening may differ this is due to other settings such as
RememberOpenedFiles = true
RememberStatePerDocument = true
and UseDefaultState = true
HOWEVER the UI should ONLY change via  UseFixedPageUI = false (or true)

So open SumatraPDF and use Settings > Advanced Options... check UseFixedPageUI is not = false change it to EXACTLY
UseFixedPageUI = false
then in Notepad  SAVE the file if Notepad throws a save or error message let us know.
Reopening SumatraPDF or an .epub should now work, if not you may have more than one settings file or it may be opening as read only.

**Comment by GitHubRulesOK** [comment]
Closing as a single historic case, that has not been reported or noted in more recent releases, which now include additional methods to change UI.
