### ISSUE TITLE
【BUG？】bookmarks are messed up 

### ISSUE THREAD

**Issue by 775405984** [sumatrapdfreader/sumatrapdf#1075]
I downloaded a pdf format book online. And I added bookmarks to make it easier to find chapters.

But Sumatra PDF couldn’t jump to the right page when I click the bookmarks I made. It always jumps to the page after the right one.

I use Foxit PDF Editor, at first I thought it was its fault. But after I edit the PDF file in Acrobat, the same mistake occurs. But, the PDF file was fine in Foxit PDF Editor, Foxit PDF Viewer, Acrobat Editor, Acrobat Viewer.

So, I was wondering if something is wrong with Sumatra PDF. But I have a much larger file with lots of bookmarks and Sumatra PDF had zero problem navigating chapters.

Anyways, thank you all for listen to my gibberish and if you could help me solve this I’ll be very grateful.

Here is the PDF file. https://drive.google.com/open?id=1Tok2qJ0VN7_2MaSuB7ptRR_IRbPPobpf

**Comment by GitHubRulesOK** [comment]
@kjk above sample not accessible to me however the description seems familiar that bookmarks (sometimes from a latex source or command driven insertion) are built at the bottom of page, rather than top, SumatraPDF may in such boundary cases show the page AT the bookmark i.e. "the next page" do we have any such samples to check?

**Comment by kjk** [comment]
Can't make progress without a test file
