### ISSUE TITLE
Can I include the SumatraPDF-settings text file into the code to compile?

### ISSUE THREAD

**Issue by LimYH** [sumatrapdfreader/sumatrapdf#1093]
Hi,

I would like to include the settings into the exe so that other people will not be able to change the settings.

May I know how can it be done?

Thank you.

**Comment by GitHubRulesOK** [comment]
That is neither practical nor sensible. SumatraPDF is intentionally open for users to change by nature, and you could fall foul of licensing intent @kjk can correct me if I'm wrong. Some applications have tried storing settings internally before and usually give up, since if settings such as the current file etc. are to be modified the file changes like a virus would alter it and triggers many anti-virus. However SumatraPDF does allow for "kiosk mode" usage and has a system to "lock down" features with an additional file, see https://www.sumatrapdfreader.org/docs/Configure-Sumatra-for-restricted-use.html

**Comment by GitHubRulesOK** [comment]
@kjk 
This behaviour defeats license intents and is usually desired by cloned versions of SumatraPDF to circumvent user control I suggest since it would be both impractical and undesirable it be classed as WONT-fix

**Comment by kjk** [comment]
You could do it if you change the code but I have no plan to add such feature.
