### ISSUE TITLE
when printing, the PDF page should be centered on the printer's page

### ISSUE THREAD

**Issue by skoehler** [sumatrapdfreader/sumatrapdf#11]
The other day, I was trying to print a PDF (A4 document) on a printer (also A4). The PDF contained a scanned document (so each PDF page consisted of one big image). I wanted to print the document without any scaling. That was easy to configure in Sumatra.

However, the upper left corner of the PDF page (which contained some black marks, artifacts from scanning) was always positioned at the upper left corner of the rectangle that you obtain after substracting the printer margins from the page size. As a result, the contents of the PDF were moved a little bit to the right and to the bottom when printing. Also, at the right and the bottom side of the page, things were clipped (due to the printer margins) that would not have been clipped if the upper left corner of the PDF page would have been printing to the upper left corner of the physical paper.

Anyhow, Adobe Reader, by default, centeres anything on the page while printing. When printing at 100% (no scaling), the PDF contents would be clipped a little bit on the left, top, right, and bottom, but otherwise the result would be an exact copy of the PDF. I had to use Adobe Reader instead of Sumatra.

Please add a switch (or make it the default) to center all printed contents horizontally and vertically on the page - unless the user selects to scale the PDF contents to fit inside the printer margins, in which case Sumatra should probably center the content within the rectangle obtained by substracting the printer margins.

**Comment by kjk** [comment]
Needed more information.

**Comment by ousia** [comment]
@zeniko, having the option to enable centering is essential when selecting _Use original page sizes_.

Imagine printing an A5 document in a A5 paper (or printing an envelope). Many printers require those paper sheets to be placed in the manual paper tray. And those paper trays have guides to center the paper.

I do it every day at work ([manual paper tray with guides](https://www.kyoceradocumentsolutions.co.uk/content/imagelib/eu/en/printer_multifunctionals/product/ecosysp2135d/p2135d_open_mpt_01.-imagelibitem-Single-Enlarge.imagelibitem.jpg)). And this is one of the main reasons why SumatraPDF cannot be our default PDF application at work.

Would it be possible to implement an option to also center the page?

BTW, _Use original page sizes_ isn’t a page scaling option. It is only a page handling option. Page scaling should be fit/shrink to printer margins and no scaling.

This is important because some printing may demand distinguishing page handling and scaling options.

Would it be also possible that both _Use original page size_ and _Center page_ could be different from page scaling options?
