### ISSUE TITLE
forgets former opened files

### ISSUE THREAD

**Issue by somefunAgba** [sumatrapdfreader/sumatrapdf#1132]
Is there a way, you can include proper remembrance functionality into SumatraPDF so it reopens all former files opened with it after a system restart or shutdown.

**Comment by GitHubRulesOK** [comment]
It does however if you get a brownout or system shutdown whils sessions are open then the dynamic settings file is effectively corrupted and zero'd on restart. my suggestion has always been that to harden against such eventualities the software needs to keep a sensible backup that is checked on start-up otherwise users need to go to advanced options and save as OR run a periodic chron script to save the current copy with perhaps a time flagon the name. However in fairness to SumatraPDF if I  exit cleanly I have never lost a session history spanning over numerous years.

**Comment by GitHubRulesOK** [comment]
It "should" always remember sessions unless altering "remember" options.
It does fail if you get a brownout or system shutdown whilst sessions are open then the dynamic settings file is effectively corrupted and zero'd on restart. 
My suggestion has always been that to harden against such eventualities the software needs to keep a sensible backup that is checked on start-up otherwise users need to go to advanced options and save as OR run a periodic chron script to save the current copy with perhaps a time flagon the name. 

However in fairness to SumatraPDF if I exit cleanly I have never lost a session history spanning over numerous years.

**Comment by somefunAgba** [comment]
Thank you.

**Comment by somefunAgba** [comment]
Please mark as closed.
