### ISSUE TITLE
old files open with new one (version 3.1.2)

### ISSUE THREAD

**Issue by Joseph9994** [sumatrapdfreader/sumatrapdf#1141]
hello,

when I have to open 1 pdf file, sumatra opens the old ones too.
for example, I open "file 1" and I close it, then i open "file 2": it opens both of them.

thank you for your work!

**Comment by kjk** [comment]
Please provide more information:
* how are you closing the file? Are you just closing the file or closing the application?
* how are you opening the files? File / Open? Double-clicking in file manager?

**Comment by Joseph9994** [comment]
I close the application.
I open the files both "open with" and double click on the file.
If you need, I can record my computer screen and send you, if I'm not clear explaining the bug

**Comment by kjk** [comment]
Please do, but I suspect this works as designed.

If you close the application, Sumatra remembers opened files so that if you re-open the application, the files will also be re-opened.

If you double-click on a file, we still re-open the files from previous session similar to how if Sumatra is opened and you double-click on a file, we add it to opened files and don't close other files.

This  shouldn't happen if you close the files first (e.g. with ctrl-w) and then close the application.

**Comment by Joseph9994** [comment]
ok, I'm sorry: I didn't expect that the app remembered the previous session even if i close the process.
false alarm

**Comment by kjk** [comment]
no worries

**Comment by GitHubRulesOK** [comment]
@Joseph9994 
You can switch off this behaviour in settings > options > Remember opened files (uncheck the box)
