### ISSUE TITLE
Can't save into document with highlight?

### ISSUE THREAD

**Issue by BruceChen2017** [sumatrapdfreader/sumatrapdf#1143]
I am using pre verison with setting `saveintodocument = true`. After using highlight,I want to save in place not into another document,how to achieve this?

**Comment by BruceChen2017** [comment]
BTW,can I change the shortcut of highlight?

**Comment by GitHubRulesOK** [comment]
The shortcut for highlight is fixed it was H(ighlight) but is now A(nnotation) 
SumatraPDF does not allow to change key shortcuts you can use 3rd party key mappers to do that.
If you have set = true then it will append the highlights to the end of file so the file is now changed and you need to "Save As" this is a feature necessary to try to ensure users do not attempt to overwrite a restricted or unrestricted but locked original file with the modified copy without thinking about "AS".

**Comment by BruceChen2017** [comment]
@GitHubRulesOK So there is no way to save in place?What a pity!

**Comment by GitHubRulesOK** [comment]
@brucechen2017
YES It does save "into" file BUT you MUST CHANGE the file name first
 the names do not matter
I have a file called WITHOUT.PDF
I make changes (SaveIntoDocument = false)
I save as WITHSMX.PDF & WITHSMX.SMX
I make changes (SaveIntoDocument = true)
I save as WITHOUTSMX.PDF

You can have OLD-NAME.PDF
make changes
Save As NEW-NAME.PDF
make changes
Save As OLD-NAME.PDF
that has changed OLD-NAME but you took a deliberate action to do so twice it was no accident.

**Comment by GenghisCrade** [comment]
Hello,

Is it possible to have a "save SMX" option then ?

Thanks for the great software, love it

**Comment by GitHubRulesOK** [comment]
@GenghisCrade Not sure why your asking, IF save into document is false then the Save As will keep the pdf and Save/update Only applies to any .smx hence the Save AS (new.PDF) changes either PDF or SMX depending on save into document. it may seen odd compared to the way some other applications work but this is not uncommon when working with "sidecar" or dual metadata system files

**Comment by GenghisCrade** [comment]
It's just that there are several aspects that slow the process down and seem overkill

- You can't quickly ctrl+s as it prompts the file picker every time
- The file picker more or less implies that it's the PDF that's being overwritten, so I thought it also overwrote the PDF, but nonetheless the "safety" argument doesn't really stand since I don't need to double-check everytime if I'm just overwriting an SMX
- **The file picker doesn't open in the same directory as the pdf file currently being used** (that actually might be my biggest issue), rather in $USER/Documents or the last directory you saved a file in

It severely hinders the workflow say, if you have two files that are very apart in the filesystem and you work on both of them in different tabs

If there was a process to only save the .SMX, you could quickly iterate on it by just pressing a shortcut and it would be lighter at every level

**Comment by GitHubRulesOK** [comment]
@GenghisCrade your comments are valid and probably one of the main reasons it is still experimental (not for productive use) however the main release can respect and work with smx files. Nod5 used background saving of smx in his highlight helper so may be worth searching on that for hints to see if possible to still add background saving but note his app is out of date and needs some edits to work.

**Comment by jerojerojeroppi** [comment]
>  but note his app is out of date and needs some edits to work
Could you please point me to what edits are necessary ? 
I would like to use "highlight helper".

**Comment by GitHubRulesOK** [comment]
@jerojerojeroppi 
the discussion was on user forum see https://forum.sumatrapdfreader.org/t/sumatra-highlight-helper-key-h-to-a-fix-soon-other-suggestions/1492 which should lead back to https://github.com/nod5/sumatra_highlight_helper

**Comment by RENANZG** [comment]
"So there is no way to save in place?What a pity!"

i have been using pdfexhange viwer precisely because of this

**Comment by GitHubRulesOK** [comment]
@RENANZG ? your comment is identical to one 10th March above, and the answer is still the same
Yes it DOES save in place (if you set it to do so)

**Comment by RENANZG** [comment]
NO, it DOES NOT save in place !

PEOPLE, USE PDF EXCHANGE VIEWER, IT'S BETTER
