### ISSUE TITLE
Logical page numbers corrupt in encrypted PDFs

### ISSUE THREAD

**Issue by rdsqrt** [sumatrapdfreader/sumatrapdf#1144]
Customized page numbers show up corrupted in encrypted PDFs, and don't work for "Go To".
I'm seeing the same result with two encryptors: new QPDF, and old iText.

Only tried AES encryption. I think it was the same with 128 and 256 bits, though maybe a different sort of corruption.

Works fine in Foxit Reader v4.

![Screenshot](https://user-images.githubusercontent.com/34013692/54092605-ccb3c680-4396-11e9-81e4-11fedef92101.png)

[Sample PDF, password is "password".](https://github.com/sumatrapdfreader/sumatrapdf/files/2950142/password.is.password.pdf)

**Comment by GitHubRulesOK** [comment]
Tried in several viewers most would not navigate like SumatraPDF they were corrupted pages 6, 7 & 8 having been badly garbled by encryption once decrypted the page numbers return correctly to 6 7 & 8 in SumatraPDF and others
[unlocked 678.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/2950548/unlocked.678.pdf)

**Comment by rdsqrt** [comment]
I'm seeing the same result with two encryptors: new QPDF, and old iText.

Only tried AES encryption. I think it was the same with 128 and 256 bits, though maybe a different sort of corruption.

**Comment by SumatraPeter** [comment]
Like Edge, the latest MuPDF 1.14.0 too displays the page numbers as 1-3. However it's interesting to note that Firefox's PDF.js has no problems at all displaying the page numbers as 6-7.

**Comment by rdsqrt** [comment]
It works okay on Xodo's Viewer (Android), which is based on PDFTron.

Even if it's outside of the standard for some reason, de facto support isn't rare, and it makes sense.

**Comment by TamirEvan** [comment]
The MuPDF viewer (and presumably Edge and Chrome) only shows the page indices. The expected "6-8" are actually page labels (see section 8.3.1, p. 594, of the [PDF 1.7 reference](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdf_reference_archive/pdf_reference_1-7.pdf)), which MuPDF doesn't currently handle ([Bug 695351](https://bugs.ghostscript.com/show_bug.cgi?id=695351)). SumatraPDF works around this by [getting the page labels entry directly](https://github.com/sumatrapdfreader/sumatrapdf/blob/7c928f6b9cd220b2117fe7ead0e2e8fb6b577909/src/PdfEngine.cpp#L1653).

The page labels get corrupted because the root version and OCG objects are loaded in the docment initialization phase, before a password could be validated (or even requested), and other objects get loaded (and decrypted) along the way, including the page labels, potentially corrupting them.

I reported a related bug on the MuPDF Bugzilla ([Bug 701559 - mutool clean garbled page labels in AES encrypted PDF file](https://bugs.ghostscript.com/show_bug.cgi?id=701559)). Towards it's resolution, [one patch](https://git.ghostscript.com/?p=mupdf.git;a=commit;h=9b52ea86479bf8900fae5f1f92f42eaf177d9387) has already been committed to their main repo, and a second one is awaiting testing and review.

For SumatraPDF, I have "backported" the first patch, and [a currently uncommitted version of the second patch](https://git.ghostscript.com/?p=user/sebras/mupdf.git;a=commit;h=754515118b8f9d3a9fdc1ce95b67a3d8ec669bc7), on my [issue-1144 branch](https://github.com/TamirEvan/sumatrapdf/commits/issue-1144). If anyone wants to try it out, [binaries are available](https://ci.appveyor.com/project/TamirEvan/sumatrapdf/builds/27647077/artifacts).

This is what I get, with my applied patches:
![issue-1144-fixed](https://user-images.githubusercontent.com/1873062/65736863-3605e780-e0e5-11e9-84e7-0593667aa1ae.PNG)

**Comment by SumatraPeter** [comment]
@TamirEvan: Thanks for the investigation, explanation, bug reporting and patching! It would be great if someone like you could restart active development of Sumatra... More than anything an update to the latest MuPDF version is _sorely_ required.

**Comment by GitHubRulesOK** [comment]
@TamirEvan you may have noticed @kjk is updating SumatraPDF to latest MuPDF however this bug is still there are you in a position to add your corrections as a pull request to recent commits, it would be nice to have closed this issue before next formal release.

**Comment by kjk** [comment]
When mupdf merges fix by @TamirEvan , we'll import it.
After the big merge updating to latest version of mupdf should be relatively painless.

**Comment by TamirEvan** [comment]
@GitHubRulesOK The first patch I mentioned seems to be included in the recent update of the MuPDF code (in SumatraPDF). The second patch is still awaiting testing and review. Like @kjk (if I understand him correctly), now that we're using a more recent version of MuPDF, I'd prefer to wait for the second patch to be committed upstream, and then import here.

@kjk The still pending fix isn't by me, but by Sebastian Rasmussen. I only backported it (along with the first patch by Tor Andersson) to the version of MuPDF being used at the time. (I probably should have been clearer about that, instead of relying on the links I gave to provide those details.)

**Comment by GitHubRulesOK** [comment]
@kjk still not included in latest update so perhaps tag as known MuPDF bug

**Comment by GitHubRulesOK** [comment]
@TamirEvan 
I note your second request in 701559 should now be committed within MuPDF lib (Thanks in advance?) , thus looking forward to testing above sample in next SumatraPDF MuPDF import.
ASIDE NOTE I saw your mutool bug scriptlet to highlight all phrases in page/document which I could with a small tweak run concurrently in SumatraPDF pre-release (I just need to add a phrase count to meet user expectation)
Do you have other snippets that if adapted may be of wide appeal?

@kjk 
Can I expect to close based on either pretty 1-3 (commonly in Edge, eXchange, Okular, Slim reader STDU et Al)
or custom 6-8 (Only Foxit ?)
I can not re-test in my Older Acrobat as its now complains internal error with the above sample !

The OP said Foxit was showing the desired "custom" sequence so I guess 6-8 is needed for closure?

**Comment by TamirEvan** [comment]
@GitHubRulesOK
I just now saw that myself. I see the second patch for MuPDF Bug 701559 is currently the latest commit on their master branch (ArtifexSoftware/mupdf@8450ad1215e4858d7a6da9895615ec58b4128205). I haven't tested the new code, either in the context of the bug I reported, nor in the context of current SumatraPDF.

Re: my "_mutool bug scriptlet to highlight all phrases in page/document_":
I guess you mean the JavaScript file I attached to [Bug 700466](https://bugs.ghostscript.com/show_bug.cgi?id=700466) there. I put together that code to demonstrate the problem I had found, in a way better than the mupdf-gl screenshot could do. It also allowed me to show the highlighting of search results of words with non-ASCII characters (in my case, Hebrew), something I can't currently do with mupdf-gl (despite [Bug 698803](https://bugs.ghostscript.com/show_bug.cgi?id=698803) being marked as 'RESOLVED FIXED'). It was a tool serving a specific purpose. I didn't think of it as something that would be of wide appeal.

I have toyed around with writing scripts to be run with `mutool run`, but currently don't have anything that I'd consider useful, or that I'd be confident sharing. One of my problems with writing these scripts, is that I often find the [documentation](https://www.mupdf.com/docs/manual-mutool-run.html) hard to understand, especially when going beyond the examples. Also, not as much of the underlying MuPDF API is exposed to JavaScript as I would have liked.

If you want to try writing your own scripts, besides the official documentation, you could look at the examples in [mupdf/docs/examples/](https://github.com/sumatrapdfreader/sumatrapdf/tree/ad9170712fdf0bfb3dca808dcb155c05d7364f56/mupdf/docs/examples), or try looking through [`mutool run`'s source](https://github.com/sumatrapdfreader/sumatrapdf/blob/ad9170712fdf0bfb3dca808dcb155c05d7364f56/mupdf/source/tools/murun.c), to try and understand how things work. That's what I usually do.

**Comment by GitHubRulesOK** [comment]
@TamirEvan 
Thanks both for the fix SumatraPDF now shows custom pages 6-8 (1/3)
 **and** also your feedback
 "documentation hard to understand" **agreed** I have tried adapting some examples with mixed success
the highlight zone bug is not relevant to the common user request to be able to highlight more than one occurrence of a search term and the subsequent request to provide an overall count of said occurrences.
