### ISSUE TITLE
Space in file name results in "Error Loading "Filepath\file name"

### ISSUE THREAD

**Issue by apala56** [sumatrapdfreader/sumatrapdf#1149]
In our CRM application "Applied Epic" when the API calls to open a pdf with a space in the file name SUmatraPDF opens the file as if each space in the file name creates a new pdf. So "New File Open.pdf" will spawn new.pdf, file.pdf, open.pdf with all resulting in error loading. The length is inconsequential as even a single space file such as "NB App.PDF" will result in two separate files attempting to be opened. Its works fine opening with Edge and AdobeReaders. 
![sumatraerror](https://user-images.githubusercontent.com/48953503/55004216-31cf0500-4fb0-11e9-8eca-e054012fc886.JPG)

**Comment by apala56** [comment]
This occurs in both 3.1.2 and current 3.2.1.11105 pre-release

**Comment by kjk** [comment]
I would need to see the exact command line that the application uses. The issue is almost guaranteed to be the CRM not calling Sumatra correctly i.e. no escaping file names with spaces in it.

This doesn't work:
```
sumatrapdf.exe my file with spaces.pdf
```
This works:
```
sumatrapdf.exe "my file with spaces.pdf"
```
You can test that syntax from cmd.exe and see that it works.

**Comment by apala56** [comment]
I will attempt to get the command line. There is some concern though since it does not happen with several other readers. SumatraPDF is so much faster and cleaner so I would prefer to use it.

**Comment by apala56** [comment]
Used process explorer to find the command line and yes it doesnt look like it calls the files with quotes.
"C:\Program Files (x86)\SumatraPDF\SumatraPDF.exe" C:\ASI\ASI.TAM\ThinClient\Temp\Attachments\0e0c5rkw.4wg\Pal Hanover 308 Hamil app.pdf
Is there some work around I could accomplish myself? I just feel like attempting to get the vendor to remedy will be futile since it works with mainstream viewers but I will certainly try.

**Comment by GitHubRulesOK** [comment]
@apala56 it is a windows failure not sumatraPDF
DOS did not allow filenames with spaces Windows introduced that when switching to LFNS (long file names) but Windows did not ensure it was a non-breaking space so now we have the situation of Command (PartName1 AnotherPartname) Many apps such as SumatraPDF and other mainstream viewers always expected Command File1 File2 so just drop one or more files onto SumatraPDF.ex and it will open them because WINDOWS will do what is needed that is add "NAMEPART1 PART2.pdf" so when you do it manually YOU NEED to do it the same way WINDOWS does it.

Without quotes C:\Users\Desktop>DIR test out.pdf = The system cannot find the file specified.
With quotes    C:\Users\Desktop>DIR "test out.pdf" =  test out .pdf               1 File(s)            763 bytes

C:\Users\Desktop>sumatrapdf "test out.pdf" "sec ond.pdf" = both opened
C:\Users\Desktop>sumatrapdf test out.pdf = cant open test & cant open out,pdf (Correct they don't exist)

**Comment by apala56** [comment]
this is the command line out of Adobe 
"C:\Program Files (x86)\Adobe\Reader 11.0\Reader\AcroRd32.exe" --channel=7576.0.1923358344 --type=renderer  /n "C:\ASI\ASI.TAM\ThinClient\Temp\Attachments\4bl20kjy.o1f\HO-REQ FROM NEW MTG TO AMEND.PDF"

**Comment by kjk** [comment]
> Is there some work around I could accomplish myself?

Unfortunately, I can't think of a work-around that wouldn't involve changing the code that calls sumatra.

**Comment by GitHubRulesOK** [comment]
The Work around is to work with the difference so save a cmd file call it SumatraPDF.cmd (if you really need to )
for a one line use when passing unquoted strings for filename (but may break on occasion) it just calls the adjoining exe with the spaces within a set of quotes

%~dp0Sumatrapdf.exe "%1 %2 %3 %4 %5 %6 %7 %8 %9"

More complicated is to catch the command line strip and store the parameters unquoted then call the quoted string

set StoredEnvFileName= see DOS reference methods for your system to convert to unquoted string
%~dp0Sumatrapdf.exe "%StoredEnvFileName%"
