### ISSUE TITLE
Starting but not displaying

### ISSUE THREAD

**Issue by abendlin** [sumatrapdfreader/sumatrapdf#1150]
In a virtual XP sumatra is running (just installed). It'll be started from a VB program via ShellExecute. Nothing seems to happen. In the task manager sumatra is started but it doesn't load the PDF document and it's not visible on desktop. Switching to Adobe X11 everything is working correct. Using Sumatra standalone i.e. starting Sumatra and loading a PDF file everything seems to be ok. In other VMs Sumatra is working, everything seems to be ok. 

Is there any solution available?

**Comment by GitHubRulesOK** [comment]
Most unusual, since if calling the same exe via any method it should produce a similar window even if contents are say "file not found". So have to question what is the command line from the VB execute command it should be (subject to methodology) generally "quoted" if it has spaces eg "program files\sumatraPDF\Sumatra.exe"  "path/and/file name.pdf" are you adding any other parameters ?

**Comment by kjk** [comment]
The problem is in how you call Sumatra with ShellExecute.

I don't have your code so can't help you.

Most likely you're not building the command line properly (most common mistake: not quoting file names with `"`, especially if they have spaces in them).

You can use tools like Process Explorer to see what command-line arguments you passed to Sumatra.
