### ISSUE TITLE
Cleaner Sumatra Icon

### ISSUE THREAD

**Issue by musm** [sumatrapdfreader/sumatrapdf#1159]
I love sumatra, but really hate it's icon. It looks very outdated and I hope a cleaner icon could be agreed to.

**Comment by kjk** [comment]
Unless someone provides a great icon it's a moot point.

**Comment by musm** [comment]
What formats are needed for proposal?

**Comment by kjk** [comment]
Ideally, it would be a vector format and created in an online tool like https://www.figma.com, so that it can be shared and improved.

That vector should then be rendered as 512x512 .png file.

The final result is a multi-resolution .ico file (see https://www.creativefreedom.co.uk/icon-designers-blog/windows-7-icon-sizes/) but that can be generated from 512x512 .png file using online converters like https://www.icoconverter.com/

**Comment by musm** [comment]
Do you think we could leave this open so that perhaps some others that are more graphically inclined would find it?

**Comment by GitHubRulesOK** [comment]
The overall discussions are still open in https://github.com/sumatrapdfreader/sumatrapdf/issues/600
where the comment is to retain the main icon as similar as possible to the current "Branding"

**Comment by kjk** [comment]
While I was open to changing the program icon in the past I no longer am.

There will be no changing of the program icon (this is different from filetype icons as discussed in #600)

3 reasons.

1. While everyone is entitled to their opinion, the current icon is high quality.

2. Current users of Sumatra are used to this icon. It's how they visually find the app. An alternative would have to really blow my mind to outweigh that.

3. I'm not a designer. I'll not create a better icon so it would have to come from someone else. 

While there's been some enthusiasm there so far it's bee a giant waste of time. People promising something and not delivering at all or submitting proposals significantly worse than the current icon.

Therefore I'm shutting this down once and for all. There will be no change to program's icon.
