### ISSUE TITLE
Problems with Swedish letters in the title

### ISSUE THREAD

**Issue by H2SO4JB** [sumatrapdfreader/sumatrapdf#1177]
Hi,

When I print as a PDF file from Excel and the file name contains Swedish letters, then strange characters are displayed instead of the Swedish letters in the title when I open the PDF file in Sumatra. I don't know if this is a bug in Sumatra or with the Print PDF function in Excel. Please, can you investigate this?

![Screenshot](https://user-images.githubusercontent.com/13471707/60420618-72aa6b80-9be8-11e9-94c1-8ac902e60191.jpg)
[TEST_ÅÄÖ.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/3344512/TEST_AAO.pdf)
[TEST_ÅÄÖ.xlsx](https://github.com/sumatrapdfreader/sumatrapdf/files/3344514/TEST_AAO.xlsx)

**Comment by GitHubRulesOK** [comment]
No issue that is what Microsoft Windows (not excel) called the file internally when it was built. SumatraPDF is echoing exactly what Acrobat or any other PDF reader should be telling You would need to find out where excel **Print to Pdf** injects the name TEST_Ã–Ã—ÃŒ.xlsx

**Comment by H2SO4JB** [comment]
I see, thanks anyway.

**Comment by SumatraPeter** [comment]
@H2SO4JB: Open the PDF in Sumatra and press Ctrl+D, and you'll see that the PDF's _**Title**_ metadata field has been set to the incorrect name.

It seems you have used the **Microsoft Print to PDF** printer to create the PDF from Excel. Looks like one of the limitations of that virtual printer is that it doesn't support Unicode properly, at least when it comes to PDF metadata.

The solution is to simply use the Save As command in any Office app like Word/Excel/PowerPoint and specify that you want to save as .PDF instead of .XLSX:

![image](https://user-images.githubusercontent.com/15380332/60471385-0b40fa00-9c82-11e9-836c-5c1edf9a95b6.png)

Not only does this _not_ automatically set the  _**Title**_ metadata field without asking, as a bonus it also creates a _far_ smaller/more optimized PDF to boot!

P.S. If you do want to set the _**Title**_ metadata field before you Save As PDF, just go to `File > Info` in Excel and edit the property.

**Comment by H2SO4JB** [comment]
SumatraPeter >>>
Thanks for a simple and detailed explanation. Save as PDF was a very simple solution, so I go with that.
