### ISSUE TITLE
[Feature request] Print actual size

### ISSUE THREAD

**Issue by Rob-Hermsen** [sumatrapdfreader/sumatrapdf#1178]
One feature for which I need to switch back to Acrobat now and then is the page size / print scaling options. For things like technical drawings it can be useful to print pages on actual document size (i.e. scale 1:1, one cm in the document is actually printed as one cm on paper). The Adobe printing menu features 4 options regarding this: "Fit", "Actual size", "Shrink oversized pages", and "Custom scale" . These kind of options would make Sumatra all the more useful in my opinion.

**Comment by GitHubRulesOK** [comment]
Those basic features are available from Windows Print system and accessible via Print > Advanced > Page scaling. Windows allows for "Shrink oversized pages"(to printable area) "Fit"(to printable area), Use original page sizes ("Actual size"), However Windows does not provide a "Custom scale" function for every print driver, so that can not be a constant option. Adobe Write PS print drivers so their team have full control over how they operate. SumatraPDF relies on generic features shipping with Windows.

**Comment by Rob-Hermsen** [comment]
An oversight on my part. I had completely missed this. Thank you. I'll close the issue.
