### ISSUE TITLE
sumatrapdf cannot open this pdf while pdf xchange editor can

### ISSUE THREAD

**Issue by simonnier** [sumatrapdfreader/sumatrapdf#1208]
Dear developers,

I found sumatrapdf can not open [this pdf](http://s000.tinyupload.com/index.php?file_id=34758768142262526324), but pdf xchange editor can. Please check it

best regards

**Comment by SumatraPeter** [comment]
Neither MuPDF (Sumatra's PDF engine) nor Firefox or Edge can open this file. I checked its internal structure and turns out it is a DRM protected PDF that relies on a third-party non-standard encryption handler ("FOPN_foweb"). A web search tells me this is made by FileOpen Systems, and as the [company's website](https://www.fileopen.com/products/3rd-party-viewers) mentions in its page about Supported Third Party Viewers:

> PDF Documents encrypted using the FileOpen software can be opened in a number of viewers other than Adobe Acrobat/Reader. These vendors have incorporated modules from FileOpen that enable the same controls as the ones implemented in the Adobe products. However, FileOpen does not mandate support for all supported features, so there is some inconsistency in the capabilities of  different products. Some of these products do not support features that are required by particular publishers, so there may be cases where a PDF will open in Adobe Acrobat/Reader but not in one of the alternative viewers. In this case the only workaround is to use Adobe Acrobat/Reader.
![image](https://user-images.githubusercontent.com/15380332/65394090-ee125800-dda6-11e9-8dc9-89b9d52bf556.png)

Now unless open-source software like MuPDF or Sumatra decide to incorporate FileOpen's proprietary plugin (assuming the license is compatible in the first place), I would suggest you look elsewhere when it comes to opening such files protected with proprietary DRM schemes.

@kjk: Unless you ever intend to incorporate said plugin into Sumatra I'd suggest this should be closed as Won'tFix.

**Comment by kjk** [comment]
Yes, if mupdf doesn't support it, we can't either. Their stuff doesn't seem to be open so most likely it's not even possible to support their stuff in an open-source product like Sumatra.
