### ISSUE TITLE
Cannot select text by mouse drag.

### ISSUE THREAD

**Issue by ageback** [sumatrapdfreader/sumatrapdf#1228]
I built with latest source code. Then I cannot select text by mouse drag. In old versions this works.

**Comment by kjk** [comment]
Restored, although it's not as good as it used to be. Maybe coordinates of text changed.

**Comment by GitHubRulesOK** [comment]
@kjk this still a big problem I suggest its revisited since It is very difficult to find the position to start dragging see previous sample attached 
[output.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/3849044/output.pdf)

![Untitled1228](https://user-images.githubusercontent.com/12754913/68903751-fc8c4880-0733-11ea-85ed-4feaa158b7c2.png)

**Comment by kjk** [comment]
Agreed, it's much worse on this PDF.

**Comment by kjk** [comment]
This bug was about mouse selection for all documents.

output.pdf is just one pdf where mupdf has regression with bounding boxes for glyphs. mupdf-gl has the same issue. Still a bug but with very limited scope and it's mupdf so if they fix it, we'll inherit it.
