### ISSUE TITLE
Regreesion color bug in recent build

### ISSUE THREAD

**Issue by Bambooin** [sumatrapdfreader/sumatrapdf#1267]
My setting is:

FixedPageUI [
	TextColor = #ffffff
	BackgroundColor = #263238
	SelectionColor = #3399ff
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
]

But the color BackgroundColor = #263238 don't match, it work in recent build.

The attch will show the bookmark backgroud is  #263238, but the page backgroud don't match.

![color](https://user-images.githubusercontent.com/7157227/69596727-8e525a80-103e-11ea-9fb8-7f89301452ff.png)

**Comment by GitHubRulesOK** [comment]
@kjk there is the delay in updating bookmarks area that I mentioned in other issue which seems to create this issue that when a user changes "paper color" then they need to close and restart to see the same colour on bookmark canvas.

**Comment by Bambooin** [comment]
I set background color for dark theme, what I want to describe is the BackgroundColor = #263238 setting has different color between version 3.1.2 and recent build.

**Comment by GitHubRulesOK** [comment]
@kjk I stand corrected this issue seems to be a change in backround rendering that occured at some point between 3.2.11325 and 3.2.11362
![image](https://user-images.githubusercontent.com/12754913/69624843-5860a680-103d-11ea-9d73-20c82372b333.png)

**Comment by R-Usher** [comment]
It looks like now background is displayed with value for B component used also for R. For example, value #e8fce8 (pale green) is used instead of #fffce8 (pale yellow). Build 11336 was OK, other troubles with colours were in build 11342 (missing GB components in title bar colour), current problem (existing in build 11348) is probably regression caused by fixing bug visible in 11342.
