### ISSUE TITLE
Add menu item to download symbols

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#1278]
Downloading symbols manually is tedious so have to make it easier.

**Comment by SumatraPeter** [comment]
Once Debug > Download symbols is clicked, the app just hangs (if you click it you get the familiar "Not responding" message in the titlebar). Can there be a progress bar, or better still, can the download be executed in a background thread so as not to lock up the app?

Also, please note that _after_ the symbols have been downloaded, it displays a dialog with the title "Download**ing** symbols", and the icon is one that commonly indicates failure instead of success!

![image](https://user-images.githubusercontent.com/15380332/70870781-72970000-1fbd-11ea-9dfb-147a096fb29f.png)

**Comment by kjk** [comment]
Those are all good suggestions. I've changed the icon because it was easy.

However the other stuff requires too much work for what is meant to be rarely used functionality.

**Comment by SumatraPeter** [comment]
Ok, then I have an alternate suggestion. Since you're gonna block the UI anyway, why not make it a modal "Download**ing** symbols..." dialog box with an active Cancel and inactive OK button? If the user Cancels, boom, dismiss, else display the result (success/failure) and activate the OK button and disable the Cancel button. Is that doable?

**Comment by kjk** [comment]
Like I said, any effort spent on this is just not worth it. This
functionality is meant for people who are willing to run Sumatra under the
debugger to investigate problems more deeply.
So far the uptake for this was one person a year.
