### ISSUE TITLE
Add text search and translation from selection

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#1280]
Still to do:
* [x] add top-level `Selection` menu after `Zoom`
* [x] more built-in services? Which ones?
* [x] a way for user to customize the list using `SelectionHandler` in advanced preferences, similar to `ExternalViewers`
* [ ] maybe: support invoking desktop apps. But which ones? Is it worth it?
* [ ] maybe: support [GoldenDic](http://goldendict.org/), it seems to accept a word on cmd-line

Desktop dictionaries:
* https://quest-app.appspot.com/home
* http://goldendict.org/
* http://www.tanos.co.uk/jlpt/extras/jwpce/

Other notes:
* https://github.com/Keypirinha/Packages/blob/master/WebSearch/websearch.ini : ideas for other websites

**Comment by SumatraPeter** [comment]
Perhaps something along the lines of **ExternalViewers** in SumatraPDF-settings.txt, with appropriate levels of sanitization?

```
ExternalSites [
  [
    # URL of the website, may contain %s for selected text
    URL = https://www.google.com/search?q=%s

    # name of the website to be shown in the context menu (implied by domain name in URL if missing)
    Name =
  ]
]
```

**Comment by GitHubRulesOK** [comment]
At present we can send external commands a filename [%1] and page number [%p] as in this example
![Annotator](https://user-images.githubusercontent.com/12754913/69907403-e2599800-13cc-11ea-8b9e-d747a81cd3ad.png)

In this case an image only page is sent to an "external editor" (MuPDF) where it can be modified and overwriten, this raises similar questions as to those such as when a music or video player application can be used to feed a recording application. Where should the boundary be ?

Current work in progress on selecting text could also allow "protected" word strings to be used in an arguably similar fashion ? Currently SumatraPDF only copies such text as an image ! however external apps can readily convert such strings to text and feed them to other commands such as a web search, text translator or TTS (text to speech). Adobe themselves have a sort of dual standard in allowing some restricted text to be used for screen readers.

**Comment by GitHubRulesOK** [comment]
For a wscript vbs method see https://forum.sumatrapdfreader.org/t/advanced-tips-pass-selection-to-another-app-e-g-web-search/2700

Depends of course on you being allowed to run wscript and vbs files on your system

With the right parameters can be used for 
Add text search and translation from selection #1280
Search selection text in search engine #877
Search selected text in default internet browser #420
Add a translation feature #1351
Auto-Copy a selected word #427
Dictionary Support #947

**Comment by DhruvaSambrani** [comment]
Bump, coz I really love @GitHubRulesOK 's method. It is simple and doesn't need too many implementation changes. All the other features can simply be relegated to the multitude of websites which support translations and searching. This will really help academicians because we can just for the DOI of a cited paper and search on whatever website to quickly get to that paper.

Side feature addition is to add it in the context menu too, but that is low priority

**Comment by DhruvaSambrani** [comment]
@kjk I'd like to implement this. I've already implemented the changes as discussed in @GitHubRulesOK 's post
> To keep this stupidly simple previous suggestion is to simply send the "text" selected to an "external application" call so the following is the result of selecting "SumatraPDF" and passing as say [%$]

I've used %2 instead, to keep along using %1 for file and because `$` kept being re-written on app open. Changing to some other character is trivial.

> Hotkey default should be [ALT F] & O for first "Open with" (perhaps could add a means to select 1st , 2nd, 9th externals ?)

So this can be done like how Recent Files are added, with a shortcut given by it's index. However, this means that users will need to press an extra enter because there are 2 actions with the same shourtcut. Users can override the shortcut by simply adding their own shortcut as part of the name. eg- `Name= Open in &Web Browser` will make `Alt-F s` as the shortcut.
Or we add another sub-menu for external viewers, adding another key in the shortcut chain.
I would however prefer to remove the shortcut on Recents, because that is a highly dynamic list so users can't commit the shortcut to muscle memory anyway.

I've also removed the "Open in " string which was added to the Menu Item, because "Open in Translate to Arabic" doesn't make sense.

I will open a PR for your perusal

**Comment by kjk** [comment]
I've added selection search / translation with online services. Built-in support for: search with Google and Bing, translation with Google Translate and DeepL.

Still to do:
* [ ] add top-level `Selection` menu after `Zoom`
* [ ] more built-in services? Which ones?
* [ ] a way for user to customize the list using `SelectionHandler` in advanced preferences, similar to `ExternalViewers`
* [ ] maybe: support invoking desktop apps. But which ones? Is it worth it?

**Comment by GitHubRulesOK** [comment]
@kjk 
giggle is set to localhost in my host file and I avoid bing as much as possible, The point about sending any selected string to any externalviewer is I can chose any insecure Tor browser or grammar pedia I prefer.

**Comment by kjk** [comment]
Customizability is coming but I want to provide most common services built-ins as well.

**Comment by githwithit** [comment]
> 
> 
> Customizability is coming but I want to provide most common services built-ins as well.

I do not use Google or Bing but DuckDuckGo works very well for me.

Could DuckDuckGo be one of the default, built-in common search services?

I really miss being able to highlight words in PDFs and then doing an internet search, thanks for working on this!

**Comment by GitHubRulesOK** [comment]
@githwithit (wish I had thought of that moniker its shorter and **wit**hier 🙂 )
```
SelectionHandlers [
  [
    URL = https://duckduckgo.com/?ia=web&q=${selection}
    Name = &Quack it to me
  ]
]
```
Shortcut=<kbd>ALT</kbd><kbd>E</kbd><kbd>Q</kbd>

**Comment by kjk** [comment]
Closing this as I've implemented customization.

I don't know about adding Duck Duck Go. I know it's used by some people but it has a fraction of users that Google / Bing.

I've added a doc on customization with Duck Duck Go example, so it's just a copy&paste to add it: https://www.sumatrapdfreader.org/docs/Customize-search-translation-services

**Comment by GitHubRulesOK** [comment]
@kjk 
amused you kept the Quaking shortcut but would help to say the key press is Shortcut=ALT+E+Q

it is a fraction since **they do not track users** but based on global averages " it works out to approximately 80 million people (as of November 2020)!" and it anonymises google
