### ISSUE TITLE
URL Hyperlink bug

### ISSUE THREAD

**Issue by motianya211314** [sumatrapdfreader/sumatrapdf#1313]
word url no set Hyperlink：
![word](https://user-images.githubusercontent.com/15711438/70719111-5d577280-1d2c-11ea-9b07-5f11b4519def.png)

adobe normal display：
![adobe](https://user-images.githubusercontent.com/15711438/70719183-76f8ba00-1d2c-11ea-8770-27271dca7bff.png)

sumatrapdf :
![sumatrapdf](https://user-images.githubusercontent.com/15711438/70719225-8c6de400-1d2c-11ea-9548-19a56cb3f7f4.png)

**Comment by GitHubRulesOK** [comment]
@motianya211314 
The  sample file (in a zip helps to check structure of the link)

**Comment by kjk** [comment]
@motianya211314  Without a file to inspect I can't tell if it's sumatra or incorrectly generated PDF file.

**Comment by SumatraPeter** [comment]
> here my sample from wordpad shows that it appears to be a problem in the way that MSWord creates such hidden links

Testing with Wordpad is pointless because it tells us _nothing_ about whether Word is or isn't at fault,

I just tried copy-pasting `打开浏览器, 打开 https://www.baidu.com/, 并登` into Word (no hyperlink explicitly added), then used Save As to save as a PDF. Subsequently opened the PDF in both 3.1.2 and prerelease-11625, and neither had a problem with correctly identifying the link to `https://www.baidu.com/`. The comma and characters after the URL were _not_ included in the link by either Sumatra version. In short, I am unable to replicate the issue even with Word.

So @motianya211314 you need to tell us exactly which version of Word you're using, how you converted the document into a PDF, and which version of Sumatra did you test with?

**Comment by GitHubRulesOK** [comment]
@SumatraPeter 
Thanks for cheking in word, although I have (paid) and used in the recent past many clients modern versions  I dont use any version other than my trusty speedy portable 97 copy. 😃

**Comment by motianya211314** [comment]
@SumatraPeter SumatraPDF 3.1.2 x64  Word 2016 and word 2019 save as pdf.
![SumatraPDF](https://user-images.githubusercontent.com/15711438/70764621-09cc3f80-1d93-11ea-90b1-30be9bd47630.png)
[test.docx](https://github.com/sumatrapdfreader/sumatrapdf/files/3958718/test.docx)
[test.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/3958719/test.pdf)

**Comment by kjk** [comment]
This was an imperfect auto-detection of links in PDF content. I tweaked it so this should be fixed. In an hour or so the build at https://www.sumatrapdfreader.org/dailybuilds.html should contain the fix.

**Comment by motianya211314** [comment]
@kjk okey thanks.

**Comment by GitHubRulesOK** [comment]
![image](https://user-images.githubusercontent.com/12754913/70765705-7293c780-1d53-11ea-817e-2749cba18be1.png)

**Comment by SumatraPeter** [comment]
@GitHubRulesOK: As I understand it, the problem's not one of spacing but that Sumatra was not considering 0xff0c (comma) as a URL terminator. So it was indeed a minor bug in Sumatra after all that is now fixed.
