### ISSUE TITLE
11641 unexpected seperate file locations (regression?)

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1326]
@kjk 
between the recent directory changes I (possibly wrongly) expected all related installed files to be in the one directory (similar to a portable copy) as per Question about latest installer #1287

in last build downloading symbols go to appdata\roaming whilst install dir is by default in appdata\local
is that seperation by design or a regression ?

**Comment by kjk** [comment]
Good catch, thanks.

The expected behavior is:
* in portable mode, download to the same directory where `SumatraPDF.exe` is
* when installed, download to `%LOCALAPPDATA%/SumatraPDF/crashinfo`. This is the same directory as used during crash reporting process and 

The reason to write to `%LOCALAPPDATA%/SumatraPDF` and not installation directory is that directories like `c:\Program File` cannot be written to unless process is elevated. Installer is elevated but the app is not. This is also default installation directory.
