### ISSUE TITLE
Print problem: Print to file did not work

### ISSUE THREAD

**Issue by Leadrive** [sumatrapdfreader/sumatrapdf#1330]
On the print dialog, if select the "Print to file" option, sumatrapdf does not create a PRN file.
It will print to printer direct.

Such as in Office, if you select "Print to file" option on the print dialog, WORD will ask you provide a PRN file name, will create a PRN file, and does not print to printer.

**Comment by GitHubRulesOK** [comment]
Since version 3.0 SumatraPDF does not use conventional printer file system but sends as bitmap to device (which as this issue illustrates does not alow us to easily capture output for in / out anaylsis)

If you need to capture AsImage.prn or Printer.prn you will need to use version 3.0 standalone from Zip file: SumatraPDF-3.0.zip from https://www.sumatrapdfreader.org/download-prev.html
