### ISSUE TITLE
Bookmark errors in recent pre-release versions

### ISSUE THREAD

**Issue by alaurene** [sumatrapdfreader/sumatrapdf#1400]
Copy of post from Sumatra Forum:

_(galileo)

Bookmarks in recent pre-release builds of SumatraPDF are not functioning correctly. The bookmark for the first page (i.e. the first bookmark) is missing and the bookmarks for the last 2 pages are going to the same page. I have created bookmarks in PDF-Exchange Editor and verified that they are functioning correctly in earlier versions of Sumatra and in MS Edge._

I have attached a PDF that was created in PDF-Exchange Editor.  This particular PDF has a slightly different error than the one mentioned in my original forum post.  The bookmarks in this document  render correctly in Sumatra v3.211131 64-bit and in PDF-Exchange Editor.  

However, in Sumatra v3.2.11951 64-bit, there is an error that shows up between the bookmarks for page 5 and page 6 or between page 6 and page 7.  The bookmark for page 5 renders the correct page but, the bookmark for page 6 actually shows page 7 - or - the bookmark for page 6 actually show page 7 - depending on the setting for "Fit a Single Page" versus "Fit Width and Show Pages Continuously".

It appears that the "View" settings are the root cause of the issue...???

I hope this will help in diagnosing this issue.

Regards,
alaurene

[Sumatra PDF Bookmarks Issue.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4046548/Sumatra.PDF.Bookmarks.Issue.pdf)

**Comment by GitHubRulesOK** [comment]
@kjk I guess you will note this is the same problem I encountered with https://github.com/sumatrapdfreader/sumatrapdf/issues/1385 the editor is at fault by setting the bookmark to end of page 6 so in "page only" mode then it behaves as expected but in continuous it also works correctly but  "UN" expectedly by the user
![image](https://user-images.githubusercontent.com/12754913/72195123-d79d1480-3408-11ea-80ed-06b67a63403b.png)

Acrobat behaves differently since it's a "continuous single page" so goes to top of page 6 **ignoring the destination** on page 6 then next bookmark is top of page 7 etc.

**Comment by kjk** [comment]
@GitHubRulesOK Good catch. I thought it might be Sumatra's heuristic in continuous mode.

@alaurene as you can see the bookmark for page 6 tells Sumatra to go to the end of the page and that's what it does. Sumatra works as expected.

**Comment by GitHubRulesOK** [comment]
@kjk [feature request]
The desire /need for a user to over-ride faulty or undesired bookmarks or for that matter simply add their own preferences. Is one of the several cases where a simple editable alternate .bkm proves exceptionally useful, and the main reason I sugest that a one on one approach to a pathless (i.e. relative filename.bkm) usage would be a boon.
Adding such entries to .vkbm in many cases would result in temporary edits requiring frequent addition and removal as each document is moved added or discarded
