### ISSUE TITLE
Problem with spaces if UseFixedPageUI = true

### ISSUE THREAD

**Issue by dawarec** [sumatrapdfreader/sumatrapdf#1446]
UseFixedPageUI = true
![1](https://user-images.githubusercontent.com/60568242/73606714-00eb3380-45b6-11ea-9dda-01eeede62fdf.png)
UseFixedPageUI = false
![2](https://user-images.githubusercontent.com/60568242/73606719-0fd1e600-45b6-11ea-8299-2455da69757a.png)
In Notepad++, no weird characters.
![3](https://user-images.githubusercontent.com/60568242/73606750-4e67a080-45b6-11ea-8ba4-82d385c6dd59.png)

File
[fb2.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4143805/fb2.zip)
Same goes to .epub and .mobi.
In general all spaces much wider in = true, layout feel broken.

**Comment by GitHubRulesOK** [comment]
Technically there is no issue other than is the font size easily varied ?

The root problem is not the difference between UI since we can see on the left screen grabs below that both display the same result when text is "reflowed" and "justified" when a line contains sequential long words.

![image](https://user-images.githubusercontent.com/12754913/73651204-db286200-467b-11ea-97e2-97bde05e8ea9.png)

On the upper right we can see that if we were to use the MuPDF default layout the result would be much more reasonable this is due to using a smaller font size.
In the bottom right I have changed the SumatraPDF font setting to 

```
EbookUI [
	FontName = Georgia
	FontSize = 11
	TextC.......
```

And then the result is similar

@kjk 
I am tagging this "ebook" issue as needing review during improvements, however I am closing it as "working per design"
