### ISSUE TITLE
page number can't be read if pages are black in mobi mode

### ISSUE THREAD

**Issue by KoleckOLP** [sumatrapdfreader/sumatrapdf#1476]
If I set my page background color to #000000 Black
my text color to #EEEEEE (or any color that is no black)
text can be read but but page number can not. (I think it's hardcoded black, could not find a way to change it, even in the source code.)

**Comment by GitHubRulesOK** [comment]
It always helps to provide screenshot.png 
![image](https://user-images.githubusercontent.com/12754913/75589324-5fe77f80-5a72-11ea-89ee-1202377a971d.png)

@kjk 
this is not possible in current pre-release since the following EbookUI settings appear not to be active ?
TextColor = #
BackgroundColor = #
