### ISSUE TITLE
Changing bookmark order causes crash

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1481]
[reorder-bookmarks.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4271915/reorder-bookmarks.zip)
Granted the sample files are certainly not good test files nor good examples of larger real world files however are handy to test potential fault conditions arising.
Avoiding nesting added a third file (actually a renamed dupe of first) then after attempting to change bookmark order .vbkm becomes unstable.

**Comment by kjk** [comment]
I think the issue here is that I'm trying to remove pages from the PDF based on which toc items are checked / unchecked. This is a heuristic which seems to be wrong (I think I'm not re-numbering pages after those that are removed).

Either need to fix the heuristic or remove that completely. If needed, a different way of removing pages can be implemented that is more explicit.

**Comment by kjk** [comment]
This particular crash should be fixed.

**Comment by GitHubRulesOK** [comment]
@kjk 
Currently, (Last couple of updates today ) not seeing any options to rebuild .vbkm when right clicking the bookmarks pane and selecting old ones causes problems

**Comment by kjk** [comment]
Strange. Looking into it.

**Comment by GitHubRulesOK** [comment]
New bookmarks is back in 12265 ?

**Comment by kjk** [comment]
Indeed, is back.
