### ISSUE TITLE
Prompt to confirm to save unsaved highlights before closing

### ISSUE THREAD

**Issue by WangYihang** [sumatrapdfreader/sumatrapdf#1499]
In order to save highlight, the user must right-click on the main panel, then click "save annotations".
But if the user clicks the close button uncarefully, all annotations will be lost.
So I'd like to request the new feature that popup a prompt dialog to ask the user to confirm.
Thank you guys to develop such an amazing pdf reader! Thank you so much!

**Comment by GitHubRulesOK** [comment]
Annotations should not be "lost" when you intentionally save them rather than just use them temporarily, the work flow sequence should be to "Fail Safe".

1) I always recommend when you work with annotations ONLY work on a copy of your master document, then if you accidentally select `save annotations` and `save as` then the master file will **not** be altered unless you deliberately respond yes to the prompt to overwrite the master

2) I always recommend that if you _must_ work with single files then change the default of `SaveIntoDocument = true` to = false (Then any changes are saved into the smx file rather than the master document.) If you want to finally flush the smx into the pdf then at that time you will need to deliberately change = false back to = true and `save as` the new annotated file for users that dont use SumatraPDF

**Comment by WangYihang** [comment]
Thank you for the quick reply, actually, I am the user who always wants to save annotations into .smx file in case of contaminating the original pdf file.
But something user will forget to right-click and save annotations before closing pdf reader, so the annotations will be unintended lost.

**Comment by WangYihang** [comment]
So it would be great if there is a prompt dialog asking the user 'If you want to save all unsaved annotations into a separated .smx file?' before closing.
Or asking the user 'where would you like to save the unsaved annotations? (.smx file/save to document)'

**Comment by GitHubRulesOK** [comment]
The prime requirement has always been to use "Save As" there is no need to ask if you wish to save either you designated smx or not via the settings choice.
The user request that instigated "save annotations" as you work was the REQUEST **NOT TO interrupt** auto saving by asking !
The context and main saving can be done by a 3rd part program in the background without interjection using those shortcuts.

**Comment by GitHubRulesOK** [comment]
@kjk 
new annotations required different methodology, so I guess this becomes a redundant issue ?

**Comment by GitHubRulesOK** [comment]
Warning on closure has now been added
![image](https://user-images.githubusercontent.com/12754913/87046111-a4d5ac80-c1f0-11ea-9098-9372714f2ea8.png)
