### ISSUE TITLE
Relative Links no Longer Can be Opened In Sumatra 3.2

### ISSUE THREAD

**Issue by sahil48** [sumatrapdfreader/sumatrapdf#1506]
When opening a relative path, a "file:\" string is inserted between the directory the file is in and the relative path, preventing the documents linked in a pdf from being opened. This behavior is different from previous versions. Please fix it.

As requested, sample files are below:

[Sumatra Bug Sample - Relative Links.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4362900/Sumatra.Bug.Sample.-.Relative.Links.zip)
![image](https://user-images.githubusercontent.com/6100774/77103753-4db58d00-69f1-11ea-9550-109cd18b17ce.png)

**Comment by GitHubRulesOK** [comment]
Please provide relative file samples with that type of link for testing 
You can post them into the initial report by clicking ... top right of your comment and selecting edit

**Comment by GitHubRulesOK** [comment]
@sahil48 
Thanks for the sample

@kjk Whilst that link structure will not open in my restricted Acrobat version 9, nor will it work in MuPDF-GL
In other viewers it throws a security message to permit running the default handler on 
file:///C:/current location of sample/Sumatra%20Bug%20Sample%20-%20Relative%20Links/Documents/Procedures/13428-SENSOR_BRACKET_ASSEMBLY.pdf

However it did in SumatraPDF 3.1.2 and it still works without warning in new MS Edge

**Comment by GitHubRulesOK** [comment]
@kjk 
In general I can get a relative file to open by using slightly different (unusual) relative syntax
The sample above is slightly wrong in my editor as it shows up as a WWW link rather than local file
but notwithstanding that I would normally expect to simply add ./ for a relative sibling folder

HOWEVER to get it to work I am having to specify //../ i.e an other child of our common parent
[SampleLocal.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4815564/SampleLocal.pdf)

**Comment by sahil48** [comment]
Thank you so much for fixing this! I can finally upgrade to the latest version. Great job! 😄
