### ISSUE TITLE
Save the document images * .jpg

### ISSUE THREAD

**Issue by vdancev** [sumatrapdfreader/sumatrapdf#155]
Please export the document in the image \* .jpg

**Comment by GitHubRulesOK** [comment]
@kjk depends how you interpret this feature request. If the intent is to copy a single image or page as Jpg that was / is always possible using copy selection. If the intent is to export all pages as seperate jpg's that is a feature usually applied in conversion or editor "page busting" applications and can be very simply achived with command driven 3rd party tools.

**Comment by GitHubRulesOK** [comment]
Closingg as duplicated by wider request in https://github.com/sumatrapdfreader/sumatrapdf/issues/687

**Comment by GitHubRulesOK** [comment]
I have published my SumatraPDF Addin script that exports different file types as selectable quality PNG (rather than as inferior lossy JPG) but once extracted, either as a single page or a range of pages, they can easily be converted by any other imaging tool.
For more details see
 https://forum.sumatrapdfreader.org/t/export-save-page-s-as-jpg-png-picture-s-image-s/1030/11

**Comment by GitHubRulesOK** [comment]
for most recent developments see https://github.com/sumatrapdfreader/sumatrapdf/issues/542#issuecomment-4151605343
