### ISSUE TITLE
any way to hide the application icon in the left up corner?

### ISSUE THREAD

**Issue by redstoneleo** [sumatrapdfreader/sumatrapdf#1568]
![image](https://user-images.githubusercontent.com/5896180/80096510-43f8e980-859c-11ea-8c83-38b8e5824508.png)
I think it is useless and redundant , so want to hide it, any way to hide the application icon in the left up corner?

**Comment by GitHubRulesOK** [comment]
It took ages to restore that ability/feature which was dropped/changed with the introduction of tabs mode,  It's restoration closed many requests to improve control  e.g. to drag window sideways, when using tabs.

It is the same application icon as seen in non-tab mode and similar to the  top left historic function in most windows applications  i.e. it is more useful than the one in Explorer, Notepad, Paint etc. since it is essential for tablet users.

Thus, I suspect in a poll to remove it again, most users would answer "don't care" then next would be "keep it" then finally "go back to previous problem behaviour"

**Comment by kjk** [comment]
No plans to do that.

**Comment by redstoneleo** [comment]
The layout of sumatrapdfreader is similar to Chrome, but Chrome doesn't put an icon in the left up corner, so I'd suggest that the developers should ponder how much value of the icon.

**Comment by SumatraPeter** [comment]
@redstoneleo: Look, personally I do agree that the icon is a waste of titlebar space that can be better used for tabs, and was perfectly fine with Sumatra not having one from 3.0 to 3.1.2. However we've already discussed this, _a lot_ (pull request is [here](https://github.com/sumatrapdfreader/sumatrapdf/pull/1410), and you can check out the 4 linked issues), and the upshot of it all is that the app now has a system icon that supports window dragging as well. End of story.

**Comment by GitHubRulesOK** [comment]
![image](https://user-images.githubusercontent.com/12754913/229372583-b4ba3788-1f01-41aa-86c7-fc6f4d43715c.png)
