### ISSUE TITLE
Bookmark auto expands and cannot collapse it all

### ISSUE THREAD

**Issue by JimWood-KXS** [sumatrapdfreader/sumatrapdf#1570]
I just upgraded to v3.2 64 bit.  I found that when I navigated to the middle of a bookmark level the bookmarks auto expanded, which in my case gives a huge list.  I had been used to having to manually expand the levels as needed.
The good part of this is the bookmarks were never grayed past level 1 and now they seem to be grayed for the level you are on.  This comes at the cost of expanding the levels, which is bad.  Not only that, Shift / no longer collapses everything.

What would be good is to have the user do the expanding but gray the bookmark to wherever you are regardless of level.

Another change is the tabs at the top for documents are washed out and hard to see.

I've been using Sumatra for a long time because it is clean and fast.  Appreciate the work of the people who built and maintain it.

**Comment by GitHubRulesOK** [comment]
The underlying control structure has changed a lot over the four years from 3.1.2 to 3.2
on your second point Tab colours/contrast is covered by https://github.com/sumatrapdfreader/sumatrapdf/issues/559 & https://github.com/sumatrapdfreader/sumatrapdf/issues/898 so I will count this as an issue about autoexpanding bookmarks.

Due to the many different uses for the "bookmarks" pane a lot of work has been going on in that area and the aim has been to try and keep it to one common control, thus it is now driven by controls more akin to other applications
Expand and shrink ALL are now usually available via right click.
The Right and Left arrow keys should expand and contract focus levels
also when focused + and - should also expand and contract
other keys such as home and end will also act accordingly

The use of all those enhanced controls does require  using F6 (if using a keyboard) otherwise  the mouse can expand and contract levels by say "collapse all" then hitting the arrow head for the section of interest or a page change will then just open the required section
![image](https://user-images.githubusercontent.com/12754913/80203605-536d4680-861f-11ea-9982-f8cfd842c42a.png)

**Comment by GitHubRulesOK** [comment]
@kjk 
generally the bookmark tree control is behaving (in some ways possibly better) like an automatic acrobat "expand current bookmark" feature.

However, other apps normally don't automatically open all branches (which arguably does help in some cases, but can become an annoyance when nested sections between two points of interest in a 1273 page document are expanded)

Is there any way to toggle bookmark auto expansion to NOT follow sidebar scrolling?

**Comment by Mike3p** [comment]
I would really like such an option too. The auto expansion is so annoying that I chose to stay at version 3.1, since it makes it really uncomfortable to navigate documents with a huge bookmark tree-structure in a non-linear way.

**Comment by GitHubRulesOK** [comment]
@Mike3p 
Whilst I agree its anoying I will stay at version 3.2 for all the extra benefits (I use the pre-release)
To reduce the effect you can fairly easily right click "collapse all" 
and pick up from the next expanded set

**Comment by Mike3p** [comment]
I know, but then I can't leave the tree in an expanded state I find suitable to navigate the document. I'm just saying that for me it is a fairly huge detriment to the usability of Sumatra PDF.

**Comment by jbusnengo** [comment]
> 
> 
> I know, but then I can't leave the tree in an expanded state I find suitable to navigate the document. I'm just saying that for me it is a fairly huge detriment to the usability of Sumatra PDF.

I'd like to echo this. While I'd prefer to use the newest version of the software, this is a significant enough issue for me that I find the 3.2 versions to be unusable.

**Comment by GitHubRulesOK** [comment]
Behaviour in latest pre-release version allows for collapsing ALL and no longer auto expands (it does auto follow) but allows user expand collapse. Also remembers location compared to expanded state.
![image](https://user-images.githubusercontent.com/12754913/126019688-ab65ac6f-1073-4a34-9975-099e51219c67.png)
