### ISSUE TITLE
Full hyperlink URL does not appear on mouse over in PDF (in tooltip or status bar)

### ISSUE THREAD

**Issue by avm19** [sumatrapdfreader/sumatrapdf#1572]
__Expected behaviour__: full URL is shown in a tooltip when mouse cursor is held over a working hyperlink.
__Observed behaviour__: mouse cursor changes to a pointing hand, but the tooltip does not appear.

I believe this feature was present in the version I had before the update to 3.2, so it more of a bug fix than a feature request.
Windows 10, v3.2 64-bit git commit fc8f35a

**Comment by GitHubRulesOK** [comment]
Tooltips are generally fixed see https://www.sumatrapdfreader.org/docs/Version-3.2.1.html

Please check your requirement against current pre-release (not version 3.2) here it is working **fine** showing me the old absolute http (not https) address is stored in this virtual PDF (darn another thing to check  !!)

![image](https://user-images.githubusercontent.com/12754913/80278201-48ccb300-86ec-11ea-8a35-283329d69882.png)

However, relative URLs are currently an open issue.

**Comment by GitHubRulesOK** [comment]
@kjk 
on checking the way the URL is presented the issue I noted in my test above of vbkm showing old http rather than https is the same in acrobat thus was embedded in the PDF which means the problem stems from the website not providing the https prefix.

**Comment by SumatraPeter** [comment]
@GitHubRulesOK: Yup, on the Docs page the very first "SumatraPDF", "latest stable release" and "pre-release builds" links all need to be updated to https.

**Comment by GitHubRulesOK** [comment]
@SumatraPeter its more than that the web site
@kjk 
My observation was that SumatraPDF appears to default to http  rather than https when  a hyperlink simply starts www, unsure how that should be handled (may need an extra option ?)

**Comment by SumatraPeter** [comment]
> SumatraPDF appears to default to http rather than https when a pdf hyperlink simply starts www, unsure how that should be handled

I've seen a whole range of site behavior. Specifying http for a site that _does_ support https may result in the site either auto-redirecting to https, or not auto-redirecting and staying on the http version. Similarly, specifying https for a site that _does not_ support https may result in the site either auto-redirecting to http, or not auto-redirecting and failing to open the site.

All things considered, from a security standpoint and since all major browsers have been pushing for https to be universal, I'd rather have Sumatra defaulting to https for incomplete/ambiguous links.

**Comment by GitHubRulesOK** [comment]
@SumatraPeter 
It's that point you raised that forcing http to https may fail that prompted my query should an option to **"not over-ride legacy http"** might be needed in a few rare cases.

**Comment by SumatraPeter** [comment]
@GitHubRulesOK: I understand, but how would such an option possibly work? If it's in the settings file then it'll apply to _all_ files, which doesn't seem like a good idea. A per-file setting would be better, but still not perfect because theoretically the same file can have multiple ambiguous links, some of which may work with https and some without.

So to simplify matters perhaps Sumatra can just choose either http or https as the default and forget about the rest. Perhaps display a warning tooltip when the link is clicked and let the user deal with any subsequent http(s)-related problems that might arise...

**Comment by GoblinLegislator** [comment]
I am sorry, but can anybody help? When I hover cursor over link in SumatraPDF 3.2 64-bit I don't see any popup or status bar or tooltip saying which link it is gonna open when I click. When I click link it works. How to know where links are leading to? I am using default settings.

**Comment by GitHubRulesOK** [comment]
@GoblinLegislator 
That was a known problem with 3.2 you would need to either use 3.1.2 of current pre-release until next formal release.
