### ISSUE TITLE
Crash in delay loading of libmupdf

### ISSUE THREAD

**Issue by rmfauzi** [sumatrapdfreader/sumatrapdf#1573]
I just update Sumatra PDF to version 3.3.12511.  When I close the app, the error dialogue appears that brought up the crash report website.
1. The error dialogue appears when I click the close button for either the app or the tab, choose exit from the menu, or press Alt+F4.
2. If I have multiple tabs open, all the tab will be forcefully closed.
3. I can reproduce the error every time I do the above-mentioned action.

Link to the gist:
https://gist.github.com/rmfauzi/8924a1f0170eded3281915d80447063d

**Comment by kjk** [comment]
The important part:
```
00007FFC69A9A799 01:0000000000039799 kernelbase.dll!RaiseException+0x69
00007FF76C21A0EF 01:00000000002390EF sumatrapdf.exe!__delayLoadHelper2+0x27b d:\agent\_work\4\s\src\vctools\delayimp\delayhlp.cpp+375
00007FF76C1EB40D 01:000000000020A40D sumatrapdf.exe!_tailMerge_libmupdf_dll+0x3f
00007FF76C16D726 01:000000000018C726 sumatrapdf.exe!EnginePdf::~EnginePdf+0x106 D:\a\sumatrapdf\sumatrapdf\src\EnginePdf.cpp+455
00007FF76C16D5F4 01:000000000018C5F4 sumatrapdf.exe!EnginePdf::`scalar deleting destructor'+0x14
00007FF76C0B08DD 01:00000000000CF8DD sumatrapdf.exe!DisplayModel::`scalar deleting destructor'+0xbd
00007FF76C1015FD 01:00000000001205FD sumatrapdf.exe!TabInfo::~TabInfo+0x10d D:\a\sumatrapdf\sumatrapdf\src\TabInfo.cpp+43
00007FF76C1072C7 01:00000000001262C7 sumatrapdf.exe!DeleteVecMembers<TabInfo *>+0x37 D:\a\sumatrapdf\sumatrapdf\src\utils\Vec.h+356
00007FF76C0F13B9 01:00000000001103B9 sumatrapdf.exe!CloseWindow+0x299 D:\a\sumatrapdf\sumatrapdf\src\SumatraPDF.cpp+2318
00007FF76C0F96D4 01:00000000001186D4 sumatrapdf.exe!WndProcFrame+0x3b4 D:\a\sumatrapdf\sumatrapdf\src\SumatraPDF.cpp+4778
```

The code related to delay (un)loading libmupdf.dll tries to throw an exception but crashes in `RaiseException`?.

No idea why this would happen.

**Comment by GitHubRulesOK** [comment]
@rmfauzi 
Can you please confirm if the above crash is repeatable in a current pre-release

@kjk
there are still one or two of these odd crash reports that may need to be snoozed as "presumed" closed without frequent confirmation or futher feedback, I have no idea which ones may now be historic as a result of fixes.

**Comment by kjk** [comment]
Maybe relevant: this seems to be a file in OneDrive. Also, there's some injected dll groupy_64.dll which might be messing things up.

**Comment by kjk** [comment]
This is a crash caused by delay loading. It looks like trying to locate a function in libmupdf.dll, failing and crashing because of that.

But if we rendered a PDF, then libmupdf must have been there.

So my only theory is that update failed partially and you have a new version of SumatraPDF.exe and old version of libmupdf, new SumatraPDF is trying to call a function that only exists in new libmupdf and crashes, because it's not in the old libmupdf.

So my recommendation is to re-install Sumatra.

How could installer fail in such way? They only thing I can think of is if libmupdf couldn't be over-written (e.g. it was used by another process, like pdf search plugin or has weird permissions). I think we try to detect it in the installer but it might happen as a race condition.

I have to audit the installer to see if I can make it more robust.

**Comment by kjk** [comment]
I think I've added protection against that.
