### ISSUE TITLE
Application freezes if you scroll in the title bar

### ISSUE THREAD

**Issue by sw9** [sumatrapdfreader/sumatrapdf#158]
I've experienced this problem on both windows 7 and windows 8.1. Move your mouse to the titlebar and scroll. The application will freeze and require a restart to become responsive again.

**Comment by kjk** [comment]
I've never encountered this problem and without a way to trigger it for debugging, there's nothing I can do about it.

It's also most likely caused by a specific version of your hardware/driver (mouse etc.).
I've never encountered this problem and without a way to trigger it for debugging, there's nothing I can do about it.

It's also most likely caused by a specific version of your hardware (mouse etc.) and a buggy driver.

Unless you can provide more information e.g. attach a debugger and provide a callstack of all threads when this happens, there's nothing I can do to investigate further.
