### ISSUE TITLE
dark interface

### ISSUE THREAD

**Issue by jonbar12** [sumatrapdfreader/sumatrapdf#1580]
would there be some way to put a dark theme for the interface for example like the image? (it is an image modified with photoshop)

![Captura1](https://user-images.githubusercontent.com/39640819/81626149-dc7ad080-93c8-11ea-9232-9b766bb6f8f7.png)

**Comment by GitHubRulesOK** [comment]
The scrollbar and tabs have constantly been asked to have change colors

changing the foreground/background colour of tabs was not easy (temporarily abandoned) and there  are still open requests to better themes

for the scrollbar on the right and approx a dozen other colour placements in the interface those are down to windows themes so using windows System colour control settings you can change them see
background color changes by color of BackgroundColor #1555 and 
![image](https://user-images.githubusercontent.com/12754913/79383182-acbce200-7f5c-11ea-89ee-3cdbc39316f8.png)

Since the main request is duplicated by many other problem issues I am closing as multiple interface items are duplicated by theming # 559 #743 #745  # 778 #898 #1275 and many others
