### ISSUE TITLE
Closing window in tabbed mode by double-clicking menu button

### ISSUE THREAD

**Issue by DuMOHsmol** [sumatrapdfreader/sumatrapdf#162]
Hello, everyone!

I've got a small feature request about adding an option to close main window with double click on menu button. Most programs have an icon in top left corner and they can be closed by double clicking that icon. It's a little-known, but very convenient feature -- you can close windows using both sides of their titles. But SumatraPDF has a menu button there and when I try to close its window from left side of the title, I just open and close menu. That's not a big issue, but just is a little confusing.

Thank you for your attention :)

**Comment by DerpMcDerp** [comment]
Right clicking on that button should display a "Restore | Move | Size | Minimize | Maximize | Close" popup.

**Comment by rottweiller76** [comment]
hey, this is a very nice thing that is missing :( i always close the programs with double clock top left 

as you can see in the picture the option to close is very very hidden when compared to almost all other programs which react at double click with - instant close / alt F4 
or with single they open the close option directly not hidden in other menu

![double click top left](https://cloud.githubusercontent.com/assets/12532841/7731895/6e1c9d66-ff2c-11e4-8e98-506223a98157.jpg) 

please make this happen, i love the program and this is the only issue i have with it :) 

ps. i made this account just to add this comment

**Comment by Chungalin** [comment]
I was coming to fill in a bug, but since this is the same I was about to report, I just second this proposal.

This is a general usability issue in Windows. Any program that uses standard windows API allows to be closed with a double click on window icon. I find very annoying when a program customizes title bar in a cool way but forgets to support all standard functionality.

Also, it’s about two lines of code!

Please consider it.

**Comment by petrasteri** [comment]
In my opinion, it might not be a good idea to make "double-click on menu button = close window", or the interval to accept this behaviour has to be very short.

People would hate it because simple mistake clicking on menu button and close it = closing window!

On the other hand, putting menu button on the left is rare in desktop app.  Other modern software without menu bar like Firefox, Google Chrome, have the menu button on the right.  Examples of menu button on the left I can find are Calculator (provided in Win10), JavaScript Studio (downloadable from Store) and some other "tiled" apps provided in Win10.  In none of them, double-click on menu button would close the window.

**Comment by rottweiller76** [comment]
97% of windows apps have that double click close there:) 

    On Tuesday, August 22, 2017 12:26 PM, 石庭豐 <notifications@github.com> wrote:
 

 In my opinion, it might not be a good idea to make "double-click on menu button = close window", or the interval to accept this behaviour has to be very short.People would hate it because simple mistake clicking on menu button and close it = closing window!On the other hand, putting menu button on the left is rare in desktop app. Other modern software without menu bar like Firefox, Google Chrome, have the menu button on the right. Examples of menu button on the left I can find are Calculator (provided in Win10), JavaScript Studio (downloadable from Store) and some other "tiled" apps provided in Win10. In none of them, double-click on menu button would close the window.—

**Comment by petrasteri** [comment]
Don't get me wrong.  I also use this double-click to close windows.

But well, this method was introduced more than twenty years ago, when every window must have a **title bar and an icon on the left**.  And those 97% or whatever percentage of apps you're talking about have this.

But things changed.  And things can get incompatible.  And it's the case here.  In place of the icon, we have the menu button at the same position.

If you really want to have double-click-is-close behaviour, you have to go to Settings > Options > Disable "Use tabs"

We all want to keep things the old way.  But we must also forge our own path and go for the new way.  The past is in the past.  So maybe it's time to let it go!

https://youtu.be/L0MK7qz13bU?t=1m4s

;)

**Comment by rottweiller76** [comment]
after they "let it go" and we got no start button, no start menu - i say "let`s keep it if it works perfectly" :) 
any other option can also be done, and this can be kept hidden for old people that remember it  

    On Monday, September 4, 2017 12:37 AM, 石庭豐 <notifications@github.com> wrote:
 

 Don't get me wrong. I also use this double-click to close windows.But well, this method was introduced more than twenty years ago, when every window must have a title bar and an icon on the left. And those 97% or whatever percentage of apps you're talking about have this.But things changed. And things can get incompatible. And it's the case here. In place of the icon, we have the menu button at the same position.If you really want to have double-click-is-close behaviour, you have to go to Settings > Options > Disable "Use tabs"We all want to keep things the old way. But we must also forge our own path and go for the new way. The past is in the past. So maybe it's time to let it go!https://youtu.be/L0MK7qz13bU?t=1m4s;)—

**Comment by amurzeau** [comment]
Hi,
I also use that feature because the mouse is usually on the left side of the screen when reading left to right.
What about an option to enable "double click on menu button = close" while still keeping tabs ?

**Comment by kjk** [comment]
Should be fixed with @amurzeau code

**Comment by rottweiller76** [comment]
thank you very much :)
