### ISSUE TITLE
How to print to Microsoft Print to PDF with specific file name?

### ISSUE THREAD

**Issue by elasticondo** [sumatrapdfreader/sumatrapdf#1623]
I currently print like

```bash
SumatraPDF.exe -print-to "Microsoft Print to PDF" -print-settings "11" test.pdf
```

This will print the 11th page of `test.pdf` to the Microsoft PDF Printer. Is it possible to also send it a filename, so that I can directly save it to something like `example.pdf`?

```bash
SumatraPDF.exe -print-to "Microsoft Print to PDF" -output example.pdf -print-settings "11" test.pdf
```

I did not find any hints within the [command line documentation](https://www.sumatrapdfreader.org/docs/Command-line-arguments.html)

**Comment by GitHubRulesOK** [comment]
Microsoft often dont include hi end features in their baseline products since it would deter developers producing competitive products, and MS Print to PDF or XPS are thus feature challenged.
What you are requesting is an Editor function to Extract or "split a copy" of the source PDF
There are many ways to extract page 11 into example.pdf either by passing the page to a CLI app or a different virtual printer that alows splitting pages. my prefered goto in this case might be cpdf as described in https://forum.sumatrapdfreader.org/t/split-merge-pdfs-using-sumatra/1696

**Comment by GitHubRulesOK** [comment]
@kjk 
I am closing this issue based on the following assumptions.
Since "printing" was always intended as a means to send output to a device, and although some print drivers do allow for saving to sequential or named spool files, the extraction of document pages to files is generically an "editor" function thus considered outside of a normal viewer apps remit.

**Comment by GitHubRulesOK** [comment]
@elasticondo 
I did like not answering the question directly so your command
`SumatraPDF.exe -print-to "Microsoft Print to PDF" -print-settings "11" test.pdf` will save to a file example.pdf in a preset folder e.g. I specified c:\test\example.pdf as the output port for "Microsoft Print to PDF", actually I used "Microsoft Print to PDF (copy 1)" so as not to break my default print to PORTPROMPT
![image](https://user-images.githubusercontent.com/12754913/84721378-6eea3300-af78-11ea-837e-169489478b0d.png)

**So it is a posibility with Microsoft Driver, However** since you then need to scoop that file before it gets overwritten by the next print I suggest it is much easier to use a dedicated driver, so look at several products such as PDfill
![image](https://user-images.githubusercontent.com/12754913/84721797-62b2a580-af79-11ea-938a-a814e732f187.png)

**Comment by elasticondo** [comment]
Thanks for the recommendation! `cpdf` was not on the list I found, but perfect for my usecase!
