### ISSUE TITLE
"Alt hotkeys" don't work on Russian keyboard layout

### ISSUE THREAD

**Issue by helperman** [sumatrapdfreader/sumatrapdf#1644]
Alt hotkeys work on English keyboard layout but don't work on Russian keyboard layout.
I suspect other keyboard layouts are also impacted.

Steps to reproduce:
- prepare russian keyboard layout in Windows
- open any pdf
- switch to English layout and press Alt + F + F to launch a feature "File -> Show in folder"
- everything OK - the folder with a document is opened
- swithc to Russian layout and press Afl + F + F again

Expected: the folder with a document is opened
Actual: nothing happens

To overcome it you may use virtual codes that are the same for two keys in Russian and English keyboards (virtual code of English symbol F equals virtual code of Russian symbol А).

**Comment by kjk** [comment]
As far as I can tell, this works as designed. On russian keyboard pressing key 'f' generates letter 'a'.
Those shortcuts are not even handled by Sumatra but by Windows, as those are derived from menu items.
Alt+F actives "&File" menu, because "F" is the hotkey. So it shouldn't be activated by 'a'.

If you use Russian keyboard you should also use Russian translation, which would be "&Файл" / "Показать в п&апке" with hotkey of Alt + Ф + п.
