### ISSUE TITLE
Remove Inexistent Files From "Frequently Read"

### ISSUE THREAD

**Issue by AndhikaWB** [sumatrapdfreader/sumatrapdf#1654]
If a file is already deleted, do not show it on "Frequently Read". On the current version (3.2), deleted file is still shown, resulting blank preview and taking unecessary space on "Frequently Read".

**Comment by GitHubRulesOK** [comment]
related to https://github.com/sumatrapdfreader/sumatrapdf/issues/166

**Comment by SumatraPeter** [comment]
The problem is, what if some of these supposedly 'deleted' files actually reside on external or network drives that are temporarily unavailable? Users might get irritated if they make the drives accessible again but in the meantime Sumatra without asking has removed files from the Frequently Read screen.

I suppose Sumatra could possibly remove deleted files that resided on local drives only, or remove files that have been consecutively inaccessible during the last 'n' program launches, but honestly it all seems like overkill to me when the user can simply get rid of the entries manually.

**Comment by AndhikaWB** [comment]
Hmm.. maybe you're right, never thought that external drive situation.
