### ISSUE TITLE
Holding middle mouse button down

### ISSUE THREAD

**Issue by bdsdf** [sumatrapdfreader/sumatrapdf#167]
In chrome and adobe, holding down middle mouse behaves differently and I think it is much more useful.

**Comment by kjk** [comment]
How does it behave and how is it different from Sumatra?

**Comment by bdsdf** [comment]
When you hold it down, it scrolls faster and when you let it go, it exits that mode. I'm not articulate enough to explain it properly to be honest.

**Comment by GitHubRulesOK** [comment]
@kjk the variations of autoscroll are as you know down to different devices document types/layouts and page viewing modes

Here the description is to alter autoscroll function, which in a document reader such as SumatraPDF will depend on zoom, continuous (scrolling faster) or page limited by boundaries.
Whichever way you change it others will want the opposite. AFAIK it works perfectly well enough and can be altered from default via any drivers for the mouse or touchpad, even windows settings.

**Comment by GitHubRulesOK** [comment]
The description of different mouse actions is mainly due to the mouse down and mouse up behaviours

In SumatraPDF the behaviour is what I expect a down and up toggles a sticky scroll, so I can rest my fingers whilst the mouse does the auto scrolling.

In Acrobat 9 and Chromium Edge you have to keep the button depressed which becomes tiring. 

Any speed enhancement / acceleration due to holding it down longer in other apps is easily altered by changing any mouse driver settings. In SumatraPDF just let go and move it towards or away from  your start position, its much less strenuous.

Consolidating with related non linear middle button request  #557

**Comment by GitHubRulesOK** [comment]
For cross reference the above description sounds like windows emulation of a mac feature described in
Make the scrolling animation more flow and smooth #1083

**Comment by GitHubRulesOK** [comment]
@kjk reopened as there is a difference in behaviour as re-reported in forum
https://forum.sumatrapdfreader.org/t/is-there-a-way-to-make-the-middle-mouse-scroll-just-by-holding-it-instead-of-clicking-it/4514

In browsers (and possibly other apps) there are two distinct modes based on timing

Holding the middle button down temporarily enables auto scroll until released
Fast click without hold of middle button latches auto scroll on until another click unlatches that behaviour

SumatraPDF will only work as if latched on or off

**Comment by cpo-ux** [comment]
I'd like this behavior to be customizable since in other apps that I use for drafting I hold down the scroll button to pan so when I'm switching between apps, it gets confusing.  In my case, I'm using QCAD at the same time but there are other common programs that behave this way (AutoCAD I think is this way).

**Comment by GitHubRulesOK** [comment]
@cpo-ux 
you are spoilt by modern tech 🙂  In my early CADD days we either had to click 2 cheap mouse ears to get a third function
or sell an arm and a leg for a 15 button "pucker" mouse, big as a rat.

**Comment by GitHubRulesOK** [comment]
Closing as fixed per https://github.com/sumatrapdfreader/sumatrapdf/issues/4529
