### ISSUE TITLE
Unable to select the text well

### ISSUE THREAD

**Issue by hehancn** [sumatrapdfreader/sumatrapdf#1687]
When  I use the sumatrapdf to select almost every text in [this](https://github.com/hehancn/Test/raw/master/FourierAnalysis.pdf) pdf file,  I can not select it correctly, as shown in the following picture (dark background).

![image](https://user-images.githubusercontent.com/52968701/87438577-4cecda80-c622-11ea-939b-4db7d847f1ac.png)

But I can select the text correctly  in Adobe pdf or Microsoft edge ( (white background).

![image](https://user-images.githubusercontent.com/52968701/87438473-29c22b00-c622-11ea-991b-d6a256a333c3.png)

Needs your help.  Really thanks !

**Comment by GitHubRulesOK** [comment]
Ongoing improvements since it worked best in version 3.1.2 so you could use a portable 3.1.2 for copy

Current [daily](https://www.sumatrapdfreader.org/dailybuilds.html) will only add a line feed for large gaps e.g. between **`continuity. and This is`**
```
This observation suggests that the pointwise convergence of Fourier
series is intricate, and may even fail at points of continuity.
This is
indeed the case, as we will see in the next chapter.
```
![image](https://user-images.githubusercontent.com/12754913/87441679-47c06900-c5eb-11ea-92e9-d4bcd575b05f.png)

**Comment by hehancn** [comment]
I'm satisfied with  the version 3.1.2. Thank you very much for your help!

**Comment by GitHubRulesOK** [comment]
Closing as OP is happy with 3.1.2  and recent builds have, as shown above, have improved continuous selection, not yet perfect nor as good as 3.1.2. but other open issues cover worse cases.
