### ISSUE TITLE
Recent files from taskbar context menu won't open

### ISSUE THREAD

**Issue by weitzhandler** [sumatrapdfreader/sumatrapdf#1697]
Hi,

After opening a file and closing it, then clicking on the file in the app's taskbar icon context-menu, it says:

> The item you selected is unavailable. It may have been moved, renamed or removed. Do you want to remove it from the list?

![image](https://user-images.githubusercontent.com/2716316/87784707-7afb3600-c83f-11ea-9a8d-a37e5d20068f.png)

Here's what I'm clicking at:

![image](https://user-images.githubusercontent.com/2716316/87784829-b39b0f80-c83f-11ea-975e-fd401fc78c3a.png)

This also happens to other files.

Additionally, SumatraPDF doesn't launch with the recent files opened as it used, and `RestoreSession = true`.

Version 3.2 (via WinGet).

**Comment by GitHubRulesOK** [comment]
When updating the application (which I do several times somedays) it is best if windows does NOT keep old entries that worked in the past. they will fail the next day.

For a basic user, updating once in a blue moon, the same principle applies. shortcuts that worked for an older version of an app are not adjusted by windows to work with the new. the blank icon indicates to me that shortcut is not going to be fired up correctly. But that is Windows Not SumatraPDF

here mine will correctly be opened by edge.
![image](https://user-images.githubusercontent.com/12754913/87789447-fc01ff80-c836-11ea-8603-8653d11165c4.png) If I re-asign the same file to SumatraPDF as the handler it takes seconds to change and will open in SumatraPDF 
![image](https://user-images.githubusercontent.com/12754913/87790089-ed681800-c837-11ea-9547-7e16989ac333.png)

**Comment by GitHubRulesOK** [comment]
The second part of your issue

Additionally, SumatraPDF doesn't launch with the recent files opened as it used, and RestoreSession = ...

true/false Does not matter for any "recent past" it is only a flag "for the current / future"

For any current/future usage
RestoreSession = true
Also consider the option for `Remember opened files`  for all files.
(RememberOpenedFiles =)
and consider how you wish to set the upper defaults on a per file basis
(RememberStatePerDocument =)
![image](https://user-images.githubusercontent.com/12754913/87792891-68333200-c83c-11ea-89d9-74c587b8061e.png)

If your problem is that a previous sesion was not restored, and you have updated, then it may be possible to replace the settings file from any personal backup copy of SumatraPDF-settings.txt which during update may have been left at %appdata%\sumatrapdf and can be used to overwrite %localappdata%\sumatrapdf\SumatraPDF-settings.txt

**Comment by weitzhandler** [comment]
After clearing all recent entries from the _settings.txt_ file it's now working, thanks.
