### ISSUE TITLE
[Feature request] Dark Scrollbar

### ISSUE THREAD

**Issue by aelisya** [sumatrapdfreader/sumatrapdf#1703]
Hello i have a simple request, on my config file, i have configured it to have a very dark Sumatra, but on windows it use the clear version of the scrollbar.

Can you please implement a way to have access, to the dark version of the scrollbar of windows 10 (even if we enable it with a settings in the .txt)

Thanks

**Comment by GitHubRulesOK** [comment]
You can see black windows scrollbars in my post at https://github.com/sumatrapdfreader/sumatrapdf/issues/1580#issuecomment-627269778 but they are generated by Windows 10 themes and cause many problems

**Comment by aelisya** [comment]
i don't see show scrollbar anywhere, but since i have found out, deactivate continus view make the scrollbar hidden. so i will let the issue open for a native way to do so, and if refused i think the dev will close it :)

**Comment by GitHubRulesOK** [comment]
Sorry forgot its  coming in version 3.3 so currently only in pre-release version
![image](https://user-images.githubusercontent.com/12754913/87974020-50201480-cac1-11ea-80c5-3d87064c0764.png)

**Comment by aelisya** [comment]
oh ok, i will close it ^^ since it's already here (just in pre-release thanks to let me know)

**Comment by GitHubRulesOK** [comment]
@kjk linking to #898 since I do not think any one mentioned the obvious desire in a dark theme

**Comment by SumatraPeter** [comment]
> You can see black windows scrollbars here but they are generated by Windows 10 themes (ALT SHIFT PRTSC) and cause many problems.

There's a good reason High Contrast theme settings are under Ease of Access, since they're meant more for folks with visual difficulties. Win10 supports both Light and Dark modes (Personalization > Colors), so if Sumatra's updated to support those then its scrollbars will automatically appear light or dark according to the user's current selection. Of course, any app dev is free to allow users additional fine-grained customization of scrollbar colors if they so choose.
