### ISSUE TITLE
Flicker when too many pages rendered at once

### ISSUE THREAD

**Issue by Axel-Shark** [sumatrapdfreader/sumatrapdf#1711]
When loading several PDFs at once (~7+) the first 7 or so appear as expected and can be zoomed, scrolled, etc without issue. Upon switching to tab 8 and beyond, the PDFs flicker and drive CPU usage to 100%.

I've tried several different PDFs and the issue can be replicated nearly every time.

Sometimes the flickering can be stopped if I resize the window to some arbitrary dimension, stopping only once the flickering ends. While that may stop that tab from flickering, it usually doesn't stop the others. So it means keeping tabs to about 7 or constantly resizing the window as different tabs are selected.

Sometimes I can catch a quick glimpse of text that says "page loading" or "page rendering", or something to that affect.

**Comment by GitHubRulesOK** [comment]
Please confirm the version you are using is it 3.2 ? did you try current https://www.sumatrapdfreader.org/dailybuilds.html

**Comment by Axel-Shark** [comment]
Yes. I was on 3.2 and just confirmed it on the nightly as well.

Only consistent trigger I can find is tab count. The files are lecture notes and if it starts flickering, it can occur on any page, so it doesn't seem to be related to images, drawings, math equations, latex, etc. It can occur even on a benign cover sheet.

**Comment by kjk** [comment]
Yes, I can  reproduce it. It's more about number of visible pages on all tabs (rather than  just number of tabs). I.e. it's easy to reproduce by e.g. switching to continuous mode and zooming out (so that many pages are visible at once).

It's been reported before.

Most likely it's caused by a fixed size of cache for rendered pages which triggers evictions / re-rendering of the pages.

**Comment by kjk** [comment]
Or there could be a bug in cache eviction logic. We shouldn't free visible pages.

**Comment by Axel-Shark** [comment]
Ah ok. Thanks!

Is there a way to increase the cache size?

**Comment by GitHubRulesOK** [comment]
@kjk 
related https://forum.sumatrapdfreader.org/t/latest-sumatrapdf-3-2-flickers-on-various-latex-generated-files/3023
In those there was no suggestion of large numbers of pages ( thus could be other zooming factors?) However the CAD file(s) at A1 would be equivalent to 8 x A4 pages of vectors zoomed out.

**Comment by kjk** [comment]
The bug in the logic was than when the cache was full, we were evicting a random page.

The fix is to ensure that we don't evict pages from the tab being shown (which flickers due to entering free / re-render loop).

Dropping a page in invisible tab is ok.

It still will have problem if the tab is visible in another window, but the probability is much lower.

**Comment by prashantk100** [comment]
To Eliminate white flicker or flashing I have changed Sumatra pdf Main WindowBackground color to black and its working
MainWindowBackground = #000000

and also added GradientColors in section FixedPageUI [
GradientColors = #000000

regards
Prashant
