### ISSUE TITLE
Bookmarks regression

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1716]
Whilst checking issue #1715 
It became apparent that adding a single valid ? bookmark which works in 3.1.2 does not work in recent builds, oddly it works if saved as .bkm or .vbkm !!
I dont have enough versions kept between 3.2.12002 (working) to get any closer but not working since 3.2.12007 (January) pre 3.2 release 

[BlankA4x2 ex VS eXpert.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5004024/BlankA4x2.ex.VS.eXpert.pdf)

**Comment by kjk** [comment]
The issue here is that there's only one item in toc tree and technically it's always selected so clicking on it doesn't change the selection and hence we don't act upon it.
This is a result of rewriting toc tree to use TreeCtrl.
Not sure how hard it's to fix. This shouldn't happen often in real PDFs.

**Comment by GitHubRulesOK** [comment]
@kjk 
That definition we dont "Act" on single bookmarks could explain other odd behaviours I experienced on occasions when building vbkm using single page pdfs.
Dont have a repeatable example at present but can keep it in mind as a cause.
