### ISSUE TITLE
Odd refresh misbehaviour since between 3.3.112932 and 3.3.112965

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1752]
Only have odd backups so it appears that between 3.3.112932 and 3.3.112965 there was a change that affects refresh/reload

described in https://forum.sumatrapdfreader.org/t/pdf-display-slightly-shifted-down-right-on-file-auto-reload-v3-3-13136/3354

It seems not to matter how a pdf is produced, but is most apparent when LaTeX recompiles the pages.

Load any PDF into a version 3.3.112965 or higher and move/zoom so as top of page is out of sight, press R makes the page scroll slightly.
In any version including 3.3.112932 or before pressing R has no effect on the view, it stays static.

**Comment by kjk** [comment]
Most likely caused by float => int truncation.
In `DisplayModel::GetDisplayState()` we call `GetScrollState()`, which returns (x,y) as float.
We store it in `DisplayState->scrollPos` which does (x,y) as int. This can truncate, say `0.5` of the float.
We then restore scroll state which can be slightly less, which explains why it moves to the top/right.
I don't remember making changes here.
The fix should be to change `DisplayState->scrollPos` to float.
