### ISSUE TITLE
Printer problem, enter the printer list, the file size becomes super large

### ISSUE THREAD

**Issue by wangpai1998** [sumatrapdfreader/sumatrapdf#1758]
Why does the file size become very large when printing and when it comes to the printer list?

At first, it was only 100kb, and then after the printer list, the file size became 25mb. Is this file too large?? Is there a problem in the middle? Have you met?

When printing, the file will become very large. In this case, if there is a large amount of printing, the C disk will not fit at all

**Comment by GitHubRulesOK** [comment]
Its not Linear, and the ratios may be much more than 100 fold,
when viewing a compressed 90KB file it may easily expand to use 9000 KB of working memory, then converted to printer pixels by the driver it might only double to 18 MB or it could just as easily bloat to GB. The source data compression, scaling, printer resolution, all compount the results.

You can try using version 3.0 **without** print as image to see if it makes a significant enough reduction, but MuPDF (the core of SumatraPDF) is not designed for efficient printing just viewing.

**Comment by GitHubRulesOK** [comment]
Much of this issue is down to the print drivers so testing with one generic MicroSoft postscript driver

Taking a small A4 PDF of about 44 KB 
a 300 dpi print file is say 42 KB (smaller than the original)
but at 600 dpi the print file is roughly 4 times bigger = 150 KB
on its own not an issue so now multiply that by 100 pages and suddenly its 15 MB

Use a document with more content per page (The more complex the colour range, usually the greater the number ink spots it might need)
start with 100 KB thats only about 2.5 times previous page
now 300 dpi requires from 15 KB (slab of same colour) up to say 10 MB for that one page and
at 600 dpi the 10 MB  requires 27 MB ( note that it is not 4x=40 !) 

You should see similar with an Inkjet driver so for the same one page with an image I get a spoolfile of 25.8 MB (Best quality or Eco Draft quality it does not matter, both are just as big)

Now we are aproaching the 64MB memory a cheap printer may have for all the pages, so sending more than 2 of such pages at the same time could stuff its buffer.

**Comment by wangpai1998** [comment]
The file of version 3.0 is still typed, but by comparison, it is reduced by half

**Comment by wangpai1998** [comment]
> 这个问题的大部分归结于打印驱动程序，因此使用一个通用的MicroSoft postscript驱动程序进行测试
> 
> 对于
> 300 dpi的打印文件，以大约44 KB的小A4 PDF 表示为42 KB（比原始文件小），
> 但是在600 dpi时，打印文件的大小大约是其4倍= 150 KB
> 本身不是问题，因此现在乘以100页，突然其为15 MB
> 
> 使用每页内容更多的文档（颜色范围越复杂，通常可能需要更多的墨水点）
> 以100 KB开头，仅是前一页的2.5倍，而
> 现在300 dpi从15 KB开始需要（相同颜色的平板） ）最多一页
> 需要10 MB，而在600 dpi时10 MB需要27 MB（请注意，它不是4x = 40！）
> 
> 您应该在Inkjet驱动程序中看到类似的图像，因此对于同一页的图像，我得到25.8 MB的假脱机文件（最佳质量或Eco Draft质量无关紧要，两者都一样大）
> 
> 现在，我们正在为廉价打印机准备用于所有页面的64MB内存，因此，同时发送两个以上的此类页面可能会塞满其缓冲区。
> 
> 如果您使用3.0版，则可以为打印驱动程序提供对输出的更多控制权，以便将25-27 MB压缩到仅130 KB（即类似于8x11英寸的低分辨率jpg），因此可以打印200个复杂的图像页面！

Why is it that when I use version 1.5, the printing is very fast and the file size is very small. Is there any harm in doing so?? Or what?

**Comment by wangpai1998** [comment]
Why is it that when I use version 1.5, the printing is very fast and the file size is very small. Is there any harm in doing so?? Or what?

**Comment by GitHubRulesOK** [comment]
Older versions with those older code libraries may have bugs or other issues.
As long as you are not using unknown files containing any security exploit (rare ?), there should be no harm other than any lower quality result. Much more depends then on the "Print Driver".

**Comment by kjk** [comment]
because we print as bitmaps and bitmaps are big. there is no plan to change that
