### ISSUE TITLE
Url / hyperlink custom coloring

### ISSUE THREAD

**Issue by jackowski626** [sumatrapdfreader/sumatrapdf#1766]
Is it possible to do? I searched everywhere and couldn't find that option. If it isn't, it would be a nice option to have

**Comment by GitHubRulesOK** [comment]
Most hyperlink customisation is done in Acrobat Pro, LaTeX Hyperref or any similar editor by the author, thus can be set by applying a Hyperlink Character Style or corresponding PDF borderstyle. However those styles are not always handled well by MuPDF so there are open issues here in SumatraPDF (see especially https://github.com/sumatrapdfreader/sumatrapdf/issues/157)
It is possible that Annotation could possibly add the ability to hyperlink and, IF so, a style may be applicable, but that is a BIG IF since MuPDF-GL does not include writing hyperlinks.

**Comment by GitHubRulesOK** [comment]
It is worth mentioning that the hyperlinks are not normally the text which any editor can set to any color or use an ordinary colored textual underline ( and SumatraPDF could not be expected to edit the textual styles.
Hyperlinks are usually an invisible layer laid over the text which includes such aspects as invisible coloured borderd thus are akin to the overlay of a bloch of highlight with a flag to say how they should look and what action they perform when clicked.

@kjk
This later aspect above is a security risk since the visible text might say go to www.microsoft.com but the invisible action can be go to malware .com this is different to those self generating entries where a visible URL is converted to a matching legitimate address. Acrobat will ask if you really want to go to https://example.com/exploit

**Comment by kjk** [comment]
Not really sure what this is asking for. If this is something other PDF readers do, please provide test document and a screenshot of how it should be handled.
