### ISSUE TITLE
the pdf screen flash when enlarge or shrink the pdf 

### ISSUE THREAD

**Issue by INTEL-AMD-NVIDIA** [sumatrapdfreader/sumatrapdf#1768]
pdf of the display there may be problems, in some cases, when I enlarge the pdf to a certain extent, the entire pdf of the screen began to flicker; similarly, at seem time, the cpu's occupancy will be very high, basically, then to half of the cpu occupancy rate; similarly, sometimes, shrink the pdf to a multi-page when a similar situation will occur!

I wonder if the size of the pdf a little large ?It's a 31.8M pdf.When the bug occured ,the can see this pictures,it shows that"Waiting - rendering"
![image](https://user-images.githubusercontent.com/61803166/94649998-6b609900-0328-11eb-8377-2905797a896b.png)

**Comment by GitHubRulesOK** [comment]
You need to confirm using a current https://www.sumatrapdfreader.org/prerelease.html version since there have been many related changes since 3.2 was released. For example see 
Flicker when too many pages rendered at once #1711 
It also helps to supply a link to a public downloadable file that shows a similar problem

**Comment by kjk** [comment]
This should be fixed in daily builds: https://www.sumatrapdfreader.org/dailybuilds.html
