### ISSUE TITLE
Change keyboard shortcut for Save As

### ISSUE THREAD

**Issue by quickfold** [sumatrapdfreader/sumatrapdf#177]
Currently, SumatraPDF has Ctrl+S for "Save As" and Ctrl+Shift+S for "Save link to document". Most of my other programs use Ctrl+Shift+S for Save As and I'd like to change SumatraPDF to do the same, possibly through the advanced settings file. Any chance this can be implemented?

**Comment by cheesecracker** [comment]
Yeah, I agree too.  It would be nice if SumatraPDF can follow the keyboard shortcut convention.

**Comment by kjk** [comment]
Before we declare that a convention, can you list some of the software with Ctrl-Shift-S for "Save-As".
What do they use Ctrl-S for?

**Comment by quickfold** [comment]
They use Ctrl+S for "Save". Most Windows document software uses this convention.

Software using Ctrl+S as Save and Ctrl+Shift+S as Save As:

- Adobe Acrobat & Reader
- Foxit Reader
- all MS Office Applications, 2010 and 2013
- Notepad
- Freeplane

Software using Ctrl+S as Save:

- Notepad++ 
- Avidemux
- IrfanView
- Quicktime

Can we declare it a convention now? :-)

**Comment by cheesecracker** [comment]
Let me insert three more:

KompoZer (HTML editor using Mozilla suite's HTML renderer):
  * (Simple) Save: Ctrl+S
  * Save as: (no shortcut)

IDLE (Python's Integrated DeveLopment Environment):
  * (Simple) Save: Ctrl+S
  * Save as: Ctrl+Shift+S

Code::Blocks (a full-featured IDE for development in C, C++, etc)
 * (Simple) Save: Ctrl+S
 * Save file as: (no shortcut)
 * Save all files: Ctrl+Shift+S

**Comment by quickfold** [comment]
The save shortcut continues to be an issue for me. Can we get a follow-up comment from the developers re: their view on changing this or letting users change it? Thanks!

Paint.net also uses the Ctrl+S for save and Ctrl+Shift+S for save as.

**Comment by kjk** [comment]
I'm not convinced that changing the shortcut at this point would out-weight breaking backwards compatibility.

The reason all those other programs use Ctrl-Shift-S is because they have a 'Save' function that is used more frequently than 'Save As' and hence gets more convenient shortcut. Sumatra doesn't have 'Save' so Ctrl-S is available.

Maybe some day we'll get capability to remap the shortcuts via advanced settings, but we're not promising anything.

**Comment by quickfold** [comment]
Even if you don't want to change Ctrl-S to save, is it possible to change it so that Ctrl-Shift-S is not "save as link"? That's actually the bigger problem for me b/c I don't have save as link in ANY other programs, so I usually assume that I'm saving the file itself.

Since Ctrl-Shift-S is a very common shortcut in other programs and it means something other than "save as link", maybe use a different combo for "save-as-link", to avoid confusion? Anything else could be used for "save as link". How about Ctrl-Alt-S?

**Comment by kjk** [comment]
I can't flip-flop on user-facing changes like shortcuts based on a single data point. I've noted your feedback but unless I hear the same thing from many people, we won't be changing it.

**Comment by norill** [comment]
All keyboard shortcuts should be rebindable

**Comment by SteveHallArchitecture** [comment]
The issue for me is that Sumatra has decided to override the standard _A_ keyboard shortcut in the File Menu item to SaveAs. Instead, it points to Open in Adobe Reader. Without a way to change it.

Alt+F,A to should trigger File... SaveAs, just as it does in 99% of applications including Acrobat Reader itself.

**Comment by GitHubRulesOK** [comment]
there is no fixed rule
As per original poster Adobe usually on mac use **⇧⌘S** and on windows use **Ctrl** + Shift + **S**   for Save As...
In SumatraPDF it varies to follow the translation so in French it is Alt +F, E in Danish it is ,G English it is ,S
In Danish Alt F A means Quit and will mean something else in other languages, so many international users would be disturbed to find those key combinations changed
Solution may be to keep translations external to exe so users can mess them up for themselves but may our deities help us with all the support calls that will produce

**Comment by SteveHallArchitecture** [comment]
Actually, there are rules. Read on "Common User Access," rules written by IBM in 1987 to fix this very problem. This convention in the 30 years since, across quite a huge stack of the world's most widely used software (Microsoft Windows and Office, Adobe products generally, Libre/OpenOffice, AutoCAD, Notepad, Firefox) is for File... A to be the accelerator for SaveAs.

I'm lost on the other points made, I don't see any relevance of Apple bindings to a Window-only application or other languages to English menus and keyboard bindings.
