### ISSUE TITLE
Run unzipped epub file from memory

### ISSUE THREAD

**Issue by OgiBalboa** [sumatrapdfreader/sumatrapdf#1778]
Hello! I am developing an open-source "document cryptography" app with Python for the authors who wants to protect their works from copying and distributing without permission when they give access to the readers for their e-books.
I have a simple algorithm for this process; First user registers to the database with specified "access code" given from author. Then he downloads pre-assigned book for him inside of a -password crypted- zip file. Then he unzips the book to a temp directory and runs the reader app. I want to use Sumatra to read epub files.

Till this, everything is cool. But unzipping book to the "temp" directory is a weakness. So I decided to unzip files on a memory (ram) and then I read the file. So, how can I start the Sumatra Reader with a file stored in RAM?

**Comment by GitHubRulesOK** [comment]
Personally I think this is solution looking for a problem, My own view is its a waste of humanities time to create DRM issues, I have not seen any DRM snake oil that works, unless you lock in a vault and delete it or pluck out the eyes of the beholder. any mobile phone camera with screen scraper can be made to work even when the system is monitored for a software footprint.

**Comment by OgiBalboa** [comment]
If I run Sumatra with -restrict command, there's no option for reader, to save copy, this is why I've choose Sumatra. And yes, there's no way to prevent data from user right now, but at least, blocking copy-paste is a one step. 
I use zipfile module of Python. App reads the book inside the zip and gets its bytes. I dont know what to do next, how can I pass these bytes to Sumatra?

**Comment by GitHubRulesOK** [comment]
SumatraPDF uses sniffing passes to confirm the file object is structured as a simple application/epub+zip i.e. = 50 4B 03 04.
Using any app to unwrap a zip renders the object as not an application/epub+zip, thus  in general cannot pass other tests as a file object for SumatraPDF to process.
You would potentially need to approach the MuPDF authors to purchase an application that handles unpacked xhtml streams in memory, however as PDF rather than ePub is their forte, I would be looking to stronger ePub developers such as Calibre .

**Comment by kjk** [comment]
It's not possible for Sumatra to open a file from memory
