### ISSUE TITLE
-print-settings "paper=statement" not work

### ISSUE THREAD

**Issue by ckrgithub** [sumatrapdfreader/sumatrapdf#1803]
not consistent with Chrome
![image](https://user-images.githubusercontent.com/18225851/98336480-fd537400-2041-11eb-9412-fc52d88a24fa.png)

![image](https://user-images.githubusercontent.com/18225851/98336956-cf226400-2042-11eb-8f09-9c0619c8de71.png)

**Comment by GitHubRulesOK** [comment]
Not clear why chrome has anyththing to do with paper size
The command line is for printer output and is working fine today
![image](https://user-images.githubusercontent.com/12754913/98525680-b4353700-2270-11eb-8fb5-884eb6520f66.png)

**Comment by ckrgithub** [comment]
Yes! The command line is for printer output and is working! 
But The output is inconsistent with Chrome!

**Comment by GitHubRulesOK** [comment]
Every app will produce different outputs sent through the same printer
So SumatraPDF overall output file bytes will be different to Chrome byte size
File: C:\Users\K\Desktop\statement from chrome.pdf

But page paper size in both cases will be as near to 215.9 x 139.4 mm as is possible (when related to pixel count). so can on occasion be roughly 1/100 inch different

Chrome using PDF Producer: Microsoft: Print To PDF
PDF Version: 1.7 File Size: 9.26 KB (9,479 Bytes) Number of Pages: 1
Page Size: 13.97 x 21.59 cm (Statement)

SumatraPDF using PDF Producer: Microsoft: Print To PDF
PDF Version: 1.7 File Size: 278.28 KB (284,955 Bytes) Number of Pages: 1
Page Size: 13.97 x 21.59 cm (Statement)

**Comment by ckrgithub** [comment]
![image](https://user-images.githubusercontent.com/18225851/98620730-c9799680-2340-11eb-81a8-c7e43f2686d9.png)
![image](https://user-images.githubusercontent.com/18225851/98620977-46a50b80-2341-11eb-8f16-f590740d6e06.png)

The output position is different, the direction is different

**Comment by GitHubRulesOK** [comment]
Thank you for the images
If the input was exactly the same size there would be less of an issue but I note the source page is undersized as is showing oddly as  20.92 rather than 21.59 so there could then be a shift if placed at 100%

SumatraPDF uses a very basic system to send the print as an image to the system and thus position in this case may push it to an edge (depending on rotation) I am not sure without samples what setting may have any impact but you could first try `-print-settings "fit"` or `-print-settings "noscale"` or `-print-settings "shrink"` without specifying a paper size, since the source is smaller as long as the printer default paper size is set to either statement or some similar custom page size.

SumatraPDF paper size does not allow for custom sizes (only those listed) so the only other paper size close enough might be the smaller "paper=A5" = 21.00 x 14.8 cm
If scaling is set to "noscale" or "fit" it may work, but without same print driver / hardware here I have to leave it to you to test if that helps.

**Comment by ckrgithub** [comment]
not work.
Can support custom size and direction rotation.

**Comment by GitHubRulesOK** [comment]
There is a very limited need for rotation the default is to align the long sides of source and target.

There is an over-ride of the default direction by 1 x 90^ using "portrait" or "landscape" HOWEVER that may be further affected by the choice of fit/noscale/shrink such as to produce **logical** but unexpected results.

SumatraPDF is tied by the way the print drivers handle the image it produces so driver and hardware marins can also have a bearing. 

As a viewer application screen position is important but printer positioning is in general left to the left to printer settings which are easily controlled from the printers GUI interface. There are other applications dedicated to command line printing that may have more controls but SumatraPDF only uses the most basic method of sending un controled input.

So as to get better control you would need to have a method of editing the image to match the desired paper position which might be possible in a multi step imaging process of adding extra canvas etc. but that task is better handled by say IrfanView batch processing using more than 1 step of read and manipulate before print.

**Comment by GitHubRulesOK** [comment]
Closing as there seems to be no way to alter printout position unless using a dedicated printing application such as Acrobats own  print dialogs or similar print driver settings for page offsets.

OP stated issue of paper size was addressed in the past, rotation is also covered by duplicate residual issues
