### ISSUE TITLE
Incorrect rendering of transparency

### ISSUE THREAD

**Issue by tkazik** [sumatrapdfreader/sumatrapdf#1811]
Dear Krzysztof

First of all: Thank you very much for your awesome pdf-viewer...my favorite since a long time!
Today, I came a cross a figure, that is not rendered correctly, see:

![pdf_rendering](https://user-images.githubusercontent.com/15689124/99281815-3f936700-2833-11eb-9b98-cb123dd6baaf.jpg)
Xodo vs. SumatraPdf

For debugging, the pdf can be found [here](https://arxiv.org/pdf/1311.2102.pdf).
Thank you very much for your investigations.

PS: You probably have been asked several times already, if you have some plans for Linux, right? :)

**Comment by GitHubRulesOK** [comment]
@tkazik 
That file was a problem for 3.2 and not 3.1.2 (thus a regression) However I am closing the issue as currently fixed in recent builds (Pre-release / Daily) but do continue to watch out for other regressions

Microsoft VS wrapper around the MuPDF library is not very Platform Portable.
Linux Wine and ReactOS (Perhaps even Mac Parallels) should run SumatraPDF in some fashion, but the only cross port I have seen (towards ARM) is an unknown status to me.

Some day I might try running on a Raspberry in Win98/XP emulation, but that would needs be a really old version if it ever did work and probably slowly.
