### ISSUE TITLE
Sumatra pdf reader search sometimes OK, sometimes very very slow

### ISSUE THREAD

**Issue by wdflannery** [sumatrapdfreader/sumatrapdf#1819]
I have a big file Young and Friedman's university physics, and the search function can run normally for a few hundred pages and then slow down to a crawl, clicking off the pages 1 by 1.   I checked the CPU is running at about 40% and the disk at .1 mbyte / second.  This is really a crippling bug.

**Comment by GitHubRulesOK** [comment]
There has been lots of attempts to balance memory search versus render times, which means that in some cases one version may behave much better than another. A sample file is needed to compare a specific issue. However first try the current daily build https://www.sumatrapdfreader.org/dailybuilds.html since that has all the improvements todate

**Comment by wdflannery** [comment]
1600 page document
Search time entire document for a word not in the doc
Adobe - about 1 min
Old Sumatra - too long to wait
New Sumatra - < 10 seconds !!!!
The daily build looks like a winner.
