### ISSUE TITLE
Slow epub rendering

### ISSUE THREAD

**Issue by mrx23dot** [sumatrapdfreader/sumatrapdf#1822]
Changing pages in epub file type is considerably slower than in text PDF.
I would say 20ms in epub, CPU load 50%
and  <5ms in pdf, CPU load 24%
on 1core 3GHz

tested with latest available SumatraPDF-prerel-13112.exe

Please try to reproduce it
[test_me1.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/5668320/test_me1.zip)

**Comment by GitHubRulesOK** [comment]
My Oranges take longer to eat than my Apples since I have to take the skin off.

ePub needs to be built from fresh each time it is opened or resized as it is a "reflowing system" so opening any page generally requires all pages to be processed both up to the point it is opened and beyond to the end, so as to get a page count.
Whilst there are also reflowing types of PDF, SumatraPDF does not need to do that in a Fixed interface, so even if opened midway through a PDF it is usually quicker to first display that fixed page, whilst loading the others.

**Comment by mrx23dot** [comment]
I understand the difference, but we still have 3Ghz to display text, that feels sluggish (during scrolling).
Eg. earliest web browser/word processor also used text wrapping/html parsing on 266Mhz .

At the very worst case we could 
- process epub once during startup, (or when zoom/display changed)
- flatten out pages, 
- store each fix page in memory  page[0..n] (technically it requires the same amount of RAM, just segmented into array items)
- display the pre calculated page on scrolling/jumping to pages
- I don't mind recalculating on window changes

typical epub is <<100MB, we have >>2GB memory, so I would trade CPU for RAM to have an ultra fast user experience.

**Comment by GitHubRulesOK** [comment]
I am closing as this example is now quite fast in 3.4.pre-rel and a much slower example is found in duplicate https://github.com/sumatrapdfreader/sumatrapdf/issues/1786

**Comment by mrx23dot** [comment]
Thanks for the work! Looking forward to test the new release.

**Comment by GitHubRulesOK** [comment]
@mrx23dot  
It may not be much faster in current pre-rel than a previous Pre-rel that you tested 
your file still takes 4 seconds to load from selection on my 32 bit netpad where as a simple PDF may take 3 seconds.
Its just that for me the other example ePub takes around 25 seconds to load.
