### ISSUE TITLE
Sumatra PDF Crash Report 3.3.13112

### ISSUE THREAD

**Issue by mikeybuhtig** [sumatrapdfreader/sumatrapdf#1831]
Some redactions. Contact me if more data needed.
[sumatrapdfcrash-submitted121420.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/5691150/sumatrapdfcrash-submitted121420.txt)

**Comment by kjk** [comment]
Looks the same as #1830 

I think it happens because downloading https://kjkpubsf.sfo2.digitaloceanspaces.com/software/sumatrapdf/sumpdf-prerelease-update.txt?v=13112 for update check is super slow now and since it's done in a separate thread it triggers gAllowAllocFailure when the app exits while gAllowAllocFailure  is still >0 from http downloading.

Fixed it by disabling the gAllowAllocFailure check.
