### ISSUE TITLE
Attachment not shown

### ISSUE THREAD

**Issue by grzegorz-janoszka** [sumatrapdfreader/sumatrapdf#1836]
Polish bank mBank sends via email PDF files with password and attachment. Foxit reader can read them, acrobat as well. SumatraPDF shows me in bookmarks something, but there is no way I can open it.

**Comment by GitHubRulesOK** [comment]
There have been changes in the core functions that in some cases stop you from running such files automatically.
For different types of attachment this has been covered in several isssues.
You dont say what type of embedment and since its your bank statement you cant post a sample here but you could email the developer if necessary
In latest daily or pre-release right click should allow you to save the attachment, If that works for you then please close this thread as working per current design (even if not as desired)
![image](https://user-images.githubusercontent.com/12754913/102831248-332a9d00-43e3-11eb-8bee-61eeeef22c16.png)

**Comment by grzegorz-janoszka** [comment]
Hi, indeed the prerelease build can open the file (although it is quite clumsy). So it seems my issue has been at least partially taken care of.
