### ISSUE TITLE
different color of tabs

### ISSUE THREAD

**Issue by szkiewicz** [sumatrapdfreader/sumatrapdf#1849]
What do I need to set to always darken the tabs with pdf documents? Sometimes they are light and sometimes dark. It does not depend on the number of tabs or the size of the window.
![jasne zakładki](https://user-images.githubusercontent.com/76468893/103337375-68865900-4a7b-11eb-9b61-2800ce9fd5b4.jpg)
![ciemne zakładki](https://user-images.githubusercontent.com/76468893/103337384-7340ee00-4a7b-11eb-9408-11e0012742c7.jpg)

**Comment by GitHubRulesOK** [comment]
SumatraPDF is tied to the current version of windows restrictions thus in earlier versions it was much easier to modify windows dressing using 3rd party windows tools such that the appearance of borders / title bars ,/ scrollbars / colours could be changed see some current windows 10 variations in https://forum.sumatrapdfreader.org/t/changing-the-background-and-text-color-of-tabs/370/11

Tab colours are slightly different
 At present in SumatraPDF it should be
the current tab is the lightest one 
the darker = inactive
darkest = focused

@kjk 
the default greys used out of the box by SumatraPDF garner complaints they do not have much contrast, I can hack those 3 colours via hex settings but it would be so much more convenient if there were 3/6 variable colour values in the settings.txt (yes we will get complaints from the dark mode users, but less likely if the text colours per setting are also exposed)

**Comment by GitHubRulesOK** [comment]
@szkiewicz 
Retrospective patching of the tab colours is itself trivial in hex but is very specific to each exe. Yours looks like its possibly one of four variants of 3.1.2 ? Thus to make any changes would require loading the chosen exe into a sha hash generator like for example virustotal **for identification** then a hex patch file for that one exe could be edited by you for your colours of choice

The resulting work is called a "modified version" of the earlier work or a work "based on" the earlier work. The GPL requires that modified versions be marked as changed, so that their problems will not be attributed erroneously to authors of previous versions.

Mainly for that last reason any patch would need to be much **much** more extensive than simply the 3 colour changes so I cannot simply provide such a patch to cover all the necessary locations that SumatraPDF would need to be changed to meet that GPLv3 license requirement. However I might be able to highlight the 3 locations for one given sha value. But I would not be willing to do so for multiple versions. So identify wisely the one wish you would be using in 2021.

**Comment by szkiewicz** [comment]
Just like that, (sorry) because the answers almost suggest flying to Mars. It is better when the tabs are darker than white.

**Comment by GitHubRulesOK** [comment]
@kjk 
SumatraPDF currently uses in common with some apps
active tab = white
inactive tab =lighter grey
highlighted tab = not so light grey

windows users often experience a different tonal sequence either like explorer

highlighted tab = lightest colour
active tab = mid colour
inactive tab =darkest colour


      or MS browsers
active tab = light colour
highlighted tab = midway colour
inactive tab =darker colour


In many cases the inactive is the darkest whereas the darkest in SumatraPDF is used to highlight next target.

There was much discussion in duplicate topic #559 about using darkest to highlight target, 
however this differs in nature from many other windows apps where the "dead" tabs are darkest

am closing as topic is duplicated by #599
