### ISSUE TITLE
[Feature Request] Change tab navigation buttons

### ISSUE THREAD

**Issue by franzribcek** [sumatrapdfreader/sumatrapdf#1852]
First and foremost, acknowledgements for the great software!

I know it seems a little quirky, but I'd like tab navigation between PDFs to be done via the CTRL + PageUp/PageDown keys, like one would do with a browser.
The reason is that I generally read academic PDFs, so alongside reading there's also browsing with many tabs open and I'd find it more natural to move between PDF tabs the way I do with my browser tabs, to make it more consistent.

**Comment by GitHubRulesOK** [comment]
SumatraPDF is not a browser so the idea that one single page = one tab as in a browser is not really relevant.
**Page** UP / Down controls are relevant to a paged document browser, whilst Tabs key is nominally applied to tabs
Only in 2014 was CTRL page accelerator added at the time to match the branded PDF reader handling of pages not tabs.

@kjk
**Adobe have repurposed those key combinations in DC to align with browsers**, Whilst I see that as ergonomically stupid since it requires on my keyboard wide spanning of right hand rather than easier left hand ctrl + tab, many users have requested this change.
