### ISSUE TITLE
Inverse search with WSL

### ISSUE THREAD

**Issue by federkamm** [sumatrapdfreader/sumatrapdf#1861]
Not quite an issue as I solved it already, but I don't know where to mention it else.

I use Emacs in WSL for writing LaTeX documents and SumatraPDF to preview them.  However, inverse search with synctex is tricky as windows access my file C:\path\to\file.tex but WSL accesses it /mnt/c/path/to/file.tex instead.  To fix this, I created a symlink /C: to /mnt/c with

    sudo ln -s /mnt/c /C:

and use as inverse search command-line in SumatraPDF

    C:\Windows\System32\wsl.exe emacsclient -n +%l "/$(echo '%f' | tr \\\\ /)"

This seems to work at least in the cases that I used it so far.  However, I don't know why it needs four backslashes in tr.

Unfortunately, a black terminal pops up for a short duration (assumingly because of the call to wsl.exe).  I would be interested if anyone knows how to get rid of that.

**Comment by GitHubRulesOK** [comment]
The "normal" cause of a "black" window is a shell call via cmd.exe (Thus a console is inherently mandatory) however it can be "hidden" using vbs or other higher level commands.
Thus the question becomes is wsl.exe just a different variant of cmd since it too is meant for console commands and could it be masked in the same way?
Emacs for windows is usually called just like any other gui thus no console is normally visible between windowed apps.
Double escaping of slashes is common especially passing through cmd.exe but as I don't use WSL I don't know why you are having to TRanslate in that fashion. 
When using C: that is usually the default thus may not be needed simply reference that as if its the root in windows
in cmd try dir \ and you should see c:\ contents, so in wsl I would expect to see /mnt/c contents i.e. the root

**Comment by GitHubRulesOK** [comment]
Under the circumstances it would perhaps be worth using a windows to linux shim file
so the inverse call would be either
wsl.exe bash.sh +%l "dosfilename" (where dosfilename is "%f")
Then the bash script converts parameters into its own terms
OR run an inverse.vbs Wscript to accept the windows parameters and convert them to nix before calling wsl.exe

**Comment by federkamm** [comment]
Thank you for your deep look into the topic.  Some comments:

wsl.exe controlls the Windows Subsystem for Linux distributions and allows to run a command in them from Windows (or from cmd.exe).  I don't know if wsl.exe spans a cmd.exe terminal window when called from Windows, but I could imagine that a solution with runHidden.vbs is possible.

The double escape could be also necessary because I think the command-line is interpreted twice by bash (the Linux shell), the syntax $(...) runs the inner command in a subshell and puts the result of the command in the outer command-line.  "echo '%f'" just prints the file name to stdin of the part "tr \\\\ /" behind the vertical bar and "tr \\\\ /" replaces each backslash in stdin with a forward slash and writes the result to stdout.  The $(...) will be replaced by this result in the command line.  Therefore, if %f = "C:\path\to\file.tex" then "$(echo '%f' | tr \\\\ /)" will be replaced by "C:/path/to/file.tex".  I add a slash in the front so that emacsclient gets called on the path "/C:/path/to/file.tex".  Since "/C:" is a symlink to "/mnt/c", emacsclient runs finally on the file "/mnt/c/path/to/file.tex" which is the WSL equivalent of the Windows file "C:\path\to\file.tex".

The Linux root file system / is a folder somewhere in the AppData folder where the WSL-Distribution is installed.  It doesn't agree with the root folder of the C: drive.  The root folder of the C: drive is only available in the subpath /mnt/c of the root file system /.  Linux has only the concept of a directory to be relative to the current directory or absolute with respect to the root file system.  There is no concept of drives (the are just "mount points" and appear as random directory paths) and therefore the concept "relative to the root folder of the current drive" doesn't exist.

I don't think a shim for the translation of the path makes much sense, since I wouldn't do anything different than the "tr \\ /" in that, anyways.  I currently don't like the idea of a separate *.vbs script file and think I can live with the short popup of the black terminal window, but this would be probably an alternative.  vbs script could be run with arguments +%l and "%f" and build up the command line without the loop over the arguments as it knows in doesn't have to quote the first argument but only the second one and there are no more arguments in the call.

SumatraPDF shouldn't be run on a pdf file in the linux file system that it could change but in this case, I run WSL Emacs on a tex-File in the Windows file system and create the PDF file there as well so SumatraPDF would be even free to change the PDF file at will.  Linux is free to work with NTSF files that are mounted over /mnt/c as the filesystem driver takes care of everything.  Also Windows is free to change Linux files over the SMB protocol under \\wsl$\... as the smb-driver takes care of everything.  Windows should only avoid to change Linux files in the NTSF tree of the WSL directory as additional file system metadate might get corrupted this way.

Thanks for including the cross references to other issues.

Backslashes vs. slashes in filenames are a constant source of annoyances for cross-platform tools.  Btw. Microsoft was in favor for slashes but IBM put a veto against it and TOPS-10 is to blame for it: http://www.os2museum.com/wp/why-does-windows-really-use-backslash-as-path-separator/

Emacs is tightly integrated with the Linux userland and for me Emacs for Windows kept constantily failing subtly here and there.  In my oppinion Emacs on WSL is the much better Emacs experience on Windows but YMMV.

**Comment by GitHubRulesOK** [comment]
It is not common to keep Synctex files since they are session related thus only of "historic" value so amongst thousands of .tex files I can only find a handful of synctex files and since they were generated on windows in general contain the windows pointers such as F:\LaTeX\Data\mybook\mybook.tex however I seem to recollect both windows and thus SumatraPDF will work with F:/LaTeX/Data/mybook/mybook.tex so if those are embeded those should not need tr

I am still not sure where the problem lies
1) Forwards SumatraPDF should be called with a compiled preview name that can be "/LaTeX/TeX folder/sample.pdf"
2) Sumatra throws that info away for the reverse call
3) the reverse call is built from the prefix from settings e.g. wsl emacs -n (InverseSearchCmdLine = users editor call to line numbers) then can add return filename extracted from local compiled synctex file (%f) and the translated indexed page reference (%p). The %f **depends on what the editor wrote**  so could be "/LaTeX/TeX folder/sample.tex" so "%f" would be all that's required.

Some TeX editors are good at writing the reverse target with complex placeholders for main and sub files such as to return to ./subfolder/chapterxx.tex.

So the question is where does Auctex or other Latex Tool generate the return call since the mnt/c seems to originate there, SumatraPDF only echo's back what's indexed in the synctex.

**Comment by GitHubRulesOK** [comment]
@federkamm 
Apologies I am wrong 😊 Sorry

SumatraPDF with syctex is not only interfering with / thus
//mnt/c/LaTeX/TeX folder/sample.tex
is returned as
\\mnt\c\LaTeX\TeX folder\sample.tex

but also makes a poor alteration to root value

so file on **E: drive** at 
/LaTeX/TeX folder/sample.tex
gets returned as
C:\LaTeX\TeX folder\sample.tex

and more pertinent

/mnt/c/LaTeX/TeX folder/sample.tex
is returned as
C:\mnt\c\LaTeX\TeX folder\sample.tex

which was not my prior understanding. So I will need to revisit some of the posts above

@kjk 
the change in returned values was unexpected to me but perhaps is understandable for use within a windows only platform

**Comment by federkamm** [comment]
My synctex file looks like

    SyncTeX Vension:1
    Input:1:/mnt/c/path/to/./file.tex
    Input:2:/mnt/c/path/to/./class.cls
    Input:3:/usr/share/texlive/path/to/package.sty
    [...]
    Input:53:/usr/share/texlive/path/to/font.fd
    Output:pdf
    [...]
    Input:54:/mnt/c/path/to/./file.bbl
    [...]
    Input:55:/mnt/c/path/to/./file.aux

Input:4: to Input:52: are all located in /usr/share/texlive and this are all paths in my synctex file.

When I double click somewhere in the PDF in SumatraPDF the inverse search command-line gets called with C:\path\to\file.tex in %f or with C:\path\to\file.bbl when within the bibliography.

**Comment by federkamm** [comment]
`ln -s /mnt/c ~/` will mount the the root of the C: drive to the home directory `~`.  One most likely wouldn't want to do this on a system that is already in use as the home directory usually holds all the configuration of the user that will be shadowed then.  One could consider to do so on a fresh install but that would mean one cludders the C:\ root folder with a lot of personal configuration files what is most likely no good idea.

The `ln -s /mnt/c /C:` makes just a symlink in /C: to the C:\ drive of windows.  The only intent is to make directory paths more similar for a simpler translation: C:\path\to\file.txt => /C:/path/to/file.txt

Note that "C:" is just a regular folder name and the colon has no special meaning in this context.

Btw. I just realized that my folder path and file names do not contain any space characters.  I'm not sure I did the escaping correct to also work with spaces in file names.

**Comment by federkamm** [comment]
`wsl_proxy` mentioned `wslpath` I wasn't aware of.  With this the command-line can be simplyfied to

    C:\Windows\System32\wsl.exe emacsclient -n +%l "$(wslpath '%f')"

`wsl_proxy` looks interesting, unfortunatelly it doesn't work for me.  When I link `emacsclient.exe` to `wsl_proxy.exe` and use the inverse search command-line

    emacsclient -n +%l "%f"

it translates the command to

    emacsclient $'-n' $'+100' "$(wslpath $'C:\\path\\to\\file.tex')"

Don't know where the `$'...'` syntax comes from and how to get rid of them.  However, for this particular case it doesn't do anything else than running emacsclient with the path translated by `wslpath`, therefore I stick with the former command-line for now.

wsl_proxy also pops up a black terminal window.

**Comment by kjk** [comment]
Closing as there's nothing for sumatra to do.
