### ISSUE TITLE
[Feature request] Decouple recently opened files from session restore

### ISSUE THREAD

**Issue by roelschroeven** [sumatrapdfreader/sumatrapdf#1862]
The option "Remember opened files" controls two things: with that option enabled, SumatraPDF (1) maintains a list of recently opened files, accessible from the start screen and from the File menu; and (2) restores the session (opened documents, and the position in those files) from the last time when you start SumatraPDF. 

I think the list of recently opened files is very useful, and I would very much like to use that without also having my sessions restored because I don't like that. It doesn't even always work, since the PDFs I read are often on network drives that are not always available, depending on whether I'm home or at work or somewhere else.

**Comment by roelschroeven** [comment]
It looks like what I want can be achieved by opening the Advanced Options, and setting RestoreSession = false and RememberOpenedFiles = true. Still I think it would be nice to have that in the regular Settings screen too.

**Comment by kjk** [comment]
No plans to split the settings file.

**Comment by roelschroeven** [comment]
I didn't ask to split the settings file?! The options I'm talking about are already split in the settings file. They're just not split in the Settings user interface.

**Comment by GitHubRulesOK** [comment]
@kjk 
There are a few settings.txt oddities here 
Priority is always that when OPTIONS is NOT remember opened files
Then in settings the following is correctly set
RememberOpenedFiles = false

and the following are ignored / over-ridden
RestoreSession = true
RememberStatePerDocument = true

However if each document contains a favorite they are naturally "Remembered as Opened Files"
 BUT even though the former file StatePerDocument may have been rotated :-) the following
setting is naturally applied
UseDefaultState = true

Only using RememberOpenedFiles=true will allow favorites to open as stored e.g rotated etc.

**Comment by izeroo** [comment]
I have the same issue with you. I have many pdfs to read, but I usually open one at a time. "RememberOpenedFiles" setting from UI does two things, remeber where i left and reopen all the tabs i didn't close manually. It causes performance issue since it takes about one second to reopen all the tabs and consumes more memory meaninglessly to load books I don't need.

Editing "RestoreSession = false" from config file solves the trouble, it's controlled by toggling "RememberOpenedFiles" option from UI, which is confusing because if I uncheck "RememberOpenedFiles" from UI, tabs won't reopen but remebering where i left is also turned off.

It will be more clear to have seperate options in UI like "Remeber where I left" and "Reopen tabs not manually closed".
