### ISSUE TITLE
Command line print not start  at top, but the exe is. 

### ISSUE THREAD

**Issue by LFdeWeb** [sumatrapdfreader/sumatrapdf#1865]
There are the images.
This one is print by command line which is wrong,
![2341611112852_ pic_hd](https://user-images.githubusercontent.com/34666154/105130783-9d3d7b80-5b22-11eb-9681-d9ce711fd667.jpg)
this one is right which is print by click the print button
![2321611112793_ pic](https://user-images.githubusercontent.com/34666154/105130849-bb0ae080-5b22-11eb-9d68-fba4d514af61.jpg)

here is the PDF
[sfmd.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5840314/sfmd.pdf)

The wrong command is 
``` shell
> .\SumatraPDF.exe -print-to-default   './sfmd.pdf'
```

**Comment by LFdeWeb** [comment]
Could someone help me,  thanks.

**Comment by GitHubRulesOK** [comment]
SumatraPDf printing control is basic thus page positioning is affected by default settings within windows
Using the Printer Dialog instructs the printing system to modify some default values such as paper rotation scale etc.
So to get identical results from a command line those values also need to be modified but that is easier said than done since many single values can affect others.
This is also much more noticeable using smaller label printers than standard page printers.
The first setting to check is the difference between inputs with fit / shrink and noscale (clue is which works best in the dialog)
 Using Advanced Settings when using exe is initialised it uses
PrinterDefaults [
	PrintScale = shrink
]
but user may manually leave it as default (shrink) OR alter that to **none or fit** it is worth testing with all 3 values in turn within settings.txt to see if that over-ride is affecting the command line running.
Once you know how the scale is having affect then the next issue is how is that affected by scale of input so the ideal is input = output e.g. it is best to be using `noscale` in both settings and commandline

Now the next issue is output and the margins that it requires for gripping.
From the command line in the past there was little control over paper size so output was often "OFFset" to just part of the default print area. Much here depends on the printer driver so most label printer users found using a more robust printer driver helps to manage that output. If you search "dymo" or "zebra" on the forum it should lead you to a very long discussion but the bottom line is that alternative drivers like "seagull" usually improve both paper handling and quality
https://forum.sumatrapdfreader.org/t/barcode-label-printer-orientation-size-quality-not-correct/197

There has been an improvement recently in command line paper definitions so for labels it is now much much easier to set "paperkind=###" so see https://github.com/sumatrapdfreader/sumatrapdf/issues/1812

**Comment by LFdeWeb** [comment]
> SumatraPDf printing control is basic thus page positioning is affected by default settings within windows
> Using the Printer Dialog instructs the printing system to modify some default values such as paper rotation scale etc.
> So to get identical results from a command line those values also need to be modified but that is easier said than done since many single values can affect others.
> This is also much more noticeable using smaller label printers than standard page printers.
> The first setting to check is the difference between inputs with fit / shrink and noscale (clue is which works best in the dialog)
> Using Advanced Settings when using exe is initialised it uses
> PrinterDefaults [
> PrintScale = shrink
> ]
> but user may manually leave it as default (shrink) OR alter that to **none or fit** it is worth testing with all 3 values in turn within settings.txt to see if that over-ride is affecting the command line running.
> Once you know how the scale is having affect then the next issue is how is that affected by scale of input so the ideal is input = output e.g. it is best to be using `noscale` in both settings and commandline
> 
> Now the next issue is output and the margins that it requires for gripping.
> From the command line in the past there was little control over paper size so output was often "OFFset" to just part of the default print area. Much here depends on the printer driver so most label printer users found using a more robust printer driver helps to manage that output. If you search "dymo" or "zebra" on the forum it should lead you to a very long discussion but the bottom line is that alternative drivers like "seagull" usually improve both paper handling and quality
> https://forum.sumatrapdfreader.org/t/barcode-label-printer-orientation-size-quality-not-correct/197
> 
> There has been an improvement recently in command line paper definitions so for labels it is now much much easier to set "paperkind=###" so see #1812

Thanks you very much, It's because  ` noscale `;
