### ISSUE TITLE
Unable to save annotation

### ISSUE THREAD

**Issue by taooceros** [sumatrapdfreader/sumatrapdf#1872]
I am not sure where I can get the log. Would you please give me some guide to get the log?

**Comment by GitHubRulesOK** [comment]
Unsure what "log" you are expecting
Normally SumatraPDF is keeping usage in memory and does not externalise your actions.
A trace "log" would only be generated for debugging, thus is normally only written when there is a crash condition, so that it can be submitted for analysis of steps prior to crash. 

First confirm which version is exhibiting problems as current daily 3.3.13256 is working for me
![image](https://user-images.githubusercontent.com/12754913/106279457-5c391b80-6234-11eb-8696-9725fb8aaae2.png)

If unable to save annotation, you would need to provide a small example file, and describe your steps taken to save.
Most obvious blocker is no user rights to save file in a protected folder.

**Comment by taooceros** [comment]
![image](https://user-images.githubusercontent.com/45326534/106281578-40158a00-61f4-11eb-9ae1-5c14427f1a6f.png)
I am on this version.
[（备份）China (Inventing the Nation) by Henrietta Harrison (z-lib.org).pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5894104/China.Inventing.the.Nation.by.Henrietta.Harrison.z-lib.org.pdf)
This is the file.
It is located inside a Onedrive folder. I believe it shouldn't include permission issue.

The step:
1. Highlight a text typing `a`
2. right click and click save annotation
3. close the document
4. open it again
5. the annotation disappear

**Comment by taooceros** [comment]
I believe I installed the daily version, but checking for update suggesting that I am on the latest version (which is lower than your version). I will install the latest version and check whether it still exist.

**Comment by taooceros** [comment]
Well, I installed 13256, but seems the issue still exist....

**Comment by GitHubRulesOK** [comment]
Open drive is a possible blocker as the file system is not pure NTFS thus can often not see the changes to a file for syncing.
 (Personally I avoid virtual drives like One Drive, having lost hundreds of MS Office edits etc. even though my employer insists my files must be kept there)

However that is NOT your problem since THANK  YOU for the sample where I do see your annotations were saved.
What I see is that they have been stored at what looks like the "wrong" locations, which is a well known problem if you are not working in "Page only" mode.
![image](https://user-images.githubusercontent.com/12754913/106288159-93f99080-623f-11eb-9d1f-02800b5222c5.png)

**Comment by GitHubRulesOK** [comment]
@kjk 
This problem of annotations being attributed to another page number is raising an understandable number of "issues" Is it possible to elevate in the list of pre-release priorities for fixing, please.

**Comment by taooceros** [comment]
Ah thank you for response!

> Open drive is a possible blocker as the file system is not pure NTFS thus can often not see the changes to a file for syncing.
(Personally I avoid virtual drives like One Drive, having lost hundreds of MS Office edits etc. even though my employer insists my files must be kept there)

haha, I do have a habit to organize my school stuff inside Onedrive, because it is provided by them.

**Comment by kjk** [comment]
I can't reproduce not saving on fixed drive and a network drive. Haven't tried OneDrive.

@taooceros  can you see if this reproduces when the file is on C; drive?

**Comment by GitHubRulesOK** [comment]
@kjk 
I recently have experienced some oddities in annotation (i only use latest daily) not tied down to a commonality but they often/frequently "disappear" I am only working on local drives C:\internal and D: (stick) and E: (usb hard disk)

**Comment by GitHubRulesOK** [comment]
[in-an.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5948290/in-an.pdf)
@kjk As just one example a comment at top of page disappeared when adding a second but did return whilst saving

**Comment by taooceros** [comment]
> I can't reproduce not saving on fixed drive and a network drive. Haven't tried OneDrive.
> 
> @taooceros can you see if this reproduces when the file is on C; drive?

Yes I can reproduce...

**Comment by kjk** [comment]
Ok, I can reproduce with context menu "Save annotations".

I can also reproduce attributing annotation to the wrong page when in continous mode.

**Comment by GitHubRulesOK** [comment]
@kjk 
the separate issue here is odd "disappearance's" whilst the core page displacement issue was covered by https://github.com/sumatrapdfreader/sumatrapdf/issues/1705 so **hopefully that is now closed** but "now you see me" "now you don't" without further testing may still be present ?

**Comment by GitHubRulesOK** [comment]
@kjk 
On revisiting both the sample above and my own simpler example above the **"disappeared" annotation were apparently not added by SumatraPDF**. For example it is the Chinese file annotations dated last second of 1969 that cause issues in SumatraPDF the 2021 annotations by SumatraPDF are well placed, or in my example the rogue one was an existing one prior to the one added by SumatraPDF.

In the Chinese file if you change the colour of an existing annotation on page 33 the others go rogue (invisible) that's partially understandable as they appear non standard compared to those generated by MuPDF

On opening **my example** in MuPDF the problem seems not apparent / cleared **after saving there in MuPDF**
 but still persists in newest SumatraPDF unless I use the MuPDF saved copy !

Oddly when I use MuPDF to change a colour of highlight in the Chinese file it only changes the one object since on reopening in SumatraPDF and attempting to add another, that MuPDF modified one stays visible but the rogue ones do not.

I will have to accept there is a problem here NOT of SumatraPDFs making but there may need to still be some work possibly in MuPDF  library to handle 3rd Party annotations.

**Comment by taooceros** [comment]
@kjk the fix seems work. Thank you!

> In the Chinese file if you change the colour of an existing annotation on page 33 the others go rogue (invisible) that's partially understandable as they appear non standard compared to those generated by MuPDF

I try delete one of them in page 33, and the other one also go invisible as well. That doesn't happen when removing other valid highlight I think.
