### ISSUE TITLE
add auto find out ExternalViewers for PdfDjvuBookmarker & FoxitPhantomPDF

### ISSUE THREAD

**Issue by Aliaksandr3by** [sumatrapdfreader/sumatrapdf#1880]
```
ExternalViewers [
	[
		CommandLine = "C:\Program Files (x86)\Foxit Software\Foxit PhantomPDF\FoxitPhantomPDF.exe" "%1"  "/A" "page="%p
		Name = Fo&xit PhantomPDF
		Filter = *.pdf
	]
	[
		CommandLine = "C:\Program Files (x86)\Pdf & Djvu Bookmarker\PdfDjvuBookmarker.exe" "%1"
		Name = Pdf&Djvu Bookmarker
		Filter = *.*
	]
]
```

**Comment by GitHubRulesOK** [comment]
@kjk 
The auto detection of external viewers does still work for hh.exe on system path but registry entries have been overtaken by many changes over time thus auto detection on windows 10 based on legacy Acrobat or Xchange Viewer reg entries at best may still find installed versions of Adobe Reader DC and possibly some Foxit Reader, but others have changed e.g. xpsrchvw is depreciated since 2018.
I think there was already a request to update depreciated Xchange Viewer to current Xchange Edit

The above request to extend to just two specific of many PDF/DjVu applications is perhaps covered well enough by above custom entries. 

However, it may be worth revisiting the more historic Xchange Viewer entry and updating that to Edit8/9
