### ISSUE TITLE
SumatraPDF doesn't render Japanese interpunction

### ISSUE THREAD

**Issue by jc3213** [sumatrapdfreader/sumatrapdf#1893]
I've read some PDF novels written in Japanese. When it have something like `メリークリスマス`, or `それは、XXXX`. The Japanese interpunction like `ー` or `、` , and many others will not be rendered correctly.

I've attached the the screenshot and the PDF novel sample.

The PDF novel sample:
[公爵令嬢の舞台裏.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6017230/default.pdf)

Browser:
![browser](https://user-images.githubusercontent.com/8744936/108616445-5f48b580-7448-11eb-8dc1-1768c736dd2e.png)

SumatraPDF:
![sumatrapdf](https://user-images.githubusercontent.com/8744936/108616446-5fe14c00-7448-11eb-8d47-ef43d92f009b.png)

**Comment by GitHubRulesOK** [comment]
On occasion there will be problems with font rendering due to the 3rd Party libraries
Some noticeable differences may be there for some time, until those libraries are updated and few of which are still present.
However in this case I am unsure of when
Version 3.1.2 showed NO text for me with this file, suggesting the characters are not included (embedded)
Version 3.2 and Current Daily version 3.3.13276 looks like this to me
![image](https://user-images.githubusercontent.com/12754913/108625226-ad0def80-7441-11eb-99c5-3f145a0f1607.png)

And I note you are also using a very recent copy so that is unlikely to be the cause.
 (please confirm version from help about)

This is more likely some issue with the local font your machine is using, but I am surprised so see that type of issue in a PDF where normally the fonts used should be universal as supplied by windows HQ

**Comment by jc3213** [comment]
I'm using Nightly 3.3.13267 on Windows 10 LTSC 2019(1809) 64bit. I've installed Japanese fonts as well when I installed Japanese IME from Windows Update.
![font installed](https://user-images.githubusercontent.com/8744936/108625601-c4230080-7486-11eb-87ec-7f79fc4bd0ef.png)

**Comment by GitHubRulesOK** [comment]
I am using an English 10H2 **1904**2.804 without supplemental fonts active (although I had loaded Japanese in the past) thus I cant say if updating windows or altering locale would help. Either way it looks like we have different font substitution's at play. I will try to determine exactly which font is actually at play in my case, but that may takes a while in comparing across multiple products.

**Comment by jc3213** [comment]
That's OK. I think SumatraPDF should have an option to overwrite rendering font-family for PDF files., and there's already an option (in advanced though) for ePUB.

Then even if the problem happens, I can just select a working font myself.

**Comment by GitHubRulesOK** [comment]
So far I see requested font as MS-Mincho,Bold-UniJIS-UTF16-V which seems to translate in another PDF viewer on my machine to **Yu Gothic** but in Wordpad it is **MS PGothic** thus not consistent between applications. If I had the font itself I would expect them to concur, still checking to see what acrobat will tell me.

**Comment by GitHubRulesOK** [comment]
Thats interesting Acrobat 9 agrees the font should be MS-Mincho
![image](https://user-images.githubusercontent.com/12754913/108626873-6670c300-744a-11eb-97c9-fdf8c92d25ff.png)

And on my machine that shows totally blank pages throughout (No Arial or Helvetica objects visible either) ! !

**Comment by GitHubRulesOK** [comment]
@kjk 
This is a case where showing the requested fonts would not help, i.e. where they are undefined locally (thus blank)
![image](https://user-images.githubusercontent.com/12754913/108627121-da5f9b00-744b-11eb-93c4-3a148523dc5a.png)
I understand font substitution for thousands/millions of bad font definitions is too much However
As seen in this issue it would be more useful to know which **local font** has been used as a substitute by MuPDF/Freetype,

**Comment by jc3213** [comment]
How to display which fonts have been used in property window? I only get very few info
![property](https://user-images.githubusercontent.com/8744936/108627790-4f55c380-7492-11eb-928d-8a9177cbb412.png)

**Comment by GitHubRulesOK** [comment]
THe secondary ctrl D screen is only active in debug versions, So would need to compile with it activated. the one I used above was a very old developer (zeniko) copy you may still find a link in an older thread.

**Comment by GitHubRulesOK** [comment]
@jc3213 
I have to say the cause effect and solution in this issue are the same as in many others.
Adobe Portable Files are often NOT portable and it IMHO borders on falsehood to claim they are ISO "STANDARD" when clearly they can be built and not displayed in the same fashion. As such I am temped to say the file is not a PDF but only parts of one. 
The best solution is to rebuild it as close to a valid PDF as is possible, and the simplest way to do that is to Print to PDF as has been done here.
[1893 default-print.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6018757/1893.default-print.pdf)

@kjk unsure if you wish to keep this open since Acrobat 9 will not render the file as its not valid and is similar issue to many others where fonts are not embedded NOR available as a universal font (MS-Mincho is designed for use within MS Office Products)

**Comment by kjk** [comment]
This is what shows in debug info:
```
couldn't find system font 'MS-Mincho'
couldn't find system font 'MS-Mincho'
couldn't find system font 'MS-Mincho'
couldn't find system font 'MS-Mincho'
couldn't find system font 'MS-Mincho,Bold'
couldn't find system font 'MS-Mincho'
couldn't find system font 'MS-Mincho,Bold'
couldn't find system font 'MS-Mincho'
```

Bottom line is: if using custom fonts, they should be embedded in PDF file. They are not embedded in this file so we try to substitute with the best font available, which is not always possible.

**Comment by jc3213** [comment]
@GitHubRulesOK Is there any batch tools to do the conversion? I have plenty of these `.pdf` novels

@kjk Any chance for an option that user can choose which font can be used? I think this should solve my problem, and other problem related to this.

**Comment by kjk** [comment]
@jc3213 that's unlikely to happen. would be a lot of work to accommodate a rare case

**Comment by jc3213** [comment]
Then I'll wait until https://github.com/sumatrapdfreader/sumatrapdf/issues/350 is implemented and try to solve the font problem on my side. Thanks for the reply

**Comment by GitHubRulesOK** [comment]
@jc3213   `"Is there any batch tools to do the conversion? I have plenty of these .pdf novel"`

The problem is  you need to replace the hinted font, to do that you normally use an editor OR in the browser where fonts look reasonable you need to make a print to Pdf.

The result I gave above was where Edge print to PDF only produces IMAGE.pdf thus there is no searchable text.
The better way to get searchable text is change the hinted font ether by print to PostScript based PDF with embedded fonts. OR tweak the font name (easier said than done) for example see if this file works for you ?
 I only changed font names on my machine by using MuPDF to open and save. So the fonts are not imbedded but perhaps they are better substituted on some machines?
[1893 default - Copy-mupdf.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6019208/1893.default.-.Copy-mupdf.pdf)

**Comment by jc3213** [comment]
@GitHubRulesOK That doesn't work, but thanks for the reply. I'll try the online converters to convert them to ePUB files
