### ISSUE TITLE
Provide 64bit builds

### ISSUE THREAD

**Issue by Stanzilla** [sumatrapdfreader/sumatrapdf#190]
Would be nice to get 64bit builds, especially for the development versions but release would be fine, too.

**Comment by renyouguo** [comment]
+1

**Comment by faramir** [comment]
Why is this important?

**Comment by Stanzilla** [comment]
It's not but 64bit is the future and it would be nice to have it.

**Comment by BillDimm** [comment]
Having a 64-bit IFilter for PDFs, so various 64-bit programs (search engines, document clustering software, etc.) can extract text from PDFs for analysis, is pretty important to some people.  You can't really expect such tools to remain 32-bit just so they can use a 32-bit IFilter, especially when 64-bit Windows doesn't ship with 32-bit IFilters (just 64-bit) for Office documents, which makes it really inconvenient to run 32-bit software that uses IFilters on 64-bit Windows.  The PDF IFilter is actually a good way for SumatraPDF to get its foot in the door since Adobe [wrecked their IFilter](http://zabkat.com/blog/adobe-ifilter-exposed.htm).  I've been recommending SumatraPDF to our clients for the IFilter (we provide both 32- and 64-bit versions of our software), but as more and more of them move to 64-bit Windows not having an official 64-bit SumatraPDF build is less than ideal.

**Comment by Stanzilla** [comment]
There are very well working 64bit builds here http://zeniko.ch/#SumatraPDF if anyone else is still looking for them.

**Comment by kjk** [comment]
Pre-release builds already offer official 64-bit builds: http://www.sumatrapdfreader.org/prerelease.html

See http://forums.fofou.org/sumatrapdf/topic?id=3184856

**Comment by Stanzilla** [comment]
Oh neat, thanks.

**Comment by cheesecracker** [comment]
Besides iFilter issue, there's also the thumbnail preview issue (or more exactly, the **absence** of thumbnail preview in 64-bit O/S if SumatraPDF is in 32-bit), as stated in https://code.google.com/p/sumatrapdf/issues/detail?id=1494

As a side-note: the 64-bit pre-release has effectively resolved the thumbnail preview issue.  Hooray \°/ !!

**Comment by vgturtle127** [comment]
For large or high resolution PDF or comic book archives, I can see SumatraPDF using more than 4GB of RAM. It could be useful for that too. *shrug*

**Comment by Stanzilla** [comment]
64bit builds are out!

**Comment by chenzx** [comment]
i found Sumatra 3.0+ supports epub very well, it's better than the ugly adobe, well done!!!
