### ISSUE TITLE
Can support for OFD file format be added

### ISSUE THREAD

**Issue by realcirno** [sumatrapdfreader/sumatrapdf#1909]
Can support for OFD file format be added？？

**Comment by GitHubRulesOK** [comment]
There are many variants of .ofd such as Office Forms Data (which I guess is NOT the one you mean since OXPS or XPS is the only similar MS format supported and that is becoming less and less common. MS no longer provide the viewer in newer win10 installs)

I am guessing you mean Ofd (open fixed layout document format), a very **young format** standard independently developed by China, (GB/T 33190-2016) possibly more popular on Linux.

Although it is potentially a cross between other formats it is generally unheard of by most Non-Chinese Windows users, so may not get the ground swell to become popular. Here is what one looks like when opened in SumatraPDF
![image](https://user-images.githubusercontent.com/12754913/112309871-cce03f80-8c9b-11eb-9cbc-4f9faf7d6652.png)

**Comment by realcirno** [comment]
> There are many variants of .ofd such as Office Forms Data (which I guess is NOT the one you mean since OXPS or XPS is the only similar MS format supported and that is becoming less and less common. MS no longer provide the viewer in newer win10 installs)
> 
> I am guessing you mean Ofd (open fixed layout document format), a very **young format** standard independently developed by China, (GB/T 33190-2016) possibly more popular on Linux.
> 
> Although it is potentially a cross between other formats it is generally unheard of by most Non-Chinese Windows users, so may not get the ground swell to become popular. Here is what one looks like when opened in SumatraPDF
> ![image](https://user-images.githubusercontent.com/12754913/112310125-1b8dd980-8c9c-11eb-9524-5e58367a9c92.png)

Looking at how it develops, I also think that PDF is relatively popular. After all, this format needs the traction of big technology companies to become popular. I agree with you very much.
