### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by DhruvaSambrani** [sumatrapdfreader/sumatrapdf#1924]
https://gist.github.com/DhruvaSambrani/c505865e8632313d09da0f63d6c8a76d

**Comment by GitHubRulesOK** [comment]
I understand why you have redacted but unless @kjk sees a different crash report then
"HandleDdeCmds: '[Open("C:\Users\redacted\redacted\redacted.pdf", 0, 1, 0)]'"
does not indicate if any path filename UTF coding was an issue since I frequently have problems with folder names such as \ÅÐ ÓÆ\
can you confirm such paths were "simple" plain text

**Comment by DhruvaSambrani** [comment]
Yes, all paths were ASCII.

**Comment by DhruvaSambrani** [comment]
I had some 30 PDFs open, all paths were ASCII, but had spaces. I frankly think this is a false positive, it seemed like an overload crash more than anything, but added it anyway

**Comment by kjk** [comment]
Unfortunately (or fortunately?) the crash doesn't seem to happen in Sumatra code but in some thread whose purpose is unknown to me.
Not enough information to make progress.
