### ISSUE TITLE
Multi monitor issue- Sumatra Maximized in 2nd window leaves a gap at the very top 

### ISSUE THREAD

**Issue by dickeypjeep** [sumatrapdfreader/sumatrapdf#1931]
Working on a Windows 10 PC/Laptop (a Lenovo X1 Yoga), current and updated, with two monitors of different resolutions- 2560x1440 Primary, 1920x1080 Secondary. 

If SumatraPDF is maximized on the _secondary_ window, it leaves a small gap at the top of the window. This is an issue as you can click on the window *behind* Sumatra, which drives me crazy as I try to click the 'X' to close Sumatra, but instead I close the document or window I was working on behind Sumatra. 

Seems like an easy fix, but also not a big functionality issue. Just an irritation.

**Comment by GitHubRulesOK** [comment]
if not using latest **[daily](https://www.sumatrapdfreader.org/dailybuilds.html)** you will need to download at least the portable zip to confirm the problem is in present code

I don't have a problem with smaller secondary on win 7 and my win 10 is not currently in a position to test such a mix (but my graphics may not show up such behaviour since a few other similar reported "boundary" issues seem very dependant on hardware/scaling)

**Comment by dickeypjeep** [comment]
My apologies; the bug does *not* exist in the daily. Thanks for the quick note.

**Comment by GitHubRulesOK** [comment]
Thanks for feedback
