### ISSUE TITLE
cbr & cbz- enlarged, doesn't scroll properly

### ISSUE THREAD

**Issue by PIK54** [sumatrapdfreader/sumatrapdf#194]
Hi folks,

whenever I open a .cbr or .cbz, and then zoom in so that the page viewd covers the width of the screen, and then try to scroll down the page using mouse wheel, the page doesn't go all the way to the bottom of the actual page but goes to the next page. Of course, I can use the page down arrows, or the scroll bar, but when you're reading, it's kinda a hassle

**Comment by GitHubRulesOK** [comment]
@PIK54 
This is a common problem with all PDF page mode readers based on Adobe PDF files,
Exactly the same behaviour is used here for comic book pages
When in page mode rather than "continuous scroll" mode then there is a point at which the bottom edge of one sheet touches the bottom of the screen and the next page starts at oddly the top of the screen. That may not be intuitive but it is the way it has all ways been designed to work since the days of Acrobat for DOS.

There are other comic book readers that can ignore the page structure in a CBZ and work on "frames" such as those saved in acbf format but SumatraPDF only reads them as plain CBZ

**Comment by kjk** [comment]
I'm not sure what the request here is.

Do you want mouse wheel to not turn pages? Then someone will complain and ask for mouse wheel to turn pages.

As far as I can tell in the scenario you described, mouse wheel does go to the bottom of the page, it's just easy to flip to the next page. At least with my mouse.

**Comment by GitHubRulesOK** [comment]
@kjk this is one of those cases I refer to in #1307 where the uses needs page mode zoom but RH document scroll However the action in this scenario would be exactly the same disorientating jarring jump from screen bottom focus to top focus like reading a book !

**Comment by GitHubRulesOK** [comment]
With all the recent changes this request should now be covered by 
Set scrollbars to ON/OFF as desired, 
Set continuous using either Icon or <kbd>C</kbd>
 and Zoom to Fit Width (or otherwise).
