### ISSUE TITLE
Sumatrapdf crash  windows 10 

### ISSUE THREAD

**Issue by fedikhatib** [sumatrapdfreader/sumatrapdf#1946]
link to the crash log 
https://gist.github.com/fedikhatib/9be9bf923b545752ed36a7d0fad8e446

**Comment by kjk** [comment]
Unfortunately, the symbols failed to download:
```
HttpGet: url: 'https://kjkpubsf.sfo2.digitaloceanspaces.com/software/sumatrapdf/rel/SumatraPDF-3.2-64.pdb.lzsa'
HttpGet: InternetReadFile failed
```
which means the callstack has no information:
```
Crashed thread:
00007FF7F2E8428F 01:00000000000F328F sumatrapdf.exe
00007FF7F2E85F10 01:00000000000F4F10 sumatrapdf.exe
00007FF7F2E8683C 01:00000000000F583C sumatrapdf.exe
```
Not enough information to investigate.

Please re-open if happens again. Better yet, provide instructions on how to reproduce the crash.

**Comment by GitHubRulesOK** [comment]
@fedikhatib
I note you are using formal 3.2, and since this crash was not tracible, unless you can repeat after debug > download symbols, then can I suggest you consider updating to daily version.

@kjk I was surprised by the number of concurrent references to sumatrapdf.exe, is that normal when as far as I could see 30 tabs were supposedly open in the one crashed session?
