### ISSUE TITLE
DefaultDisplayMode automatic

### ISSUE THREAD

**Issue by lwl504** [sumatrapdfreader/sumatrapdf#1948]
In my opinion, the default value of 'DefaultDisplayMode' automatic means:
if the page width is larger than height, the effect should by like 'single page'.

**Comment by GitHubRulesOK** [comment]
The LAYOUT name Automatic was first set in 2009 to add  a **default** automatic opening behaviour between single centred or double spreads in continuous mode, and you have 6 other choices of setting those to your preferred default on opening.

It is perhaps misleading that the settings file name is not `DefaultLayoutMode`
however in the code it was part of displayMode
```
memzero(ds, sizeof(DisplayState));
    ds->displayMode = DM_AUTOMATIC;
```

The secondary preferences for ZOOM to Fit Width or Fit Page are not directly controlled by "Automatic"

In all cases AFAIK there is no regard for Portrait/Landscape variations on opening, since that would in turn need a much greater array of permutations.

**Comment by kjk** [comment]
We're not going to change that after 10 years.
