### ISSUE TITLE
Send current file/page to other apps

### ISSUE THREAD

**Issue by fpopineau** [sumatrapdfreader/sumatrapdf#195]
Hi,
I'm an happy user of SumatraPDF for years now, especially because it was supporting forward/inverse search for TeX. I am also an happy user of Emacs and today, with the ubiquitous Org mode, I would like to be able to capture the location I am reading. A configurable button allowing to run a command with the current filename and current page as argument would do it.
Thanks a lot for SumatraPDF and keep up the good work.

**Comment by GitHubRulesOK** [comment]
@kjk This requirement to pass filename and current page can be addressed by use of [external viewer] option and suggest that is probably adequate for reconfiguration (closed) IF a button is not to be introduced

**Comment by GitHubRulesOK** [comment]
@kjk I think this is already covered otherwise perhaps consolidate with current discussion in #1280

**Comment by GitHubRulesOK** [comment]
@fpopineau 
The ability to pass current filename ("%f") and page number (%p) to another external application and run using a configurable keyboard shortcut is covered many times here and in forum i.e. search for the word ExternalViewers.
Tthus the only bit missing in your original request is to run from a button which I take to mean via a toolbar icon which means this request is no different to all those users that want their preferred Icon using just another few percent of reading space. If all the commands were to occupy screen space it would no longer be lightweight nor an uncluttered viewer.
Since this thread is already crosslinked to #1280 I am closing as the core requirement is already met

**Comment by fpopineau** [comment]
Thanks for the answer. I must admit that at the time I asked, I overlooked the fact that there were configurable keyboard shortcuts, which are much better than buttons/toolbar icons.
