### ISSUE TITLE
 Are there plans to support image printing? 

### ISSUE THREAD

**Issue by sujiewen** [sumatrapdfreader/sumatrapdf#1951]
Are there plans to support image printing? Now there is a blank problem when printing pictures !

**Comment by GitHubRulesOK** [comment]
Printing is by definition always "Print As Image" (since v3.1 and optional before then)
Has always been working, except when using inferior Print Drivers OR MS rolled out bad updates in March.
So you need to check if you updated then (or since), and update again, or give a better description of why it is not working for you
