### ISSUE TITLE
Thunderbird and Firefox fail to open new pdfs if tabs are used

### ISSUE THREAD

**Issue by qnxor** [sumatrapdfreader/sumatrapdf#196]
Windows 8.1 Pro x64, all recent versions of Thunderbird (31.\* and 38 beta too). If I enable tabs in Sumatra and if a pdf is already open in Sumatra, then trying to open another pdf from Thunderbird using Sumatra fails ... nothing happens. No error either. It just doesn't open anything.

If I disable tabs in Sumatra then it works fine, i.e. Sumatra opens a new window with the new pdf.

Happy to debug. Any pointers?

p.s. Firefox too, but I don't use Sumatra there too much.

**Comment by GitHubRulesOK** [comment]
@qnxor 
I guess you stuck without using tabs unless there was a significant change in the past.
If this issue is no longer a problem for you and there are no "me too's" do you allow it to be closed?

**Comment by kjk** [comment]
From the symptoms looks like admin (existing Sumatra process) vs. non-admin (Thunderbird) launcher.

It works without tabs because if tabs are disabled, we start a new process (unless -reuse-instance cmd-line option is given).

Can't really fix it but #1609 is to notify about this issue so that it doesn't fail silently.
