### ISSUE TITLE
C++17 and the 'register' keyword

### ISSUE THREAD

**Issue by gvanem** [sumatrapdfreader/sumatrapdf#1983]
Using `clang-cl` to build SumatraPDF, it fails on the use of `register` in `ext/libdjvu/GBitmap.h`:
```c
inline int
GBitmap::read_run(unsigned char *&data)
{
  register int z=*data++;
  return (z>=RUNOVERFLOWVALUE)?
    ((z&~RUNOVERFLOWVALUE)<<8)|(*data++):z;
}

inline int
GBitmap::read_run(const unsigned char *&data)
{
  register int z=*data++;
  return (z>=RUNOVERFLOWVALUE)?
    ((z&~RUNOVERFLOWVALUE)<<8)|(*data++):z;
}
```

clang-cl error:
```
In file included from ext/libdjvu/DjVuToPS.cpp:71:
./ext/libdjvu/GBitmap.h(623,3): error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
  register int z=*data++;
  ^~~~~~~~~
./ext/libdjvu/GBitmap.h(631,3): error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
  register int z=*data++;
  ^~~~~~~~~
2 errors generated.
```

I used `-std:c++latest` in my `CFLAGS`. Which on clang-cl ver. 12 is C++17.

Trying `-std:c++14` since it's mentioned in `clang-cl -?`  does *not* work at all.

So I simply removed those `register` keywords.

**Comment by kjk** [comment]
I don't use clang-cl myself and I don't modify external libraries (like libdjuv) if I can avoid it.

If you have a custom build process then I bet clang-cl has an option to disable this warning (-Wno-register ?].

The second best approach would be to add equivalent of `#define register` when compiling libdjvu. Again, I bet clang-cl has a cmd-line option to achieve that.

You could also report this to libdjvu so that they change it and then Sumatra would inherit such fix.

But like I said, I modify external libraries only when everything else fails.
