### ISSUE TITLE
More keyboard shortcut for annotations

### ISSUE THREAD

**Issue by RamonUnch** [sumatrapdfreader/sumatrapdf#2002]
I like very much the ability to highlight text with the `a` key and to highlight+annotate with `Shift+A`.
However I think more shortcuts of this kind should be available for adding/editing annotations.

In particular I think the DEL key should strikeout the selected text (`Shift+DEL` to also open the annotation panel).
I also think the `INSERT` key could be used to add a floating text comment, where the cursor is pointed.

It would be preferable in my opinion to set the keyboard focus to the **Contents:** Edit field by default, when pressing `Shift+A`, so that one would directly type in the comment instead of having to click into the field before typing the comment.

Also in the Annotations list, the DEL key could be available to delete the selected annotation in addition to the `Delete annotation` button (it is usual to have the DEL key to delete an item in a list).

When deleting an annotation in the list, the previous or next annotation should be automatically selected, so that it is not necessary to click on it to see its content.

Maybe some of those suggestions are already in your plans, but I would like very much to see any of those implemented.

**Comment by GitHubRulesOK** [comment]
I think the last one above may need an edit as the latest changes still allow using context "edit annotation" to GoTo exact editor entry from selected annotation under cursor **but no longer says so** (its a "hidden" feature and can't remember if its mentioned in the documentation) it is then trivial to click on the delete word rather than find the DEL key
Note I think the reverse "scroll to exact annotation on page" is not available from editor which **was** mentioned in passing in another issue.
I suggest test latest daily and reduce multi-requests towards Each key issue as then its more likely to be implemented and closed.

**Comment by kjk** [comment]
> Finally It would be nice also to have the ability to edit the content of an annotation without having to look through the whole list

I believe this is already possible: position mouse over annotation, right click, select "Edit Annotations". The annotation under mouse cursor should be auto-selected in the list.

When editor window is already visible, use right click and "Select Annotation In Editor".

**Comment by RamonUnch** [comment]
> I believe this is already possible: position mouse over annotation, right click, select "Edit Annotations". The annotation under mouse cursor should be auto-selected in the list.

I was indeed using latest daily build, but I had not realized that, now that I understand, navigation is much more easy.
Why do you hide the `Select Annotation in Editor` when the editor window is closed? the `Edit Annotations` is the same verb that is used when clicking anywhere on the document, it is a bit tricky to figure out that it will select the annotation in the editor.

Thanks a lot for the info, it is vert helpful. I had not seen that, I should have dug more.

**Comment by GitHubRulesOK** [comment]
@RamonUnch 
Check out current build as there was a change based on your observation then perhaps please revise your Original Post to reflect current shortages

**Comment by RamonUnch** [comment]
Thanks a lot for your efforts, I think the grayed menu entries are not bloating the context menu (that remains small) and are giving usefull hints to the user.

**Comment by kurbi** [comment]
I'm using version 3.4.14210 and there seems to be no "add text annotation" hotkey.

(I hope I'll have some spare time to inspect the code by myself :) )

**Comment by GitHubRulesOK** [comment]
@kurbi 
see open issue https://github.com/sumatrapdfreader/sumatrapdf/issues/2468 so watch for any change in that

**Comment by GitHubRulesOK** [comment]
@RamonUnch 
With all the recent changes you can now assign most of your requested enhancements to add your own shortcuts
![image](https://user-images.githubusercontent.com/12754913/163696356-3e5aa146-cdb7-42b0-ba51-46cc4993d66b.png)

For any new shortage in your usage, please only mention one item per remaining issue since multiples like this get closed on the basis the most important aspect is addressed

**Comment by koppor** [comment]
GitHub issue search finds this issue as first for "StrikeOut". Therefore, I post the solution here.

I have following settings - and they work:

```
Shortcuts [
	[
		Cmd = CmdCreateAnnotStrikeOut
		Key = Del
	]
	[
		Cmd = CmdCreateAnnotText
		Key = Ins
	]
	[
		Cmd = CmdCreateAnnotCaret
		Key = Shift+Ins
	]
]
```

One can reach the .txt file to insert via the menu:

<img width="488" height="394" alt="Image" src="https://github.com/user-attachments/assets/cba2e512-3119-4357-9028-b422b6de543f" />
