### ISSUE TITLE
Regression: With multiple windows open, SessionState is not properly saved on application exit

### ISSUE THREAD

**Issue by hg421** [sumatrapdfreader/sumatrapdf#2024]
## Issue
In version 3.3 there is a bug with saving the session state on application exit (by File->Exit, or <kbd>Ctrl</kbd>+<kbd>Q</kbd>) with more than one window open:

In this case, the state of **only one** window is being stored in the `SessionState` array, while the states of the other windows are lost.

With version 3.2 all windows were saved (and hence, restored on next launch).

## Cause
This problem looks to be an unfortunate side effect of the fix for issue #1659 (which was that the session state was only saved on exit, hence was lost if Sumatra didn't terminate gracefully).
Now, the session state is always kept up to date over the application lifetime.
Specifically, commit 351f73d1e2b8269b3a6262987e72c3ea21727fd0 changes `prefs::Save()` so that it always calls `RememberSessionState`, which means that on each call to `prefs::Save()` we store the current state of all windows to disk.
In particular, this happens every time a window is closed by `CloseWindow`.

Now, the problem is that `OnMenuExit` closes all the windows by iterating over them and calling `CloseWindow` for each one:
https://github.com/sumatrapdfreader/sumatrapdf/blob/8578d1723a7beac5eb627e3cc0dac2169a92fad1/src/SumatraPDF.cpp#L2157-L2160
Consequently the current session state (when some windows may be already closed) is getting saved before **each window closing**. And what finally ends up in the settings file is the state before closing the *last* window, which explains that only one window remains.

By the way, in version 3.2 this problem was avoided because `RememberSessionState` used to be called only *once*  by `OnMenuExit` but then not by `CloseWindow`. See old code in `CloseWindow`:
https://github.com/sumatrapdfreader/sumatrapdf/blob/ff1e03f71c9783273ad1ec2562d6265ddc091a87/src/SumatraPDF.cpp#L2390-L2395
(note: since, before the fix of #1659, sessionData was normally empty when the app was running, it could check that to find out whether `OnMenuExit` had saved it already...)

## Fix
I'm not sure what is the best way to fix this... we would probably have to prevent `RememberSessionState` from being called while `OnMenuExit` is closing the windows one by one...
(e.g. separating `RememberSessionState` from `prefs::Save()` again; or have some way to tell `prefs::Save()` not to call `RememberSessionState`?)

**Comment by GitHubRulesOK** [comment]
I would need to look more closely. The initial problem with 3.1.2 was NO session data held until clean closure.
That was considered a bug & fixed for #1659 by saving session state progressively TO settings rather than only on termination. (We get fewer complaints per month about MS Updates taskkilling SumatraPDF)

Adding a second window to a session naturally results in a "Last man standing" writing to final settings issue which is what some users require ! (Dont open all my old tabs from another session that dont work)

@kjk will need to confirm but I have not noticed any difference apart from before bug fix and after bug fix. The extra wrinkle in the ointment is the introduction of "New Window" which now adds a difference in user behaviours as AFAIK only the Current Master Session is allowed for in settings. However I will look to see if there was a regression.

**Comment by hg421** [comment]
> Adding a second window to a session naturally results in a "Last man standing" writing to final settings issue which is what some users require ! (Dont open all my old tabs from another session that dont work)

hm, not sure if I understand you correctly, what do you mean with "from another session"? AFAICT Sumatra seems to support just one session (per settings file)...
But that one session can contain several windows, which also seems to be by design (since SessionState is implemented as an array of TabStates).
>will need to confirm but I have not noticed any difference apart from before bug fix and after bug fix. The extra wrinkle in the ointment is the introduction of "New Window" which now adds a difference in user behaviours as AFAIK only the Current Master Session is allowed for in settings. However I will look to see if there was a regression.
Well there is definitely a difference in behavior between versions 3.2 and 3.3.
Following these steps
1. launch Sumatra with fresh settings file
2. open file A, file B (in 2 tabs)
3. File->New Window
4. open file C, file D in second window
5. File->Exit
6. launch again

With version 3.2 both windows will be restored (and the SessionState array contains both windows).
With version 3.3 only one of them. (BTW, *before* hitting File->Exit, it contains all the windows, which confirms that the problem is with how application exit is handled.)
So it indeed seems to me that the fix of #1659 introduced the change, see original post...

**Comment by kjk** [comment]
@hg421 Thanks for great report and investigation.

Yeah, this code is tricky and should have had more thought put into it when originally implemented.

But here we, adding band-aids.

I'm not opposed to a "dirty" solution e.g. a global flag that says `don't save preferences anymore`. In clean shutdown scenario make sure to save state early enough that it represents the correct app state, set the flag and then ignore any subsequent calls so that it doesn't get corrupted.

**Comment by hg421** [comment]
> 
> 
> @hg421 Thanks for great report and investigation.
> 
> Yeah, this code is tricky and should have had more thought put into it when originally implemented.
> 
> But here we are, adding band-aids.
> 
> I'm not opposed to a "dirty" solution e.g. a global flag that says `don't save preferences anymore`. In clean shutdown scenario make sure to save state early enough that it represents the correct app state, set the flag and then ignore any subsequent calls so that it doesn't get corrupted.

Ok, thanks for the confirmation! 
Well, as you say a global flag seems to be the most straightforward workaround,
I've tried to add that and it apparently works for me when testing locally.
I will open a PR so you could have a look at it...

**Comment by hg421** [comment]
@kjk thanks for merging!
Latest build is working fine now 👍
