### ISSUE TITLE
sumatra don't open some pdf

### ISSUE THREAD

**Issue by fabdoc** [sumatrapdfreader/sumatrapdf#2053]
trying to open some pdf, sumatra 3.3.3 tell that there is an error, but other reader can read this files
[21072411262254627_ricevuta.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6872285/21072411262254627_ricevuta.pdf)

**Comment by kjk** [comment]
According to mupdf, it's an invalid PDF:
```
cannot find startxref
trying to repair broken xref
repairing PDF document
syntax error in object (16 0 R)
cannot load object (16 0 R) into cache
document has no pages
```

**Comment by GitHubRulesOK** [comment]
The `cannot find startxref` is **usually** an indicator of two common conditions (in formerly good files)
1) the file is truncated (incomplete) possibly due to an interrupted download
2) an edit failed to rewrite the new end of file **correctly** leaving the file "xref less" (even if it has multiple xrefs)

MuPDF will trace any broken xref(s) as best it can before giving up on other bad entries (in this case object 16)

The next common issue is
3) the file was built badly so some PDF readers may struggle to understand how to trace objects, is also too common with the use of hundreds of  user defined libraries rather than mainstream ones. (even Acrobat API can be abused)

This file fits into ALL above categories
 A signature was attempted to be added (stuffed  into the start of file) but failed to terminate thus both the signature and the file are totally invalid.

**Comment by GitHubRulesOK** [comment]
Here I corrected the file but that signature is not mine so also should not be trusted
![image](https://user-images.githubusercontent.com/12754913/126876162-fd4cccb4-cbb5-4d4d-878b-fcc0c16a5201.png)
[2053 21072411262254627_ricevuta (2).pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6872806/2053.21072411262254627_ricevuta.2.pdf)

**Comment by fabdoc** [comment]
thank you very much.
anywhay browsers and other pdf reader can display this pdf.
i use sumatra as default but thoose pdf generated from minister of economy i wish to view directly without modification.
why sumatra don't open at all instead of oen and notify that pdf is bad?

**Comment by kjk** [comment]
I've opened mupdf bug about this issue: https://bugs.ghostscript.com/show_bug.cgi?id=704138

If they implement a fix, we'll inherit it

**Comment by GitHubRulesOK** [comment]
@kjk looks like mupdf added a means to handle this type of broken file by working around the bad data.

**Comment by kjk** [comment]
Fixed in latest pre-release https://www.sumatrapdfreader.org/prerelease
