### ISSUE TITLE
Wrong characters for special danish letter æøå ÆØÅ in version 3.3.3-64 bit

### ISSUE THREAD

**Issue by wmb356** [sumatrapdfreader/sumatrapdf#2069]
Wrong symbols for special danish letters æøå ÆØÅ in version 3.3.3-64 bit.
The pdf file shows correct symbols in Firefox browser, but wrong characters in SumatraPdf 3.3.3-64 bit.

**Comment by GitHubRulesOK** [comment]
**Cant check without a sample,** However it is usually a poorly defined files font.

If the glyphs are one of the older Standard Fonts OR correctly sub-setted inside the file as recommended by Adobe to be a portable document, then SumatraPDF should display the included font characters.

**Comment by wmb356** [comment]
Hi
I have both versions of SumatraPdf installed on Microsoft Windows [Version 10.0.19042.1110].
Attached you can see clip from the screen after opening a pdf file containing special danish letters, æøå.
Regards Jan

**Correct, using 3.3.2-64 bit:**

![correct-clip-from-3 3 2](https://user-images.githubusercontent.com/18662516/127444203-79809d07-dbd7-46cc-af62-e6e737e79dd1.PNG)

**Wrong, using 3.3.3-64 bit:**

![wrong-clip-from-3 3 3](https://user-images.githubusercontent.com/18662516/127444204-91272a84-46f2-43f3-83d7-9676893cd2d2.PNG)

**Comment by GitHubRulesOK** [comment]
@wmb356 
Whilst possible, It would be odd if the difference is between 3.3.3 and 3.3.2 (so few changes)
Did you close accidentally, or find a reason for the difference ? A sample file would help if a fix is needed.

**Comment by wmb356** [comment]
Correction: The correct version of the pdf-file is shown when opened in SumatraPdf version 3.2-64 bit
The wrong version of the pdf-file is shown when opened in SumatraPdf version 3.3.2-64 bit
Sorry - my mistake (using copy-paste).

**Comment by GitHubRulesOK** [comment]
@wmb356 
As I show there **should** be no problem with 3.3.3 (the latest formal release)
Can you please test with a portable copy of [3.4 pre-release](https://www.sumatrapdfreader.org/prerelease.html) but **if it shows incorrectly**
you can paste a public copy here or email in confidence to KJK

**Comment by wmb356** [comment]
Hi - Installed pre-release: v3.4.13949 64-bit and opened the pdf-file in question.
The pdf-file is still shown with wrong letters, instead of danish letters.

**Comment by GitHubRulesOK** [comment]
OK then it is that file or type of contents that is the problem since other Danish files are good to view.
It sounds like it is a bad font definition that would also be poorly shown by viewing the page in [MuPDF 1.18 viewer ](https://mupdf.com/downloads/index.html)) (the PDF engine that SumatraPDF is built upon.

If the document/brochure is public please try to drag and drop or upload into your reply
If it is personal / private then either try to find identical problem  public file or send the problem  file to KJK by email

**Comment by wmb356** [comment]
Very strange !!! 
I downloaded mupdf-1.18.0-windows.zip and ran mupdf.exe, thereby loading the pdf-file. The file is shown with the correct danish letters in this version of MuPdf.

**Comment by GitHubRulesOK** [comment]
I did understand the contents could be personalised, hence request for a similar file perhaps a more generic document **from the same provider** as it is likely but not definite that they use the same creation library to build personal and public PDF documents.

Your confirmation that it works in MuPDF 1.18 and 3.2 do suggest a regression either in recent MuPDF library or potentially SumatraPDF itself, thus should be a valid open issue. The problem is without a sample for testing then the developer cannot fix this or similar failings.

**Comment by esskov** [comment]
I can confirm that this problem is unresolved - unsurprisingly as ver 3.3.3-64 bit is still the current version. So why is this issue closed actually?

**Comment by kjk** [comment]
The person who created the issue closed it.

Furthermore: is it fixed in https://www.sumatrapdfreader.org/prerelease ? If yes, then it's fixed. The bug tracker represents the latest state of the code, not the state of latest release.

If it's not fixed in pre-release then create a new issue and provide a sample document showing the problem.

I can't fix a problem I can't see and this issue doesn't contain any sample files.

**Comment by esskov** [comment]
Ok, I understand - thanks for the clarification. I'll test the prerelease version.
-------- Original message --------From: Krzysztof Kowalczyk ***@***.***> Date: 17/04/2022  23.56  (GMT+01:00) To: sumatrapdfreader/sumatrapdf ***@***.***> Cc: esskov ***@***.***>, Comment ***@***.***> Subject: Re: [sumatrapdfreader/sumatrapdf] Wrong characters for special danish letter æøå ÆØÅ in version 3.3.3-64 bit (#2069) 
The person who created the issue closed it.
Furthermore: is it fixed in https://www.sumatrapdfreader.org/prerelease ? If yes, then it's fixed. The bug tracker represents the latest state of the code, not the state of latest release.
If it's not fixed in pre-release then create a new issue and provide a sample document showing the problem.
I can't fix a problem I can't see and this issue doesn't contain any sample files.

**Comment by wmb356** [comment]
Hi

I cannot remember if I closed the issue !!!

I deleted version 3.3.3-64 bit

I am still using 3.2-64 bit.

Regards Jan

**Comment by esskov** [comment]
I have now tested the same two documents with SumatraPDF-prerel-64
(portable) build 14471, and can confirm that the problem is no longer
present!
So no reason to re-open this issue - but looking forward to the release :-)

    E.

Den man. 18. apr. 2022 kl. 23.05 skrev E.S. ***@***.***>:
