### ISSUE TITLE
Always prompts that annotations exist on exit, even if none exist

### ISSUE THREAD

**Issue by a1346054** [sumatrapdfreader/sumatrapdf#2091]
Whenever I try to exit sumatra, it always prompts me that there are unsaved annotations.

I never created any annotations in that PDF file. Even if I click Discard, and then open the same file again, and close it again, then it will yet again ask what to do with unsaved annotations.

This is the dialog that I'm talking about:
![sumatra](https://user-images.githubusercontent.com/36859588/128028372-bcc90139-ec33-48a6-bdcc-beb16573ba38.png)

It happens with many PDF files, not just one. I cannot attach the PDFs because of their sensitive contents. The PDFs are also digitally signed, so they *must never* be changed by sumatra in any way. Providing a workaround to completely disable all annotation editing would be welcome too.

These are the Document Properties as shown in sumatra:
![form](https://user-images.githubusercontent.com/36859588/128029561-5902a0ac-3732-40ef-868d-aaaa6deb7f6e.png)

Happens in both SumatraPDF 3.3.1 and 3.3.3, 64bit on Windows 10.

**Comment by GitHubRulesOK** [comment]
Without a sample the following is just conjecture. SumatraPDF should be safe enough but is based on MuPDF code.
To avoid the changed signal you would currently need to use version 3.3.3.
A PDF/A should be static (that is the reason for /Archive) so am surprised if they self modify. It is a mistake to use dynamic signing since the certification will eventually fail in time defeating archiving.

It is most likely the signatures are the trigger, but not always.

A PDF can be programmed to alter its appearance, such as a field showing todays date, or communicate with adobe HQ to show the file is opened at a specific location and verify the content with a tick, thus may trigger a flag it has changed (itself). Annotation is one such area where objects can include that flag.

MuPDF should restrict actions that could be abused, but are under client pressure to "improve" functionality in matching newer PDF structures. Sensitive files (such as those with self certification) are best opened in a secured Adobe viewer where web beacons can be enabled or restricted as desired.

**Comment by a1346054** [comment]
From my testing, it doesn't matter if I click Discard, Save changes to existing PDF or Save changes to a new PDF. The original PDF is never modified, and a newly saved PDF also has the same sha256sum as the original PDF.

However, it is still worrying messaging/behavior from sumatra.

**Comment by kjk** [comment]
Which version of Sumatra?
Does it still happen with pre-release builds from https://www.sumatrapdfreader.org/prerelease ?

If yes, then we need to see the document that triggers this issue.

mupdf had this issue where the tracking of dirty status of the doc was not perfect for broken PDFs that had to be repaired by mupdf.

They improved this tracking recently and Sumatra merged their latest code but it could still happen.

Hence we need the document that shows the issue in order to fix it.

**Comment by GitHubRulesOK** [comment]
@kjk 
Stack overflow is full of dirty signatures even from reputable sources, its the fashionable way to corrupt a previous good PDF.

**Comment by a1346054** [comment]
Here's one PDF where you can experience the problem.

[template3.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6927672/template3.pdf)

**Comment by kjk** [comment]
Doesn't happen in latest pre-release builds (https://www.sumatrapdfreader.org/prerelease) so must have been fixed.

**Comment by a1346054** [comment]
Latest pre-release build indeed works. Is it safe to use the pre-release build? Will the fix for this particular issue come to a stable version of sumatrapdf soon-ish?
