### ISSUE TITLE
v3.4.13978 x64: Fails to open XML files (follow-up to #2093)

### ISSUE THREAD

**Issue by deus-e-x** [sumatrapdfreader/sumatrapdf#2094]
I cannot re-open a closed issue, so I raised a follow-up issue here:

Find attached an archive of example XML files that still either fail to display properly or at all in recent prerel-13978, but do render fine with prerel-13940.

I also included some example screenshots to document the differences. I hope that is of help to you.

[deus-ex_prerel-13978-64_XML_display_issue_examples.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/6929907/deus-ex_prerel-13978-64_XML_display_issue_examples.zip)

**Comment by GitHubRulesOK** [comment]
The files should appear reasonable in formal release 3.3.x since in the past they would just be handled as Plain Text

I note that About.xml does not have the header an xml file would be expected to have thus its technically corrupt and will show as blank if opened in Edge unless the header is added. The same for one or two others. Those should not be tagged.xml but simply .txt

One thing that surprised me was that **in some cases Edge will add the header itself** !! although not in the .xml file

**Comment by deus-e-x** [comment]
I simply made a recursive search for *.xml in my \Program Files (x86) folder and randomly picked a couple of files from the search result.

Btw, the XML files without a valid header are from the Winamp v5.6.6.3516 (Windows Media Player) distribution.

**Comment by GitHubRulesOK** [comment]
@deus-e-x 
I cant find13940 only 13936 so am presuming it's similar enough for comparison, there was no expanded support for XML it was simply opened as plaintext (with an xml extension) so was displayed in the legacy textual ebook UI (which could support some limited web links or mailto much like MD can)

**Comment by kjk** [comment]
@deus-e-x thanks. I've made a change to display .xml files as text, which fixes the examples you provided.
