### ISSUE TITLE
SumatraPDF-3.3.3-64-install bug

### ISSUE THREAD

**Issue by Pi56** [sumatrapdfreader/sumatrapdf#2096]
[2021.08.04 Bug Sumatra 3.3.3-64.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6930603/2021.08.04.Bug.Sumatra.3.3.3-64.pdf)

**Comment by GitHubRulesOK** [comment]
- Since 3.1.2+ SumatraPDF defaults to a single user installation. (Win 10 security changes make it much more difficult for some users to install mixed per user handlers) see https://github.com/sumatrapdfreader/sumatrapdf/issues/1287

_Dal 3.1.2+ SumatraPDF utilizza per impostazione predefinita un'installazione per un singolo utente_


- Administrators for multiple users should chose options carefully, based on usage, and install handlers as required into any common "Program Files" area they administer. Also they need to decide if their system shortcut should be added to "Public Desktop", Start Icons, Task Bar Icons or other usage preferences.

_Gli amministratori di più utenti devono scegliere attentamente le opzioni, in base all'utilizzo, e installare i gestori in base alle esigenze in qualsiasi area comune "Programmi" che amministrano. Inoltre, devono decidere se il loro collegamento di sistema deve essere aggiunto a "Desktop pubblico", icone start, icone della barra delle applicazioni o altre preferenze di utilizzo._
