### ISSUE TITLE
More a query than issue ReopenOnce

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#2098]
I note the ReopenOnce feature was added as "experimental" in https://github.com/sumatrapdfreader/sumatrapdf/commit/69c332b3ff5542c10e26e5d648ac118a24985dbe and was updated recently https://github.com/sumatrapdfreader/sumatrapdf/commit/2e0f04ccdf1d91e9b0ba63831f1ee12e59887916

Usually I have only one file open when updating thus am, from experience, not surprised that on update a single tab is **not normally reopened**, however I thought that was the reason for this addition since It should equally restore multiple session tabs in a similar fashion

**Comment by kjk** [comment]
As you can see, this was written in 2014, not by me, for a different auto-update system.

That setting is not actually used and I'll remove it.

I'm not sure if at the time we had auto-restore of files, because it makes reopenOnce list redundant.

The only difference would be for the case of a single file opened. My thinking behind not auto-reopening a single file is that the app starts with home page which has that file in Frequently Read list so it's easy to open a single file from there.

Longer term I want to have home page tab always visible (as opposed to hiding it when a file is opened) in which case it'll make sense to restore a even a single file on startup, but this is just an idea at this point.

**Comment by GitHubRulesOK** [comment]
I had used it as a workaround sometime a long long time ago so was surprised at the update but forgot how I ab-used it :-)
