### ISSUE TITLE
"Wobbly" rendering of letters in some documents

### ISSUE THREAD

**Issue by yuriks** [sumatrapdfreader/sumatrapdf#210]
I've seen a few documents where in certain zoom ranges the letters appear to "wobble" or "wave" up and down along lines. It makes reading quite distracting. Adobe reader doesn't have this problem: [Comparison Image](http://i.imgur.com/LK6G0Hs.png).

The pictured document is available at: http://www.cs.utsa.edu/~wagner/knuth/fasc1a.pdf

**Comment by kjk** [comment]
Confirmed it happens in master.

**Comment by GitHubRulesOK** [comment]
I am not sure how less "wobbly" the characters could be due to the dvi source of the glyphs
viewing the raw dvips in acrobat we see they are bitmaps as modified by ghostscript but MuPDF does not show the crude Type3 pixels it renders the PS glyphs positioned as best it can (possibly could be better)
![image](https://user-images.githubusercontent.com/12754913/86828668-712d4200-c08b-11ea-81f7-fec3832c3529.png)

Since SumatraPDF uses MuPDF (or GS for the PS versions) it could not correct for every character or glyph. This one has only 25 different font groups but similar ones can use way over 50 font types.

**Comment by GitHubRulesOK** [comment]
Old link is lost so here is a similar replacement but the issue still stands that MuPDF handles these bitmap Fonts differently to Acrobat. However, In my view it is as good as may be expected translating DIV fonts quickly.
![Screenshot 2021-07-14 002134](https://user-images.githubusercontent.com/12754913/125537622-51fd9035-40ea-40db-8797-17158b7be03b.png)
[fasc1.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6812514/fasc1.pdf)

**Comment by kjk** [comment]
Realistically, if mupdf doesn't fix it, I won't either. This needs to be reported to mupdf: https://bugs.ghostscript.com/
