### ISSUE TITLE
Feature Request: Restore Multiple Windows

### ISSUE THREAD

**Issue by sahil48** [sumatrapdfreader/sumatrapdf#2125]
If multiple windows are opened and user presses File > Exit, when they open SumatraPDF, all windows should be restored instead of the last window closed.

**Comment by GitHubRulesOK** [comment]
It usually does restore all previous session
Please test with current pre-release since it is possible your unknown version may be different and only pre-release can be changed.
Settings Options must include "Use tabs" and "Remember opened files" both Checked
There must be two or more tabs active when session is closed

If the above is true then current 3.4.14025 works for me.
Using update will close all and re-open thus "should" restore all tabs as they were
Using menu File > Exit should also restore all tabs next time unless the file locations were changed.

Same for Ctrl+Q or Alt+F4 or Top Right X
