### ISSUE TITLE
Annotations not working on .epub

### ISSUE THREAD

**Issue by Esentries** [sumatrapdfreader/sumatrapdf#2156]
Hi, thank you for making a simple PDF reader that makes stuff done. I really like how you can modify it through advanced options. There is just one thing I noticed whenever I open .epub files in which they don't highlight text. I am not sure if it's a bug or hasn't been implemented to other files that are not .pdf.

**Comment by GitHubRulesOK** [comment]
Latest versions can only add PDF annotation, they are a feature only of PDF format. 

Much older SumatraPDF had an experimental highlight only overlay for other types such as txt etc. which was removed due to conflicts with newer PDF annotation. 

There are very few readers that have ability to highlight all formats including those based on plain text such as ebooks, usually it can only be done well by using an extra file alongside every one, then there are two files to handle at a time.

**Comment by kjk** [comment]
There is no plan to annotations to epub. There is no standard for saving annotations in epub files.
