### ISSUE TITLE
Can't print multiple copies of multiple page documents

### ISSUE THREAD

**Issue by RedDragonWebDesign** [sumatrapdfreader/sumatrapdf#2168]
Steps to reproduce
- Open a document that has multiple pages
- Hit print. Settings dialogue opens.
- Set # of copies to 2
- Hit print. Printing begins.

Problem
- Will only print 1 copy. Should print 2 copies.
- I notice that, in the printing modal (e.g. printing page 1 of 7), Microsoft Office sends each page of each copy to the printer. Sumatra appears to only send each page of one copy. Not sure if it's a bug, or if the printer driver is not honoring the # of copies requested. But maybe this is a good idea... to send each page to the printer driver, repeatedly if needed.

Version
- Windows 7
- SumatraPDF v3.2 64-bit

**Comment by GitHubRulesOK** [comment]
It can depend on the driver, thus using 3.2 in my current win10 but expect similar behaviour in 7 some drivers are locked to one copy at a time, Most noticeably those that work using filename rather than physical sheets of paper . So the question is which print driver? and is it set to output to a paper port.

**Comment by GitHubRulesOK** [comment]
@kjk 
I suggest this is intentional Windows Print Driver behaviour and not SumatraPDF issue

For example with virtual MS print to PDF 1 is the Max (same for fax or text or other file type outputs)
![image](https://user-images.githubusercontent.com/12754913/228701846-8db63443-f5b8-47e1-ae96-a20cf30557b6.png)
send to a real physical printer, same file its over 1000 copies allowed
![image](https://user-images.githubusercontent.com/12754913/228702113-28ab501c-7878-4ee2-befc-c0c421b1ae47.png)

**Comment by GitHubRulesOK** [comment]
Closing as this appears to be an MS printing dialog intentional restriction and thus outside of SumatraPDF remit 
If a file is sent via command line or internal printing to  a prompt less virtual port  (generally a fixed filename) then MS limits the number of copies to one at a time !
