### ISSUE TITLE
Feature request: keyboard shortcut for Save Annotations

### ISSUE THREAD

**Issue by codito** [sumatrapdfreader/sumatrapdf#2169]
I use SumatraPDF to read and annotate literature. The highlight shortcut `a` is god-send :) Saving annotation takes a few additional clicks. It will be awesome to have a keyboard shortcut for Save Annotations or a keyboard mapping to work with `Alt + F`, similar to `Alt + F + S` for Save as.

![image](https://user-images.githubusercontent.com/28766/134807897-125b72a4-13f1-4c9e-a1fc-01ef1ae64048.png)

SumatraPDF version: v3.3.3 64-bit.

**Comment by GitHubRulesOK** [comment]
It is generally advisable to save annotations on closing file, (unless extensive changes have been made in a long session), since each incremental save can add an unnecessary overhead in saved storage of data and decoding multiple annotation indexes on file loading. Just adding and deleting all of a few comments, can quickly bloat a small file if save between  add and subtract.

 However changes can only be against current 3.4 pre-release.

**Comment by GitHubRulesOK** [comment]
related to https://github.com/sumatrapdfreader/sumatrapdf/issues/1388

**Comment by GitHubRulesOK** [comment]
Currently there are several ways to save whilst working apart from using the annotation editor.

The shortest key combination is use <kbd>Context</kbd><kbd>Up Arrow></kbd><kbd>Enter</kbd> (or Return)

**Comment by kjk** [comment]
Recently added `Ctrl-Shift-S` shortcut.
