### ISSUE TITLE
Tooltip and URL creation errors, 3.4.1.4210 pre-release

### ISSUE THREAD

**Issue by Amphiboly** [sumatrapdfreader/sumatrapdf#2233]
I see a few issues with the 20211028 pre-release. (I have not tested with prior pre-release versions.)

1. The most serious issue is that tooltips and links are, in some cases, improperly formed. The image shows a tooltip that should be for https://www.archive.org, but it and the link it represents point to https://www.archive.org/Languagehat. All of the tooltip links in the second column of the table include the first word from the next entry. 
2. In the non-tabular section, tooltips for the highlighted text take the form of the URL from the previous line plus the first word of the current line. For example, hovering over Languagehat I see https://www.archive.org/Languagehat. The resultant link, however, is correct.
3. Not all of the visible URLs are recognized and treated as links.

The first two problems do not appear in version 3.3.3. The third problem is much more prevalent in 3.3.3, and is what led me to test with the pre-release.

The uncompressed pdf and ConTeXt source are attached.

![image](https://user-images.githubusercontent.com/10307457/140201013-7fb3b8ce-fa7a-489e-b047-84b2c4ca5fce.png)
[earl.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/7470983/earl.pdf)
[earl.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/7470984/earl.txt)

**Comment by kjk** [comment]
Some of those issues are caused by auto-detection of URLs in the text, which is a heuristic.

In this particular document the auto-detected URLs are not always correct. In this particular case e.g. `https://www.archive.org/` seems to incorrectly capture `Languagehat` from the next line.

Also the rectangles for auto-detected links sometimes overlap with actual links in PDF and are shown / executed instead of them.

When clicking on a link, should give precedence to those actually in PDF over auto-detected.

And should improve auto-detection, although it's a loosing game either way.

**Comment by GitHubRulesOK** [comment]
I may be often wrong, but I think part of the issue it that a longline url gets wrapped at/
to continue next linerather than terminated.com#extra_data

And without sufficient white spacing between text blocks the overlap is in acrobat treated as if multiple lines are wrapped in the block a bonus for paragraph heuristics but a problem for hyperlinks.

**Comment by kjk** [comment]
There's also an issue with `ShowToolTip()` in `OnSetCursorMouseIdle()`.

Seems like there's delay where it might show the value from previous `ShowToolTip` call.
