### ISSUE TITLE
Multi-Page Tiff regression in recent build

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#2234]
[pr6D135939.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/7471678/pr6D135939.zip)

sample 7 page tiff 7 pages shown in prior versions up to 3.3 but only 1 shown in current 3.4.14210

**Comment by kjk** [comment]
This is a single multi-image .tif file.

Can it be because we switched to using Window's decoder instead of our own?

**Comment by GitHubRulesOK** [comment]
Now you mention it it also seems to apply to GIF animations e,g, Multipage GIF

ok in 3.3.3
ok in SumatraPDF-prerel-13952-64 about 2nd aug
broken in SumatraPDF-prerel-14060-64 which still had the ebookUI ? 26th Aug

**Comment by kjk** [comment]
The issue is we change default to `WICDecodeImageFromStream` from `Gdiplus::Bitmap::FromStream`, which only loads first image from multi-image files.

Simple solution is to change the order of decoders.

Less simple: would be to extend `WICDecodeImageFromStream` to decode all images in multi-image file.
