### ISSUE TITLE
Add a way to Delete a PDF

### ISSUE THREAD

**Issue by ludovicandrieux** [sumatrapdfreader/sumatrapdf#2246]
Hi,

In the menu file, you can do a lot of action like open, save, show in folder, rename or print but you cannot delete just delete the PDF and remove from viewing.

You could add this function ? 

You could add 2 shotkys :
* Key => Move to recycle bin
* Shift + Supp => Delete without recycle bin

Just a screenshot to show menu file and all actions already useful :
![2021-11-12_152307](https://user-images.githubusercontent.com/11213740/141482441-d0f3cbfa-9f38-4b81-980b-07b4bef297e2.jpg)
Sumatra 3.3.3 64bit

Thanks

**Comment by GitHubRulesOK** [comment]
There is a big problem that needs to be overcome in your request, since a file or its folder locked open in a tab by a viewer cannot be moved , try moving or deleting a pdf whilst acrobat is holding a file open.

SumatraPDF is slightly different so whilst that same problem would also be a blocker for many ebook or image files, 
SumatraPDF does not lock all files thus it is in some cases possible to move delete or manipulate smaller tabbed PDF files and then find on a later refresh they misbehave. But it would be confusing to allow for a few smaller files but not do it for some others or larger ones.

You can use SumatraPDF menu to show in folder and delete those smaller ones then refresh screen to see the reload failure.

Elsewhere I wrote a script to instantly store current file names that you wish deleted, then later when either all tabs are closed or you exit SumatraPDF you double click "deleteall" selected filenames, its quicker that way for multiple files that are known not to be locked open.

**Comment by ludovicandrieux** [comment]
Thanks for the technical details. However, I do not agree with your conclusion.

I use SumatraPDF precisely because in the majority of cases, it does not lock files while Acrobat leaves no choice. This was my first criterion of choice with its high opening speed. I understand that in some cases this is not possible (file too large) and usage would like us to display an error message in this case. I think users can figure it out.

Reading your various links, I read that the recommended method is: alt + f, f, supp, ctrl-w. Yes, it works but frankly the risk of error is high and it is not very user friendly.

You talk about images and I use for example Faststone viewer which also does not lock the images and leaves the user free of his choices. You can "supp" or "ctrl + supp" directly from the viewer and it's a real comfort. Faststone, even goes a little further than my basic request. If Faststone displays an image while in Explorer the file is moved or deleted, the software automatically changes the image to the next one but we are not there today with SumatraPDF.

**Comment by kjk** [comment]
Adding more file management functions to menu is too much.

Maybe when we have a command palette I'll add "Delete file" command.

**Comment by qwksilver** [comment]
actually you can just queue the item
c.lose and release the file when the delete key is pressed, wait 2 seconds or so then send the delete, if you get an error back, send a rename command. and append delete- to the front of the filename so it stands out later to be removed. if you still get a file open error, then....report error, file.....can't be deleted or marked.
