### ISSUE TITLE
Feature requests for frequently read

### ISSUE THREAD

**Issue by 2ndHouse** [sumatrapdfreader/sumatrapdf#2261]
Apologies if these have already been requested, I did a quick search. It would be handy for the frequently read main page to have a couple of small enhancements I think.

1. Displaying progress under book titles. "Page 4 of 8 (50%)", as an example.
2. Rectangular covers instead of square, to show more of the covers.

Maybe these could be included in the advanced options?

**Comment by GitHubRulesOK** [comment]
2) currently are 10 rectangles (all landscape or top half of portrait) would be less useful the other way?
  however  today the daily pre-release AFTER 3.5.15685 should increase that number from 10 to 30
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/80028f3e-373f-4b39-9d82-31a669927d2d)


1) might be possible to show from last history plus current tabs, 
but its another overhead to check if home tab has been selected, otherwise it would needs be a drain running constantly in background.

**Comment by kjk** [comment]
No plans to implement those due to lack of time.
