### ISSUE TITLE
some features in gui [Delete File & Open Document in New Window]

### ISSUE THREAD

**Issue by AblePart** [sumatrapdfreader/sumatrapdf#2275]
hi,

I watched source and saw `CmdDuplicateInNewWindow` to open document In new window! it's very handy. also added `Delete File` feature. I know `DeleteFile` API isn't cross platform but I am using sumatrapdf in Windows.

![menusumatra](https://user-images.githubusercontent.com/12184131/147835262-cc84586f-b6a2-40fa-813f-852ca5d5d513.png)

**git diff file :**
[sumatra.dif.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/7796849/sumatra.dif.txt)

**Comment by GitHubRulesOK** [comment]
Note the English word is Shif**t** and the E accelerator key is already used so would suggest &w for window (if not already used)

`+        _TRN("Open Document in new &window\tShift+Ctrl+N"),`

The issue with delete file is more complex since the files lock may not belong to SumatraPDF and when SumatraPDF applies its own locks they would need to be unlocked which may potentially cause  other knock-on issues, thus a lot more error checking of robust in all situations code would be needed before writing such menu selection

**Comment by kjk** [comment]
Adding too many menu options is overwhelming and makes the rest of the menu items harder to use.
