### ISSUE TITLE
Recent Crash 

### ISSUE THREAD

**Issue by RushilShandilya** [sumatrapdfreader/sumatrapdf#2279]
https://gist.github.com/RushilShandilya/e14f58a418292946cfed8fccd750dd86

**Comment by GitHubRulesOK** [comment]
Most likely cause is a significantly corrupt PDF since the fault starts with
```cannot find startxref
trying to repair broken xref
```
Recommend try to open such a file in current portable [pre-release](https://www.sumatrapdfreader.org/prerelease) to see if it can handle the corruptions better.

If not you will need to supply that PDF for analysis to see if there is a possible workaround for the corruption.

**Comment by kjk** [comment]
There's no symbols in callstack and no repro document / steps so can't do anything about it.
