### ISSUE TITLE
Crashes on starting

### ISSUE THREAD

**Issue by AndyThorby** [sumatrapdfreader/sumatrapdf#2287]
Exception: C0000094 INT_DIVIDE_BY_ZERO
Faulting IP: 00007FF8F4AB8C31 01:0000000000097C31 nviewh64.dll!DestroyThreadFeatureManager+0x3de1

https://gist.github.com/AndyThorby/2139f7d211852a0bcb6a7c46adca0abb

**Comment by GitHubRulesOK** [comment]
Your version is 3.3.3 64-bit which did have issues with some file types that have been addressed in current pre-Release which would be the one to include all the latest changes.  (However your long list of files does not include the ebook types that would be expected to potentially cause such a problem)

However I have to request you download a [portable 64bit pre-release](https://www.sumatrapdfreader.org/prerelease) and see if that works better with your file selection. **To automatically pick up your current file history** you need to place that single exe in the same folder as your current *SumatraPDF-settings.txt* it will alter the setting file slightly but should not change history. 
If that also crashes you may need to find if one file is the culprit. most likely is *FIRMAN_ONE_DESIGN_OFFICE\FR01\SUSPENSION ANALYSIS\FSUS\GEOMETRY\190823-1_FR01-FSUS-CP_LOADS.pdf'* but since your using `Dropbox` is that using a file synchronization  monitor or is it simply a un-monitored folder called that for convenience.

**Comment by kjk** [comment]
According to the callstack the crash happened in nvidia graphics card driver, not sumatra

**Comment by AndyThorby** [comment]
Thank you for your help. The portable version seems stable, but I will
check the Nvidia driver.
