### ISSUE TITLE
Is it possible to see the preview in file explorer of mobi files?

### ISSUE THREAD

**Issue by ComptonAlvaro** [sumatrapdfreader/sumatrapdf#2290]
I would like to know if it is possible to configure Sumatra Pdf to can preview mobi files and other supported formats, because in my case it only works with PDF files.

I have tried the portable version and  the install version of the application.

Thanks.

**Comment by GitHubRulesOK** [comment]
the potential was there, if you compile it yourself but only the PDF previewer is active in released versions, there were a few shortcomings for some filetypes and since icons for different types were not available that was a traditional reason for not including in any pre-release. I wiill close this query as duplicating issues

https://github.com/sumatrapdfreader/sumatrapdf/issues/1676 https://github.com/sumatrapdfreader/sumatrapdf/issues/382
https://github.com/sumatrapdfreader/sumatrapdf/issues/1677
https://github.com/sumatrapdfreader/sumatrapdf/issues/840
https://github.com/sumatrapdfreader/sumatrapdf/issues/1248
