### ISSUE TITLE
Some character sequences starting with 'f' are replaced with an 'unknown glyph' box

### ISSUE THREAD

**Issue by mcavanagh** [sumatrapdfreader/sumatrapdf#2291]
SumatraPDF Version: 3.3.3 64-bit (commit 21678b8)

Some character sequences beginning with 'f' are being replaced by an 'unknown glyph'-style box (see images below)

So far I have seen examples of this with the sequence 'fi' and 'fl'

![image](https://user-images.githubusercontent.com/6319592/150657735-09e8cb0d-98ae-404f-b943-479dbac184b1.png)

![image](https://user-images.githubusercontent.com/6319592/150657771-aec69344-4d22-4def-9e16-faea8d75f9c3.png)

The source document in question can be found at http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1548.pdf

A similar issue was reported here in 2014, but only for printing, not viewing:
https://github.com/sumatrapdfreader/sumatrapdf/issues/24

**Comment by GitHubRulesOK** [comment]
Those single glyphs will be "ligatures" where a single character was inserted by the PDF writer in place of two characters for aesthetics (but a constant thorn for font display and or print). Most commonly f+ but can be th and several others in some font styles. since they are not in the standard a-z range they are often not well defined in the font metrics/character look up table.

However the fonts in that file are basic type 1 and long established, but **only Courier and Symbols** are included the others are standard font as provided pre 1999 by the Operating System. 

Subject: Programming languages - C

Created: 1999-04-22 17:51:25
Modified: 2010-12-31 16:17:13

Fonts: Courier-Bold (Type1; embedded)
Symbol (Type1; embedded)
Times-Bold (Type1)
Times-Italic (Type1)
Times-Roman (Type1)


Unsure if we are looking at same file location but your first example in both 3.3.3 & current pre-release is fine in Windows 7 32bit
so will be closing on the basis it must be a machine font failing to provide those ligature characters, Are you using a standard windows set of fonts?

![image](https://user-images.githubusercontent.com/12754913/150662385-00c92b97-2f99-4d04-a9ea-797a56afa60e.png)


@kjk do you concur?

**Comment by mcavanagh** [comment]
Thanks for the explanation - happy for the issue to be closed.  I'm using what I assume to be the 'standard' set of fonts that come with windows 10.

For comparison, the in-browser pdf viewer in Chrome displays them as you'd expect - presumably that means the browser can choose to switch fonts to display the ligature glyphs? (apologies if this is simply not how pdf fonts work, I'm not familiar with the internals)

Based on the font details you listed, does that mean that if I have the Courier, Symbol and Times variants installed, I should expect it to display properly, or is the issue that none of those fonts can display the ligatures?

**Comment by GitHubRulesOK** [comment]
See the similar next days (today) question, which stems from similar font handling, so it appears to be version 3.3.3 that has problems on newer platforms, however it works on my current old Win7 !

**Comment by kjk** [comment]
On Win 11 for me it's broken with 3.3.3 but works with latest pre-release https://www.sumatrapdfreader.org/prerelease

**Comment by mcavanagh** [comment]
👍 Thanks both.
