### ISSUE TITLE
Add support for each section to have its own window

### ISSUE THREAD

**Issue by curiosport** [sumatrapdfreader/sumatrapdf#2306]
Each section should have its own independent window, at the moment when you want to open a second section Sumatra
 ignores the request, in short make this command work:

`SumatraPDF.exe -new-window -appdata <dir>`

**Comment by GitHubRulesOK** [comment]
-appdata absolute\folder [filename] is not a listed command and adds a second history location it was not intended for one history

Currently the historic way to get two windows without a second session you need to switch tabs OFF

To get one file in two windows there are simpler ways but manually use CTRL +  SHIFT  + N

**Comment by curiosport** [comment]
@GitHubRulesOK The solutions you offer do not allow multiple windows with multiple tabs in each window.

I only mentioned the command as a way of explaining the requested feature.

**Comment by GitHubRulesOK** [comment]
Here are two tabbed windows with version 3.3 (introduced) called from command line the manual method is the hotkey above if you need two sets of windows with seperate history you already have that via -appdata no need to call a new-window on command line
![image](https://user-images.githubusercontent.com/12754913/151723599-ac79cde5-2797-419f-bd88-6f5ca3ec8077.png)
```
sumatrapdf -page 1 c:\users\k\documents\sticker_book[1].pdf & sumatrapdf -new-window c:\users\k\documents\sticker_book[1].pdf
```

**Comment by curiosport** [comment]
@GitHubRulesOK Your last solution does not store a history and it is only for temporary use.

I already use -appdata to store the history of different sections the problem comes when I want to open two sections in two separate windows.

To put it another way:
`SumatraPDF.exe -appdata <dirSection1>`
`SumatraPDF.exe -appdata <dirSection2>`

When executing the second command Sumatra ignores it, the desired behavior is to open a second window.

**Comment by GitHubRulesOK** [comment]
Thats slightly different to what -new-window is designed for.

So lets think on this, you want one.exe to run two histories **which is not a good idea** they should be seperate sessions with their own memory and always done by having two exes even if one is a copy of portable in the same folder, hence that needed seperate folders with -appdata settings folders.

**Comment by curiosport** [comment]
Making Sumatra copies is what I wanted to avoid, a Sumatra process should be able to treat two sessions as separate instances without getting confused.

I guess that's it, the solution: make Sumatra copies.

**Comment by GitHubRulesOK** [comment]
OK I confirm the one exe in memory cannot thread two sessions after starting (seem to recollect that was mentioned sometime in the past), but solution for split personality was clone a twin.exe each using own -appdata

**Comment by curiosport** [comment]
And isn't it possible to use a single .exe and run several independent processes? I say this because making copies is a very ugly solution.

**Comment by GitHubRulesOK** [comment]
The idea of -new-window and @kjk can correct me was for when viewers wanted one file two windows with tabs (previously only possible without tabs) the session history has been improved since introduction and dont know how well current pre-release handles the history aspect other than it only remebers one part of set (is it the main window or the last closed)

What would be needed is on closing window 1 its history is stored seperate from closing window 2, however users can open 100 windows with tabs and that may become unweildy.

**Comment by GitHubRulesOK** [comment]
So what we have boiled down to is that using -new-window (or its hot key equivalents) has oddities in terms of behaviour (say favorites) and session history limitations when both are combined in the same settings and would benefit from  seperation such as is provided by -appdata as can be used by seperate sessions ?

@kjk is that possible to keep a setting file for each window such as 2nd window 3rd window (perhaps thats the max required ?)

**Comment by kjk** [comment]
I've changed the behavior of `-new-window` without a file opened to start a new instance.

This might be confusing since it doesn't respect single instance (process) behavior, but if it did, then it would make `-appdata` not work.

Maybe should only launch new instance if also `-appdata` is given. Or maybe `-appdata` should imply starting new process.

Or maybe Sumatra processes should be grouped by appdata dir. Multiple processes shouldn't be sharing the same data dir - it's a recipe for disaster. But then I don't really feel like writing too much code to enable a niche functionality like `-appdata`
