### ISSUE TITLE
Links to local files are not interpreted correctly

### ISSUE THREAD

**Issue by RomanKal** [sumatrapdfreader/sumatrapdf#2308]
Running Version 3.3.3 x64 (and others) in Win 10.
A PDF file, created by LaTeX, containing a URL link to a local file displays as "file:///T:/Misc.txt" but upon clicking it SumatraPDF returns the error message "File T:\T:\Misc.txt not found". It appears that the file name is incorrectly parsed.
Acrobat correctly processes the URL link.
[Test-Any.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/7975651/Test-Any.pdf)

**Comment by GitHubRulesOK** [comment]
I agree current release does not handle that odd entry

A<</S/URI/URI(file:///T:/Misc.txt)>>/Rect[...

 whilst MuPDF 1.18 does handle it and launch as a notepad object its more usual to use file relative pdf calls since it borders on calling executable files such as vbs via system associations

@kjk is it a bug or a security feature ?

**Comment by kjk** [comment]
I don't know about 3.3.3 but in latest pre-release this is correctly parsed as `t:\\misc.txt`.

So the bug of incorrectly parsing the file path seems to be fixed.

However, for security reasons we don't open files with absolute path. This might be improved. I opened #2309 for that.
