### ISSUE TITLE
Improve LinkHandler::LaunchFile

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#2309]
Currently `LinkHandler::LaunchFile` for security reasons silently rejects absolute paths and only opens files in SumatraPDF.

This might be too draconian. Maybe we should white-list "safe" file formats (like .txt, .jpg, .png etc.) and open them.

And if we don't open them, we should tell the user why.

Repro file from #2308 with absolute link: https://github.com/sumatrapdfreader/sumatrapdf/files/7975651/Test-Any.pdf

**Comment by hilavoku** [comment]
Hi.
Sorry to bother you, but I can't see that the problem of opening links (for example other PDF files) with absolute path is working.

When I have a PDF open in Sumatra and the PDF contains another link to a PDF with an absolute path it concatenates the path to the already opened PDF with the rest of the absolute path.
The problem does not occur in Foxit/Adobe/Edge/Chrome.

I haven't found the original code section for modifying/changing the behavior. 
(We have a main PDF file which contains links to files (PDFs, Excel XLSX, Word DOCs) which are lying on other servers. So we need the absolute path option.)

Hope someone can show me the right direction on how to fix this problem. Or is there a chance that within the next release absolute path files can be opened?

Thanks in advance

**Comment by GitHubRulesOK** [comment]
The security issue is that such links can be abused i.e. hijacked since what you see in a PDF is NOT what you get.
![image](https://user-images.githubusercontent.com/12754913/219438894-1dc31aa1-f686-4155-b877-7bdf49a0a9cf.png)

**Comment by hilavoku** [comment]
Thanks for the ultra fast answer!
I understand your concerns but where I work we have a closed environment with its own secure measures and Sumatra would be part of it and used only for opening specific Documents with known Links. So it would be nice to have the option of enabling opening such files/links.

**Comment by GitHubRulesOK** [comment]
What happens in other viewers is they raise a warning explaining the consequences
![image](https://user-images.githubusercontent.com/12754913/219443498-fed8fdd9-18be-452d-943f-866110c56118.png)

**Comment by hilavoku** [comment]
Okay. Never saw such a message with other PDF Readers in our environment but at least I have the choice to open the file and remember it for future use.
I'am aware of the possibilities / the risks involving when opening links but I like to have the choice of my own if I want to and take the responsibility.
What options do I have?
Going through the source code and changing Sumatras Code so that it opens files with absolute path or finding another free PDF Reader. I would like to stay with Sumatra but in our working environment I cant reorganize the structure of our PDF files so that they reside all on one server.

If someone could point me to the right direction where to take a deeper look into the code it would be very nice!

**Comment by GitHubRulesOK** [comment]
The whole topic is loaded (Adobe defined loosely as a two level process, visual appearance and underlying action, why would a printout need to link to a different file?). So as it stands SumatraPDF will auto open relative files, which could be a problem, but assumes they are safe enough to action, without warning. 
In browsers such links have an alternative of rightclick for user to make choices. 
www.google.com ![image](https://user-images.githubusercontent.com/12754913/219449401-f397b788-640b-4f50-9668-3f1f5a975a53.png)

![image](https://user-images.githubusercontent.com/12754913/219448273-e2f7c8e3-2ea1-4f63-be7a-52f9869e73d8.png)

**Comment by hilavoku** [comment]
We have PDF Documentations which have links in it to other PDF files which reside on other servers within our domain. So that is why we need to have a chance of opening such referenced files.

If Sumatra can't and I don't know the sourcecode that good and there is no chance of changing the behaviour than we sadly need to move away from Sumatra and use another PDFviewer.

**Comment by kjk** [comment]
Should work now
