### ISSUE TITLE
no preview for chm or epub...

### ISSUE THREAD

**Issue by NSP-0123456** [sumatrapdfreader/sumatrapdf#2322]
SumatraPdf 3.3.3 installer do not have install preview button nor any way to define installation folder. 

I registered the dll manually but even if i add the preview entry for chm the file is not rendered in explorer preview...

Could it be possible to integrate preview for chm, epub like viewed in the sumatrapdf.exe ?

**Comment by GitHubRulesOK** [comment]
The installer should have the option to install pre-viewer (I suggest re run installer and verify option is shown bottom left of install screen)

Manual registration is certainly not advised since in windows 10 there are problems registering FTAs without resolving Security Hashes (was easier in Windos XpVista7)

You will need to build your own version dlls from source to get additional previewers other than the PDF one (you can make choices for including each group) However, that area is unknown teritory with the more recent engine choices and newer formats like HEIC.

So you need to test each sub format to see which works well (certainly sub groups of Fb2 and DjVu may not all be supported and Chm was a variable group too, so often not included) 

Some 3rd Party pre-viewers may be better for targeted types. Thus ePub DjVu and CBx may sometimes be better as individual dedicated pre-viewer apps.

Related to https://github.com/sumatrapdfreader/sumatrapdf/issues/840 https://github.com/sumatrapdfreader/sumatrapdf/issues/1248
https://github.com/sumatrapdfreader/sumatrapdf/issues/1676 https://github.com/sumatrapdfreader/sumatrapdf/issues/1677

Anyway am closing as duplicat of https://github.com/sumatrapdfreader/sumatrapdf/issues/382
