### ISSUE TITLE
Cannot find words/strings which are wrapped

### ISSUE THREAD

**Issue by ron-mcleod** [sumatrapdfreader/sumatrapdf#2369]
When using the find feature to locate text in a PDF document, SumatraPDF fails to recognise text which is wrapped to another line.  This is different than behaviour of other document readers such as Acrobat.  This same behaviour is also found when selecting a word with a double-click.  The selection does not include the wrapped portion of the text.

For testing, search the document downloaded from: https://www.gsma.com/esim/wp-content/uploads/2020/10/SGP.23-v1.8.pdf for the string AUTH_SERVER_RESP_DEF_DP_UC_8_1_6_1_SIG will find not results, but the string is located at the top of page 704.

![image](https://user-images.githubusercontent.com/25831829/155258501-362939d9-5cc8-4038-ad5b-2a821aa7929d.png)

**Comment by kjk** [comment]
As @GitHubRulesOK explained, that would require heuristics that would never be good enough for everything. No plans to work on that.

**Comment by ron-mcleod** [comment]
OK.  Thanks for looking at this.

**Comment by GitHubRulesOK** [comment]
@ron-mcleod 
since the word in that file was written with white space between the lines, in a similar case knowing the limits then seaching on an increasing basis should eventually lead to `AUTH_SERVER_RESP_DEF_DP_UC_8_1_6_ 1_SIG` as the match for the way it is stored in that PDF not very helpful i agree but if you search  `AUTH_SERVER_RESP_DEF_DP_UC_8_1_6` it is only one of two matches
