### ISSUE TITLE
About tab‘s Suggestions

### ISSUE THREAD

**Issue by Kinvy66** [sumatrapdfreader/sumatrapdf#2372]
I hope to remember the location of the last open file. I enable the "Remember opened files". It can remember the location of the file opened last time, but I don't need it to open all the tabs last time. In a nutshell,  I only need it remember the pageNo last opened, but don't need RestoreSession .

**Comment by GitHubRulesOK** [comment]
The usual complaint is it does not remember tabs under X conditions, 
One of the common ways to remember all previous positions without any tabs is :-
 - when closing to only have one tab active 
 
Thus a workaround of your issue was to use CRTL SHIFT N to open a second window with ONE tab then close the window with many tabs . then when done with reading the one tab it will not be reopened in next session unless that page is re-requested.

**Comment by Kinvy66** [comment]
If it can automatically close all open tabs when user close the main window. And next time  it doesn't open some files which i don't need

**Comment by kjk** [comment]
Not going to support such granularity for that option.

**Comment by izeroo** [comment]
set RestoreSession = false while keep Remember opened files = false in **config file** will solve your problem.
Also see https://github.com/sumatrapdfreader/sumatrapdf/issues/1862

**Comment by Kinvy66** [comment]
> set RestoreSession = false while keep Remember opened files = true in **config file** will solve your problem. Also see #1862

谢谢！按你说的配置的确有效
