### ISSUE TITLE
Drag tabs between windows

### ISSUE THREAD

**Issue by sahil48** [sumatrapdfreader/sumatrapdf#2416]
Drag tab from one window to another or drag tab out to create a new window.

Easier implementation could be done via context menu on a tab.

**Comment by GitHubRulesOK** [comment]
Latest change (few weeks ago) should allow to drag and drop from folder/desktop etc to each window but tearing a tab off and drag to the other window is a much bigger task, not currently possible.
![image](https://user-images.githubusercontent.com/12754913/158038539-c162dd55-e108-413e-a497-38fb4a595fc6.png)

**Comment by sahil48** [comment]
Thanks. That's where I was wondering if a right click > move to window menu button would be feasible in comparison.

**Comment by GitHubRulesOK** [comment]
Hmm since not the developer I don't know how feasible that is, but I can always foresee a problem

@kjk the question this raises in my mind is that, I observe the two (ore more) windows share the same file ID from 1 to zer0 yet can be in separate session windows e.g. both or either, thus it would not be easy to assign a window # direct to the menu entry, however without a drag action it seems not unreasonable to allow a shift of one entry between one to the other window, BUTT thats ASSuming only two windows, and certainly someone  will try to do it with three.

**Comment by sahil48** [comment]
Oh no! I might be that someone! Look out, world. 😅

**Comment by WhiteChairFromIkea** [comment]
hmm, I think this issue is missing ability to drag (move) tabs at the same window (I always thought this issue was about reordering tabs at the same window). Should I create a different issue for such feature request? (I really like tab dragging features tha tmodern web browsers supports (I use chrome):

1. Drag tabs (reorder) in the window itself (**not covered by this OP**);
2. Move out tab outside the window to create new window (2nd instance) of sumatrapdf with dragged tab opened (**OP covered**);
3. Move tab from one window to another (**OP covered**), drop the tab dragged at any tab space available in another window (aka my point no 1, not sure if OP covered);

**Comment by GitHubRulesOK** [comment]
@WhiteChairFromIkea it was there from early on certainly in 3.1.2 untested if it was as soon as tabs were added

**Comment by qiangbro** [comment]
同样需要在窗口之间拖拽标签

**Comment by GitHubRulesOK** [comment]
@sahil48 

Note **half** your wishes 
- drag tab out to create a new window.
are now available in current pre-release

**Comment by GitHubRulesOK** [comment]
@sahil48 
I think we can declare this closed by recent updates to allow drag between windows 
use more recent pre-release https://www.sumatrapdfreader.org/prerelease
