### ISSUE TITLE
Option to hide bookmarks on fullscreen mode, and show again once exited fullscreen mode

### ISSUE THREAD

**Issue by helioxy** [sumatrapdfreader/sumatrapdf#2435]
I both use bookmarks and fullcreen mode a lot. But I don't want them together. So I have to toggle bookmarks everytime I need it. Which is painstaking. I know there is shortcut for that but I don't want to memorize shortcuts for every app

**Comment by GitHubRulesOK** [comment]
Well if you want them off most of the time, the easy way is to set them off using setting
`ShowToc = false` then you only need to use F12 or right click less often to switch them on once required

Personally since often using favorites for navigation I don't see a problem on wider screens only on small tablet, especially using portrait mode

**Comment by kjk** [comment]
Not planning to add that. A bit too much customizability.
