### ISSUE TITLE
Allow copy&paste of properties

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#2439]
Things to do:
* [ ] re-implement properties window using rich text editor, instead of custom drawing, which will allow copy & paste
* [ ] change how we get properties from `EngineBase::GetProperty()` => `EngineBase::EnumProps()`. This allows for more flexibility in the engine (show more properties for a given document type)
* [ ] either always enumerate fonts in PDF doc or add a button to the form

`EnumProps` could either take a `void (*cb)(void* data, const char* propName, const char* propVal)` or `std::function<void(const char* propName, const char* propVal)`

`typedef void(*EnumPropsFunc)(void* data, const char* key, const char* val)`

`propVal` could be multi-line, which would allow for showing props like: list of files in .zip document.

I also considered `EnumProps()` to return an array of key/val strings but callback function seems simpler to implement.

Alternatively, could implement array of key/val as `seqstrings` (in StrUtil.h). Simple to build, simple to iterate. Bad for random access (although when needed could build an index once with int offsets for each string).

Or could have indexed seqstring in the format:
* 4 bytes : number of strings
* (nStrings+1) * 4 bytes : offset of each string in seqstring. +1 for setinel value so that we can uniformly get length of string n as offset[n+1] - offset[n]
* zero-terminated sequence of strings

It's easy to convert from seqstring to indexed seqstring

We could have `SeqStrings` and `SeqStringsIndexed` typedefs.

**Comment by kjk** [comment]
Ended up with this design:

![image](https://user-images.githubusercontent.com/7935/160526854-0b6bbf49-7e83-43d9-bc69-1a550003170e.png)

**Comment by WebMechanic** [comment]
Nice.
Does it word wrap/resize? 
I frequently run into this, feels like watching tennis.
![image](https://user-images.githubusercontent.com/638340/160779782-d99ddb75-f1d8-4344-9651-07b9134d00a6.png)

**Comment by GitHubRulesOK** [comment]
@WebMechanic 
Looks like that match ended "Love all",  ?
I would suggest the Author should have used a shorter Subject like "War & Piece", but if wrapping was added we are likely to see bigger problems so perhaps truncation may be better  same as for bookmark/favorites that should only be precise Précis  not the contents of each paragraph

**Comment by WebMechanic** [comment]
well, I think educating publishers, authors (or build tool authors) to please SumatraPDF's UI esthetics or anybody's "best pratice" is futile...  I could mail that specific publisher (Smashing Magazine) to have an eye on it for future publications though :D

> (subject) ... SHOULD be the human-readable heading or label, ...

The epub spec does not define the length of `subject` nor what a "heading" should look like. 
American non-fiction typically has very, very long titles, bylines and they often end up in the subject field, too. The subject in this case here might simply match the marketing blurp/abstract -- who knows, and I don't bother to change it anyway.

I have plenty of ebooks and pdf with long titles, bylines, subjects etc. some feature the whole pack of authors in the title field. 
These files and their metadata show up in online book stores, catalogs, search engines to various extend, and the more crap publishers put into the metadata the more likely some of its content will match in search.

Maybe instead of "painting" the text, some **native** plain vanilla (read only) text input and textarea fields would do the trick out of the box? That's what many (most?) other programs do to display similar information.
The text is selectable and can be copied by default. A basic OS feature.

---
As for the long file path: I don't just dump every file in "My Documents". They are located on different drives and often within deeply nested folders -- easier to backup that way.
For the same reason I don't use Calibre or some other "libray" tool to hog gigs of data.

It's much easier and faster to fire up SumatraPDF, which is why I am using it :D

**Comment by WebMechanic** [comment]
different publisher then. 
**same book as pdf and epub**, different fields... 

![marcotte-pdf](https://user-images.githubusercontent.com/638340/160813885-fef0d1d5-158d-4640-8bac-3f18dfd2af43.png)

![marcotte-epub](https://user-images.githubusercontent.com/638340/160813902-2de2c686-4e48-4786-9676-cffa0abc4a91.png)

**Comment by dominiosc** [comment]
Please consider copy property values line by line, too, with double click or right button.

Another shortcut click in label "file:" to open the folder contains the file.

If we could modify and add the metadata values, even by shell, that would be great.

**Comment by GitHubRulesOK** [comment]
@dominiosc 
Older versions used Windows Ctrl+C and that was often used by other apps, however line by line may be "nice" but is excessive
that feature has been improved recently to simply click a button to do the Ctrl+C for you then paste or run via program externally. (see below)

![image](https://user-images.githubusercontent.com/12754913/166847162-ed517922-644d-4d0a-aea5-3e5283ae5499.png)

Alt+F+F (in English) is the easiest shortcut for open file name in folder, but you can change to your own choice, 

You cannot edit PDF meta without a full rewrite of file in editor so you can call an ExternalViewer Editor like Tracker xChange
SumatraPDF can export the filename and CurrentPage Number to any CLI application such as a batch file

**Comment by dominiosc** [comment]
I prefer to be able to copy a property each time as needed, title, path, author...

That the text is selectable does not take up more space :)

Of course there are other ways exiftool.org
Sumatra has a lot of power, if it reads it could write, it is not essential,
for me, it is more functional to copy property line by line,
or a one-action mode to open the folder, without having to do multiple interactions.

**Comment by WebMechanic** [comment]
>  however line by line may be "nice" but is excessive

if what looks like plain text in that dialog would actually be **plain simple selectable text** (like on this very webpage) you wouldn't have to bother coding anything for it, simple or excessive.
I dunno what GUI Library you use for this, but standard windows text elements/controls have a bitfield that allows or prevents their content to be selectable. Done.

Let your users **select the portion of the text** they're interested in (i.e just the file name, a part of the folder path, a sample from the description, the author's lastname, whatever) and allow Window's very own Ctrl+C system command to copy the selected string.

I understand you mean well by dumping all that metadata into the clipboards, but I believe for most users and use cases this is just overload. Keep that button now that you have it, but make these text labels selectable, and everybody's happy. :D

To me it looks like to made something basic and fundamental, like copying selected text, that works everywhere and across all platforms all the same for ages, into a very complicated and over-engineered dialog for no apparent reason.

I also don't understand, why I can select and copy text from any PDF, but not from an EPub 🤯.

Sumatra is such a great, fast and simple to use app. Don't complicate matters, please, and keep in mind that users will rarely use any app the way their developers imagined or intended to.

**Comment by WebMechanic** [comment]
selecting text in epubs **never** worked for me in the past (using 3.1/3.2)
I updated to 3.3 a while back, but didn't bother to check again.
It does work now.

**Comment by GitHubRulesOK** [comment]
@WebMechanic  selecting text in previous versions was always possible when in fixed position interface but in ebook reading mode it reflowed all over the page, so not fixed in a position to copy.

**Comment by WebMechanic** [comment]
ok, thanks. That explains the "inconsistent" behaviour.
Still don't understand that limitation though.
The reason I prefer epub over pdf is its ability to reflow and adjust to the window width, much like a well designed web site adheres to the user preference instead of forcing a line length/font size combination I'm not comfortable to read.
It seems like that reflow feature has been removed? 
Settings View/Width Options don't appear to do anything.

**Comment by GitHubRulesOK** [comment]
Not removed just ePub has moved fully to be handled same as PDF by main rendering engine (MuPDF) thus many more consistent behaviors (Good and Poor) A few options may still apply but others are now confined to ebooks such as Mobi here font is Comic Sans MS reflowed at roughly 10 point but its also searchable in fixed UI
![image](https://user-images.githubusercontent.com/12754913/167248271-da582000-1fdf-4eed-b52a-32e7bba9ea23.png)
