### ISSUE TITLE
Outlook 2016 PDF Preview not working with 32Bit Outlook and 64Bit Sumatra

### ISSUE THREAD

**Issue by Meth0d007** [sumatrapdfreader/sumatrapdf#2456]
There are multiple issues for this and multiple people state that they should be re-opened.
PDF-Preview in Outlook 32Bit simply does not work on the current 64Bit Build (3.3.3)
It does work once you switch you office install to 64Bit, but that obvisouly may not be possible in all scenarios.

One example:
https://github.com/sumatrapdfreader/sumatrapdf/issues/393

**Comment by GitHubRulesOK** [comment]
windows security has not removed the requirements that for applications to communicate fully without limits then 16 bit cannot be used in conjunction with 32bits nor 64bit

**Comment by Meth0d007** [comment]
So why does this work with all other PDF-viewers, PDF-XChange 64 and Adobe DC 64 can both show previews in 32Bit Outlook, so that limitation you are refering to does not seem to exist.

Also Sumatra 32Bit does not show any preview (not even in explorer) on our systems.

**Comment by GitHubRulesOK** [comment]
not wishing to labour the point SumatraPDF was designed for the Windows preview functionality the fact that different previewers can compete for different abilities in Outlook is a by product of Outlook preview designed to work closely with Acrobat. and foxit or tracker try to emulate Acrobat functions however they too can have issues see https://www.tracker-software.com/knowledgebase/251-Why-cant-I-see-PDF-previews-in-MS-Outlook also see ["Adobe Acrobat Reader is not installed in the same bitness as Outlook Desktop"](https://support.microsoft.com/en-gb/office/outlook-pdf-preview-error-this-file-cannot-be-previewed-because-there-is-no-previewer-installed-for-it-b78bfe24-ba13-44bd-8289-1919ece7ded2)

**Comment by Meth0d007** [comment]
Well yes every software "can have issues" especially with MS office, im fully aware of that. Generally speaking both Tracker and Adobe DC work and have been working on our install base (around 500 clients) in 64Bit flavours with 32Bit Office 2016 for years.

I understand now that Sumatra will not put ressources into development for the issues it has with Outlook in 32Bit, however this has worked in the past so i had assumed that was something that "should" work.

I was hoping to replace a large chunk of our "just viewing" clients with Sumatra, but not beeing able to preview in Outlook is a showstopper for most of our users.

**Comment by GitHubRulesOK** [comment]
I understand but it is based on several Microsoft system step changes to increasingly "secure" your interests even if SumatraPDF is more secure than any of those other applications that run PDF contents. Microsoft Outlook 32bit PDF-Preview written with Foxit (the ones that put PDF viewing into Edge) was retired a long time back, hence your need for another.

I understand that the workaround used by those apps such as foxit and adobe may possibly be emulated (untested) by a small set of registry hacks, but I am not the part time developer and as such ,outlook is not a supported method thus the basic feature of MS using it in outlook is a bonus. 

If you alter "in house" your users security, it likely will not be an acceptable as a pull request/enhancement.

The areas that potentially need changing for Foxit are here https://kb.foxitsoftware.com/hc/en-us/articles/360040660091-The-file-cannot-be-previewed-because-there-is-no-previewer-installed-for-it-in-Outlook the fix for acrobat is here file:///C:/Users/WDAGUtilityAccount/Desktop/SandBox/SumatraPDF/Why%20cant%20I%20preview%20PDF%20In%20Outlook_.pdf 

Thus by reviewing their methods you may be able to work out a suitable hack to coax SumatraPDF to do likewise but as repeadedly shown by even microsofts own outlook previewers their system polict is the apps and the bitness should all be the same to behave and be suppported.
