### ISSUE TITLE
F3 stopped working from search box

### ISSUE THREAD

**Issue by endolith** [sumatrapdfreader/sumatrapdf#2479]
In the past, if I press Ctrl+F, it highlights the search box. Then I paste the string I want to search for, then I press F3 to cycle through the matches.  

This no longer works in 3.4.14423 pre-release (commit 466d1c6) because F3 doesn't work when search box is focused.  I have to click back on the main body of the PDF to get F3 to work.

**Comment by kjk** [comment]
It's tough. F3 is handled via accelerators.
When I implemented more functionality via accelerators (to enable customizing keyboard shortcuts) I had to disable processing of accelerators when search box is active (otherwise turning 'n' into a command will block edit control from seeing 'n').

Will probably have to add some hack in `WndProcFindBox` to special-case `F3` and similar.
