### ISSUE TITLE
Problems with synctex files

### ISSUE THREAD

**Issue by Alfonsib** [sumatrapdfreader/sumatrapdf#25]
LaTeX users appreciate the capabilities of SumatraPDF  as regards synchronisation between source file and the resulting .pdf, through .synctex files, which works fine. However, as these files are rather bulky, we have two  possibilities:

1)  Store them, as the myriad of other auxiliary files generated by LaTeX and friends, in a .\TeXAux subdirectory of the working directory. This is very useful to easily find source documents in directories.

2) Compress them to a .synctex.gz format.

The issue is that in either case , forward and inverse search do not work any more. Would it be possible to add these features: understanding synctex.gz files and looking for them in subdirectories of the working directory? All LaTeX users who work with SumatraPDF would really be very grateful.

Best regards,

Bernard Alfonsi

**Comment by GitHubRulesOK** [comment]
In case anyone else comes here
1) this is not a SumatraPDF failing since it works as originally designed
i.e. synctex file was intended to sit squarely in the same folder .pdf > .(pdf)sync(tex)[.gz] > .tex
some TeX variants may be encouraged to work differently but should not break this fundamental rule because:
2) TeX is a complex suite of interdependent threaded workflows and many downstream processes may not respect conflicting relative references as equal. So .\sub\work.pdf relative to mnt0\absolute path\work.tex can easily fail in odd processes even if it appears to work for some.
