### ISSUE TITLE
Remove "old" documents from settings file

### ISSUE THREAD

**Issue by execrable** [sumatrapdfreader/sumatrapdf#252]
Adding a LastOpenedTime field to the individual document data in the settings file would allow the removal of old data, either by the user choosing a menu action or automatically. The age to remove (e.g., not opened in 6 months) could be settable.

**Comment by GitHubRulesOK** [comment]
The key issue is if files in history are only inaccessible for a short duration due to network or plug in drives.

This seems to be one of the better workable suggestions to reduce file history based on a per user time based setting so for some it may be  =**never**=false/-1, or clear all Now=0, a day =1 or for others a few years=999 days. 

Related to https://github.com/sumatrapdfreader/sumatrapdf/issues/192

**Comment by kjk** [comment]
I've added `Clear History` command you can trigger from command palette (`Ctrl + K`).
