### ISSUE TITLE
Is there any way to automatically save the annotation?

### ISSUE THREAD

**Issue by hkayann** [sumatrapdfreader/sumatrapdf#2578]
I appreciate if someone can answer the question.

**Comment by kjk** [comment]
No, there's no way to auto-save annotation. Saving annotations is an expensive operation.

**Comment by GitHubRulesOK** [comment]
Since old forum is not easy to link/search I am reposting a comment from there to here

Frequent (Auto) Saving Annotations is ***not a good idea*** as each one requires lots of duplicated resources "Expensive" in more than just time or storage, on its own,  a small highlight can be several KB so by waiting until all annotations are placed the overheads are minimal, but you dont want to loose that one entry you added an hour ago, so common sense, says save before going to lunch.

Unless redacted annotations are usually appended to/in the PDF and even if marked as deleted/removed from view may in embarrassing cases still be present 🙂 

![image](https://user-images.githubusercontent.com/12754913/168697115-08bb17dc-ef88-4619-92cc-005104547e7d.png)
![image](https://user-images.githubusercontent.com/12754913/168697153-0d78a229-dbb7-4b8a-93c7-155a8429854f.png)
After Freda saves the file “without” Freds comment, Freds annotation is still there, that is NOT a bug it is the way a PDF is supposed to keep historic changes but they need to be decoded (as I did) to reveal them. A simple text search may not reveal how Adobe PDF annotation were designed to work most easily by keeping additions and deletions.

![image](https://user-images.githubusercontent.com/12754913/168697191-2b1393d5-5fae-4905-9529-628deea93f23.png)
