### ISSUE TITLE
Option to disable home tab

### ISSUE THREAD

**Issue by edo9300** [sumatrapdfreader/sumatrapdf#2682]
With 81b7407bed9679d8d0175e0943a9bb64dbe834ed an "home tab" got added, from other issues it seems like this was a requested feature, but could an option be added to disable it? I open pdf files from outside sumatra and thus i don't need such tab always present as i never use it in first place so it's only using extra space.
Also right when writing this issue i noticed that if you disable the "use tabs" option the home tab will still be forcefully created thus creating rendering glitches.
![image](https://user-images.githubusercontent.com/18705342/172253405-bc7e7609-eabb-451c-af95-74e026fcd29e.png)

**Comment by kjk** [comment]
I have to think about adding. Adding options has a cost.

**Comment by edo9300** [comment]
> I have to think about adding. Adding options has a cost.

Well, from the glitched state of the second scenario, i think this will require to have an internal check already to block the home tab from showing in tab mode, should be a matter of also checking for an "X" option.

**Comment by kjk** [comment]
That's a separate thing. It's a bug, it'll be fixed.

**Comment by vlakoff** [comment]
After upgrading to version 3.5, I also got annoyed by this forcibly open tab…

I did a bit of searching and found the NoHomeTab advanced setting, but I think this setting should really be exposed in the options UI.

**Comment by losevskiyfz** [comment]
Menu -> Settings -> Advanced Options. Then find in the file 'NoHomeTab' property and set it on 'true'.

**Comment by jumper444** [comment]
I dont think 'more options' are needed.  Show the Home tab perfectly fine until the user opens a document either by windows association or File->Open.  Then replace "Home" tab with the document opened resulting in one tab.  Word or Excel or Browsers dont have an option to 'keep the opening blank document/tab open' so I suggest Sumatra doesn't need one.

**Comment by kjk** [comment]
You can use `NoHomeTab = true` advanced setting to get exactly that behavior.

**Comment by navossoc** [comment]
> You can use `NoHomeTab = true` advanced setting to get exactly that behavior.

I already tried that, but it doesn't have the same behavior as 3.4.6.

If you open the program directly, the home tab does not appear (OK), but if you open a pdf by double-clicking on it, the home tab still appears.

This doesn't happen in 3.4.6.

**Comment by GitHubRulesOK** [comment]
@navossoc 
3.4.6 only has a home screen not seen with double click a file (it was a complaint there was no tab for that screen)
3.5+ has a tab for home screen which is on by default so double click adds BOTH home AND current file tabs there are 2 options
1) disable home tab same as 3.4.6 by setting nohometab true **once saved it should stay that way.**
2) close that tab (double click it) and or open more files at the same time

**Comment by kjk** [comment]
I just tested bunch of scenarios with latest pre-release (https://www.sumatrapdfreader.org/prerelease) and with `NoHomeTab = false` I didn't get home tab when opening via double-clicking or by drag&dropping.

If you have a scenario that reproduces in pre-release, then please open a new issue with exact steps to reproduce it.

**Comment by GitHubRulesOK** [comment]
@kjk 

Hmm when NOHOME=false then it should appear ?
`NoHomeTab = false`
Installed and double click a file, not it is official pre-release

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/6f4fd383-8583-49cd-b099-43b22082ebac)

**Comment by navossoc** [comment]
False or true? Now I'm confused too...

@GitHubRulesOK This is exactly what is happening to me.

**Comment by GitHubRulesOK** [comment]
@navossoc 

The wording could be better NOHOME=true then it should NOt appear ?
NoHomeTab = true
Installed and double click a file, note it is official pre-release

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/13dc1511-b76f-4e6b-8486-30d714bf3460)

**Comment by GitHubRulesOK** [comment]
@navossoc 
**The current PRE-RELEASE** has Alphabetic list
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/39cbd14f-6a39-45fe-aa99-93c8e6cfe7ec)

**Comment by navossoc** [comment]
Now I see the problem, when I updated from 3.4.6 to 3.5.2 something messed up with the settings file.
There was no `NoHomeTab` on it, so I added one at the end `NoHomeTab = true`.

Now I was checking the file again and there was another `NoHomeTab`. So having the same config set twice didn't played well.
Now it is working as expected.

So yeah, the config should be `NoHomeTab = true` and look if there is no other `NoHomeTab` lying around.

Cheers.

**Comment by kjk** [comment]
Sorry, I mistyped. I meant `NoHomeTab = true`

**Comment by mlevy-emanuel** [comment]
When I open my advanced settings file, it's completely blank. Adding "NoHomeTab = true" to this file seems to do nothing.

**Comment by GitHubRulesOK** [comment]
@mlevy-emanuel 

your settings file will be generated on first usage but thereafter should always have lots of contents unless wrong file location or wrong contents.

Which variant/version are you using ?

**Comment by mlevy-emanuel** [comment]
> @mlevy-emanuel
> 
> your settings file will be generated on first usage but thereafter should always have lots of contents unless wrong file location or wrong contents.
> 
> This one shows it on line 13 of over 1000 ![image](https://private-user-images.githubusercontent.com/12754913/367065595-f5bc190f-9e55-48ee-b467-342b76d9866b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNzY5NDksIm5iZiI6MTcyNjE3NjY0OSwicGF0aCI6Ii8xMjc1NDkxMy8zNjcwNjU1OTUtZjViYzE5MGYtOWU1NS00OGVlLWI0NjctMzQyYjc2ZDk4NjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDIxMzA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YTlkZTNjMzY0ZTg2M2I3ZDg1OGY0OTNhYjk5MTdkYjBhZDczMjFiNzUzZjZkYzA5YTcxNDc4NmMxYmZjOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2yBX_zxZ8sgqmrqUTInyqz5L-qq39Flca_xzkgtg7GU)
> 
> Which variant/version are you using ? and where is that blank settings to be found ?

3.5.2 64-bit on Windows 11 -- when I click Settings > Advanced Options it's opening in Visual Studio Code for me, I guess because that's my default text editor.

**Comment by mlevy-emanuel** [comment]
It looks like going to Settings > Advanced Options and trying to open the file that way for some reason created a new folder structure underneath my SumatraPDF folder, instead of going to the appropriate location to open the settings file.

Location that it should have opened:
C:\Users\USERNAME\AppData\Local\SumatraPDF\SumatraPDF-settings.txt

Location that actually opened:
C:\Users\USERNAME\AppData\Local\SumatraPDF\USERLASTNAME\AppData\Local\SumatraPDF\SumatraPDF-settings.txt

strange behavior... I'm guessing some sort of bug? Still not sure why it is opening visual studio code and not my default text editor.

I was able to modify the proper file in the proper location just by navigating to it myself and it's working now.

**Comment by vlakoff** [comment]
> Location that actually opened:
> C:\Users\USERNAME\AppData\Local\SumatraPDF\USERLASTNAME\AppData\Local\SumatraPDF\SumatraPDF-settings.txt

That repeated path with `USERLASTNAME` is really strange. Microsoft accounts do have a first name and a last name indeed. But I had a quick look at SumatraPDF's code, it ends up to a simple `SHGetFolderPathW()` call with `CSIDL_LOCAL_APPDATA`, so I don't understand how such a path could have been generated.

> Still not sure why it is opening visual studio code and not my default text editor.

FWIW, I have a similar issue in [WinMerge](https://winmerge.org/): if I do "Open Left > With Registered Application" on a `.jpg` file, it opens in Paint, although `.jpg` files are registered with another editor.

----

Getting debug information that would be very helpful:
* In SumatraPDF,  run that command "Settings > Advanced Options...".
* Go back to SumatraPDF, and [open the log](https://www.sumatrapdfreader.org/docs/Debugging-Sumatra): <kbd>Ctrl + K</kbd> > double click "Show Log".
  * Namely, there are two lines "BuildOpenFileCmd" and "OpenFileWithTextEditor" that should provide a lot of insight.

Some other thoughts:
* Do you have spaces in `USERNAME` and/or `USERLASTNAME`?
* What happens if you run `code C:\Users\USERNAME\AppData\Local\SumatraPDF\SumatraPDF-settings.txt`?

**Comment by mlevy-emanuel** [comment]
I do have spaces in my username, it's in the format: "Firstname Lastname"

Here's the log entries:
BuildOpenFileCmd: path: 'C:\Users\Firstname Lastname\AppData\Local\SumatraPDF\SumatraPDF-settings.txt', pattern: '"C:\Users\Firstname Lastname\AppData\Local\Programs\Microsoft VS Code\Code.exe" --goto %f:%l'
OpenFileWithTextEditor: '"C:\Users\Firstname Lastname\AppData\Local\Programs\Microsoft VS Code\Code.exe" --goto C:\Users\Firstname Lastname\AppData\Local\SumatraPDF\SumatraPDF-settings.txt:1'

Running code on the text file opens the proper file in VSCode.

**Comment by mlevy-emanuel** [comment]
My guess is that because there are spaces in my username it trips up the code that tries to open the file.

It looks like VSCode is actually opening 2 files when trying to open this, the blank file at the bad location, and another file called "Firstname" with the path "C:\Users\Firstname" ... so perhaps the space in the username is tripping up the command and it tries to open a file Firstname in the first location, and then after the space treats the rest as a new file to open in a separate location, "C:\Users\Firstname Lastname\AppData\Local\SumatraPDF\Lastname\AppData\Local\SumatraPDF\SumatraPDF-settings.txt"

**Comment by mlevy-emanuel** [comment]
Just tested in the pre-release. The pre-release is opening in Notepad, not VSCode, and it's opening the correct file.

**Comment by kjk** [comment]
Opening in VSCode was also fixed with https://github.com/sumatrapdfreader/sumatrapdf/commit/d70c6524874cb80e3bfdf9da44c59ab254314e7a

**Comment by vlakoff** [comment]
And the file now opening in Notepad is probably due to [this change](https://github.com/sumatrapdfreader/sumatrapdf/commit/c885a1917abd695901532b7c6cab9840a761a471#diff-a3f32f33122b5ce398c1d3035cf818f7075f1945b3561377f071ef3798dd5953) (#2762), with which I agree (Notepad is sufficient for this use case, and using the registered `.txt` editor is better than querying in a hardcoded list of editors).

**Comment by mlevy-emanuel** [comment]
Yes the pre-release seems to fix the bug, the expected behavior is to open .txt in notepad (default editor).

**Comment by vlakoff** [comment]
Back to the issue at hand, disabling that home tab seems to be a popular request. Looking at this again, I really don't understand the rationale for such an extraneous tab.

An advanced setting to disable it is (quite) fine for me, but as stated previously, I think it would be worth having a regular setting in the UI.

**Comment by FunctionPoint** [comment]
Yes please, *only* show the home tab if there are *no* other documents open (or being opened).
Does not have to be a setting, even, imo.
