### ISSUE TITLE
Option to remove tab scrollbar

### ISSUE THREAD

**Issue by WhiteChairFromIkea** [sumatrapdfreader/sumatrapdf#2694]
Is there a way to remove "scrollbar" control from the tabbar, I mean this:

![2123d](https://user-images.githubusercontent.com/46539653/172604836-ff1e268d-4216-4cd2-81a9-e19ac39ce0f0.png)

I want to see all my tabs fitted aka an old behavior, maybe it could be set via preferences...

**Comment by GitHubRulesOK** [comment]
That was common past variable problem with scaling (tabs overflowing minimize) introducing sometimes a tab navigator, now apparently added in pre-release as a fixed position control to avoid the tabs overflow.

To adjust tabs width there is one variable, but otherwise the space for tabs is from "hamburger" to that if needed control

**Comment by GitHubRulesOK** [comment]
@kjk I am seeing odd behaviors with that control in that it seems not to be working correctly ?

**Comment by kjk** [comment]
Should be fixed in next pre-release
