### ISSUE TITLE
german umlaut not correct in the DB online ticket

### ISSUE THREAD

**Issue by seebronn** [sumatrapdfreader/sumatrapdf#2777]
for some time now, the letters in the Deutsche Bahn ticket (pdf DB online ticket) are no longer displayed correctly. Instead of umlauts, only placeholders are shown. Example:
![grafik](https://user-images.githubusercontent.com/50779703/176991771-9dc1d10e-a1eb-4e6c-af0f-a1318db0f91e.png)

**Comment by GitHubRulesOK** [comment]
It will be due to the Character Mapping and there can be generally two primary reasons

1) SumatraPDF in a few recent versions did not replace those characters efficiently (check your version number and try latest pre-release)
2) the tickets have the wrong mapping for widespread use (a sample would be needed to test and possibly allow for any fix)

**Comment by GitHubRulesOK** [comment]
You should not send private data to GitHub
The file should be sent to developer kkowalczyk   at   gmail.com with Issue 2777 as reference 
I think lucky for you it did not get included by github system via email?

**Comment by seebronn** [comment]
Problem solved by installing the latest version direct from the homepage. Now umlaute are displayed correctly.
Unfortunately, the program does not show that a new version is available under "Help - search for new version". In my case 3.3.4 was installed.
