### ISSUE TITLE
Strange behavior of tabs

### ISSUE THREAD

**Issue by sergsako** [sumatrapdfreader/sumatrapdf#2806]
I use the Latest SumatraPDF pre-release build version 15226, x64 portable, on Win10x64 21H2. The problem appears only if the window of SumatraPDF is maximized (if important, my screen resolution is 1920x1080 with scaling 1.25). I have 2 tabs: the Home tab and the 1st document tab. Both are in their usual positions. Then I open a 2nd document, via the file explorer or by right-click to the SumatraPDF icon on the taskbar. The tab of the 2nd document does not appear in its right position, instead it goes over and upon the Home tab. If I restore down the program window, positions of the tabs become right, and if I then maximize the window, positions of tabs remain correct. However, if I close the maximized window with 3 or more tabs (in correct or smashed positions, no matter) and then start Sumatra again, the tabs become smashed.

**Comment by WhiteChairFromIkea** [comment]
Hi, I am providing video and shorter steps to reproduce
This bug is seen in time interval 0:00 .. 0:17:

https://user-images.githubusercontent.com/46539653/179678637-5424a0d9-9fbb-4f3c-8bf2-690ebc704d5e.mp4

1. Have associated windows pdf extension with sumatra. Close all tabs in sumatra and close sumatra window when it is maximized, before the test;
2. Doubleclick pdf file in windows explorer -> Sumatra launches with new initial tab opened;
3. Return to explorer, open 2nd file -> Sumatra pop ups with 1st and 2nd tabs drawn over each other;
4. Repeat step 3, get 3 overlapped tabs;
5. De-maximize sumatra -> Tabs return to normal.

I have the same resolution but 100% scaling as OP user.

@sergsako , could you rename this issue to "Overlapping when sumatra is maximized"?

**Comment by WhiteChairFromIkea** [comment]
Related: https://github.com/sumatrapdfreader/sumatrapdf/issues/2807

**Comment by meteorquake** [comment]
My tabs are broken since some days ago when I updated. Screen 1280 x 1024, Tabs particularly when opened by explorer launch into an existing instance often lack titles and features, or are missing, and can't be closed except with Ctrl-W. When they are closed they often stay there rather than being removed and other tabs sliding to their space.
I've waited through a few updates expecting it would be noticed and fixed but it's still occurring.
As a usability problem the severity is fairly high given these are basic elements, mitigated by the fact that the documents themselves are readible as usual.
Sumatra 3.5.15229 64bit pre-r
Cheers. d

**Comment by edo9300** [comment]
Can confirm i'm experiencing the same issues on the latest prerelease (15229)
![image](https://user-images.githubusercontent.com/18705342/182259001-9521458f-e17a-4783-91c7-1f21daa5c67d.png)

**Comment by kuro68k** [comment]
Can confirm in pre-release v3.5.15229 64 bit on Windows 8.1 x84. My screen is 4k, 175% scaling.

**Comment by meteorquake** [comment]
Just a bump that his relatively new problem is still happening.
I'm finding the tabs are 'cured' of corruption (until the next tab change) if I click the button (top right) to make Sumatra part-screen then click maximise again.
3.5.15234 64-bit -- Win10

**Comment by jupester** [comment]
Just to add some info, I have got a slightly different issue with tabs, just upgraded from 15189 to 15234 skipping all pre-releases in between, and now my whole tab bar is white as indicated in the below image, top image is 15234, bottom is the normal display in 15189 and earlier, I assume this is not an intended change.

![2022-08-21_062330](https://user-images.githubusercontent.com/50538846/185764979-bd5f44ff-f2d3-4c19-873a-072d3ba7c770.png)
.

**Comment by GitHubRulesOK** [comment]
@sergsako  please re-check against 15235

**Comment by sergsako** [comment]
In **15235**, I see no problem with tabs. I have to close this issue.

**Comment by meteorquake** [comment]
3.5.15237 64-bit looks good for me tabwise. Cheers! d
