### ISSUE TITLE
How can I set the default color of strike out of annotation?

### ISSUE THREAD

**Issue by ALPNZ** [sumatrapdfreader/sumatrapdf#2851]
In the Advanced Options, I don't find the related settings about the default color of strike out of annotation

**Comment by GitHubRulesOK** [comment]
This option has been added recently in pre release https://www.sumatrapdfreader.org/prerelease
![image](https://user-images.githubusercontent.com/12754913/229224526-da632c57-c784-42fb-a656-1391385e0b2d.png)

**Comment by A-Infor** [comment]
> This option has been added recently in pre release https://www.sumatrapdfreader.org/prerelease ![image](https://user-images.githubusercontent.com/12754913/229224526-da632c57-c784-42fb-a656-1391385e0b2d.png)

I set `StrikeOutColor = #000000`, but Sumatra v 3.4.6 64-bit keeps setting red as default... What to do?

**Comment by GitHubRulesOK** [comment]
@A-Infor 
Tust tested it should be working as black here on a random PDF
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/79e0230c-f2f8-40b0-ade4-5c1443cafb7e)

**Comment by A-Infor** [comment]
@GitHubRulesOK Oh, I understood now.
When looking at [Customizing SumatraPDF 3.5](https://www.sumatrapdfreader.org/settings/settings3-5), it says:

"strike out annotation color (introduced in version 3.5)"

Well, I was using Sumatra v 3.4.6 64-bit. That's why it was not working, I needed to be using v 3.5 ...

I [downloaded the pre-release](https://www.sumatrapdfreader.org/download-free-pdf-viewer) 15481, built on 2023-04-18, installed, and now it works perfectly. Thank  you.
