### ISSUE TITLE
Several files from different directories open. Modify one file, save it, its directory is not remembered.

### ISSUE THREAD

**Issue by SandKierkegaard** [sumatrapdfreader/sumatrapdf#288]
A----
    |- a.pdf
B----
    |- b.pdf

When I open a.pdf and b.pdf, make some changes to a.pdf (highlighting, etc) then try to overwrite a.pdf, the save file dialog doesn't points to directory A (but maybe B instead, probably the last used dir, not 100% sure).

Can we make it so that each file remember its directory in the save file dialog?

**Comment by kjk** [comment]
PDF editing functionality is not even enabled in official builds so this is not a common scenario.
We let Windows pick the location for "Save As" dialog and that behavior will remain for the foreseeable future.

**Comment by kevivs** [comment]
Related to this and other issues like #177, can we enable 'save' pdf file (without changing the current 'save as' shortcut) in the **prerelease** version? (so that it overwrites the currently opened pdf without any prompt whatsover for each file in it's own folder location). 
This will be very, very convenient e.g in my use case when reading pdf books and highlighting texts (in prerelease - v10844) but saving with one keystroke instead of going thru 'save as' scenario, which becomes very cumbersome as the folder locations are not remembered by Sumatra and we have to navigate to file's own folder for each file opened while saving only the highlighted text. Please enable 'save' atleast in pre-release.
