### ISSUE TITLE
possible caching problem with network files

### ISSUE THREAD

**Issue by dackelblut** [sumatrapdfreader/sumatrapdf#289]
Hi,

summary: opening a PDF with sumatrapdf from a network drive properly displays the file but windows continues to download it until the program exits or the file is closed. Network in this case is a novell one (university network). I don't know wether this is a problem within sumatrapdf or windows 7 itself, I only observed it with sumatrapdf (and several files from different network drives) and no other pdf viewer (tested acrobat/mupdf). Because of limited debugging abilities on this machine I can only provide screen shots (maybe FileMon from sysinternals could be helpful).

regards, frank

edit: it does not happen with PDFs downloaded from internet (e.g. using a browser)

**Comment by kjk** [comment]
How do you determine that "windows continues to download it" ?

How big is the file?

**Comment by dackelblut** [comment]
Aah sorry, I forgot to commit the promised screenshots (they are at my machine at work). I usually have a small network meter app running that shows in/out transfer rate. Opening a pdf from a network drive shows that after the expected transfer (e.g. 1 second for a 2 MB file) the rate doesn't drop back to zero but continues with several kbit/s. And its not the sumatrapdf process but the windows "system" one. File size is not important I think because it happend with all files I tried so far (low kB ... low MB).

**Comment by kjk** [comment]
Correlating network activity to Sumatra opening a file is not enough.

If you can't tie the network traffic directly to Sumatra, there's nothing we can do. Windows is a black box to me, there are number of reasons Windows might decide to do network i/o.

I need stronger evidence that i/o traffic is generated due to something that Sumatra does.

**Comment by dackelblut** [comment]
Yeah, sounds reasonable.

**Comment by VictorVG** [comment]
***dackelblut***

What you are asking to complete the network I / O operations do not possible because until the network layer OSI / ISO 7498 does not gather all the packages that passed the original message, they will not be passed to the transport layer for its assembly and sootvetvetstvenno in the session and presentation layer OSI / ISO 7498, and because the application layer is running custom applications do not have access to them. The network application response "operation continues, wait." and it will wait for the completion of data transmission.

Browsers, FTP, WebDAV, mail and P2P clients are special applications that do implement the specifications of the transport and session layer OSI / ISO 7498, and just for this they use their inner workings to the network, but they can be viewed, not all received data - it depends on the properties of a particular set of input data network.

**Comment by kjk** [comment]
Closing until more information provided that points to Sumatra being the issue.

**Comment by VictorVG** [comment]
***Krzysztof***

Once again, you will support, and I think you will agree with me - to forum.ru-board.com even had to specially write (a dozen of the same questions I asked different people):

If someone tries to read files from the network, then wait for them to receive and do not write bug reports in vain that they say does not cache - the network does not give to the application file until all the transfer operation completes. SumatraPDF is not a program of data transmission over the network and it does not have and does not need the implementation of network and transport layer OSI/ISO 7498. It refers to the operating system for the data received and their shows. And if you have a large delay in the channel then any application will wait until the OS does not give him received their remote site data is completely normal and is not the basis for the bug report. In the case of large time delays in data transmission as well as see where you need to refine your communication channels or networks.

***P.S.***

I think that it is in the documentation indicate a course setting out in simple terms because many people simply do not realize the difference between local and network location of the object because the whole mechanism of interaction of distributed systems, we as engineers intentionally hide from it by simplifying the interaction with a computer to the limit.
