### ISSUE TITLE
Can I read the exact width and height of a page from the command line?

### ISSUE THREAD

**Issue by mo-bai** [sumatrapdfreader/sumatrapdf#2911]

**Comment by GitHubRulesOK** [comment]
No because it is not easy to describe a page that could have multiple definitions thus not trivial

A PDF page is defined if available as optional values /Media (paper) /Crop (the viewport) /Trim (cut paper) /Art (draw area) /Bleed etc
That is compounded by orientation which is not just /Rotate but includes a complex matrix so simplest is width and then height in that pages defined units which may be different to another pages units.

Easiest is use a more focused dedicated CLI tool like pdfinfo or mutool
