### ISSUE TITLE
ReuseInstance = 

### ISSUE THREAD

**Issue by Romko-M** [sumatrapdfreader/sumatrapdf#2929]
ReuseInstance = false / true does not change the behavior in Sumatra 3.4.6 x64

**Comment by kjk** [comment]
When tabs are enabled (which is default) it always acts as reuse instance.

**Comment by tjkirch** [comment]
Is there any way to get two tabs of the same document, then?

**Comment by GitHubRulesOK** [comment]
@tjkirch 
Two tabs same document is often possible such as open file twice or open copy of document in new window (ctrl shift N)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/2c2c729e-fe94-4a44-836a-2696a3b9f0e6)

The reuse-instance was desired for the command line when SumatraPDF was used as a single frame post-viewer (after latex continuous recompile) thus either needed -reuse-instance to not open a fresh window (equivalent to -unique? in okular) OR with tabs not needed, since there the default. But then there is now a `-new-window` as the opposite action for a tabbed window.
