### ISSUE TITLE
Tab bar background color swallowing up title bar

### ISSUE THREAD

**Issue by ImportTaste** [sumatrapdfreader/sumatrapdf#2933]
In recent pre-release builds of SumatraPDF, the way the tabs render has changed:

![image](https://user-images.githubusercontent.com/53661808/188338851-5ca5bc92-8f13-45f8-afce-2deb0bf7c15b.png)

Before, all the unused space on the tab bar would match the color of the titlebar, but not anymore. It's rather ugly this way.

**Comment by SainoNamkho** [comment]
#2806 says this has been fixed.

**Comment by GitHubRulesOK** [comment]
hmm
@SainoNamkho thanks for heads up
@ImportTaste please retest and if ok please close, note due to a current issue with current pre-release needs a workaround please test using this version if available https://www.sumatrapdfreader.org/dl/prerel/15244/SumatraPDF-prerel-64.exe

**Comment by GitHubRulesOK** [comment]
your version looks fine there is no theming in SumatraPDF so you seem to be over-riding the top bar title colour above tabs that should look like this. so whatever theme tool is active needs to also modify tab canvases.
![image](https://user-images.githubusercontent.com/12754913/193107288-26c6579a-b967-42aa-a9a1-a952ef27110e.png)

**Comment by kjk** [comment]
Please re-open if this is still happening.

I can't reproduce this. Are you using a custom theme on Windows? If yes, which one?

**Comment by kjk** [comment]
Thanks @GitHubRulesOK that did it. I can reproduce it now.

**Comment by kjk** [comment]
We should ignore that setting. I have like 6 apps opened right now and only Directory Opus respect them. All other apps draw their own caption and ignore the setting.

**Comment by kjk** [comment]
Please post a screenshot and annotate to point which color you're referring to.

**Comment by GitHubRulesOK** [comment]
@kjk 
users incorrectly presume that tabs bar will follow border colour so its not going to differ until theming allows for such behaviours

**Comment by kjk** [comment]
Unfortunately the API we use "is supported starting with Windows 11 Build 22000"

**Comment by pulbitz** [comment]
I use a dark theme and have a setting that uses an accent color for the title bar, so I was able to darken the SumatraPDF title bar and use it well until this point.
Due to a fix related to this issue, the title bar is now always white in the recent pre-release version.

After reading the article, it seems that Windows 10 does not support the API, so the title bar color is darkened normally as shown below. (I do not use the tab feature.)
![win10](https://user-images.githubusercontent.com/58905725/227708817-57fa1c39-464a-4df2-88a9-e486907f4507.png)

In Windows 11 22H2, the color is fixed to white as shown below.
![win1122h2](https://user-images.githubusercontent.com/58905725/227708821-253cfa63-d592-4f12-94a0-2aa66e6073b6.png)

I wonder if this is a necessary fix.

**Comment by pulbitz** [comment]
The issue I reported above has been fixed in version 3.5.15375, thanks for the quick fix!
