### ISSUE TITLE
The annotations are not saved

### ISSUE THREAD

**Issue by afik14** [sumatrapdfreader/sumatrapdf#3006]
Hey everyone,

When trying to save the annotations I received that message (picture below).
Could anyone help me to repair this?

![image](https://user-images.githubusercontent.com/112687548/194030061-f04d1894-b69a-4713-92b9-711da9a8f2df.png)

**Comment by tactilis** [comment]
Do you have the PDF open in any other application at the same time? Some apps, such as Acrobat, lock the file while it is open.

**Comment by afik14** [comment]
> Do you have the PDF open in any other application at the same time? Some apps, such as Acrobat, lock the file while it is open.

I don't. using just this app

**Comment by GitHubRulesOK** [comment]
most likely of 2 reasons is the file size is potentially over 32 MB ? thats the file locking boundary
174MB=https://notesmed.com/wp-content/uploads/2021/11/Harrisons-Principles-of-Internal-Medicine-20th-Edition-Vol.1-Vol.2.pdf
Other posibility is use of a path that is either too long OR contains problematic characters since eveery non latin character is 2 or 3 bytes

**Comment by GitHubRulesOK** [comment]
@kjk I suspect the problem here was possibly the same as some previous ones, since it is not a problem with current release.

I emulated file location Hebrew foldername and content and it saved without problems but note the OP title suggests a file from a known source of problem files. Harrisons Principles of Internal Medicine, 20th Edition 2020 by J. Larry Jameson (z-lib.org).pdf
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/578df489-1328-4466-a4fb-7f7120c20fda)

Without further evidence am closing as no longer an issue using current pre-release.
