### ISSUE TITLE
When starting from Windows Service printing doesn't work

### ISSUE THREAD

**Issue by robbaman** [sumatrapdfreader/sumatrapdf#301]
I'm not sure why this happens, but I'm trying to print a PDF file from a Windows Service using the following code:

    Process proc = new Process();
    proc.StartInfo.FileName = executable;
    proc.StartInfo.Arguments = String.Format(@"-print-to-default -exit-on-print ""{0}""", pdfFileName);
    proc.StartInfo.UseShellExecute = false;
    proc.Start();

When I use this code from a regular Console application it works fine, but from a Windows Service all that happens is that a *SumatraPDF-settings.txt* file is created with a bunch of settings in it.

I've confirmed that alle the paths are correct, but it just won't print. Have tried installing the service as LocalService, LocalSystem, my own user account and even tried using the User/Password options on the Process object (with and without LoadUserProfile) all to no avail.

I'm a bit at a loss what's going on, but not being a C++ programmer myself I'm not sure where I'd even start looking in the sources to figure out what it could be.

Any help would be appreciated.

**Comment by kjk** [comment]
Running inside a windows service has a bunch of restrictions but I'm not an expert either.

**Comment by metainilesh** [comment]
Hello robbaman,

I'm facing the same issue please help me if you have already solved it 

Many thanks 
Nilesh

**Comment by robbaman** [comment]
In the end I just created a console application and run that using the windows scheduler.

**Comment by metainilesh** [comment]
Hello Robert,

Thanks for the reply

Do you have any other way around for the printing the pdf on client silently other than sumatra pdf from web application .net 

if you want me to buy the coffee for that even I'm ready for that 

And if not can you send  me the small example for the console application will be great help

Thanks & Regards
Nilesh Metai

**Comment by robbaman** [comment]
Well, the console application does some moving around to get the files in the right folder. After that it simply loops through the files in the folder and calls the ```printFile``` function below with the full file path of the file as parameter.

		private bool printFile(string item) {
			log.InfoFormat("Attempting to print: {0}", item);

			Process proc = new Process();
			proc.StartInfo.FileName = _executable;
			proc.StartInfo.Arguments = String.Format(@"-print-to ""PakbonPrinter"" -exit-on-print ""{0}""", item);
			proc.StartInfo.UseShellExecute = false;
			proc.Start();

			if (proc.HasExited == false) {
				if (proc.WaitForExit(7500)) { // Give it 7.5 seconds to print
					var code = proc.ExitCode;
					log.InfoFormat("Exit successful: {0}, code {1}", item, code);
					return true;
				}
			}
			// Kill the process if it's still up now.
			proc.Kill();

			log.InfoFormat("Exit fail for item: {0}", item);
			return false;
		}
	}

I hope that helps

**Comment by amir-ashy** [comment]
i'm suffering from same problem.
i want to print some custom document from windows service (because i want it to be silent and be done on client side of a web application) but i get confused so much.
i have already read "[System.Drawing.Print](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.printing)" document which said :

`Classes within the System.Drawing.Printing namespace are not supported for use within a Windows service or ASP.NET application or service. Attempting to use these classes from within one of these application types may produce unexpected problems, such as diminished service performance and run-time exceptions.`
but sometimes it works well and sometimes just stop working with out any possible reason

**Comment by acicali** [comment]
I, too had this issue. As it turns out, the '-print-to-default' parameter of SumatraPDF was the culprit. When you're logged into your Windows account, the default printer is one thing, but the Window's service you've written has a *different default printer*... and it's probably something like "Microsoft XPS Document Writer"... so your service is just hanging there waiting for the user to type in a target filename for the resultant document. The issue is that Windows services cannot use the GUI, so your dialog is not displayed.

Anyhoo... if you're facing this problem, try setting the printer via Sumatra's CLI, e.g. '-print-to "HP LaserJet 5Million Series"'
