### ISSUE TITLE
Epub not rendering some sort of table or indent format correctly

### ISSUE THREAD

**Issue by ghost** [sumatrapdfreader/sumatrapdf#3014]
It looks fine on my kindle, so I think something might be wrong with the renderer.
![ss](https://user-images.githubusercontent.com/20543556/194990295-cf7740a6-d317-43ed-85b9-95ff832a9d74.png)
page 27 of the file at `http://library.lol/fiction/A161E8B96064372FC20DA62B83A20368`

This was rendered using pre-release build 15252, the section in question does not appear at all in the release version.

**Comment by GitHubRulesOK** [comment]
@kjk zipped above sample
[(The Best New Horror 1) Jones, Stephen_ Campbell, Ramsey (Editor).zip](https://github.com/sumatrapdfreader/sumatrapdf/files/9753906/The.Best.New.Horror.1.Jones.Stephen_.Campbell.Ramsey.Editor.zip)

**Comment by GitHubRulesOK** [comment]
@starshipcoffeecake 
Tables are a traditional problem and here I suspect it is the method of using css rules with `p class="noindent"` adds to the overlay error since in effect those in "old" HTML request " align paragraph hard left" so it is the fact they are both nested in same row via <td> that causes the problem.

**Comment by GitHubRulesOK** [comment]
closing as resolved in 3.5 
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/fa7dd2b9-6e41-445c-b62d-18abd29ed3ca)
