### ISSUE TITLE
Feature Request - Allow scrolling PDF while on "Save as..." dialog

### ISSUE THREAD

**Issue by sturgman** [sumatrapdfreader/sumatrapdf#303]
As a researcher I come around many PDF files and I have a particular system for their file names when they are saved. For example, I use authors, year, publication name, and keywords when saving a file. Often time all this information is spread along several locations in the first page. It would be extremely useful to be able to scroll the PDF viewer while the "Save as..." dialog is open. Of course, the "Save as..." dialog would have to remain on top of the viewer Window ideally.

**Comment by kjk** [comment]
In Windows file dialog is blocking. No way around it.

**Comment by thomas2net** [comment]
There should be a way to work around this. Document Viewer 2.32.0.145  (also known as Evince) enables scrolling and zooming while the Save As... dialog is open. 
It is the only reason why I still often use Evince instead of SumatraPDF.
Many thanks for your work and looking into this feature request. Please re-open this Feature Request.
