### ISSUE TITLE
Unable to print in landscape format?

### ISSUE THREAD

**Issue by Fiskaner** [sumatrapdfreader/sumatrapdf#3073]
Somehow I'm unable to print any pdfs in landscape format in SumatraPDF. It happen with any pdf, tested it with two different printers and two different SumatraPDF versions. It doesnt matter what i select in the printer settings (portrait or landscape format), SumatraPDF will always print it portrait.
Printing in landscape format works fine in Adobe Reader or Browser Add-Ins (e.g. Chrome or Edge).

version of Sumatra: tested on 3.1.2 and 3.4.6 (newest)
version of the OS: tested on Windows 10 & 11
name of the printer: tested Zebra GK420d & Canon LBP223dw
can you open and see the file in Sumatra?: yes
what exactly happens, are there any error messages?: see above, no errors

**Comment by GitHubRulesOK** [comment]
SumatraPDF has autorotate to paper so in a dialog you can spin it how you like, 
thus I am guessing perhaps you are using SumatraPDF for command line print PDF2ZPL (doubly not recommended)

Zebra printers use a pageDescriptionFormat so a non vector compatible internal textual language totally unsuited to laser PDF printing, however if you must then use a ZPL driver like Bartender Seagull to resolve many of the potential failings due to colour to mono mismatching Rubbish in rubbish out. For label orientation its a different set of problems as widows only provides one default form at a time from several defaults.

The default printers default printing orientation needs to be set for the current media, so to allow for 2 different rotations you need 2 different defaults, so in such situations I have 2 printer names A4L & A4P

For colour rendering PDF as mono text it is best to use a converter like Acrobat Reader, to realign PDF units with pixel printers it is best to use a converter such as Acrobat Reader To realign orientation of PDF media aligned with Roll cutting printers it is best to use a PDf rotatig application such as Acrobat Reader.

**Comment by priyeshshah11** [comment]
yes that happens due to this https://github.com/sumatrapdfreader/sumatrapdf/blob/master/src/Print.cpp#L473-L477

I think it should only rotate the page if `landscape` orientation is explicitly mentioned, rather than rotating the PDF based on its dimensions

@kjk Are there any plans to fix this?

**Comment by priyeshshah11** [comment]
the above PR actually didn't fix this issue, I had to explicitly specify the paper size in `-print-settings` to print it correctly. I was expecting `SumatraPDF` to respect the default printer settings.

**Comment by GitHubRulesOK** [comment]
rotation is sent to windows defualt but windows uses default paper so paper as portrait or landscape is windows resposibility, what auto rote dit d was try to follow or via prortrait/landscape attempt to rotate in one direction  always a thorn that it is 90 180 rater than 90 270

that facet is explaind that its input rotation not output rotation
***can provide 90 degree rotation of contents (NOT the rotation of paper which must be pre-set by the choice of printer defaults)***
