### ISSUE TITLE
Crash due to touchpad scroll in zoom

### ISSUE THREAD

**Issue by aman7554** [sumatrapdfreader/sumatrapdf#3082]
When scrolling is done using a **touchpad** it works fine but when zoom using it, it works in vertical scrolling and in **_horizontal_**l scrolling it freezes then suddenly app crashes.

**Comment by GitHubRulesOK** [comment]
which version ? crashreport ?
but fixes can only be applied relative to current pre-release https://www.sumatrapdfreader.org/prerelease

**Comment by aman7554** [comment]
sumatra pdf v3.5.15261 pre release

**Comment by kjk** [comment]
Not enough information.
Please submit crash information as described in: https://www.sumatrapdfreader.org/docs/Submit-crash-report

Also more information like: does it happen with every file or just specific file?

And please provide step-by-step instructions to reproduce the problem.

I can't tell if the crash happens when zooming or scrolling.

**Comment by kjk** [comment]
I don't quite understand the report and without more information / repro steps there's nothing I can investigate.
