### ISSUE TITLE
Direct link to pdf page with mediawiki

### ISSUE THREAD

**Issue by Prasselschruz** [sumatrapdfreader/sumatrapdf#320]
Hi Krzysztof,
could it be possible to implement the same #page=x function to jump to the specified page x in an pdf from a Mediawiki-Link (e.g. [[http://localhost/wiki/images/f/fe/nice.pdf#page=8]])?
I configured Firefox to use Sumatra (instead of Adobe) as PDF-Viewer because its way superior. This direct link function would make it perfect!
br
Tom

**Comment by kjk** [comment]
We only support things that are in PDF standard.

**Comment by Prasselschruz** [comment]
On 16.10.2015 21:00, Krzysztof Kowalczyk wrote:
>
> We only support things that are in PDF standard.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sumatrapdfreader/sumatrapdf/issues/320#issuecomment-148807322>.
>
Hi Krzysztof,
Adobe PDF behaves just this way, or what do you mean with "PDF standard"?
Sumatra does already support to jump to a page via the command line. The 
question is if this functionality could be implement when Sumatra is 
started via a html-link from Firefox.
Best regards,
Tom

**Comment by zeniko** [comment]
SumatraPDF already supports such links (see [the source](https://github.com/sumatrapdfreader/sumatrapdf/blob/master/src/SumatraStartup.cpp#L393)), but only when used together with the browser plugin that was deprecated and removed after version 2.5.2.

When SumatraPDF is used as a stand-alone application, such behavior isn't possible because Firefox does not include the page number in the filename that's passed to SumatraPDF for opening. The behavior for Adobe Reader should be the same.

If you want to try the browser plugin, please [install version 2.5.2](http://www.sumatrapdfreader.org/download-prev.html) and then the current version on top of it. For version 2.5.2, you'll have to activate the browser plugin in the installer's options.
