### ISSUE TITLE
Selecting pages from a PDF document

### ISSUE THREAD

**Issue by andreasvarga** [sumatrapdfreader/sumatrapdf#3222]
Selecting pages from a PDF document can be done easily by printing the respective pages to a file, e.g., using Microsoft Print to PDF tool. However the resulting file is excessively large, for example, just to print one page from a book of 4.1 MB with almost 500 pages, the resulting file is 1.1 MB ! Is any way to obtain a reasonable size file? Or, even better, the selection of page ranges would be a possible functionality of Sumatrapdf?

**Comment by GitHubRulesOK** [comment]
SumatraPDF does not split or in anyway edit PDF and the method your suggesting is not good for many quality reasons including massive memory requirement. 

To explain in effect you are converting one compressed vector page source into a lossy jpg image at a high resolution (two cardinal sins for a PDF page).

By far the simplest would be to use Acrobat export 1 page from many, however that will never be proportional to number of pages say 100 pages = 100 kb then one page can easily be 50 kb for several reasons such as all fonts need inclusion and images are decompressed. Or simply be 2 KB because no images are altered and a font is not embedded.

**Comment by avorobey** [comment]
@andreasvarga A tool I heartily recommend for this is [pdftk](https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/), available both as a command-line version (somewhat weirdly renamed "PDFtk Server") and a GUI program. It's all about splicing PDF into pages, recombining them into another PDF, etc. At least from what I remember, the files stay small because it genuinely copies pages with their PDF drawing/text/image instructions. Printing to PDF creates a huge bitmap for each page instead, losing the compact "drawing" representation.

**Comment by GitHubRulesOK** [comment]
@andreasvarga
MuPDF/Mutool (related to GhostScript) is able to selectively export page content or pages in many formats that may help to try options such as text outputs (I have mentioned for plain text task Poppler/Xpdf tools can be more useful) 
PDFtk is also powefu; tool for working with tasks like splitting/merging and even Ghostscript can split and merge PDFs and print typewriter style outputs, with even more additional tasks available too via PostScript. 

Each command tool has its place in a PDF toolbox along with qpdf and cpdf

**Comment by vadimkantorov** [comment]
It would be great if SumatraPDF natively supported exporting/saving a range (or single) of pages into a new PDF (especially if it's already based on muPDF/mutool)

**Comment by GitHubRulesOK** [comment]
@vadimkantorov 
The code for MuPDF and MuTool are common Fitz library and its dependencies but they diverge as two sets of applications Like Ghostscript and MuTool can be made to display a PDF on screen, but that task is best handled by MuPDF-GL which has many abilities such as annotation, but NOT printing like GhostScript nor draw/convert like MuTool etc.

It is the Viewing functions of MuPDF viewer that SumatraPDF is built on with some limited conversions such as convert standard Images (GiF PNG JPEG) into PDF wrap or using ghost script convert PostScript to PDF for speed of reading after conversion, or append basic annotations to end of PDF.

SumatraPDF can convert a range of pages into images for convert to PDF via MS PDF printing, but thats not what most people want except for printer images or falsely flattening forms (should not be done that way).

There is no problem sending current page or file reference to Acrobat for 3D/XFA viewing, Edge or others for Inking/Read Aloud or PDFtoTEXT for text extraction or MuTool for any of its dedicated abilities.

**Comment by vadimkantorov** [comment]
I think the usecase for splitting/merging in SumatraPDF is for casual/occasional users (who do not have Acrobat): e.g. need to fill out some PDF form or split out a single page once in a while. So maybe even embedding something like https://github.com/pmaupin/pdfrw could be used for a task like this. At least for page slicing, the UI could be quite simple: specify a range or ranges of pages to save (akin to the standard input field of printing in Windows)

**Comment by GitHubRulesOK** [comment]
the reason I avoud Python or Ruby is the phenominal amount of dependencies and thir problems , any yes I know Windows is the most bloated of all systems with side by side duplications and dot.net this, that and the other.

So that's the reason I like SumatraPDF as one.exe for a broad range of tasks
Mutool is another one.exe with a different power range of tasks so splitting is simple, but it does not attempt merging which is fraught with potential points of failure.

For merging you need say PDFtk one exe and one.dll
- Burst a single PDF document into pages and dump its data to doc_data.txt
pdftk in.pdf burst
- Join in1.pdf and in2.pdf into a new PDF, out1.pdf
pdftk in1.pdf in2.pdf cat output out1.pdf

**Comment by vadimkantorov** [comment]
I think by some hacking, one could embed python interpreter along with some virtual FS for dependencies into the single exe

**Comment by GitHubRulesOK** [comment]
I keep telling python and ruby users they don't need 1,022 Files, (or usually more) in 64 Folders to test if a pdf has text or images

Python is perhaps more basic than basic was but the users like its complexity of failure when those 1000 files fail to see each other its much like java or its script versions.

**Comment by vadimkantorov** [comment]
Btw one way could be embedding a small WASM machine and use Python compiled for WebAssembly, as these virtual FS things / static compilation are usually solved in that world

**Comment by GitHubRulesOK** [comment]
Closing as in effect a related duplicate or an addenda to exporting pages in different formats as per https://github.com/sumatrapdfreader/sumatrapdf/issues/687
