### ISSUE TITLE
Page number "20.1"?

### ISSUE THREAD

**Issue by sergsako** [sumatrapdfreader/sumatrapdf#3225]
I attached ZIP containing PDF of a paper (21 pages) and JPG of a screenshot made on page 21. Look at the top-left corner: the page number is shown as 20.1 21/21. I tested SumatraPDF 3.1.2, 3.4.6, and 3.5.15263, all the same, page number is 20.1. In other PDF readers it is shown as 21 (of 21). Very strange.
[page_20.1_.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/10421001/page_20.1_.zip)

**Comment by GitHubRulesOK** [comment]
Hmm
`/PageLabels << /Nums [ 0 << /P (1) >> 1 << /P (2) >> 2 << /P (3) >> 3 << /P (4) >> 4
<< /P (5) >> 5 << /P (6) >> 6 << /P (7) >> 7 << /P (8) >> 8
<< /P (9) >> 9 << /P (10) >> 10 << /P (11) >> 11 << /P (12) >> 12
<< /P (13) >> 13 << /P (14) >> 14 << /P (15) >> 15 << /P (16) >>
16 << /P (17) >> 17 << /P (18) >> 18 << /P (19) >> 19
<< /P (20) >> ] >>`

PDF numbers start at 0 and are therefor counted as +1 so unusually this file is labelled (should not be needed)
However you can see 0 = (1) etc so 18+1 =19 19+1=20 however 20 was not labelled so cannot be 20 again it is thus incremented to 20.1

**Comment by GitHubRulesOK** [comment]
@avorobey 
good (better description) 
ONE FEATURE(S) of SumatraPDF is to allow GoTo by various means including commandline switches, so I susspect that needs unique page names (labels), however if the ISONORM allows duplicate names then perhaps it should follow such conventions, even if causing related goto problems

**Comment by kjk** [comment]
I have no strong opinion here. Not sure if zeniko did this because someone complained or because he thought it's the right thing to do.

Or maybe something subtle was breaking. Labels can be used to go navigate with PDF so if they are duplicate, which one to use?

I would tend to just do what other popular PDF readers do (unless there's a good reason to do differently).

Removing that code would be easy enough.
