### ISSUE TITLE
Synchronizing bookmarks

### ISSUE THREAD

**Issue by vldanch** [sumatrapdfreader/sumatrapdf#3230]
How do I sync the bookmarks I've added to my favorites?

**Comment by GitHubRulesOK** [comment]
Please clarify sync, thats normally an external files concept. 
and SumatraPDF holds favorites as file locations in settings file that can be backed up or edited as required

**Comment by vldanch** [comment]
@GitHubRulesOK I mean the transfer of favorites if I for example open the same pdf book on another computer, it would be very convenient to have a synchronization button.
And then you open a book on another computer and have to look for what you added on your computer in the bookmarks...

**Comment by GitHubRulesOK** [comment]
When you store a "favorite" it is like most files considered unique (unchanging) thus moving SumatraPDF via portable use is always going to cause a problem as drives can differ (historically this is the same for all applications) so when I move any app that references C:\mydata at home I need c:\mydata  at work or if one computer uses x:\shared data then another device also needs to reference x:\shared data thus "synchronisation" works.
Over the years cloud drives and sync drive have caused problems with apps that depend on the local FAT or now NTFS filesystem for supported abilities and this affects dynamic app use more than static app usage. (It is best not to use such systems with applications that open files as read/write) so SumatraPDF synchronising with dynamic PDF usage is often affected.

Favorites are tied to the file history filename so if that is "synced" the favorite is too, however if its moved externally then called  SumatraPDF will complain it is not present and throw an error message.
![image](https://user-images.githubusercontent.com/12754913/213138439-bbac4d5e-ad09-4e4f-81c2-02862b2baec1.png)

![image](https://user-images.githubusercontent.com/12754913/213138149-e262940d-c8e5-44be-a83f-82b6b9fa8dc9.png)


SumatraPDF does make some attempts to re define the stored filename in some cases like rename or usb letter reassign otherwise by necessity keeps the old folder assignment for when the active user or drives return to normality.

Traditionally users that roam with portable apps needed to edit fixed drive letters in settings files and several workarounds attempt that with SumatraPDF settings. For example you can use multiple -appdata histories specifically to allow for different sets of files, however it can then be the cause of other related issues. If you know exactly how it is needed you can use a custom start-up script  that if necessary does find and replace on the settings file.

**Comment by vldanch** [comment]
@GitHubRulesOK Thank you so much for expanded response! Great!
