### ISSUE TITLE
Page 100+ doesn't load

### ISSUE THREAD

**Issue by lrrosa** [sumatrapdfreader/sumatrapdf#3240]
After page 99 of a certain PDF I opened (double-click in file manager), Sumatra tries to render page 100 and then crashes.

Log file of crash: https://gist.github.com/lrrosa/168011bf927c020c93828d40598cb37a

The PDF file is too big to attach here, but can be found in this link: [https://www.nartlof.com/livros/rc30.pdf](url)

**Comment by kjk** [comment]
The crash is fixed in latest pre-release: https://www.sumatrapdfreader.org/prerelease

However, the pages after 100 do not render while Chrome can render them.
Mupdf complains `cannot find page size for page 100`.

**Comment by avorobey** [comment]
I uploaded a fix to the mupdf issue. I'm not sure how attentive they are to bugs and patches (threw a cursory look and it seemed like there's a bunch of bugs opened by you w/ no attention, but I honestly have no clue and may be misjudging).

**Comment by avorobey** [comment]
The PDF has an unusual (I guess?) object structure with deep nesting: Pages object -> (Page 1 obj, Pages object -> (Page 2 obj, Pages obj -> (Page 3 obj, Pages obj...))). mupdf code is running into its own hard limit of a 100 recursion depth while trying to retrieve an inheritable property from Page 101, and walking up the inheritance hierarchy.

[Your recent commit](https://github.com/sumatrapdfreader/sumatrapdf/commit/65632a6c36422464e6787d2aadc786b0a969ebf7) for another issue therefore fixes the rendering here for pages after 100, but predictably fails again on page 601.

My guess is other parsers which don't have this issue use a set or a dictionary object to detect inheritance cycles rather than recursion (which is O(n^2) in addition to stack-consuming). Probably mupdf should do the same. If long inheritance chains are rare (I don't know), maybe start with a fixed-width array of size 10 and linear lookup, and move to a dictionary when the size exceeds that.

**Comment by avorobey** [comment]
I wrote a mupdf patch for this and uploaded it to https://bugs.ghostscript.com/show_bug.cgi?id=706484.

**Comment by kjk** [comment]
@avorobey Impressive speed of coding.

Want to contribute to Sumatra itself? I can promise I'll review and merge any changes quickly and there's so much that could be improved.

**Comment by kjk** [comment]
Yes, good catch, this should be fixed now.
