### ISSUE TITLE
Feature request: "copy rendered page"

### ISSUE THREAD

**Issue by atomicthumbs** [sumatrapdfreader/sumatrapdf#3249]
I'm browsing old computer magazines scanned as PDFs, and would like the ability to copy the whole page to the clipboard so I can clip out advertisements in an image editor.

"Copy image" on some scanned files works fine, depending on how they've been generated. However, the files I'm reading have apparently been lossily compressed by the Internet Archive's OCR process, which involves several layers and masking of characters, so when I use "copy image" the output looks like the second image here. Because of this I'm forced to open the PDF manually in Photoshop to extract useful images.

![good pdf](https://user-images.githubusercontent.com/4148004/216128312-2243dcbf-b0e2-4d44-b077-7aec59b69098.jpg)
![bad pdf](https://user-images.githubusercontent.com/4148004/216128327-fe0adf84-b945-40c5-843b-9aa21d62a286.jpg)

I would love the option to simply copy the entire rendered page to the clipboard so I can more easily do something with it.

**Comment by aionbo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by GitHubRulesOK** [comment]
There are two ways to save to clipboard one is to select the content which without a sample reference cant confirm if thats what your using but yes web archive uses exotic slow to decompress format (wavelets ?) the other is set your page to single page and desired zoom level (can be say 200%) then select all page with CTRL +C for text and  or image then try paste in notepad or wordpad or paint.

**Comment by atomicthumbs** [comment]
I appreciate the input and help, but this is a feature request specifically for a feature that would avoid every step of that.

**Comment by GitHubRulesOK** [comment]
editing (converting0 a file is as simple as rightclick a file i a system the click call any designated verb like read with sumatrapdf of edit with paint

**Comment by GitHubRulesOK** [comment]
A pdf in SumatraPDF should not have problems extracting a conventional image but this is not conventional it is distorted
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/d14698cb-fe1a-4fe2-a5e7-0330ed4e43a1)


![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/204dc129-84d8-4b09-9124-df911c158c2f)

The only way to avoid this output is reprint or convert pages  to images and many tools like poppler or MuTool can do that using about as much code as SumatraPDF needs, thus adding that extra feature is not necessary as SumatraPDF can send a single page to MS printers so all you need is an image printer like GhostScript since the only Windows inbuilt one is 200dpi Fax or 600 DPI colour PDF

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/abf9dff9-8e79-4333-bfc8-0587b92fe4d8)

**Comment by GitHubRulesOK** [comment]
Closing as in effect a related duplicate or an addenda to exporting pages in different formats as per https://github.com/sumatrapdfreader/sumatrapdf/issues/687
