### ISSUE TITLE
Settings was changed

### ISSUE THREAD

**Issue by wodecx** [sumatrapdfreader/sumatrapdf#3318]
When I installed the new version of SumatraPDF the settings had been changed. The file SumatraPDF-settings.txt was replaced with a new one. Font size, background color, all became the default.

**Comment by GitHubRulesOK** [comment]
the newer versions 3.5(pr) 3.4, 3.3 and 3.2 use a different location for settings than earlier  to 2006 file or 2007+ prefs.txt or other various pre 2019 (3.1.2 XP etc.) locations but since 2020 onwards has been the same default localappdata location

So it depends which version you had and which version you are running. If you had custom settings in an older location it may be possible to reuse those, if not deleted.
