### ISSUE TITLE
Image problem

### ISSUE THREAD

**Issue by wodecx** [sumatrapdfreader/sumatrapdf#3320]
Version: 3.4.6 64-bit

Some epub and mobi ebooks have image inside it. The image are too small when it's Single Page. There are too much space on the left and right. If I choose Fit Width then the text will become very large. 

The old version 3.3.3 has not this problem.

I tried to edit the settings file. It's not working. Maybe you can tell me how to do it.

**Comment by GitHubRulesOK** [comment]
The behaviour of ebook images can be erratic with the MuPDF engine
 some issues raised have been fixed in recent updates
 some may be in progress or can not be altered
 but each case depends on source file definition of scale and placement. 
Always test with current pre-release lower portable single exe version will do for test https://www.sumatrapdfreader.org/prerelease
If problem is still there a sample is needed for any fixing, otherwise you stick with a copy of version that works best for your files.

**Comment by kjk** [comment]
I would need at least screenshots but preferable a sample document.
