### ISSUE TITLE
PDF Render Regression (3.4.6 vs 3.3.3)

### ISSUE THREAD

**Issue by Hiche3** [sumatrapdfreader/sumatrapdf#3328]
Some PDFs render worse in 3.4.6 compared to 3.3.3.
The issue was introduced in version 3.4.

I have encountered several PDFs from different sources with similar issues.

Same windows 10 machine.

**Version 3.3.3:**
 
![3 3 3](https://user-images.githubusercontent.com/65008496/222931765-cc7275f2-c79b-480a-927c-4e188cb66e70.png)

**Version 3.4.6:**

![3 4 6](https://user-images.githubusercontent.com/65008496/222931775-90873c82-6885-44da-aa56-71b5f8f921d8.png)

**Comment by GitHubRulesOK** [comment]
appearance wise that is reminiscent of poor source font CMaps with different heuristic solutions applied 
whatever the cause, a sample is need to report as issue or attempt fix.

**Comment by kjk** [comment]
Can't do anything with a sample file showing the problem.

**Comment by Hiche3** [comment]
@kjk 
Please find attached.

[pdf.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/10890741/pdf.pdf)

**Comment by kjk** [comment]
I can see the differences. It's a mupdf issue.

**Comment by avorobey** [comment]
FWIW, I've bisected the problem to [this commit](https://github.com/sumatrapdfreader/sumatrapdf/commit/f3d98f69a4d2a3c490a1e819b8570a1af37b04a2).

**Comment by kjk** [comment]
Most likely http://git.ghostscript.com/?p=mupdf.git;a=commitdiff;h=b1e505d1824d4356e48ce9e11cc5a02d6fa785dc

**Comment by kjk** [comment]
@avorobey Thanks for narrowing down the commit.

I've reported it to mupdf: https://bugs.ghostscript.com/show_bug.cgi?id=706480

**Comment by avorobey** [comment]
I uploaded a fix to the mupdf issue. I'm not sure how attentive they are to bugs and patches (threw a cursory look and it seemed like there's a bunch of bugs opened by you w/ no attention, but I honestly have no clue and may be misjudging).

**Comment by robinwatts** [comment]
Sadly, we are quite busy, and, while it may look like we're floating along serenely ignoring bugs, it's generally because we're frantically paddling away under the water where you can't see. We do try to get to everything eventually.

As @kjk says, we do have a Discord channel. Talking to us there is a good way to catch our attention. We can't promise to get to stuff earlier, but we can generally give you some indication of how long it might take us to get there (and you can be sure we haven't missed the bug go in).
