### ISSUE TITLE
jp2.zip not rendered correctly

### ISSUE THREAD

**Issue by altongusta** [sumatrapdfreader/sumatrapdf#3355]
Zipped jp2 files not rendered correctly. A single non-zipped jp2 file rendered ok. This happens with version 3.4.6 x64. Attached a comparison of 2 renderings and a test file. Image is from [archive.org](https://archive.org/download/northdevoncoast00harp/northdevoncoast00harp_jp2.zip).
![sumatrapdf_jp2_zippedjp2_compare](https://user-images.githubusercontent.com/209519/225711958-eac0f9cd-473f-409e-bc30-b8c5e1bd3a57.jpg)
[northdevoncoast00harp_0028_jp2.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/10994257/northdevoncoast00harp_0028_jp2.zip)

**Comment by avorobey** [comment]
Definitely the funniest bug I've seen recently. Attaching the fix:

[patch1.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/11001365/patch1.txt)

In the JP2 image header, the height comes before the width, while the code assumed otherwise. [Evidence
the new code is correct](https://github.com/uclouvain/openjpeg/blob/master/src/lib/openjp2/jp2.c#L582).

When the JP2 file is loaded directly and not through .zip, a different engine is used (image instead of comic book),
and different code path is used to load image size: GdipGetImageWidth()/Height() from a native image. I'm not sure
why.

**Comment by kjk** [comment]
Good catch @avorobey , patch applied!

**Comment by kjk** [comment]
@avorobey the reason we have Jp2SizeFromData() and similar is a performance optimization.

To do layout we need the sizes of images.

Decoding the whole image just to get the dimension is very slow so we wrote those functions  to get dimension just by reading a few bytes from the file.
