### ISSUE TITLE
tab stays higlighted when mouse leaves the tab

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#3396]
When mouse leaves a tab, the tab stays drawn in highlighted state. That WM_MOUSELEAVE had a purpose after all :)

**Comment by avorobey** [comment]
Damn it :) 

OK, let me fix it by directly doing stuff in WM_MOUSELEAVE. That fallthrough was still a bad idea, there's so much stuff going on WM_MOUSEMOVE that has no idea it could be happening on WM_MOUSELEAVE.

**Comment by kjk** [comment]
Isn't my change enough?

**Comment by avorobey** [comment]
It brings the crash back. The problem is that sometimes you get a spurious WM_MOUSELEAVE while your pointer is inside the window. I don't really understand why it happens. Assume for a second it  happens for some reason. Then you set tabHighlighted=-1, but it's not really true, your pointer is still there. The next WM_MOUSEMOVE is going to be confused, its tabUnderMouse will be correct, but tabHighlighted is wrongly -1. That's what caused the crash originally. 

One way I have of reliably causing it is: right-click to bring a popup context menu, then move pointer a little, still saying in the same tab, and left click + move. Crashes reliably for me, and I see WM_MOUSELEAVE happening. I just found Raymond Chen [saying](https://devblogs.microsoft.com/oldnewthing/20101206-00/?p=12113) that the spurious WM_MOUSELEAVE is because someone called SetCapture(). But the crash doesn't happen if I just left-click + drag, which calls the same SetCapture(), but doesn't send WM_MOUSELEAVE. And the popup context menu doesn't (I think) call SetCapture(). Something's weird is going on.

**Comment by kjk** [comment]
I guess a hackish thing could be to check in WM_MOUSELEAVE if the cursor is over HWND and disregard. But even better would be to understand :)

This code is tricky.

**Comment by kjk** [comment]
Looks like only Contains() needs to be fixed. Will look into it.
