### ISSUE TITLE
Not rendering characters

### ISSUE THREAD

**Issue by ingyer-ks** [sumatrapdfreader/sumatrapdf#3403]
Dear,
I have a pdf file which seems fine on pdf.js of Firefox like below:
![image](https://user-images.githubusercontent.com/75936561/228591327-f880db0f-8468-43b9-af34-c65ef5bdfffd.png)
But, on SumatraPDF, the numbers are not rendered at all, in the table.
![image](https://user-images.githubusercontent.com/75936561/228591585-84dc40d5-4861-4efb-a8e4-a798982c7e6a.png)
How I can read the file with SumatraPDF correctly?

**Comment by kjk** [comment]
First, which version of Sumatra?

Missing / bad rendering of text is most likely caused by incorrectly generated PDF file. Missing fonts, incorrectly encoded characters etc.

PDF readers try to understand even broken files but they don't always succeed. Log output will likely have some hints (`Ctrl + K` for Command Palette, `show log`).

Here pdf.js did a better job at repairing the file but that's all I can tell without access to the file. 

Our rendering engine is mupdf so it's best to report bugs like that to them: https://bugs.ghostscript.com/

**Comment by kjk** [comment]
Nothing for us to do here without a sample document.
