### ISSUE TITLE
Printing individually selected pages only prints page 1

### ISSUE THREAD

**Issue by syntaxartisan** [sumatrapdfreader/sumatrapdf#3427]
When printing on Windows 11, the page range option is not being honored. I select to print page 2 but it's printing page 1. This is repeatable, but only with certain PDF files. Other PDF files print correctly.

Process:
* Press Ctrl-P
* Click on All pages
* Select Custom Range
* Scroll down
* Enter page range: 2
* Click on Print button
* Page 1 is printed

**Comment by syntaxartisan** [comment]
Same issue with versions 3.2 and 3.4.6 (latest).

**Comment by GitHubRulesOK** [comment]
SumatraPDF simply hands over to the windows printing system that's why there will now be more issues on Windows 10/11 and were in 7/8 more compared to say XP when SumatraPDF had more (and less) options to play with.

The choice of dialog and its functions per driver are entirely down to the Print Driver, so its not usually related to this input or that (will be as many pages from 1 to total as specified) its down to this output or that, where MS (and others) control the number / limit of page copies.

If it is repeatable
Then please provide a file as per bug reporting, and other info such as is it present in current pre-release (portable will do), and what type of print driver is involved.

NOTE the SumatraPDF progress will always show logical pages requested so always starts with 1 so if I ask for 20-30 I will see 1-11

![image](https://user-images.githubusercontent.com/12754913/230696343-7d80204e-9932-4668-9b79-c7a1d06975f2.png)

**Comment by syntaxartisan** [comment]
I printed the PDF in Microsoft Edge without issue.

How do I upload a PDF privately?

**Comment by GitHubRulesOK** [comment]
for privacy email to developer per bug reporting his email withe the requirements is at https://www.sumatrapdfreader.org/docs/Reporting-printing-bugs

**Comment by syntaxartisan** [comment]
Email sent using the reporting guidelines.

**Comment by kjk** [comment]
I can't reproduce it using latest pre-release.

I printed that file, used the range `1-2` in printer dialog and it printed both pages.

You said you enter the range as `2` which is not the correct syntax. It says "print page 2". A range is `1-2`.

**Comment by syntaxartisan** [comment]
Range would be "2" if you wanted to print page 2 only. Did you try printing page 2 only?

**Comment by syntaxartisan** [comment]
The dialog shows the example that you can print a range of pages (1-2) or an individual page (5), or both in the same print job (1-2,5). This is a common feature in print dialogs (to select individual pages or page ranges) and appears to be the case in the Sumatra print dialog as well. Are you saying that the Sumatra print dialog is showing in the example that you can print individual pages but it doesn't actually support that?
![image](https://user-images.githubusercontent.com/37125672/231246020-41732dff-a28b-43be-b584-4e7ec760d829.png)

**Comment by GitHubRulesOK** [comment]
@syntaxartisan 
if windows accepts the range sumatrapasses it but reports the windows print progress so PAGE=2 in = PAGE= 1 out

**Comment by syntaxartisan** [comment]
I haven't had an issue with the print progress display. I will say that I have two example PDF's that are causing the issue and when I print them on Edge, Firefox, Brave, and Opera, they correctly print page 2. But if I print them on Sumatra they incorrectly print page 1. So if Sumatra is indeed handing the requested page range directly to the operating system (Windows) then Windows is singling out Sumatra and ignoring the range that it gives but honors the page range from other applications. That's harder to believe than Sumatra is struggling with page endings on certain formatted PDFs.

Just to verify, did you try printing page 2 only? It would be useful to see if the correct page is being printed for you.

**Comment by GitHubRulesOK** [comment]
@kjk can you verify if setting range =2 in sample only prints a copy of page 2  not 1?
