### ISSUE TITLE
Continuous page view mode is not working if the opened file is called "image.pdf"

### ISSUE THREAD

**Issue by pgp** [sumatrapdfreader/sumatrapdf#3431]
Hi, I noticed that, when I open in SumatraPDF a file with name "image.pdf" containing more than 1 page, the continuous page view is not working. Instead, after scrolling to the end of page i, the reader immediately jumps at the begin of page i+1. If the file is renamed to another name, everything works correctly instead.
I attach a sample pdf file, generated using Irfanview multipage pdf feature, using 2 sample PNG images (attached as well) - indeed I discovered this bug because Irfanview's pdf export default name is "image.pdf".
[sumatrapdf_continuous_page_bug.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/11183839/sumatrapdf_continuous_page_bug.zip)

**Comment by GitHubRulesOK** [comment]
Unclear description of issue HOWEVER

@kjk the `C` shortcut on occasions seems to be non functional when focus is pulled from main screen? is there a way to elevate some more desirable functions back to main canvas area I.E seem to remember (possibly wrongly) users confused when focus was not where mouse was with bookmarks pane

Current Pre-Release no issue ?
In Continuous mode the file works as expected but in non continuous page mode it will by design jump pages
![image](https://user-images.githubusercontent.com/12754913/230739527-4aaea5ed-d27b-4597-acb7-fd3d102786c1.png)

**Comment by pgp** [comment]
Hi, I confirm that everything works correctly using latest pre-release build of Sumatrapdf - clearly the bug has already been fixed somewhere in last year's commits. 

Thanks for the support and happy Easter :smile:
