### ISSUE TITLE
Crash when opening pdf.

### ISSUE THREAD

**Issue by bobadaliev** [sumatrapdfreader/sumatrapdf#3443]
https://gist.github.com/bobadaliev/5b44fad018a0416341cd1ba23261fee6

**Comment by GitHubRulesOK** [comment]
Usually such crashes are often due to bad Pirate Copies this one behaves reasonably but as a conversion from calibre has many flaws in how pages are referenced.
![image](https://user-images.githubusercontent.com/12754913/232547384-e6c15e31-bd6c-4972-8b38-377a9ce1e147.png)

So if its just one book from many not direct from publisher then suspect it is a faulty version.

Howevr you may find pre-release can handle such poor copies better so always test using current pre-release. https://www.sumatrapdfreader.org/prerelease (portable will do for testing), if that fails too repeatedly with one document then you need to supply a copy.

**Comment by kjk** [comment]
This is most likely already fixed in latest pre-release version https://www.sumatrapdfreader.org/prerelease
