### ISSUE TITLE
Bookmarks navigate to the wrong position.

### ISSUE THREAD

**Issue by liplushe** [sumatrapdfreader/sumatrapdf#3501]
As shown in the following picture:
<img width="1920" alt="Snipaste_2023-05-17_17-43-32" src="https://github.com/sumatrapdfreader/sumatrapdf/assets/52035356/f8d9f7c7-2853-4980-a0db-de311fa914d0">
The PDF file is [here](https://github.com/liplushe/JournalsCrawler/blob/main/%E5%A4%A7%E5%9C%B0%E6%B5%8B%E9%87%8F%E5%AD%A6.pdf) for test.

**Comment by GitHubRulesOK** [comment]
Closing since Sample works in current pre-release, gust to confirm action is go to page 13
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/96f5766f-4932-41f3-adb0-9b6617515f23)

Current Pre-release goes to page 13 as seen here
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/cb2e4b6b-a522-4e0d-854d-d397cbb4ca79)
