### ISSUE TITLE
Cannot show text in .svg files

### ISSUE THREAD

**Issue by hrishikesh-deshpande** [sumatrapdfreader/sumatrapdf#3506]
I am not sure if svg is supported or not, but opening an svg file does not display text in it.
Image for reference below. I hope it can be saved as svg.

![temp](https://github.com/sumatrapdfreader/sumatrapdf/assets/70664941/2379df8b-fb4b-4b29-8b39-768ba14d6418)

**Comment by GitHubRulesOK** [comment]
The text in that file says see "https://www.drawio.com/doc/faq/svg-export-text-problems" which explains why it is for embed in html only which is why it displays in your question. 
So the SVG warns you its not always to be seen, so will appear when saved in a Graphics package as PNG but will loose any font intent as its now Times Roman Serif rather than the source Sans Serif.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/4552ed9c-2eaf-4bd4-833a-3f079fa08c4f)

Thus to retain PDF vector output its best to export as PDF in Drawio
