### ISSUE TITLE
loading speed

### ISSUE THREAD

**Issue by gthb1** [sumatrapdfreader/sumatrapdf#3509]
Hi,
Why is v3.4.3-64 fast and v3.4.6-64 slow loading, especially if you have 50 tabs+ open?
Please advise what can be done to have same or better speed than in v3.4.3-64.
Thx

**Comment by GitHubRulesOK** [comment]
3.4.6 had fixes that may have increased some speeds and reduced others but only comparisons can be made using current pre-release which could be slowest or hopefully quickest of all

**Comment by gthb1** [comment]
The speed difference is huge. It is like the previous version loads only the currently visible tab, while the current version seems to load all tabs fully. Maybe that is the reason for the snail speed. Where can this be adjusted?

**Comment by GitHubRulesOK** [comment]
3.4.6 has show log CTRL K > Show log
usually slow load is due to bad font description

so times are ms = 1/1000 seconds
prefs::Load() took 0.67 ms
couldn't find system font 'serif'
LoadDocument: 2908.33 ms, 344 pages for 'C:\Users\lz02\Downloads\pg70683-images-3.epub'
DisplayModel::BuildPagesInfo took 0.02 ms

**Comment by gthb1** [comment]
Thx for explaining one possible reason for v3.4.6 being slower.

Why were the same 50 documents loading fast in version 3.4.3 (and slow in v3.4.6) ?

How can v3.4.6 be adjusted to load (the same 50 documents) as fast or faster than v3.4.3?

Thx for practical/usable advice in advance.

**Comment by GitHubRulesOK** [comment]
Part of the speed issues is that to improve one of many formats aspect, the adjustments will usually result in collateral damage in another format, thus its often a round of balancing see saw tasks.

The switch from old code (legacy) rendering engines to as much MuPDF core as possible has resulted in thousands of such alterations and the fact that MuPDF in turn depends on other code libraries will alter the balance from time to time.

For the files you use heavily it seems those changes had for your sources a negative effect but for other files you may find comparative improvements.

3.4.6 itself cannot be changed since the more recent code changes are often incompatible with prior code, hence the only way to improve speed in any given case is, supply a known poor rendering example to see if it can be used to re-address any imbalance.

**Comment by kjk** [comment]
There's no concrete info about what exactly is slow.

Also, check pre-release version https://www.sumatrapdfreader.org/prerelease
