### ISSUE TITLE
[Installer] Uninstall

### ISSUE THREAD

**Issue by xmha97** [sumatrapdfreader/sumatrapdf#3516]
Hi, I use a standard user and don't have admin permission.
Now I installed SumatraPDF without admin permission.
But Now can't uninstall it because the uninstaller needs admin permission!
Please fix this issue.

**Comment by xmha97** [comment]
Even if the system administrator enters the password, the app will not be uninstalled. 🙁

**Comment by kriswilk** [comment]
I've noticed this, too. Local user installation does not present a UAC prompt, but uninstalling DOES. Is there an important reason for this? If not, I agree that it needs to be fixed.

**Comment by xmha97** [comment]
I think this project has been discontinued :(

**Comment by GitHubRulesOK** [comment]
@kriswilk 
Administrators can install for all users apart from personal local apps
All users can use Program Files as a secured application area for running multiple user installs via elevation to run as admin
If a user needs elevation to install extra features (options like preview) they should also need elevation to uninstall said system options.

**Comment by kriswilk** [comment]
> However if installed without need for UAC elevation it seems odd that uninstall needs some system closure ? is search files or preview files active ?

That's exactly the problem. I just tested again on a different system with no previous SumatraPDF. System details are:

- Windows 10 Pro 22H2 with latest updates
- My logged-in user is in the admin group

Steps are:

1) Double-click 64-bit installer EXE.
2) Click "Install SumatraPDF"
3) Open a PDF, everything works.
4) Close SumatraPDF
5) Open Add/Remove Programs
6) Find SumatraPDF and "Uninstall"

Step 6 immediately generates a UAC elevation prompt. Once elevated, the uninstaller appears and clicking "Uninstall" proceeds as expected.

@GitHubRulesOK, do you not get this behaviour??

**Comment by GitHubRulesOK** [comment]
My test system will be "dirty" so I need to shut down apps that are using SumatraPDF first.

Ok unsure how clean I made this system for normal comparison, but uninstall will here ask my user for permission as its a drastic removal.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/e42f2cc5-31c1-44c8-93f2-2b452ac164ea)

However its exactly the same warning for run another applications uninstaler.exe
Cant capture screen as its blocking anything other than yes no !
Simply the name of the exe is different

**Comment by kriswilk** [comment]
I appreciate your attempt to clarify but the prompt is NOT just a notification that a standard user can dismiss.

My previous testing was done while logged in as an admin user. I just repeated my test as a NON-ADMIN user. My observations are:

- Installation works fine, without any extra permissions required. The app installs to the user's AppData folder as expected.
- Uninstallation presents a UAC prompt REQUIRING an administrator's password to proceed. The non-admin user CANNOT uninstall the software, even though they could install it.
- EVEN WORSE, if I enter my admin credentials to allow the uninstall to proceed, the software is NOT uninstalled...it remains in Add/Remove Programs, Start Menu, and can continue to be used.

The last point is EXACTLY what @xmha97 [reported earlier in this issue thread](https://github.com/sumatrapdfreader/sumatrapdf/issues/3516#issuecomment-1564682384).

There is definitely a problem here!

**Comment by kriswilk** [comment]
After writing my last reply I figured out what's happening.

When a non-admin user attempts to uninstall and an admin user provides credentials to proceed, the uninstaller removes the software FROM THE ADMIN ACCOUNT rather than the non-admin account. Yikes!!!

Try it for yourself:

- sign in as an admin user
- install (no UAC prompt)
- sign out
- sign in as a non-admin user
- install (again, no UAC prompt)
- uninstall (UAC prompt, provide admin credentials)

After this process, the non-admin account still has SumatraPDF, and the admin account has had it uninstalled!

This is a serious issue.

**Comment by xmha97** [comment]
> I appreciate your attempt to clarify but the prompt is NOT just a notification that a standard user can dismiss.
> 
> My previous testing was done while logged in as an admin user. I just repeated my test as a NON-ADMIN user. My observations are:
> 
> - Installation works fine, without any extra permissions required. The app installs to the user's AppData folder as expected.
> - Uninstallation presents a UAC prompt REQUIRING an administrator's password to proceed. The non-admin user CANNOT uninstall the software, even though they could install it.
> - EVEN WORSE, if I enter my admin credentials to allow the uninstall to proceed, the software is NOT uninstalled...it remains in Add/Remove Programs, Start Menu, and can continue to be used.
> 
> The last point is EXACTLY what @xmha97 [reported earlier in this issue thread](https://github.com/sumatrapdfreader/sumatrapdf/issues/3516#issuecomment-1564682384).
> 
> There is definitely a problem here!

Thank you for testing.
This is exactly the problem I reported.

**Comment by k2pctdn** [comment]
I can confirm this problem. It's very annoying.

**Comment by k2pctdn** [comment]
Hello,

This is my way to uninstall SumatraPDF without the admin rights.

- First, make sure your installation is just for you (installed in `C:\Users\Your-User-Name\AppData\Local\SumatraPDF`).
- Then check the folder `C:\Users\Your-User-Name\AppData\Local\Temp` for the file `Sumatra-Uninstaller.exe`. Make sure it is here.
- Open the cmd in this `Temp` folder above and run the command: `Sumatra-Uninstaller.exe -uninstall`. Follow the on screen instruction to uninstall the program without the admin rights. In case you don't know how to open this `Temp` folder in cmd, just open cmd and run this command `C:\Users\Your-User-Name\AppData\Local\Temp\Sumatra-Uninstaller.exe -uninstall`
- Remember to replace `Your-User-Name` with the corresponding name on your computer in every step.
- Also, make sure you run the command in the Command Prompt, not PowerShell.

It's really annoying when this problem is still there after many versions.

**Comment by GitHubRulesOK** [comment]
@0lm 
the installed version is ONE.EXE so it is installer/viewer/uninstaller
the switches tell it what state it is in 
Installed for all users it is located in a protected area thus needs permissions to run as uninstaller, these are built-in features so when invoking the system uninstall the system protected exe responds in uninstall mode hence a need for more than single user  access (UAC)

**Comment by kjk** [comment]
This should be fixed in latest [pre-release](https://www.sumatrapdfreader.org/prerelease)
