### ISSUE TITLE
Sumtra installed in a nonstandard place

### ISSUE THREAD

**Issue by zivran** [sumatrapdfreader/sumatrapdf#3533]
I have a standard Windows 10 pc; somehow Sumatra got installed in
C:\Users\ziv\AppData\Local\SumatraPDF\SumatraPDF.exe
This seems to cause compatibility problems.

Why is it there and should/could it be installed in a standard folder like Program Files ?

**Comment by GitHubRulesOK** [comment]
you can chose the traditional install location c:\program files [(x86] as desired for multiple users with one device, but default for single user is appdata local since its a local install for one users data and easier to keep all files relative to each other
Thus not to be sullied by other users concurrently.

Unsure why you have compatibility unless installed by an admin user for use by others.

**Comment by zivran** [comment]
I am using Sumatra as external pdf viewer for Tex Studio.
Tex Studio will not launch Sumatra though it's supposed to, but once
launched it will
interact normally with Sumatra.
I have other Windows pcs and the problem is just with this one.

**Comment by GitHubRulesOK** [comment]
Hmm I think my old notes may be out of date for installations with TeX but it should not matter as long as pathing is correct.
but there is a known issue with 3.4.6 installed as 64bit due to synctex compression.

perhaps show your TeX Studio command but note it should be simply something like 

>For forward search modify Configure > Commands > External PDF Viewer to
"path\to\SumatraPDF.exe" -forward-search "?am.tex" @ "?am.pdf"

TeX enhancements and reuseinstance should be true in SumatraPDF advanced settings

the return call should be something like

>"path to\editor\texstudio.exe" "%f" -line %l

**Comment by zivran** [comment]
Inverse search works ok.

The 'external pdf viewer' command is
"C:/Users/ziv/AppData/Local/SumatraPDF/SumatraPDF.exe" %.pdf
The path is correct.

**Comment by GitHubRulesOK** [comment]
the usual structure for calling a previewer when compiling is to pass the tex and pdf names as shown above

>SumatraPDF.exe" -forward-search "?am.tex" @ "?am.pdf"

 beware the older long  description here https://texstudio-org.github.io/configuration.html#sumatra is designed for the alternative DDE method (should work) but dont include the inverse search part in every compile its only needed once for configuration thus the shorter method per above.

**Comment by zivran** [comment]
modified the external pdf viewer as suggested but no change
it will not launch sumatra
if sumatra is open, it will not open the requested pdf (that can still be
opened through sumatra's file menu)

**Comment by zivran** [comment]
I wonder if this is relevant:
under user commands/ search:forward search found this
dde:///"C:/Program Files
(x86)/SumatraPDF/SumatraPDF.exe":SUMATRA/control/[ForwardSearch("?am.pdf","?c:am.tex",@,0,0,1)]

Is this bad?

**Comment by GitHubRulesOK** [comment]
no that looks like TexStudio is trying to do it using its own way using DDE  so it thinks that works using the historic location for an all users install, simply change the path to your personal local exe

The only reservation I have is that address is expecting an older 32 bit  (x36) version (thus if its using 32bit DDE you need a 32bit SumatraPDF (portable or installed), I cannot tell so you need to determin if its using 32 bit or 64 bit calling by start SumatraPDF first (either portable can work that way if its running) and see which works!

**Comment by kjk** [comment]
This is the correct location for non-admin install
