### ISSUE TITLE
Support for encrypted zip containers (zip/cbz)

### ISSUE THREAD

**Issue by mfaizsyahmi** [sumatrapdfreader/sumatrapdf#3539]
Currently the reader displays blank pages when it encounters encrypted files in zip containers. It should instead check if the file is encrypted, and if so, ask for a password.

**Steps to reproduce**

1. Start SumatraPDF and open a zip container (zip/cbz) with encrypted files.

**Expected outcome**

1. Program checks if file is encrypted.
2. If file is encrypted:
    1. Program asks for password.
    2. Program decrypts the file contents, displaying it on the reader.
4. Else, open and display file as normal.

**Actual outcome**

1. It displays blank pages on the viewer.

**Comment by mfaizsyahmi** [comment]
I saw that this is a duplicate of #95, but I don't agree with the last commenter's sentiment there.

**Comment by GitHubRulesOK** [comment]
The problem is a bit like XY problem

- PDF does not need encryption EXCEPT ONE and only ONE person desires access via their private keyword.
- PDF does not function (cannot show) inside another compressive wrapper such as zip folder, since it needs be 100% decimal relative address to unzip to display its own content, only possible as a file system object in its own write.
- So although PDFs in zip may help for transportation (where only one file at a time is possible), after transport such single wrapped files need to be come system files not transport packets.

- Thus PDF only needs Password in rare cases once extracted from any container such as DB or rar etc

It is fairly similar for other zip containers such as DocX but each file structure has its own peculiarities.
