### ISSUE TITLE
Welcome to SumatraPDF Reader Discussions!

### ISSUE THREAD

**Issue by simoncireneo** [sumatrapdfreader/sumatrapdf#3544]
### Discussed in https://github.com/sumatrapdfreader/sumatrapdf/discussions/2293

<div type='discussions-op-text'>

<sup>Originally posted by **kjk** January 28, 2022</sup>
## 👋 Welcome to SumatraPDF Reader forum!
  This is a place to:
  * ask questions about SumatraPDF
  * share ideas on how to improve SumatraPDF

**Reporting a bug or requesting a feature**? Please [create an issue](https://github.com/sumatrapdfreader/sumatrapdf/issues).

If bug involves a specific PDF (or CHM or XPS or ...) file, please provide the file showing the problem. Either attach to the issue or e-mail to `kkowalczyk@gmail.com` if confidential.

Here's an archived version of [previous forum](https://forum.sumatrapdfreader.org/) (still has potentially useful infomration).
</div>

**Comment by simoncireneo** [comment]
I would like to know if is it possible to do something like this woth sumatra using the command line

firs creating a .bat file with this:
open file1.cbr
open file2.cbr
open file3.cbr
save file1.pdf
save file2.pdf
and so on...

**Comment by GitHubRulesOK** [comment]
@simoncireneo 

Not direct with the command line since  SumatraPDF uses Dynamic Data Exchange

so you will either need to use traditional send keys (fiddly vbs from cmd)
or work out how to drive DDE (not easy from a command line)
or one the other AutoIt AutoHotKey macro tools

I would suggest for the VBS route that Orlando's sendkeys.exe is a good option to write easy command strings thus avoiding VBS as can be simply used in a batch file.
small, neat, well documented https://orlandomvp.org/SendKeysMore.asp

so you can 

sumatrapdf file#.cbr
sendkeys ALONG THE LINES OF save as  folder\file#.pdf

from another cmd run above by loop file to next file in a folder
OR above can be used with rightclick sendto for single file
OR drag and drop single file
Or modify to drag and drop a folder.

**Comment by GitHubRulesOK** [comment]
closing as strictly not an issue (it works within limits to "save as" designed)
There are inherently limited types of image acceptable for convert to pdf. So jpeg must be "1992" baseline, PNG will work for lossless, NOT heic/webp and many other file types, as cannot be accepted by PDF.

Thus this is more an extension of other requests to drive the many SumatraPDF internal commands  via external cli
related to https://github.com/sumatrapdfreader/sumatrapdf/issues/3051
