### ISSUE TITLE
There are many blank pages in the EPUB file.

### ISSUE THREAD

**Issue by friendflower** [sumatrapdfreader/sumatrapdf#3580]
In version 3.4, when I open my EPUB book, there are many blank pages interspersed throughout, whereas in version 3.3, it functions properly.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/74846225/6fc6d2af-819f-4276-9998-36eeac959907)
The following zip file contains the book mentioned above.Due to the large file size, I made modifications to it by removing some images.
[book.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/12080130/book.zip)

**Comment by kjk** [comment]
Nothing we can do. This is a very broken file with malformed css and missing images.

Our old engine was just skipping missing images. mupdf chose to show a placeholder with `[image]` to notify about the problem. I'm not going to modify mupdf to change this behavior.

**Comment by FasterFall** [comment]
Bringing this up again, as I think it is an actual big issue, whether you think it's due to the epub being broken or not, as it happens with a lot of files (from my experience), and thus is not really practical.

**Comment by GitHubRulesOK** [comment]
@FasterFall with respect I have had to handle many broken file formats not just documents over the decades and there are so many ways they can be bad I have forgotten the numbers. 

The point is any reader product/application is not an editor to correct or fix such problems beyond reason.

Whilst epub is not PDF an example for others
Acrobat READER will for PDF even on occasion totally re-edit a poor PDF that is because under the hood it is a crippled Acrobat Pro with some proprietary parts removed and some parts retained that are Adobe Only.

SumatraPDF is a front end to Artifex MuPDF and they will for a price improve their code.
