### ISSUE TITLE
PDF jumps up after deleting the last annotation

### ISSUE THREAD

**Issue by wskaa** [sumatrapdfreader/sumatrapdf#3590]
Jumps up = jumps to the page containing the first annotation (which in my case is the uppermost annotation in the document). This only happens when the annotations editor is open. 

A potential solution I considered is shortcutting a command for closing the annotation editor (but this command doesn't exist).

In case this needs to be said: it is a problem because it disrupts the annotating process by moving the user away from the page where they last wanted to annotate. In cases where the pdf file is large and is being read top to bottom (as in my case - I'm reading a long book), the problem increases as reading goes on (because you jump more pages to the first annotation).

**Comment by GitHubRulesOK** [comment]
probably will close as duplicate
If I can find the one I seem to recollect raised in the past
Also may have been fixed in a pending fork but have not tested if that is its current behaviour?

**Comment by GitHubRulesOK** [comment]
cant find the duplicate yet but is corrected in this fork
https://github.com/youmjb/SumatraPDF-mod

**Comment by kjk** [comment]
I believe this is fixed in latest pre-release.

Specifically my test:
* create 2 annotations on 2 separate pages
* delete second annotation in annotations editor

In 3.4.6 this would select the first annotation in listbox of annotations and automatically jump to the page with first annotation.

Now it selects but doesn't auto jumps to the page.
