### ISSUE TITLE
copy email address

### ISSUE THREAD

**Issue by LenkaV01** [sumatrapdfreader/sumatrapdf#3597]
I created excel list of email addresses and then I want to copy one of them.
When i move cursor over it changes to "hand" and if i click to select it opens  browser with empty web page.

Would be better to make selection first (or double click) and support mailto: (or link) with click and press ctrl or shift.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/141139705/ca7c510a-8132-4250-90a5-9ef8d10ab9a8)

**Comment by miloush** [comment]
You should be able to right-click it and _Copy Link Address_, which seems to be designed to address exactly your issue.

The system handles the "mailto:" links according to user's settings, it composes a new message in Outlook for me.

**Comment by GitHubRulesOK** [comment]
when an email address is encountered in a PDF reader it is auto converted to mailto
Here plain text in Edge before it it is printed as PDF text is activated as a browser mailto function
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/469c9198-b76d-4fc3-9469-7c7e0e4d4b3f)

Here in SumatraPDF Reader that too is the default for text same as in a PDF
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/e65946f1-08ba-4ffb-8607-46ff4badd00e)

In order to select as text you need to select outside the active email area any where inside is expected to call Windows to trigger the system default email handler, whatever that may be.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/e0ca9a63-ef88-4771-b740-974ae3b03dbe)

**Comment by LenkaV01** [comment]
Milouch, thank you are right. It helps.

For example same file opened in Firefox  works as I expected before.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/141139705/0290abe1-e098-4fb8-94f2-124286a15ac8)
