### ISSUE TITLE
can't edit on annotated files on other pdf readers

### ISSUE THREAD

**Issue by HelenS2ODS** [sumatrapdfreader/sumatrapdf#3608]
After saving highlights and comments to existing pdf by pressing Ctrl + Shift + S, people using other pdf readers can only view it but have no access to edit on it. It seems like the annotated file contains a digital signature, others have to create a new copy and then work on it. Any solutions to get around with it?

**Comment by GitHubRulesOK** [comment]
there should only be one experimental highlight that's different to the official pre-release, which should be standard annots, thus editable , personally seen no difference between apps so it may depend on the save method or source files you use? need a sample for comparison but here only saved a highligh and opened after save in Acrobat.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/07189805-3954-48f6-913e-19e47626c40a)

**Comment by GitHubRulesOK** [comment]
without a sample I am closing since current pre-release annotations apper to work well enough in other reader editors. as an example
convert this page and add annotation and save
---
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/9276cc07-6776-472a-84f3-90f16dd75e14)
open in edge and the text can be edited
---
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/eba91334-5678-4fe3-8eb4-5269377e0cae)
