### ISSUE TITLE
Right-click on slide page → export as JPG

### ISSUE THREAD

**Issue by Shohreh** [sumatrapdfreader/sumatrapdf#367]
Hello

I often need to extract diagrams in PDFs, and it'd help if I could just right-click on the page and have it exported as JPG.

Curently, I have to open the file in LibreOffice, which is much bigger and slower than SumatraPDF.

Cheers,

**Comment by kjk** [comment]
closing as dup of #687

**Comment by GitHubRulesOK** [comment]
I have published my SumatraPDF Addin script that exports different file **whole page** types as fixed quality PNG (rather than as inferior lossy JPG) but once extracted, either as a single page or a range of pages, they can easily be converted by any other imaging tool.
For more details see
 https://forum.sumatrapdfreader.org/t/export-save-page-s-as-jpg-png-picture-s-image-s/1030/11
