### ISSUE TITLE
15623 Create Text Annotation Crash

### ISSUE THREAD

**Issue by kerryland** [sumatrapdfreader/sumatrapdf#3699]
On page 208 of "Emma", right click just at the end of the first paragraph and create a text annotation.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/398113/0d4177ad-3cf5-4459-9a1e-3866f375055d)

It might take a few attempts, the spot is not always easy to find. I think it's actually a little more to the right than what is shown in the screenshot.

https://gist.github.com/kerryland/4512c5f20909f9cea8d984d57c9113e0

**Comment by kjk** [comment]
> 3.5.15623

Note that I've made a bunch of updates and fixes on master and 15623 doesn't have those. I thought you can build from sources?

Anyway, this one is fixed on master.

**Comment by GitHubRulesOK** [comment]
@kjk 

I dont as you know compile so stuck with daily so you may see crashes without reports possibly similar reasons 
HOwever the problem I have is that I need to download symbols manually since they will never download themselves
Windows 10 has both a `curl` and `tar` cmd so not a problem to write a download and unpack but takes time, 
my gripe is that if I test download symbols and they atre already there they are deleted in prep for the failed download rather than download and then either delete or overwrite ?

**Comment by kjk** [comment]
@GitHubRulesOK Sorry about that, had the wrong url for symbols.

Should be fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/e77823168a3a31d39654cd2d2a6cc7a26aaa6bd6 and available in next daily build.

**Comment by kerryland** [comment]
> I thought you can build from sources

I can, but I don't know if I should consider them test-worthy because you may be in the middle of something. and might not consider them ready.
