### ISSUE TITLE
15623 Adding an Annotation shouldn't adjust the PDF view

### ISSUE THREAD

**Issue by kerryland** [sumatrapdfreader/sumatrapdf#3700]
To reproduce:
- Scroll the PDF view so that a page split is in the middle of the screen (you can see the bottom half of page 1 and the top half of page 2)
- Highlight a word near the top of page 2, and press 'a'
- The PDF view should not rearrange itself, placing the view at the top of page 2. (this is new behaviour)

**Comment by GitHubRulesOK** [comment]
Ok This is an odd one because annots are very like "goto" so page based is not a problem in single page view however

In 2 page view annots often went to wrong page as it is possible for annots to be outside a viewable page area (just did one via muPDF where it is at PDF limits so "miles" off page (default page is 200 inches in each direction) thus "wrong" page is not uncommon.

In Continuous view the page position is not always so noticable when using goto (compared to placing annots) so  often a jump in focus is intentional.

**Comment by kjk** [comment]
I can't repro this with `a` but can with `A` i.e. when edit annotations window is opened.
