### ISSUE TITLE
List of current tabs with names of current documents.

### ISSUE THREAD

**Issue by ghost** [sumatrapdfreader/sumatrapdf#371]
Hello developers,
When the number of pdf files or other documents which are opened are quite high like 10, it is very hard to switch from one document to other ones precisely. There is only one option that readers must to click on each tab to find the wanted one. It is much more convinient if there is a button whose function is to show all current tabs including names of documents as foxit reader or Xchange viewer does. Hope this function will be available in the next release.

Thank you for reading this.

**Comment by SumatraPeter** [comment]
+1 Tab-related improvements have been on my wish list ever since Sumatra started supporting tabs.

See request #5 in my forum thread for example: http://forums.fofou.org/sumatrapdf/topic?id=3184717

**Comment by SumatraPeter** [comment]
Also requested in the new forum: https://forum.sumatrapdfreader.org/t/feature-request-list-all-tabs/131

**Comment by GitHubRulesOK** [comment]
@kjk perhaps consolidate both this #371 and  #63 with master issue #1188

**Comment by SumatraPeter** [comment]
#63 can be consolidated with #1188 for sure since both are about tooltips for individual tabs (displaying the full tab titles), but this one is completely different. It's about showing something like the following screenshot from Firefox:

![image](https://user-images.githubusercontent.com/15380332/70727937-896ff500-1d26-11ea-98b3-7b99aa6a5d47.png)

At one glance we can see a complete list of all open tabs, the currently open tab is clearly marked with the blue bar, and we can simply click on any other entry to jump to that tab.

**Comment by boardtc** [comment]
I have to mark 30 scripts via pdf now because of the virus, constantly switching between all 30 pdfs for each of 7 questions. Not having a quick way of seeing the tab name and switching too it - that's available with all browsers (albeit perhaps with an extension) - is incredibly frustrating and causing a lot of needless extra work. Up to this I have been delighted with Sumatra but now disappointed that an issue raised 5 years ago is still not put to bed. No chance there is a nightly or something with an early version of this available?

**Comment by GitHubRulesOK** [comment]
@boardtc 
So many files open is not whats "expected" from a book reader that sounds more like a business usage working around such limitations needs understanding of workflow, so are the scripts the same 30 objects each time, then its easy just add them as 30 favorites
![image](https://user-images.githubusercontent.com/12754913/81498162-3b522400-92bb-11ea-84c4-727f78a3cdac.png)

**Comment by boardtc** [comment]
Ok. I did not know that was Sumatra was focused around books. I use PDFs all of the time but not very often with books, PDFs are much more than books imho.

**Comment by GitHunter0** [comment]
It is an important feature, I hope this get done in the near future. Thank you

**Comment by GitHubRulesOK** [comment]
@kjk **[important]**
I was looking at this thread and interested to see @SumatraPeter  s earlier comment (I would normally address him about a change but he has noticeably been missing a long time, I hope he is still live)
Anyway the point is that the above fofou link
http: // forums. fofou. org/sumatrapdf/topic?id=3184717 (and thus many other similar ones) appear to be hijacked to a rogue infected location I thus suggest the above post and others be changed to Internet Archive or as a minimum be deleted
Just for the record Peters old entry was captured at https://web.archive.org/web/20160525173158/http://forums.fofou.org/sumatrapdf/topic?id=3184717&comments=4

**Comment by bbahes** [comment]
Any update on this?
Maybe simple right-click on tabs brings list of all open pdf's ?

Thanks!

**Comment by kjk** [comment]
Command Palette (`Ctrl + K`) shows list of tabs at the top, allows filtering by partial name match so it should be acceptable implementation of the general idea.
