### ISSUE TITLE
Unknown source file (d:\home\john\Dropbox\sp\paper1_theories_v25.tex) under Windows 10 & Cygwin64

### ISSUE THREAD

**Issue by thjwong** [sumatrapdfreader/sumatrapdf#377]
Hi Krzysztof,
From Sumatra-PDF to Emacs, backward-search works, but I could not yet get forward-search to work up till now after fiddling with the settings (and giving up, and then trying again) for few months. If forward-search works, it would be MUCH better for my editing. Thanks in advance.
Under Windows 10 64-bit and Cygwin64, I am using GNU Emacs 24.5.1 (i686-pc-mingw32) with cygwin-mount.el and setup-cygwin.el. I believe it does pass some values to Sumatra-PDF from Emacs or else there won't be the Unknown source file message as the full path of the existing file in brackets, here is the forward-search setup in my .emacs file:

(setq TeX-PDF-mode t)
(setq TeX-source-correlate-mode t)
(setq TeX-source-correlate-method 'synctex)
(setq TeX-source-correlate-start-server t)
(server-start)

(setq TeX-view-program-list
      '(("Sumatra PDF" ("\"C:/Program Files (x86)/SumatraPDF/SumatraPDF.exe\" -reuse-instance"
			(mode-io-correlate " -forward-search %b %n ") " %o"))))

(eval-after-load 'tex
  '(progn
     (assq-delete-all 'output-pdf TeX-view-program-selection)
    (add-to-list 'TeX-view-program-selection '(output-pdf "Sumatra PDF"))
    )
  )

**Comment by kjk** [comment]
This is more of a question than a bug report.

Personally I don't use tex integration and don't know it well enough to offer any assistance.

**Comment by thjwong** [comment]
Thanks for your quick reply.
By "tex integration", do you mean TeXLive or do you mean AUCTeX?
It would be nice to know if this message "Unknown source file (d:\home\john\Dropbox\sp\paper1_theories_v25.tex)" means actually that the value passed to Sumatra (should or) should not be inside a pair of brackets.

**Comment by kjk** [comment]
First, does "d:\home\john\Dropbox\sp\paper1_theories_v25.tex" exists?

If no, then error message is correct.

If yes, then looking at the error message it seems that the code that invokes sumatra passes `(c:\foo.txt)` instead of `c:\foo.txt` (and really `"c:\foo.txt"` to correctly handle spaces in the path).

Given that it's generated from lisp code, it's not entirely surprising that there would be a typo adds '()` to file name.

**Comment by haoyun** [comment]
Sorry to reply to this closed issue.

But I have the same problem. After searching the keywords ``sumatrapdf unknown source file" in google, I find quite a lot of people have this problem but I didn't find an answer. 

I re-describe the problem. I am using dde via tclsh.

    package require dde
    dde execute  SUMATRA control {[ForwardSearch("d:\test.pdf", "d:\test.tex",231,0,0,1)]}

The the file `d:\test.pdf` opens correctly and the first page show up. But on the upper left corner, 
    
    unknown source file (d:\test.tex)

appears. The file `d:\test.tex' does exist.

**Comment by kjk** [comment]
Please note I'm not synctex expert (I didn't write this code).

I think the message here is a bit misleading and really it's about missing .pdfsync/.synctex/.synctex.gz file, not the .tex file.

I guess the code expects corresponding d:\test.synctex (or .pdfsync or .synctex.gz) file which describes a mapping between test.tex and test.pdf, which is needed to do search.

Those commands are meant to communicate between sumatra and an editor that does tex => pdf conversion while also generating synctex files.

See https://tex.stackexchange.com/questions/118489/what-exactly-is-synctex

**Comment by haoyun** [comment]
Thank you @kjk.

I found the problem. It's really a problem of `synctex.gz`.

I was writing test code. In order to type less, I just copied `.tex`, `.synctex.gz` and `.pdf` to `d:\`, so the path is shorter. But the copied `.synctex.gz` does not work, as it contains the original path information inside.

This was my own fault.

**Comment by gx-xg** [comment]
how to solve the problem,

**Comment by GitHubRulesOK** [comment]
@gx-xg 
Please provide more detail of your editor and tex system with sample files e.g. zip up a small sample.tex with compiled sample.synctex and compiled sample.pdf, however note this issue is generally down to bad behaviour in the editor building of the synctex file header (often the path to the tex file is incorrectly stored in the synctex file)

**Comment by gx-xg** [comment]
I am working with emacs 25.2 version, Texlive2019 on Windows 10
Everything is compiling, there is no problem there. when I enter shortcut c-c, c-v, Sumatra opens after compilation,  I receive a tiny message on top of the pdf file that stays for a few seconds:
unknown source file (c:\User\gx\Desktop\Files_xgx\Project\Project_1\Notes on writting paper\2D\ main.tex)

here is my configure code in .emacs
;;forward and inverse search
(setq TeX-PDF-mode t)
(setq TeX-source-correlate-mode t)
(setq TeX-source-correlate-method 'synctex)
(setq TeX-source-correlate-start-serve t)

(setq TeX-view-program-list 
  '(("Sumatra PDF" ("\"D:/SumatraPDF/SumatraPDF.exe\" -reuse-instance" (mode-io-correlate " -forward-search \" %b \"  %n ") " %o"))))
(setq TeX-view-program-selection  
      '(((output-dvi style-pstricks) "dvips and start")
	(output-dvi "Yap") 
	(output-pdf "Sumatra PDF")
	(output-html "start")))

(add-hook 'LateX-mode-hook
	  (lambda ()
	    (assq-delete-all 'output-pdf TeX-view-program-selection)
	    (add-to-list 'TeX-view-program-selection '(output-pdf "Sumatra PDF"))))

**Comment by gx-xg** [comment]
my problem has been solved by modifying my configure code in .emacs

**Comment by GitHubRulesOK** [comment]
@gx-xg 
Thanks for the feedback "solved by modifying my configure code in .emacs" 
It looks like there may have been a missmatch in the pairs of " (quote marks) in your call

I would suggest the bit with ` -reuse-instance"` is old and redundant since SumatraPDF depreciated that entry a long time ago, just ensure in SumatraPDF Settings> advanced options that the value for `ReuseInstance = true`
