### ISSUE TITLE
Version 3.5 is very slow compare with 3.4.6

### ISSUE THREAD

**Issue by cmkpl** [sumatrapdfreader/sumatrapdf#3791]
Hi, I am using SumatraPDF on a VM, I always open around 30 PDFs from network drive at the same time.  When starting up the software with previous opened PDFs or switching tabs, version 3.5 is very slow compare with 3.4.6.  

Any idea?

**Comment by kjk** [comment]
Could you provide a video recording of the difference?

3.5 has lazy loading so startup should be faster because the file is only loaded when you switch to the tab.

So startup should be faster (no need to open all the files) but switching to the tab will be slower (need to open the file when you switch to the tab vs. already being loaded).

I might switch back in 3.5.1 but would like to understand in what cases exactly it's slower and by how much.

**Comment by kjk** [comment]
I've reverted lazy-loading in 3.5.1. Let me know if it changes anything.

**Comment by th3v4n** [comment]
I don't know if this is related or not, but I'm randomly losing the titles from my tabs (3.5.1)

I love everything else though—so many improvements! Real bummed about this glitch.

Just lemme know you need anything else; maybe I can troubleshoot.

**Comment by kjk** [comment]
Unlikely to be related and already fixed, see https://github.com/sumatrapdfreader/sumatrapdf/issues/3799

Will be in 3.5.2 and even faster in next pre-release

**Comment by cmkpl** [comment]
Hi, 3.5.1 is now at the same speed of 3.4.6.  maybe LAN network access causes the issue.
