### ISSUE TITLE
Finish up gyp

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#38]
Things left to do:
* [x] add libmupdf.dll
* [x] PdfFilter.dll
* [ ] add installer
* [ ] sumatra with libmupdf.dll
* [ ] tighten warnings (bump to /w4 and add necessary adjustments to each component)
* [ ] figure out /analyze target
* [ ] add 64bit (additional configuration or do we need a separate .sln?)
* [ ] convert premake targets and remove premake files
* [ ] fix guids for generated projects
* [ ] -f ninja fails (on cygwin it complains about SYSTEMROOT, in dos throws
  KeyError: 'Release 64_x64')

**Comment by lrarbin** [comment]
Hello Krzysztof,
Sorry if I'm addressing this in the wrong way. I'm a bit new to this. But I've been looking at a tutorial on CodeProject:
http://www.codeproject.com/Articles/498317/Rendering-PDF-Documents-with-Mupdf-and-P-Invoke-in

This uses the libmupdf.dll . I've tried building the current source code, but I think the DLL is missing.
I'm guessing this is because of this issue.
Am I correct in thinking that the DLL is left out of the build at the moment?
Thanks
Laurence

**Comment by kjk** [comment]
We can't really solve your build issues. It has nothing to do with this issue and bug tracker is not the right place to ask such questions.

**Comment by lrarbin** [comment]
Thanks for the reply anyway :)

**Comment by vgturtle127** [comment]
Are these issues still prevalent in the newer builds? Or has most of this been resolved?

**Comment by kjk** [comment]
Gyp has been abandoned.
