### ISSUE TITLE
bug(dark-mode): tooltips/icons are not readable when using dark/black theme

### ISSUE THREAD

**Issue by AnonymousWP** [sumatrapdfreader/sumatrapdf#3802]
Black theme:

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/50231698/061a6975-16c0-4f2d-bb25-79ae2e40433a)

White theme (how it's supposed to be):

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/50231698/345ae28e-716c-461c-a4de-3dc769f4393a)

The icons colours should change in colour too once the theme is changed.

**Comment by regis586** [comment]
Hi, same thing with white mode..
![20231025-Bug-SumatraPdf-V3 5-64-bit](https://github.com/sumatrapdfreader/sumatrapdf/assets/67907497/d70545f0-901f-4c8f-ab65-7f2619367b3e)

**Comment by AnonymousWP** [comment]
> Hi, same thing with white mode.. ![20231025-Bug-SumatraPdf-V3 5-64-bit](https://user-images.githubusercontent.com/67907497/277950847-d70545f0-901f-4c8f-ab65-7f2619367b3e.png)

Not with dark theme? Also, update to 3.5.2 and you'll see that it's at least fixed for white theme: https://www.sumatrapdfreader.org/download-free-pdf-viewer

**Comment by regis586** [comment]
Bug with each theme..

**Comment by regis586** [comment]
> Bug with each theme..

I've just loaded V3-5.2..
it look's fine :-)

**Comment by dftf-stu** [comment]
Yes, same issue here with the new themes.

In "Light" mode, things look as they used to.

But in either of the new "Dark" or "Darker" modes, the menubar items (such as "File", "View" and "Go To") all become much-more spaced-out than usual, and some of the toolbar icons render corrupt, especially when viewing a PDF:

![SumatraPDFDarkThemeIssues](https://github.com/sumatrapdfreader/sumatrapdf/assets/83965343/d8f0000e-78f1-4999-a008-d28188b24b09)

(You'll also notice the menubar doesn't appear dark entirely: after the final item, "Help", it then reverts then to the light theme)

If it helps for any troubleshooting, I'm on Windows 10 Home x64 22H2 (OS Build 19045.3570)

**Comment by dftf-stu** [comment]
Yes, same issue here with the new themes.

In "Light" mode, things look correct (the UI appears the same as it did in the 3.4.6 version I used before updating).

But in either the new "Dark" or "Darker" modes, the menubar items (such as "File", "View" and "Go To") all become much-more spaced-out than usual, and some of the toolbar icons render corrupt, especially when viewing a PDF:

![SumatraPDFDarkThemeIssues](https://github.com/sumatrapdfreader/sumatrapdf/assets/83965343/c6e996f3-cc5a-4fc1-89a2-f0e14d70c9f1)

(You'll also notice the menubar doesn't appear dark entirely: after the final item, "Help", it then reverts then to the light theme)

If it helps for any troubleshooting, I'm on Windows 10 Home x64 22H2 (OS Build 19045.3570)

**Comment by actimem** [comment]
I am experiencing same issue, I'm on V3.6.15850 64-bit pre-release (menu background half painted, you can't make out icon shapes, ugly thick textbox borders).  

Not fun to look at for those of us dark theme aficionados.

**Comment by GitHubRulesOK** [comment]
the icons are just as readable with light or dark backgrount the issue is the contrasting colours dont work at nominal 96dpi screen scale

Here is a capture of one with a light background and a dark background and BOTH ARE IDENTICAL.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/5781e5ee-60dd-4c1b-bc28-5e01d44b9e90)

**Comment by adamwirth** [comment]
I have this issue with the new dark/darker themes. I'll attach a screenshot:

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/22478533/016a5087-aa1e-4c26-b109-8bc5258b9fd6)

I am on 3.5.2 64-bit, using Windows.

**Comment by GitHubRulesOK** [comment]
@adamwirth technically not an issue as I show its simply a human contrast  problem the icons are perfect as designed for dark on light but simply not inverted.

**Comment by actimem** [comment]
Just trying to establish the baseline whether you agree this is an issue that needs fixing, or it is simply a config error/user perception issue that would be up to the user to sort out.

I have been confused by your comment that this is "technically not an issue", when it is clearly an issue for many people.

Looking at @adamwirth and @dftf-stu dark theme screenshots, the icons look blurry and horrendous, at least in my monitor. The icons might have been perfectly designed for light theme, but we cannot claim they work in dark theme looking like that.

**Comment by dftf-stu** [comment]
@GitHubRulesOK , @actimem :

Just to clear-up any possible confusion here on what the issue is, perhaps another screenshot would help:

![SumatraPDFIconComparison](https://github.com/sumatrapdfreader/sumatrapdf/assets/83965343/00ac2386-97bd-455c-a9c4-28fa62e6298d)

That shows how the toolbars look in both the "Light" and "Darker" themes; the top toolbar in each theme is when no PDF is open, and the bottom toolbar is how it looks when at-least one PDF is open.

As you can see:
•  When no PDFs are open, only the "Open" button looks corrupt in the "Darker" theme
•  When a PDF is open, many of the buttons look corrupt (the most-noticeable ones I've marked with a red-arrow)
•  When a PDF is open, the text-box fields after "Page:" and "Find:" also have thicker-borders

Yes, all of the buttons are still _functional_ (you click them, they do something) but they clearly don't _look right_

HOWEVER...

If you take the screenshot of the "Light" theme toolbars, then simply select them in Microsoft Paint, right-click and do an "Invert colour" then look how-much better this then looks:

![SumatraPDFIconInvertColour](https://github.com/sumatrapdfreader/sumatrapdf/assets/83965343/132c5634-b918-4236-b4fc-802b3414f05f)

To me, the icons there all look correct.  Can SumatraPDF's dark-theme not just match that? 🤷🏻‍♂️🤔

**Comment by GitHubRulesOK** [comment]
@actimem 

> I have been confused by your comment that this is "technically not an issue", when it is clearly an issue for many people.

> Looking at @adamwirth and @dftf-stu dark theme screenshots, the icons look blurry and horrendous, at least in my monitor. The icons might have been perfectly designed for light theme, but we cannot claim they work in dark theme looking like that.

I agree this is in effect a "Users Interface" issue but technically not a bug hence I have kept this open as a separate thread about Icons and just linked to suggested means to resolve.

@dftf-stu  note the suggested means to resolve would generally require new resources
The icons as SVG are fixated as designed to be rendered into black and greytones on white, and thus could be reversed **by alternatives designed** for white on black.

**Comment by kjk** [comment]
@dftf-stu the issue with text fields for page/find should be fixed with https://github.com/sumatrapdfreader/sumatrapdf/commit/e7f3ebc7e861d9b63e826426eab6c3d2968f7997 and available in next pre-release (in about 24 hrs).

I'll try to fix the icons as well.

**Comment by kjk** [comment]
Icons fixed in latest [pre-release](https://www.sumatrapdfreader.org/prerelease) 16037 or later (should be available within 24 hrs).

**Comment by g-i-o-r-g-i-o** [comment]
broken in 3.5.2


![Image](https://github.com/user-attachments/assets/e6b68a9c-f897-434e-a82b-4e7bf3c1e400)

**Comment by GitHubRulesOK** [comment]
@g-i-o-r-g-i-o

As discussed above 3.5.2 was long ago when this thread was started 2023-10-25
There have been 1000+ changes since then including the one in the comment before yours e.g. Changed in **3.6.16037** or later 
Currently we are about 750 versions later at 3.6.16881 but [last published version will do as 3.6.16779]https://www.sumatrapdfreader.org/prerelease](https://www.sumatrapdfreader.org/prerelease) thus 740 times better than 3.5.2

**Comment by dftf-stu** [comment]
Hi @GitHubRulesOK 

Great to hear this issue may be fixed in an alpha / beta pre-release, but most of us only run the stable-versions.

As of now, this remains v3.5.2 as [found here](https://www.sumatrapdfreader.org/download-free-pdf-viewer), released 25 October 2023 (or at-least, that's when the file was Digitally Signed), so... do you have any-idea when the next stable-release will be?  (I'd have thought for such a noticeable, end-user facing UI issue, that a small v3.5.3 update just containing the fix for this would have dropped by-now.  Seems odd to promote "new dark themes have been added", but then leave them broken for so long... 🤔)

I've just been permanently using the light theme for now, to avoid the broken-looking icons and the over-spaced menus.

**Comment by GitHubRulesOK** [comment]
@dftf-stu 
The Pre-release has generally worked for me in all its 32bit variations including those not yet available (Beta pre-releases)

The one I linked is the last publicly signed pre-release version and thus without signing the more recent 100+ variants are unpublished.

When a new formal release of 3.6 will be, depends on many factors but traditionally was only known a week after publication whenever that was so the gap can be as seen from history from just 1 day to 3.5 years

**Comment by dftf-stu** [comment]
@GitHubRulesOK : so v3.5.2 of SumatraPDF (the current stable) was released on 25 October 2023, meaning we're now just-over 2 years and 1 month on from then.

I'm surprised if this is apparently fixed in the pre-release builds that by-now a minor v3.5.3 bump couldn't have been released solely to fix this one issue (or perhaps to simply withdraw the themes, and advise in the "version history" section of the official website that "Dark themes were removed, due to issues: they aim to return in the eventual v3.6 release" or similar).

Seems odd to keep offering the current stable, when it's known the themes have issues, not advise anywhere on the downloads page they are a known-issue, which then just invites people to log new tickets on here for the same issue (of which 5175, from around two-weeks ago appears to be the most-recent...) 🤔

**Comment by GitHubRulesOK** [comment]
@dftf-stu the latest "3.6 pre-release" is  at this time 
>Latest SumatraPDF pre-release build version 17065, built on 2025-07-27 

So well over 2 weeks but there are (including no free way to currently securely sign any 3.5.# replacement) several reasons why that pre-release should not be classed as a full "stable" release. Since then, there could be a flood of format related issues that should be resolved before any official publication.

Whilst for many users the Windows means of theming is a problem, as defined by MS software system fluctuations, there are possibly better reasons for a 3.5.3 than cosmetic ones, but it bears significant costs to republish.

**Comment by dftf-stu** [comment]
@GitHubRulesOK : don't fully understand your reply, sorry

I said the latest **stable** release (you know, the one users are recommended to download) is currently version 3.5.2, as is found [here](https://www.sumatrapdfreader.org/download-free-pdf-viewer).  That version was released on "2023-10-25", as per the [Version history](https://www.sumatrapdfreader.org/docs/Version-history) page (and per the Digital Signature of the EXE itself).

What I asked was... why could a small, interim update (i.e. a hypothetical version 3.5.3 , one digit up from 3.5.2 ) not have been issued in the meantime solely to address this one issue?  If it would cost money to do so, fair-enough (though if the main developer has a code-signing certificate, aren't they issued for a set amount of time, not on a per-version-published basis?  Beyond that, I'm not-sure what other costs would be involved?)

Just seems a bit odd to me to still offer version 3.5.2 where the issue with the dark-themes rendering poorly is known, and yet the official [Download](https://www.sumatrapdfreader.org/download-free-pdf-viewer) page doesn't even mention this as a known issue, leading to endless reports about it on here...

<img width="1366" height="712" alt="Image" src="https://github.com/user-attachments/assets/7d431519-1669-4c05-a424-3eb20ed77e55" />

**Comment by GitHubRulesOK** [comment]
Look at 3.5.2 Certification **expired ‎Friday, ‎August ‎23, ‎2024 11:59:59 PM** (More than 1 year ago and had been issued about 3.5 years prior without any revenue (Just Pirates charge $100+ per copy) the pre-release (Polish) Certificate expired 2nd September 2025

A full MS Defender compatible certificate is expensive 
> DigiCert: Offers multi-year subscription plans, with prices starting at £459/year for DigiCert EV Code Signing Certificates.
These prices may vary based on the specific features and options selected.

SumatraPDF is a very expensive "Hobby" for whoever maintains it. Hence, I support it with my time as payback for all that effort.

**Comment by dftf-stu** [comment]
@GitHubRulesOK : so... just do what many third-party developers do (who aren't part of a project that receive a regular-stream of income from donations) and just _don't_ bother digitally-signing the app?

7-Zip is one of the most-used open-source, freeware apps in the world, and has _never_ been digitally-signed to my knowledge -- I've just downloaded the most-recent 25.01 release (2025-08-03) and neither the .EXE or .MSI installer are digitally-signed, yet it still manages to hook-into File Explorer via the "7-zip.dll" file.  Likewise, VLC Media Player isn't signed either, and also manages to integrate with File Explorer, both adding context-menu items, and allowing thumbnail-generation for videos.

So maybe SumatraPDF could still do the PDF-indexing and thumbnail-generation features without signed DLLs? 🤔

I'd prefer to have an unsigned new stable-release that finally backports the themes fix from the pre-release channel, than have to wait until something like 2028 or 2029 when v3.6.0 might finally drop with the fix...

**Comment by LAZERAI** [comment]
OMG, it looks so much better with the pre-release version installed, thank you! I hope it makes it into the stable release.

<img width="655" height="68" alt="Image" src="https://github.com/user-attachments/assets/8dcac33b-82fe-42b8-a012-523305f7bff1" />
