### ISSUE TITLE
For the pdf content, cut the blank area.Thx.(FoxitPhantomPDF Enterprise support this)

### ISSUE THREAD

**Issue by wkl17** [sumatrapdfreader/sumatrapdf#381]
For the pdf content, cut the blank area.Thx.(FoxitPhantomPDF Enterprise support this)

**Comment by GitHubRulesOK** [comment]
More recent SumatraPDF has better support for Fit to Content however there are various ways to remove white or black space borders.

PDF and Image editors such as Phantom provide auto clipping functions and of course you can use them to cut the pages down. Save it clipped and SumatraPDF viewer can display it from edge to edge.

It is not so simple with image viewers It only needs 1 edge pixel to be darker (or lighter) than its neighbours. Then that becomes THE EDGE of the clipping area OK so let's ignore that one then the next 1 in say 1000 is significant and there could be millions to test,  so how long are you willing to wait for each page to be tested and then the widths / heights all become wobbly variables

Usually it's the top and bottom of each page that determines the boundaries and as shown working here it does not have much effect I would be better off simply using fit width.


![image](https://user-images.githubusercontent.com/12754913/73993257-933e5f00-4949-11ea-90b0-d2abd221b054.png)


Anyway since the feature is available and works per the current design I am closing as not an issue.
