### ISSUE TITLE
Inverse Search - Multiple files

### ISSUE THREAD

**Issue by eggsterino** [sumatrapdfreader/sumatrapdf#384]
Hi 

It will be extremely helpful to pair the inverse-search command to the opened PDF rather than to the SumatraPDF process.

I'm working on different tex files simultaneously (and open multiple PDFs in Sumatra) and this feature is very important because every time I double click in Sumatra I get back to the first tex file opened rather than to the relevant one.

Thanks!

**Comment by GitHubRulesOK** [comment]
@kjk SumatraPDF s handed the "inverse" file in the .synctex file It can only work with the names given. If the PDF is a sub file and the attendant .synctex points at the subfile.tex then sumatra WILL give the correct inverse call. Thus working as designed and intended by some editor apps, I suggest this one can be closed since many changes would be required in other editor apps rather than down to SumatraPDF.
