### ISSUE TITLE
Dark Mode Issue

### ISSUE THREAD

**Issue by TemkinTegegn** [sumatrapdfreader/sumatrapdf#3877]
![282680884-c6325d88-387c-4f9b-b3d6-ddcec58563f0](https://github.com/sumatrapdfreader/sumatrapdf/assets/77839113/00cbc6cb-2338-4392-adca-addb33c1ccf7)
As you can see in this screenshot. I selected dark mode but the reading background is still white and when I switch it to light mode, the reading background background will be dark. So my question is how can I make the reading background dark in dark mode and why it can make it dark automatically when I switch it to dark mode by itself?

**Comment by GitHubRulesOK** [comment]
There has been some recent changes in experimental pre-release to allow custom colour choices so depends on the revision
However the  inversion setting should be easier to flip just press `i` key.

**Comment by kjk** [comment]
You can press `i` which inverts colors and will make document / text match the color.

We don't do it by default because that's not what most people want.

**Comment by TemkinTegegn** [comment]
> There has been some recent changes in experimental pre-release to allow custom colour choices so depends on the revision However the canvas inversion setting should be just as easy to flip, so as before, just press `i` key.
> 
> Ok there does seem to be a problem with light scheme
> 
> @kjk in light scheme the inversion is not functioning ? unless colours are reversed !
> 
> ```
> FixedPageUI [
> 	TextColor = #ffffff
> 	BackgroundColor = #000000
> ```

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/77839113/1f2e74d8-5e9c-4a69-8c53-3c28badc0a3e)
I set invercolors to true and it get what I wanted but you cannot change the color no matter what. It's like take-or-leave-it kind of option.

**Comment by TemkinTegegn** [comment]
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/77839113/3295c576-af24-4e4f-bf36-5118aa921a9d)
As you can see, the color change I made in advanced options doesn't have any effect at all! BTW, check the icons also
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/77839113/099538a4-a5cd-4a0c-b0c6-6254583dc4db)

**Comment by ArmanHayots** [comment]
Is there any chance of setting colors per theme? 
I'm using blueprint-style for reading schemas (that helps so much, especially in terms of eye fatigue), but for book reading the green on black is much better. And in other hand watching color printed things like catalogues needs colors to be unchanged.
Anytime I need to swap settings file because simple inversion there is not enough.

**Comment by GitHubRulesOK** [comment]
@ArmanHayots there always has been colour setting and that's why themes are such a problem there is a fixed range of colours between 2 endpoints green and any other
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/68659fd4-2555-4dbe-8a89-754d7c9e4419)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/2fe1f712-eb33-4cef-b8f7-8ecf7cf1e956)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/3842ed41-a20a-409e-a224-bc449d218078)

**Comment by ArmanHayots** [comment]
@GitHubRulesOK in my case ability to set text and background colors per theme is more than enough.

**Comment by GitHubRulesOK** [comment]
As long as I can remember you could have 2 profiles and send a document and page number from one to the other,
this does require some customisation by users setting a command and their choice of a name/hotkey, since every user would want their own one of thousands of dark side modes.

Now SumatraPDF pre-release has a few problems with the way it handles commands ! 
so the current best way is write a cmd file and call it via externalviewers
```
ExternalViewers [
	[
		CommandLine = C:\Users\lez\AppData\Local\SumatraPDF\plus\SumatraPDF2.cmd %p %1
		Name = Suma&traPDF2
	]
]
```
shortcut is thus ALT +F + T
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/c374feb2-ea28-42ab-bf9e-da0e41c05732)

in that folder alongside the cmd file is another copy of portable sumatraPDF.exe which uses its own settings with different preferences so can be no menu no tabs or simply a different colour setting.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/62863810-ad5a-4b88-82ee-d24b4cce5eb2)

SumatraPDF2.cmd
```
"C:\Users\lez\AppData\Local\SumatraPDF\plus\SumatraPDF.exe" -page %1 %2
```

**Comment by bradrn** [comment]
> JavaScript PDF.js readers can do little more than also set foreground and background end points to their colour rendering.

On this note, it may be worth looking into Emacs [pdf-tools](https://github.com/vedang/pdf-tools), which uses the OKLab colour space to do true colour remapping (e.g. https://github.com/vedang/pdf-tools/pull/197). In my experience, the results are very good.

**Comment by ArmanHayots** [comment]
Things get even worse. Windows 11, dark mode on.

![w](https://github.com/sumatrapdfreader/sumatrapdf/assets/25264017/cadbee16-b226-41ae-a561-b3caa4f4d48c)

**Comment by kjk** [comment]
I believe this issue is resolved by pressing `i` to invert colors to match the theme.

If not, please open a new issue is describe what is happening and what you expect to happen.

People also raised other issues but the rule is: one clear problem per issue. Don't add more stuff to existing issues, even if adjacent or similar. Unless it is the exactly same problem, open a new issue.

**Comment by mooglestiltzkin** [comment]
https://oak.dev/2020/05/06/dark-mode-for-sumatra-pdf/


did this

```
TextColor = #eeeeee
BackgroundColor = #111111
GradientColors = #000000
```

and press I


thats the best i could do.

yes it is dark, but the inverted colors is not #000000 total black which is what i and most others would prefer especially if they use oled monitors. How do i achieve that for the "I" mode?

**Comment by GitHubRulesOK** [comment]
@mooglestiltzkin  dont mess with colour settings leave them alone just use shifted eye (Caps) `I` with 3.6 dark theme

<img width="858" height="410" alt="Image" src="https://github.com/user-attachments/assets/6cba3e21-f7b0-404d-b3ca-67b0201d26da" />

**Comment by mooglestiltzkin** [comment]
i reinstalled and did as u said, and choose dark theme,. there was no 3.6 dark.

mine doesnt look like yours :( looks exactly like TemkinTegegn's pic.

its looks grayish. not #00000 hex black

i downloaded sumatrapdf from unigetui

sumatrapdf.sumatrapdf 3.5.2


*update

oo i see. 3.6 is on the main website, not the github nor unigetui. ill check it out ty

**Comment by mooglestiltzkin** [comment]
thats very weird.

pressing I doesn't invert. I did a clean install using the 3.6


so i had to go advance settings and look for invert, and change to true.

have to figure out why "i" to toggle invert is not working


*update


oo it changed


> ·	i toggle showing page info (ver 3.6+ )
> ·	i invert colors in the document (ver 3.5.2 or earlier)
> ·	Shift + i invert colors in the document (ver 3.6+)


so yes like you said, download install 3.6 (beta preview. downloadable from mainwebsite)

change settings theme to dark.

Then SHIFT + i to toggle color invert. This did the trick.


The novel pdf i read has certain parts where there are color pics in transition where this doesnt look nice. But i wasnt expecting perfection to begin with. those parts i can simply toggle invert off, read that part, then toggle back on. u probably dont need to do anything for that, i dont see a possible solution for that part, but thats ok. 

The important part is the normal reading bits, these look fine with tthe dark theme 3.6 + color invert. Perfect for oled monitor
