### ISSUE TITLE
New feature: Close all other tabs / close right tabs

### ISSUE THREAD

**Issue by TomXJ900** [sumatrapdfreader/sumatrapdf#388]
Just an enhancement proposal. 
I love the feature of some browsers where I work with multiple tabs an can close all other tabs (or all right tabs) by right click on a tab. I'm really missing such a feature in Sumatra-PDF. 

Currently I have set "RestoreSession = false" in SumatraPDF-settings.txt to avoid a multiple "Ctrl-W" because I often use many tabs simultaneously. 

thanks and regards, 
Thomas

**Comment by petebachant** [comment]
Definitely a good idea!

**Comment by edwinyzh** [comment]
Yes, the most wanted feature, preferably via right click context menu.

**Comment by SumatraPeter** [comment]
Would love to see all of the following [tab-related suggestions](http://forums.fofou.org/sumatrapdf/topic?id=3184717) implemented.

**Comment by DamienHelp** [comment]
Thank you TomXJ900 for
RestoreSession = false
This behavior was driving me nuts, having to hit Ctrl W until all open documents closed then closing Sumantra PDF.
I was ready to uninstall the software.
Surely it could be an option in the file menu to Close All.

**Comment by HoldOffHunger** [comment]
Hey, ya'll,

Just set the following to a blank file and set ReadOnly = 1:

C:\Users\YOU\AppData\Local\SumatraPDF\SumatraPDF-settings.txt

This will permanently cause Sumatra to forget all saved tabs on close.  NOT PERFECT, but it's a work around to closing 1,000 tabs for me.

**Comment by Base-IQ-ly-Loud** [comment]
Nah, don't worry, brov.
We will co-live.

-------- Original Message --------
On 20 Nov 2021, 03:48, HoldOffHunger < ***@***.***> wrote:
Hey, ya'll,
Just set the following to a blank file and set ReadOnly = 1:
C:\Users\YOU\AppData\Local\SumatraPDF\SumatraPDF-settings.txt
This will permanently cause Sumatra to forget all saved tabs on close. NOT PERFECT, but it's a work around to closing 1,000 tabs for me.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. ￼
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[https://github.com](<a href=)/sumatrapdfreader/sumatrapdf/issues/388#issuecomment-974572014">https://github.com/sumatrapdfreader/sumatrapdf/issues/388#issuecomment-974572014", "url": "[https://github.com](<a href=)/sumatrapdfreader/sumatrapdf/issues/388#issuecomment-974572014">https://github.com/sumatrapdfreader/sumatrapdf/issues/388#issuecomment-974572014", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by kjk** [comment]
This is now possible with context menu on tab and also via [Command Palette](https://www.sumatrapdfreader.org/docs/Command-Palette) (`Ctrl - K`)

**Comment by gmnreader** [comment]
this is a must-to-have feature.

**Comment by GitHubRulesOK** [comment]
@gmnreader 
did you not use the pull off tabs or the close to right click ?
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/4924fa6f-ee91-4dee-982d-7e969035be96)
