### ISSUE TITLE
Another problem with command line arguments

### ISSUE THREAD

**Issue by umbertoB67** [sumatrapdfreader/sumatrapdf#3903]
I've this commands in two batch files:

- Batch1.bat:
start C:\Temp\PDF\SumatraPDF.exe "C:\Temp\PDF\FileName.pdf" -page 10 -view "single page" -new-window

- Batch2.bat
start C:\Temp\PDF\SumatraPDF.exe "C:\Temp\PDF\FileName.pdf" -page 20 -view "single page" -new-window

When I execute the first batch, SumatraPDF opens a new window with the pdf at page 10
When I execute the second batch, SumatraPDF opens a new window with the pdf at page 20, but the first window brings the PDF at page 20.

I'm using SumatraPDF pre-release build version 15900, built on 2023-11-23.

**Comment by GitHubRulesOK** [comment]
That again is fairly normal behaviour for a single session the one setting file is used by both window panes.
to achieve that behaviour in one session try set these alternate settings
```
ReuseInstance = false
ReloadModifiedDocuments = false
```

To have 2 settings files there are different approaches, so you could start a second session or instance with a separate set of controls even with one exe.

**Comment by kjk** [comment]
Doesn't happen always. Easy to reproduce when starting with empty settings.

What I think is happening:
* we delay saving the state of the file (including current page) until some events
* so the state for first file is not saved
* when we load second file, we save settings which we then re-load, which updates the state of this file which I guess is causing of reload of the file and changing the page no to what we think is current

Need to look more deeply how exactly this happens.

**Comment by kjk** [comment]
The issue is the when reusing instance we open the second file via DDE, sending 2 commands:

```
[Open("C:\Users\kjk\Downloads\Closing pack.pdf", 2, 1, 0)]
[GotoPage("C:\Users\kjk\Downloads\Closing pack.pdf", 20)]
```

The problem is that we target by file path so what's really happening is that the first file is the target of `GotoPage 20` command and the second file is actually opened on either first page or one from settings.

This is not a problem if there's only one file with a given path opened and I just didn't anticipate this combination.

No obvious way to fix it, maybe a hack when remembering most recently opened `DocController` and it's path, clearing it at the beginning of dde handling loop and then if set, give it precedence in HandlePageCmd() over `FindMainWindowByFile`.

Or maybe in `FindMainWindowByFile` search backwards which should return most recently opened file. Less reliable.
