### ISSUE TITLE
Sumatra Crashing

### ISSUE THREAD

**Issue by SquidHM3** [sumatrapdfreader/sumatrapdf#3908]
https://gist.github.com/SquidHM3/99758cd7640158825a3cb023e1288e8d
[i486_Data_Sheet_Apr89.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/13462973/i486_Data_Sheet_Apr89.pdf)

**Comment by SquidHM3** [comment]
I was just trying to open the file when I got the "Sumatra PDF has crashed" message. My drive is encrypted with Bitlocker - I wonder if that might be an issue? The drive is auto-unencrypted when I start up Windows (I use Bitlocker on Windows 10 Pro)

**Comment by kjk** [comment]
I tried to repro crash in 3.5.2 with the attached file and couldn't.

According to the log you had a few files opened but none of them was the file with the name `i486_Data_Sheet_Apr89.pdf`. Per logs you were opening a file `iFixIt Kit.pdf`.

Also, the symbols are missing so the callstack doesn't tell me anything useful.

What you can do to help debug this:
* use `Ctrl + k` `Debug: Download Symbols` command to pre-download symbols so that next time the crash happens crash report has more useful information
* figure out a minimal set of steps that cause a crash and  submit the crash report with symbols and provide step-by-step instructions to reproduce the crash

For example "I was just trying to open" is not specific enough. Did you use ` File / Open` menu? Double-clicked on a file? Drag & dropped? etc.

**Comment by SquidHM3** [comment]
No worries! It actually seems to have resolved itself, because I tried
to open the same file again and had no problems opening that file, so
you can safely delete this issue, or consider it closed.
Thank you!

	-----------------------------------------From: "Krzysztof Kowalczyk" 
To: "sumatrapdfreader/sumatrapdf"
Cc: "SquidHM3", "Author"
Sent: Saturday November 25 2023 8:46:34PM
Subject: Re: [sumatrapdfreader/sumatrapdf] Sumatra Crashing (Issue
#3908)

 I tried to repro crash in 3.5.2 with the attached file and couldn't. 

 According to the log you had a few files opened but none of them was
 the file with the name i486_Data_Sheet_Apr89.pdf. Per logs you were
 opening a file iFixIt Kit.pdf. 

 Also, the symbols are missing so the callstack doesn't tell me
 anything useful. 

 What you can do to help debug this: 

 * use Ctrl + k Debug: Download Symbols command to pre-download
 symbols so that next time the crash happens crash report has more
 useful information
 * figure out a minimal set of steps that cause a crash and submit
 the crash report with symbols and provide step-by-step instructions
to
 reproduce the crash

 For example "I was just trying to open" is not specific enough. Did
 you use File / Open menu? Double-clicked on a file? Drag & dropped?
 etc. 

 —
 Reply to this email directly, view it on GitHub [1], or unsubscribe
 [2].
 You are receiving this because you authored the thread.Message ID: 

 Links:
 ------
 [1]
 https://github.com/sumatrapdfreader/sumatrapdf/issues/3908#issuecomment-1826463637
 [2]
