### ISSUE TITLE
Window does not maximize on the next run

### ISSUE THREAD

**Issue by pulbitz** [sumatrapdfreader/sumatrapdf#3945]
In Sumatrapdf 3.6.15920(2023-12-09), when the 'Remember open files' option is turned off, the window does not maximize on the next run.

**Comment by GitHubRulesOK** [comment]
It does start to the MAX but it can only maximise if it was PREVIOUSLY saved at max or told to start as such 
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/55bd9fb9-0038-4d5f-9635-050a8a0ca3f0)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/28bc2098-b8da-423a-8f9f-1ef3f8734590)

**Comment by GitHubRulesOK** [comment]
@kjk 

These does seem to be a problem with fullscreen command on first call it does not maximise. 

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/3560159c-15bc-4207-8b22-7c13c0bc21e5)

On second call it changes to presentation ALSO `F` key switches to presentation NOT fullscreen
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/0256806c-cf3b-4237-b1f8-544ad13adeb9)

**Comment by paulmorel21** [comment]
I'm seeing that this issue is closed but I must say that I'm having the same problem. I understand that you can use the shortcut to open sumatra maximized, but I don't use shortcuts, I have sumatra as my default pdf viewer and I directly open the pdf file and every time I open a pdf file it isn't maximized, it's in a window and that's very annoying. The only way I could change this behaviour was to change the windowstate setting to 1 (as opposed to 2) and make the settings file read-only. I didn't have this problem with the stable version and that's why I stopped using the pre-release version.

**Comment by GitHubRulesOK** [comment]
@paulmorel21 
SumatraPDF current pre-release will re-open full screen IF closed in full screen mode using Exit (alt+F4) 
if `EscToExit = true` is set that can also be (too) easily used to exit in that state

IF not in Full screen it is easy to press `F`
