### ISSUE TITLE
Sync Scroll or cursor sync on line for file comparison

### ISSUE THREAD

**Issue by mxav1111** [sumatrapdfreader/sumatrapdf#3979]
Can we have sync up scrolling when two files can be compared in two windows are open side by side? One window is the output generated (text file) from ocr and second is the  original pdf window.
Alternatively (better) , can we have cursor or a marker in pdf keeps moving as we navigate inside text file on one side for changes when both windows are open side by side.

This could be of huge convenience; as once the text file is generated from ocr , we need to correct the output where scan couldn't identify the correct characters.

Thanks for your help.

**Comment by GitHubRulesOK** [comment]
there are very few viewers that can provide such sycronisation (it is not easy to trace 2 dissimilar formats in any application unless pages are identical in scale and sumatraPDF does not even have that ability unlike a dedicated twin pane viewer.

**Comment by mxav1111** [comment]
Thank you. Whichever way it can be easier to achieve.   Line break and page break can probably help to maintain page position and line position for sync scroll.

**Comment by GitHubRulesOK** [comment]
Presuming we are discussing PDF it has no native line or page breaks. Each page is composed of multiple objects assigned to a number from page zer0 and onwards and those objects are binary numbers often with internal line breaks at variable points along a line path of letters so OCR is often one line per letter thus will not be matchable with lines that have variable multiple line breaks such as justified text since breaks in a line are often simply bigger gaps.

 PDF works on page co-ordinates for converting numbers into letter positions.

**Comment by mxav1111** [comment]
Thanks so much for detailed explanation.  Actually,  post scan text files do create new line characters but for scanned pdf that would be difficult. 
However,  for page breaks it seems easy because scanned pdfs usually are all set of graphic images packed in single pdf in certain order.  So each page of graphic can be used for  page number calculation.  Even page level sync  scroll sync in first version will be very useful.  Thanks for consideration and your help.

**Comment by kjk** [comment]
Not likely too happen: complicated and rarely used functionality.
