### ISSUE TITLE
text selection omits letters

### ISSUE THREAD

**Issue by dk** [sumatrapdfreader/sumatrapdf#4004]
Version: 3.5.2

Hello all,

This is most probably not a bug per se, but I have this weird problem that I cannot pinpoint.

The problem is that I test my pdf-generating code, and when trying to select text in the files I produce, with the mouse, Sumatra selects not every letter in the text. This is fairly consistent, if the text is large then this happens also on almost all words in a paragraph. I'd be extremely curious if this is my own bug (but I can't for the life of me figure out why), or if it is Sumatra. I'd be also open for recommendation if the way I'm generating text is not the best way to do so, for one or another reason.

Anyway, I'm attaching the example pdf, where the text section is rather straightforward:

```
<00> Tj
10.15 0 Td <01> Tj
7.81 0 Td <02> Tj
3.12 0 Td <02> Tj
3.12 0 Td <03> Tj
7.81 0 Td <04> Tj
3.91 0 Td <05> Tj
10.14 0 Td <03> Tj
7.82 0 Td <06> Tj
4.68 0 Td <02> Tj
3.12 0 Td <07> Tj
```
and this is how the selection works:

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/50233/80959cde-5ec4-4297-9b67-7690791951ce)

[out.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/13840013/out.pdf)

and this how it looks on a larger text:

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/50233/ba24a26d-7184-413d-aa08-949fa2d316ad)

Any advice (or a confirmation that this is Sumatra's bug) would be much appreciated

Regards,
Dmitry

**Comment by GitHubRulesOK** [comment]
Technically you have 11 lines of text, these can be concatenated into one line
[issue 4004 out-overwrite.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/13842270/issue.4004.out-overwrite.pdf)

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/2c50ec10-dcdc-4b23-aee1-db829f222fa9)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/6a3c6217-9968-4553-87ab-eea15fcc5307)

**Comment by dk** [comment]
You have a point, but the pdf file you attached has the same problem, the last letter "d" is not selected either

**Comment by GitHubRulesOK** [comment]
The size of a selection is a guess based on a nominal spacing as there is no clue other that what the writer provides, I accepted the given values which will be computed by MuPDF (and its font reading dependencies)
The permutations for such a placement amounts to thousands of possibilities, since the letters can be placed in any order and still be counted as one word that contains a space character or more.
If I switch the font to MS Windows Arial it works
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/1a80d9cc-39d4-4515-a04e-2b4cb44078dc)

However playing around with those values in the original, it does look like total width calculated is less than visible placements. so perhaps there is some oddity in the MuPDF assessment of PS Arial character widths. It would need to be compared with MuPDF reader to see which one is reducing (not increasing) the selection .

**Comment by dk** [comment]
Ah, I wasn't aware that Sumatra is based on MuPDF. Just tried it, and it shows same issue. I shall try to talk to MuPDF dev then -- thank you!
