### ISSUE TITLE
cannot rename current file while open another file from 'Save As...' dialog by pressing F2

### ISSUE THREAD

**Issue by enihcam** [sumatrapdfreader/sumatrapdf#401]
repro steps:
Given two PDFs, A.pdf and B.pdf
1. open A.pdf, and press F2
2. in the pop-up dialog, open B.pdf
3. in the dialog, give A.pdf a new name new_A.pdf
4. Try save

**Comment by GitHubRulesOK** [comment]
@kjk given that you can never anticipate how others are doing the unexpected this  issue raises some questions. 
It is difficult to achive the test condition using portible, I could have worked round that and perhaps got different results, so decided to install 3.1.2 for testing and had no problem with the rename as such,
HOWEVER unexpectedly (as requested elsewere as a desire) the newly renamed file instantly opened with the new name 
So the behaviour is in effect correct since SumatraPDF recognizes the changed name and renders the file anew however the undesired result is the second file is no longer open and the first file is as per normal still open.
Any change to alter this unusual behaviour, needs to take into account any affect on latex users where auto refresh is essential.

**Comment by kjk** [comment]
This is just how Windows works: you can't over-write a file that is opened by some program. The fact that the program is Sumatra makes no difference.
