### ISSUE TITLE
SumatraPDF-settings.txt is not saved

### ISSUE THREAD

**Issue by AlexL2024** [sumatrapdfreader/sumatrapdf#4020]
**SumatraPDF version**
- Version [e.g. 3.5.2, release]

**Describe the bug**
The settings are not saved when I change them in the Options window. The settings for each documents are not remembered despite the checked option

**Additional context**
in previous version 3.4.6 all options worked as intended. After upgrade despite the checked options "Remember these settings for each document" and "Remember opened files" they didn't work. To open previous files I had to manually copy SumatraPDF-settings.txt from 
..\AppData\Local\SumatraPDF\SumatraPDF-settings.txt to "d:\Program Files\SumatraPDF\.." 
*
![Sumatra options](https://github.com/sumatrapdfreader/sumatrapdf/assets/156461054/2427520a-efd8-4904-9bea-8d201b4c5623)

**Comment by GitHubRulesOK** [comment]
"d:\Program Files\SumatraPDF.." may only be a PORTABLE version thus the settings in that case would potentially be fresh in that folder unless you have copied from another portable copy.
 the all users installation folder C:\proga... is not allowed to hold data  hence an installed version would start by building settings in current users localappdata

**Comment by AlexL2024** [comment]
The problem is that SumatraPDF-settings.txt resides in both folders "..\AppData\Local\SumatraPDF\" and "d:\Program Files\SumatraPDF\", but the program doesn't save any data to any of these configuration files
And "yes", the data in "..\AppData\Local\SumatraPDF\SumatraPDF-settings.txt" is NOT used at all (that was the reason to copy SumatraPDF-settings.txt to "d:\Program Files\SumatraPDF" folder
I've never encountered such problems earlier. I just upgraded from 3.4.6 to 3.5.2 and on opening SumatraPDF after that I found that no previously opened tab was opened and no change in options is remembered either

**Comment by GitHubRulesOK** [comment]
ALL portable (non installed) versions use their .exe folder for settings. 

All installed versions single or multi user use the users local data folder (to not conflict with other users)

thus there should be only 2 possible locations per user.

What can happen is much older versions used the user "Roaming" folder  but MS now suggest user %localappdata%

**Comment by AlexL2024** [comment]
No records in the Roaming folder found
What I found out is that when I simply copied the whole folder "d:\Program Files\SumatraPDF" to "**C**:\Program Files\SumatraPDF" (without SumatraPDF-settings.txt in it) everything started to work properly - the changes are written in "..\AppData\Local\SumatraPDF\SumatraPDF-settings.txt". 
So the problem is probably incorrect functioning of SumatraPDF.exe if it's installed in a directory other that default "C:\Program Files\SumatraPDF"

**Comment by markjeeninga** [comment]
I had the same issue with version 3.5.2, and even with version 3.4.6. I noticed the program did not generate a settings-file in the folder. The issue was solved for me by executing the program with admin rights. In the end I updated the rights in the installation folder so that the user profile full (writing) access for the folder. This solved it for me. Hope it works for you too.

**Comment by AlexL2024** [comment]
Hi, Mark
I tried executing the program version 3.5.2 with admin rights and it did began to save settings, but not in the \AppData\Local\SumatraPDF\SumatraPDF-settings.txt and in the "d:\Program Files\SumatraPDF\SumatraPDF-settings.txt" (sort of like a PORTABLE version). Besides there appeared "sumatrapdfcache" folder ...

**Comment by GitHubRulesOK** [comment]
It sounds like you are using outside of the all users protected area 
If it was an installed copy it should outside of the C:\program folders attempt to re-install and if you say all users into c:\program files since thats the detected all users folder 
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/6343feb6-0d60-41af-b480-39586a77a0a5)

**Comment by AlexL2024** [comment]
I installed (actually I just upgraded the previous version) using SumatraPDF-3.5.2-64-install.exe file (not portable) in the folder "d:\Program Files\SumatraPDF\" (so before the problems described in my first post I didn't have "C:\Program Files\SumatraPDF\" at all). And with versions up to 3.4.6 everything worked fine with that configuration. 
Now I have 2 working options:
1. By manually copying all files to "C:\Program Files\SumatraPDF\" and starting the program from that folder I got the situation in which the program works with c:\Users\User\AppData\Local\SumatraPDF\SumatraPDF-settings.txt 
2. If I start "d:\Program Files\SumatraPDF\SumatraPDF.exe" with admin rights then he program works with "d:\Program Files\SumatraPDF\SumatraPDF-settings.txt" 

So something has changed in 3.5.2 :-)

**Comment by kjk** [comment]
Based on description this must be a permission issue most likely settings file was created with admin permissions or in a directory where only admin apps can write to.

That's why it works in admin but not otherwise.

This could be related to imperfect upgrade code but not knowing what exactly happened I don't see a way to figure out how it got in that state.

Check permissions or just delete / un-install all versions and re-install from scratch.
