### ISSUE TITLE
When you scale the page, the page view always stays in the center

### ISSUE THREAD

**Issue by lamescholar** [sumatrapdfreader/sumatrapdf#4024]
**Is your feature request related to a problem? Please describe.**
The problem is related to PDFs with big pages. In such PDFs, when you zoom in on regular size page, zoom comes in direction of the pointer. After that, the page is usually not in the center of the window. You need to use horizontal scrollbar to adjust its position.

**Describe the solution you'd like**
You could add an option in the settings. When you scale the page, the page view always stays in the center. Page view is not moving in direction of the pointer. So you don't need to adjust horizontal position of the page after scaling. You can find such mechanics in WinDjView.

**Describe alternatives you've considered**
None.

**Additional context**
Here is a book with big cover (it can be a book with big maps).

<img width="960" alt="Снимок экрана 2024-01-15 125443" src="https://github.com/sumatrapdfreader/sumatrapdf/assets/80561975/c1c4f694-d0b8-4d48-9f15-ac6ddaede0ab">

You zoom in on regular size page.

<img width="960" alt="Снимок экрана 2024-01-15 125945" src="https://github.com/sumatrapdfreader/sumatrapdf/assets/80561975/b3b338fa-3ab8-4aea-85cd-25bf6087e715">

You need to adjust its horizontal position by hand.

<img width="960" alt="Снимок экрана 2024-01-15 130102" src="https://github.com/sumatrapdfreader/sumatrapdf/assets/80561975/942f868b-2a00-4aa0-9c44-7ac6471b7b50">

If you close the document and open it again, you get this:

<img width="960" alt="Снимок экрана 2024-01-15 130204" src="https://github.com/sumatrapdfreader/sumatrapdf/assets/80561975/0698c007-d856-4d60-b6f2-6f8e8d326f4a">

So, you need to use horizontal scrollbar again. You need to bother finding the center. It is better to have an option so that the scrollbar slider is fixed in the center by default, unless you move it to look around if you're looking at double page or something.

**Comment by meteorquake** [comment]
Fine by me as an option so both are available - most of my zooming in any program uses the ability to zoom at the cursor.

**Comment by l0oo** [comment]
What about:
[Feature request] When you scale the page, the page view always stays in **the same position** on every pages?
This is great feature when you need to zoom part of bigger page etc

**Comment by meteorquake** [comment]
You'd need to elaborate the feature request.
When I zoom, the zoom is maintained for subsequent pages as I scroll through them.
However when I click the 'Next Page' button, it ends up at the top of the page.
What might be useful I think is if you Shift-NexttPage it could go to the next page keeping the same position as it had been on the prior page rather than going to the top.

**Comment by l0oo** [comment]
Thanks for your comment [meteorquake](https://github.com/meteorquake)
Well... I prefere to use keyboard instead of clicks... IMHO Shift-NexttPage could open at the top of the next page. ;) Click NexttPage could retain zoom and position, as it is more desired anyway and I expect wider used... :)
As for keyboard: people use usually (I guess) 'fit page'/'full page' - so simply PageDown could inherit zoom level (and zoom position!) in fact, for  most ppl it can be not important, when use with typical view settings. If someone would like to go to the top of the page could use Shift-PgDwn. 
(BTW: Dunno ppl behaviour but to me it is really surprise noone adressed it yet).

**Comment by meteorquake** [comment]
Generally I prefer keyboard but I hop around computers and often it's easier to correctly click the page button than remember how to hit the page key on the current keyboard layout :)
Currently my PageDown key jumps a screen page rather than a media page which has its own sense for going systematically through a document, which works well for me.
But Shift, Ctrl and Alt modifiers have no action with PageDown so I think there's a lot of scope for different modifiers meaning different things.
There's also scope for more modifiers to modify the action when you click the scrollbar space regarding paging up/down.
I'm also a fan of plenty of options the user can change so that their preferred outcome is easiest.
d

**Comment by kjk** [comment]
Should be fixed in next pre-release. Please read https://github.com/sumatrapdfreader/sumatrapdf/discussions/4011#discussioncomment-9397354 for new expected behavior
