### ISSUE TITLE
Invert Colors not working on pre-release

### ISSUE THREAD

**Issue by Chivos** [sumatrapdfreader/sumatrapdf#4030]
**SumatraPDF version**
- Version pre-rel 3.6.15941 (and before)

**Describe the bug**
The Invert Colors function is not working anymore

**To Reproduce**
Try to invert colors using keybord shortcut or command palette

**Comment by pulbitz** [comment]
I've been having this issue since the version that fixed it.

I'm using the Darker theme UI, with black set to full black and white set to low contrast.

Theme = Darker
FixedPageUI [
	TextColor = #000000
	BackgroundColor = #bbbbbb

When using the Invert Colors, if the Theme is Dark/Darker and not Light, the TextColor/BackgroundColor provided by the Theme will be used, not the Color value I set.
If TextColor and BackgroundColor are not the default and are custom set by the user, I would like them to respect the Color value regardless of the Theme.

**Comment by kjk** [comment]
Please open a new issue for this because the bug reported here has been fixed. This is more specific issue.
