### ISSUE TITLE
When inserting a free-text annotation, the Chinese character "这" is not displayed

### ISSUE THREAD

**Issue by istery-cracked** [sumatrapdfreader/sumatrapdf#4046]
**SumatraPDF version**
- Version [e.g. 3.5.2, pre-release]

**Describe the bug**

When inserting a free-text annotation, the Chinese character "这" is not displayed.

**To Reproduce**

Reproducible in all .pdf files

**Expected behavior**

**Comment by GitHubRulesOK** [comment]
that is common when the annotation box has no  universal font added to the file and when files do have fonts they often do not include a full set of characters (sub setting imbedded fonts) what is needed is an extra means to add a font for those other languages but then the file would bloat.

The Problem is not "display" we can see it in the annotation and description, the problem is the Helvetia Font does not exist and also is not in the file and even if it was there is no such caracter in the 0-256 ANSI range (non Unicode).

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/d34a02ac-ba3b-4924-a7c7-48f3cbc2f1a2)

**Comment by GitHubRulesOK** [comment]
this is a valid issue but a duplicate raised before thus does need fixing as other readers can show such characters

**Comment by istery-cracked** [comment]
Thank you for your reply

**Comment by GitHubRulesOK** [comment]
duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/2255
