### ISSUE TITLE
Two install entries, one of which does not do anything

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [sumatrapdfreader/sumatrapdf#4049]
**SumatraPDF version**
3.6.16927 pre-release. [I wish that string were copy-pasteable from within the program.]

**Describe the bug**
I have two entries within add/remove programs, albeit only one within the 'modern' add/remove; and performing the uninstall action (via context menu) upon one of the entries (the one marked, in the screenshot below, 30/12) does nothing.

**To Reproduce**
I am unsure how I ended up in this state. Probably by installing one version atop another (but you do not discourage that, I believe).

**Expected behavior**
One entry.

**Screenshots**

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/47056543/340fc277-0f1a-480c-b5ca-f719aa13a67e)

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/47056543/631d3f0f-6b47-4424-9fa4-5d63cdbf6e1f)

**Additional context**
I use Windows 10 Pro - 22H2 (2009: 19045).

**Comment by kjk** [comment]
Sadly without repro steps there's nothing I can investigate.

**Comment by LinuxOnTheDesktop** [comment]
@kjk : thank you for your work.

> Sadly without repro steps there's nothing I can investigate.

Strictly speaking, that is false. For, you could investigate the logic of the installation and uninstallation code with an eye to how it might be going wrong. Moreover, are there no reproduction steps within #3516?

**Comment by ThioJoe** [comment]
Noticed something similar today:
<img width="344" alt="image" src="https://github.com/sumatrapdfreader/sumatrapdf/assets/12518330/10085173-850c-4e06-8837-9d9d3eb2b8bd">

It looks like the uninstall entry appears in two places in the registry:
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF`
`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF`

For me, both entries list the same exact location as the install directory (`C:\Program Files\SumatraPDF\SumatraPDF.exe`). I tested in a VM running the installer twice, one selecting to install for all users, and one not, and while that does create two separate entries, the entries do list different install locations: One in the program files, and one in the user AppData folder (which is actually what happens behind the scenes when any program asks you if you want to install for all users or not).

So @LinuxOnTheDesktop and @0lm at least one possible explanation is to check whether you just installed it twice, once for all users and one not.

For me however this doesn't seem to have been the case because both entries have the same install directory, so not sure. Maybe it happened as the result of updating to 3.5.2 somehow. I notice that there's not any binaries in the AppData Local folder where it normally installs either.

In any case, since both entries are effectively identical and I know that the data corresponds to an installation to all users, I can just delete the entry at `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF`

**Comment by LinuxOnTheDesktop** [comment]
@ThioJoe 

Thank you very much for your work.

Unfortunately right now I am lacking brain power. So, would you please explain _how_ I can check whether I have installed Sumatra both for a specific user and system-wide?

**Comment by ThioJoe** [comment]
@LinuxOnTheDesktop Sure basically for each type (Single-user Installation and All-user Installation) I'd check whether each is both physically installed (like the binaries are there) and whether the registry entries are there.

To see if the actual program is installed (regardless of what the installed apps list says), check to see if Sumatra.exe is in these locations:

- All Users Install Directory: `C:\Program Files\SumatraPDF`
- Single User Install Directory: `C:\Users\WhateverUserName\AppData\Local\SumatraPDF`
   - For this it might exist either way for settings files and stuff, but just look for an exe file

To see if Windows thinks either type is installed go to these places in the registry and see if each `SumatraPDF` folder exists under `Uninstall`. 
- All Users Install: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\`
- Single User Install: `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\`

If the `SumatraPDF` folders exist in one or both of those places (at least one should if you have it installed), you can see where it thinks it's installed by looking at the "InstallLocation" registry entry.

**Comment by LinuxOnTheDesktop** [comment]
@ThioJoe 

Thank you very much.

Things turn out to be as follows on my system.

I have a program executable in, only, `C:\Program Files\SumatraPDF`, i.e., in the all-users installation directory.

I have an uninstall entry at, only, `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall`, i.e., the registry path for a single-user install.

So there seems to be a mismatch: the executable's location is that of a multi-user installation; the uninstall registry entry is that of a single-user installation. Still: _currently_, Windows nowhere reports more than one version of the program being installed. (I have to put it like that - 'nowhere reports' - because of the schizoid way that Windows 10 has an old UI for listing installations and a new one.)

I am pretty sure that I have only ever - or at least recently! - installed 64-bit versions. (For, the computer is x64, and the only installer files I can find on my PC for Sumatra are labelled as x64.)

**Comment by GitHubRulesOK** [comment]
Hmmm 

For others as per suggestion you can quickly test the two potential install locations from command line

```
reg export HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\Sumatrapdf AllUsers.txt
reg export HKCU\Software\Microsoft\Windows\CurrentVersion\Uninstall\Sumatrapdf ThisUser.txt
```
If it is there you get one if both you get 2 responses `The operation completed successfully.` and details are in the text file(s)

**Comment by LinuxOnTheDesktop** [comment]
@GitHubRulesOK 

Thank you. 

```
> reg export HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\Sumatrapdf AllUsers.txt
ERROR: The system was unable to find the specified registry key or value.
> reg export HKCU\Software\Microsoft\Windows\CurrentVersion\Uninstall\Sumatrapdf ThisUser.tx
The operation completed successfully.
```

**Comment by GitHubRulesOK** [comment]
@LinuxOnTheDesktop 
I use many versions through the day for different reasons but "only one installed"
I have used  that mix before e.g THIS single user only uses `Program files`, since it was the historic installation directory and works well for that single user. any other version I use the standalone portable (however more recent pre-release portable also uses a local appdata for some data)
