### ISSUE TITLE
Double click to select word exits full screen/presentation mode

### ISSUE THREAD

**Issue by mgeorge** [sumatrapdfreader/sumatrapdf#4063]
As of version 3.5, double clicking a word to select it will exit full screen or presentation mode.  This is annoying for those of us who use double click to quickly highlight a word during a presentation.  Apparently I do this all the time when I am giving lectures because I am constantly kicking Sumatra out of full screen mode, which is getting frustrating.

Given you can just hit the escape key, or Ctrl+L, I am not sure why the double click to exit feature is necessary.

Could we please:

A)  Revert this behaviour, or
B)  Add a setting to disable it

**Comment by kjk** [comment]
It's already fixed in pre-release (https://www.sumatrapdfreader.org/prerelease), as long as you're over the word. If you double-click over non-word, then we'll still quit fullscreen.

I might further restrict it to non-document area and / or edges of the screen.

The feature exists because people without keyboards (no Esc or Ctrl+L available) asked for it.
