### ISSUE TITLE
If exiting with one or more tabs/files open, then next open will have those files still open

### ISSUE THREAD

**Issue by mikeybuhtig** [sumatrapdfreader/sumatrapdf#4091]
**SumatraPDF version**
- Version 3.5.2, release

**Describe the bug**
If a file (or multiple files) is open when SumatraPDF is closed, regardless of the keys used to exit, the file(s) is reopened when SumatraPDF is next started.

**To Reproduce**
1. Open at least one file in SumatraPDF
2. Press "q" (until all tabs are closed and window closes) or Ctrl+q (to close all tabs and the window)
3. Reopen SumatraPDF, either with or without a filespec on the command line 
4. All files that were open when the window was closed are reopened. If only one file was open and "q" was pressed, that file will be opened

**Expected behavior**
I expect reopening SumatraPDF would have no files/tabs open unless one was specified on the command line. 

Often, after viewing a file, I will move it to another directory or delete it. This causes a banner to display to say the file cannot be found. Even if the file isn't moved or deleted, having it open automatically means I have an unneeded file open.

The only way I've found to ensure the file(s) doesn't reopen when SumatraPDF is next opened is to press Ctrl+w on the last tab, before pressing "q" or Ctrl+q, but that's an extra step that wasn't required in previous versions. In previous versions, I could press "Esc" if I only had one file open and the next time I opened SumatraPDF, a file would be open only if I specified one on the command line.

**File that reproduces the problem**
Any file

**Screenshots**
Screenshots won't illustrate this. If the description isn't clear, I can attempt to create a video.

**Additional context**
As noted, this seems to be new with 3.5.2, I did not experience this with prerel-64-3.5.15183. I could press "Esc" when down to the last file and that file would not be opened the next time I started SumatraPDF.

**Comment by GitHubRulesOK** [comment]
Expected changed behaviour in recent versions
As you note previous versions needed 2 or more files closed to be counted as a "session" that was under peer pressure "improved" to one with or without home tab !
- Home tab is controlled by Advanced setting `NoHomeTab = false`
- opening previous closed file(S) is controlled by `RestoreSession = true`

**Comment by mikeybuhtig** [comment]
Thanks for the explanation. I searched the docs and couldn't find anything. I'm satisfied with setting `RestoreSession = false` to stop this behavior.

**Comment by Chivos** [comment]
I have the same comment. The current behaviour, with the reopening of the last closed file using "q" when NoHomeTab = false is a bit unexpected. 
A setting to restore old behaviour (start page when all tabs were closed or reopening of tabs that were left open) would be amazing.

**Comment by kjk** [comment]
The problem is: other people want it to work differently and I can't solve every disagreement with one more setting.

I'm pretty sure the reason I changed to restore a session with a single file is because people were confused / complaining that it doesn't. I should keep a log of intentional behavioral changes so that I can remember what motivated a change.

**Comment by Chivos** [comment]
Thank you for your response.
I fully understand this position.

**Comment by qwertfisch** [comment]
As mentioned in the other issue, I do not see the problem with the distinction of a session by two (or more) or only one previously opened window. If I understand @mikeybuhtig correctly the issue is the default behaviour of opening a session.

It is of course the decision of @kjk the enable the `RestoreSession` feature by default, and it makes sense if tabs are enabled.
But after disabling tabs I find it difficult to handle and to understand (before research here and reading issues) the behaviour. In my case I do not need / want tabs but single windows, so there is GUI option for that, but not for session restoring (which is, contrary to using tabs, a bit annoying with all the extra windows).

Is there a possibility to also add this as a GUI option? Might confuse less people if they see what options there are without having to rely on try/error in the settings file.
