### ISSUE TITLE
Applying background and text customed color settings in Settings.txt when print or save as.

### ISSUE THREAD

**Issue by sivenlu** [sumatrapdfreader/sumatrapdf#4135]
**Is your feature request related to a problem? Please describe.**
When I change the background and text color in Settings.txt, it just worked when I view it but not worked when I save it.

**Describe the solution you'd like**
I want to apply the color settings when printing or save as.

**Describe alternatives you've considered**
I think you can finish it because you already finish it.

**Additional context**
I would be appreciated if you could take my application into consideration.

**Comment by GitHubRulesOK** [comment]
Sumatra PDF is a Reader (limited editing to only extra annotations)
Acrobat Reader  that is also a Limited Acrobat writer it can do more than sumatraPDF because it has hundreds of Megabytes of editor code from it Pro Version so can edit the whole file not just include additions , How does Acrobat reader save the colours different ?

To alter the colors of a PDF you need Full Acrobat Pro Editor (or a cheaper competitive version) However there a hundreds if not thousands of MegaByte Command line editors so MuPDF command line can do more than SumatraPDF uses e.g. it can invert SOME pdf pages (not all)

**Comment by sivenlu** [comment]
Thanks for your reply. I really need someone to tell me this and you are the person.

**Comment by GitHubRulesOK** [comment]
to alter all text colour without change background cpdf has a "blacktext" command that can actually use any one colour like orange. there is also a java script invertpdf available somewhere in GitHub that can invert all the contents with a set background colour before you change the text from white to orange. so 2 single commands will alter much of a pdf contents without acrobat.
