### ISSUE TITLE
Large font in some EPUB files

### ISSUE THREAD

**Issue by dgdegiorgi** [sumatrapdfreader/sumatrapdf#4162]
**SumatraPDF version**
- 3.5.2 and 3.6.15987

**Describe the bug**
For some EPUB files Perfect PDF can show them good, but Sumatra PDF seems to use a too big font, cuts some chars and make the text almost unreadable.

For the attached EPUB file, Perfect PDF shows 76 pages, while Sumatra PDF shows 12651 pages.

**File that reproduces the problem**
If this is related to a specific PDF etc. file, please attach the file.

As an EPUB file is not custom, I copied the EPUB file to a PDF file.

The strange is that if I use 3.5.2 with this PDF file it work passably good (using 211 pages) while 3.6.15987 still shows the problem (still 12651 pages)
[Epubfile.epub.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/14816579/Epubfile.epub.pdf)

**Comment by GitHubRulesOK** [comment]
Basically the Fonts are unexpected units since it appears to be an Apple iBook so measures fonts in ems (but seems to not define fonts in Printers Points) You can see MuPDF (the core reding part of SumatraPDF sees them as defined much larger than an iPod would. Even edge needs them redefined well in order to convert to English. When defined as 10 Points (as the header and paragraph testo are) SumatraPDF on the Right would have no problems, note the Roman Italic has not yet been redefined.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/6deb23c1-2e92-40b0-b984-e1b15171dc22)

**Comment by kjk** [comment]
This file has css with `font-size: 100`.

As far as I can tell this is invalid. I assume we/mupdf treats it as `100 px` (i.e. very large) when it should be interpreted as `100%` (i.e. whatever the default size in the browser is).

**Comment by kjk** [comment]
Reported to mupdf: https://bugs.ghostscript.com/show_bug.cgi?id=707713
