### ISSUE TITLE
printing error

### ISSUE THREAD

**Issue by joshua1000** [sumatrapdfreader/sumatrapdf#417]
Printing PDF file from Sumatra 32 or 64bit is erratic. Please see http://ge.tt/9E9DO4W2?c for the original and scan of printed file. Printing worked fine with Sumatra v3.0, errors appeard only after updating to v3.11.

**Comment by dragosdobrota** [comment]
I can confirm the issue. 
It appears as horizontal white lines in the printed document.
Had to rollback to version 3.0 for the printing to work again.

**Comment by vdemonchy** [comment]
I have the exact same issue with Sumatra 3.1.1 x64 running on windows 7 pro x64.

**Comment by vdemonchy** [comment]
I've tested with versions 3.1.1 & 3.1 in both 32 & 64bit, they all contain the print bug described here (white stripes). It doesn't happen with every document though, so there must be some common properties in the impacted PDFs.
Downgrading to 3.0 fixes the issue, so the bug has definitely been introduced in the 3.1 version.

**Comment by vdemonchy** [comment]
Ok, I think I've found the origin of the bug : since 3.1, the printing always happens as an image and the advanced option to disable that has been removed (it's in the 3.1 changelog). 

In the 3.0 version, the option is present but it is disabled by default ( *PrintAsImage = false* ).
Changing that option to _true_ definitely triggers the white stripes bug, so I think there must be something wrong with the way some PDFs are converted to images before being sent to the printer.

A temporary workaround would be to re-introduce the PrintAsImage option, I've tried to put it in the config file on the latest version but I guess it's not interpreted anymore, so it doesn't change anything.

**Comment by vdemonchy** [comment]
A quick search indicates that [commit 71e41092ed0c8b10335725cf7e958571857d2bde](https://github.com/sumatrapdfreader/sumatrapdf/commit/71e41092ed0c8b10335725cf7e958571857d2bde) from 02/02/2015 is responsible for the disappearing option. It should be reverted IMO, with the PrintAsImage option changed to true by default if you want to keep the current behavior of the 3.1.1 version.

**Comment by glszakacs** [comment]
I'm seeing the same bug, but only on a particular printer (HP Color Laserjet 5500 Pcl6).  Other printers, also HP (4100 PCL and 4550 PS) don't show the problem.  I can verify it is in 3.1, 3.1.1, and the latest pre-release portable version as of 28 March 2016.  Other than that, I see a very long time to spool some documents, and if "print as image" is always enabled that could explain it (no such issue in 3.0).

**Comment by ct-graz** [comment]
We have the same problem here with a Xerox printer...

**Comment by madsl** [comment]
With Xerox, try to disable "Print optimization" under Printing Preferences -> Advanced tab -> Driver. Fixed the problem for me.

**Comment by bensoibj** [comment]
Same problem on a Xerox (WorkCentre 7835) with Sumatra 3.1.1. Thanks to @vdemonchy for the investigation. The suggestion from @madsl did not work for me. My workaround instead is to use Adobe reader for printing. :expressionless: I roughly compared the processing time it takes the printer to start printing:
- Adobe reader: 5 s
- Sumatra: 14 s (with printing errors)

**Comment by joshua1000** [comment]
I disabled "Print optimization" and the issue persists.

**Comment by justbur** [comment]
I'm one more person this affects. I print from a Brother printer at home with no problems on 3.0 or 3.1.1. At work (also with a Xerox), my printouts on 3.1.1 have horizontal white lines even with printasimage set to true. There is no problem on 3.0 at work. I don't see a "print optimization" setting.

By the way, thank you for sumatra. I've been using it for years.

**Comment by mortenfyhn** [comment]
Same issue here on xerox printers at university and Sumatra 3.1.2.

**Comment by tungwaiyip** [comment]
Another sighting like @justbur . Prints good with Brother. Gets white stripes using Xerox. Downgrade to 3.0 solved the problem.

**Comment by da-anton** [comment]
Same problem here. I switched back to Acrobat as most printouts were broken and at the office that stuff must just work.

**Comment by patrickmdnet** [comment]
Using Sumatra 3.1.2 Windows 32-bit with HP Color LaserJet CP2025dn UPD PCL 6 driver, all on Windows 10.  Same problem observed with horizontal lines on printouts.  

What does not fix the problem:
* Print-> Preferences -> Advanced -> "Print Optimizations: Disabled"

What does fix the problem: (either one)
* Print-> Preferences -> Color tab -> check Grayscale to true
* Settings -> Advanced Options... -> change "PrintAsImage = true"

**Comment by kuon** [comment]
I got the same issue and found no working workaround for my Xerox printer.

**Comment by royshearer** [comment]
Similarly getting very odd print behaviour from Sumatra 3.1.2 on XP with  Samsung ML4500. FIles come out shifted diagonally or completely mirrored. Prints fine from Adobe Reader.

**Comment by johannesfranken** [comment]
Please backport the option "PrintAsImage = false" from version 3.0.

I love Sumatra 3.1.2 for its general perforamce, usability and pdfTeX-support, but it sucks for printing.
With 3.1, the rendered spoolfiles are huge (e.g. 100 MB spoolfile for 1 MB PDF), almost unprintable over mobile network, and sometimes even break the Windows printer driver (HP LJ Enterprise M604 PCL @ 1200 DPI), so that I need to restart the spooler.

**Comment by kuro68k** [comment]
Ricoh network printer here. V3.1.2 64 bit. Same issue, white bands, PrintAsImage setting makes no difference.

**Comment by horusofoz** [comment]
Same issue still present. Is this being looked at all?

Sumatra 3.1.2
Windows 10 1607 Enterprise

[PrintTest.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/2463086/PrintTest.pdf)

[PrintOutput.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/2463088/PrintOutput.pdf)

**Comment by GitHubRulesOK** [comment]
@horusofoz In order to level the playing field since 3.0 SumatraPDF  uses exactly the same  technology (Windows print to image) for all printers (the only exception was an older tweak for Xerox images)
There are often changes to the code so you are always advised to see if the latest pre-release makes a difference (you only need a portable copy to test) and if so please let us know https://www.sumatrapdfreader.org/prerelease.html
Printing as image works with the majority of printers since it is then down to your print driver to handle the output and if not adjusting the content it "should" work. The disadvantage is the size of the print stream can cause memory issues with some print driver buffers which may explain problems such as intermittent  drop out. Some users find changing memory or format settings in the driver can clear these irregularities, hence you will see suggestions such as alter "optimization" or switch to raw etc. rather than can you add more memory to the printer.

**Comment by alexandre-lg** [comment]
Hello,

Disabling optimization worked for us:

- OS: Windows 10 LTSB 2016 or Windows 10 LTSC 2019
- SumatraPDF: 3.1.2 64-bit
- Printer Driver: Xerox Global Print Driver PCL6 5645.500.0.0 (64-bit)

To disable optimization, I do that (sorry my OS is in french):
![2019-06-26 15_27_02-printingProblemSumatraVSXerox](https://user-images.githubusercontent.com/3471351/60184320-23e78500-9828-11e9-8cb9-782180fd739a.png)

**Comment by snissenCC** [comment]
I've been using SumatraPDF exclusively for years with our Xerox printers and Canon MFDs. (With an odd HP LaserJet or two thrown in for enevlopes.) I've never run into this "white stripes" problem before now. The documents I like to test with are the Xerox Small Business templates [here](https://www.xerox.com/en-us/small-business/templates), specifically the pretty annual calendars. 

I never had one fail until now, using SumatraPDF 3.1.2 with the 2020 year-at-a-glance calendar, on a Xerox VersaLink C600 with the latest Xerox Global Print Driver PostScript. None of the printer settings changes suggested here made any difference.

Printing the calendar from Adobe Acrobat DC worked correctly, with the same print driver.

So I'll add my voice to those requesting a fix in SumatraPDF. I'll go looking for version 3.0 now.

**Comment by GitHubRulesOK** [comment]
That file is possibly optimised for use in adobe products i attach a variant and wonder if it prints without issue
[OACAL-35U-Imaged.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/3881515/OACAL-35U-Imaged.pdf)

**Comment by SumatraPeter** [comment]
@snissenCC: Besides v3.0 don't forget to test the latest [Sumatra daily builds](https://www.sumatrapdfreader.org/dailybuilds.html) as well!

**Comment by GitHubRulesOK** [comment]
@kjk dupe / consolidate with https://github.com/sumatrapdfreader/sumatrapdf/issues/919
