### ISSUE TITLE
forward search failed with multi source file.

### ISSUE THREAD

**Issue by changlichun** [sumatrapdfreader/sumatrapdf#4173]
**SumatraPDF version**
- Version 3.5.2

**Describe the bug**

When I input another tex file located in the parent directory, the forward search fails.

**To Reproduce**
1. Go to `main` folder
2. Build
3. Trying 
```
SumatraPDF.exe -forward-search ..\\section\\example-section.tex 5 .\\example.pdf
```

**Expected behavior**
Forward search currectly.

**File that reproduces the problem**
If this is related to a specific PDF etc. file, please attach the file.
[latex.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/14895926/latex.zip)

**Screenshots**

**Additional context**

It seem that the `synctex` record the inputed file as:
```
/latex/main/../section/example-section.tex
```
However the `SumatraPDF`  always cenvert sourdefile to absolute path. 

When I chenge the `.synctex` file to `/latex/section/example-section.tex`, the forward search behave well.

It might be help Modifying the [`_synctex_is_equivalent_file_name`](https://github.com/sumatrapdfreader/sumatrapdf/blob/34a168fc242de441f493ecbf93cdc09482e5470d/ext/synctex/synctex_parser_utils.c#L159) function to handle such paths might be helpful.

**Comment by GitHubRulesOK** [comment]
Syctex was designed for MACs but allowed for other platforms thus your file starts
```
SyncTeX Version:1
Input:1:f:/latex/main/./example.tex
Input:2:c:/texlive/2023/texmf-dist/tex/latex/base/article.cls
Input:3:c:/texlive/2023/texmf-dist/tex/latex/base/size10.clo
Input:4:c:/texlive/2023/texmf-dist/tex/latex/lipsum/lipsum.sty
Input:5:c:/texlive/2023/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty
Input:6:c:/texlive/2023/texmf-dist/tex/latex/l3kernel/expl3.sty
Input:7:c:/texlive/2023/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def
Input:8:c:/texlive/2023/texmf-dist/tex/latex/lipsum/lipsum.ltd.tex
Input:9:f:/latex/main/./example.aux
Input:10:f:/latex/main/../section/example-section.tex
Output:pdf
```
the first point that springs to mind is you are mixing devices and using relative paths (especially see 10 10:f:/latex/main/../section/e...) that will only cause problems as the TeX PRO guidance is ALWAYS use one folder for LaTeX sincce pathing is down to varieties in Operating System alias workings.

By NOT using Subfolders applications like bibliography double indexing imports and many others will find all the project files as siblings to each other thus avoiding any downstream issues such as this.
So Synctex in Windows uses folder divisions `/` exactly same as Mac and Linux BUT it needs translation by Windows OS into `\`

**Comment by changlichun** [comment]
I use the VScode which can treat the two file as one project. So, on clicking the inputed file, it can find the right pdf file. But  SumatraPDF gives an error.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/46743938/28aeed79-31fc-48bf-ab03-5f1a2619a0f4)

**Comment by changlichun** [comment]
> ```
> SyncTeX Version:1
> Input:1:./example.tex
> Input:2:c:/texlive/2023/texmf-dist/tex/latex/base/article.cls
> Input:3:c:/texlive/2023/texmf-dist/tex/latex/base/size10.clo
> Input:4:c:/texlive/2023/texmf-dist/tex/latex/lipsum/lipsum.sty
> Input:5:c:/texlive/2023/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty
> Input:6:c:/texlive/2023/texmf-dist/tex/latex/l3kernel/expl3.sty
> Input:7:c:/texlive/2023/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def
> Input:8:c:/texlive/2023/texmf-dist/tex/latex/lipsum/lipsum.ltd.tex
> Input:9:./example.aux
> Input:10:../section/example-section.tex
> Input:11:./example.aux
> ```
It do not work for me. Is it modified manually?

I quite understand that this may be some sort of characteristic of LiveTeX. I'm wondering if it's possible to do the path simplification first when doing a file lookup.

**Comment by GitHubRulesOK** [comment]
I am using the uncompressed and manually edited file and a directed call to notepad.vbs so everything simplified to the basics
```
' Usage:- in a Latex PDF viewer add this Reverse command or equivalent
' cscript C:\Path to\notepad.vbs "%f" %l
' where %f will be the file.tex and %l is the line number
' invokes 'WScript.ScriptFullName WScript.Arguments(0) WScript.Arguments(1)
Dim inShell
Dim Arguments()
SET inShell = WScript.CreateObject("WScript.Shell")
' the following will open each copy on run to get re-usud you need to find application 
inShell.Run ("%windir%\notepad.exe " & WScript.Arguments(0))
' add a delay for file opening
WScript.Sleep(1000)
' % is alt key and + is shift following REQUIRES NOTEPAD IS CURRENTLY Format "Word Wrap" OFF (can be set in registry)
inShell.SendKeys ("%EG" & WScript.Arguments(1) & "{enter}+{end}")
```

No interference by TeX or VSCODE settings it works with SyncTeX as vanilla design in windows XP+. 
It is the usage of drives or sub folders that then causes downstream problems which is why the tex.stackexchange.com TeXpert advisers will always suggest no remote/auxiliary folders. It may work for simpler runs  by relative paths but fail and lead to issues with more complex pathing when running multiple passes.

**Comment by GitHubRulesOK** [comment]
Hmm not currently using LaTeX but do not recollect any difference in such code since last time. 
But it is possible something slipped past me.

Let us start with the basic test in my system with no latex it works perfectly

![Image](https://github.com/user-attachments/assets/c088f1e9-65b7-4f52-9de3-fbce6d966743)

**Comment by GitHubRulesOK** [comment]
@kjk For what it is worth this open issue is not a SumatraPDF problem BECAUSE AFAIK it is working in current SumatraPDF as inverse search per intended by the synctex file behaviour https://github.com/user-attachments/files/18688532/main.zip 
The prognosis by J. Laurens (he who wrote synctex) suggests it is a VS code editor problem!

click in PDF opens TEX and highlights correct subsection 

<img width="554" height="312" alt="Image" src="https://github.com/user-attachments/assets/191bd3f2-cc69-4d1c-a790-89abe920028d" />

**Comment by kjk** [comment]
The file in synctex file is:
```
Input:10:f:/latex/main/../section/example-section.tex
```
I can't reproduce by extracting latex.zip it any directory. No magic will map `..\\section\\example-section.tex` into non-existent `f:/latex/main/../section/example-section.tex`

This might or might not be the issue but unless you provide step-by-step instructions on how to re-create this setup I can't even investigate.
