### ISSUE TITLE
Suggestion: Move state information to a dedicated config file

### ISSUE THREAD

**Issue by fgimian** [sumatrapdfreader/sumatrapdf#4193]
**Is your feature request related to a problem? Please describe.**
It is currently a little bit difficult to backup and restore a SumatraPDF settings file because it contains state information in addition to application settings. Thus overwriting the settings file will typically also overwrite file states, session data etc.

The goal would be that you could open SumatraPDF, view a bunch of documents; and as long as you don't change any settings, the SumatraPDF-settings.txt file should not change.

**Describe the solution you'd like**
I believe that keys such as FileStates, SessionData, TimeOfLastUpdateCheck and OpenCountWeek should ideally live in a separate file, perhaps called SumatraPDF-state.txt or similar.

**Describe alternatives you've considered**
I can't think of any other suitable alternatives.

**Additional context**
N/A

Thanks heaps
Fotis

**Comment by kjk** [comment]
No plans to do that.

**Comment by eugenesvk** [comment]
It's indeed unfortunate to have one single mess of a user config + user data in a file with not plans to fix.

Just wanted to share one potential workaround from similar experience with other apps (though also not a very easy one): you can use a config manager like chezmoi and set up a template python or similar script that will only store real user config and skip other data like `FileStates` and `SessionData` etc, though this will require parsing the config file, and it uses a non-standard format, so that adds to the difficulty
