### ISSUE TITLE
3.6 Pre-Release doesn't open referenced .pdf file

### ISSUE THREAD

**Issue by yjcui** [sumatrapdfreader/sumatrapdf#4197]
**SumatraPDF version**
- Version [3.6, pre-release]

**Describe the bug**
When clicking the index item in one pdf file, it does not jump to the corresponding external pdf file.

**Expected behavior**
Sumatra shall open the linked external pdf file after cliking on the link

**File that reproduces the problem**
Tested on pdf files from a conference, where a `.pdx` file is provided for easy indexing.

**Additional context**
Tested with 3.5.2 and it works fine.

**Comment by GitHubRulesOK** [comment]
PDX is very much an Adobe proprietary file so 
A)Ii dont think it is universally supported by any other PDF applications apart from Acrobat, unsure if even Edge with Acrobat plug-in can use it.

B) is AFAIK not part of their PDF Open Licensed ISO Standard, thus no need for 3rd party support.

C) has limited application other than to the source applications location.

Without a Sample of how a single PDF compliant file READER is supposed to respond to such a niche interoperation this issue is likely to go way beyond any PDF viewer/handlers remit.

**Comment by kjk** [comment]
Please provide a sample file(s). Nothing I can do without a sample.
