### ISSUE TITLE
Theme: Icons aren't clearly lit up in Dark/Darker theme

### ISSUE THREAD

**Issue by esdnm** [sumatrapdfreader/sumatrapdf#4213]
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/90970080/ae574d9f-1c1b-4a78-98ee-8fce63c1b68b)

Icons need adjustments for dark or darker theme

**Comment by user1823** [comment]
Which version are you using? This issue seems to be partially fixed in the latest pre-release.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/22017508-ccea-4151-bc13-1301b98343eb)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/7d088eb9-fe95-4888-8c54-4b76e88dd050)

The icons looks fine normally but when highlighted, they don't look fine.

**Comment by kjk** [comment]
please check latest pre-release https://www.sumatrapdfreader.org/prerelease

**Comment by user1823** [comment]
I am using the latest pre-release (v3.6.16121) and the icons still don't look good when highlighted.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/617e8ede-ecc2-4ab2-9a53-6568a5f6efbe)

**Comment by kjk** [comment]
Well, that's the best I can do given the limitations of toolbar control and / or my knowledge of toolbar control.

**Comment by GitHubRulesOK** [comment]
@user1823 
I think its a Windows Theming thing (have had recent issues with the way they are handled across versions) here on Win10 with official build I dont see the colours you do!

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/02bc5a8e-b85e-4bed-9f32-844d2933ada1)
