### ISSUE TITLE
Feature Request: Add one or two pixels above tabs in title bar when maximized

### ISSUE THREAD

**Issue by voidray** [sumatrapdfreader/sumatrapdf#423]
In Windows 7 and above it is possible to drag a window to and from the top of the screen. When sumatra pdf is maximized and many tabs are open it is not possible to click and drag the window by the title bar. Instead the tab is clicked.
It would be great to have that one or two pixels (or whatever is appropriate) to be able to support this scenario. 

The same problem exists in firefox by the way. I use the addon "Extra Padding When Maximized" in that case.

**Comment by stefanocaselli** [comment]
Please make it optional: I like to move the mouse to the top of screen and just click the tab: if you add some extra pixels at the top then I have to position the mouse pointer more accurately.
By the way: also in Firefox I don't want some extra pixels at the top of the screen :-)

**Comment by voidray** [comment]
Thanks, yes an option would be perfect.

**Comment by timhandschack** [comment]
+1 for this feature request
But instead of adding some extra pixels, please consider either 
following the (old) OS constraints of having a title bar with no content apart from min/max/close buttons or 
simply not filling the complete title bar with tabs (but leaving some padding towards the buttons).

**Comment by FrankSFLYS** [comment]
Another option is to add more space to the right of title bar. Considering opening a lot of tabs, it is difficult to drag the window. So just do as what chrome does now, no matter how many tabs opened, there is a wide fixed area on the right so that we can drag the window without clicking on the minimize button.
![Snipaste_2019-09-14_22-28-33](https://user-images.githubusercontent.com/10843159/64909501-a6a12180-d73f-11e9-9223-87c6296853a2.jpg)

**Comment by SumatraPeter** [comment]
@FrankSFLYS: That is precisely what I had suggested quite some time ago as well: https://github.com/sumatrapdfreader/sumatrapdf/issues/1053#issuecomment-410807509

**Comment by GitHubRulesOK** [comment]
@kjk this issue could be consolidated with #1053

**Comment by kjk** [comment]
Should be fixed thanks to @amurzeau adding app icon in the top-left menu bar that can be used to move the window and is always there.
