### ISSUE TITLE
Question about the feature: "faster scrolling with mouse wheel when cursor over scrollbar"

### ISSUE THREAD

**Issue by Noomene** [sumatrapdfreader/sumatrapdf#4244]
Dear SumatraPDFreader developer,

First thank you for this gem.

Issue: The feature: "faster scrolling with mouse wheel when cursor over scrollbar" was introduced in 3.4. Is there a way to turn it off via settings?

Reason: My mouse sometimes wanders to the side and then the scrolling speed suddenly changes and throws me off completely. A constant scroll speed would be better in this case.

Best regards,

**Comment by kjk** [comment]
Sorry, no way to turn this off.

**Comment by jotaf98** [comment]
I'd like to second the comment that this throws me off somewhat regularly -- it's disconcerting to jump to another place in the document when I meant to scroll down a bit, just because the mouse wandered off.

In terms of UI, if the mouse is over the scrollbar then you already have a way to scroll quickly to any point in the document: just drag the scroll handle there. Alternatively, hold the click down and the scroll position will get there.

These two standard behaviours make the mentioned feature somewhat redundant in my view, so I'm not sure it's worth the amount of grief it causes (for me :) ).

**Comment by namemv** [comment]
Actually, for me this causes so many disruptions to me, I can't use Sumatra. 
I don't get it why no way to turn this off.
I work with text, read like normal, instinctively move the cursor away from text (that I'm reading, isn't that natural?), then get thrown to a random place and I spend so much time finding the place where I was.
Had to switch to another viewer.

**Comment by kjk** [comment]
So I decided to turn it off by default and added `FastScrollOverScrollbar` advanced setting to turn it on.
