### ISSUE TITLE
Crash with CHM document

### ISSUE THREAD

**Issue by Fubaxiusz** [sumatrapdfreader/sumatrapdf#4253]
**SumatraPDF version**
- Version 3.5.2

**Describe the bug**
When Sumatra is opened with a default tab with CHM document manual from game RC Daredevil, and user switches the tab to any other in the background, Sumatra PDF crashes.

**To Reproduce**
1. Go to [RC Daredevil download page](https://www.myabandonware.com/game/rc-daredevil-ft4) and download the setup version of the game, or use the file attached.
2. Goto the installation location, inside `Home` folder there is a `RC DAREDEVILS.chm` file
3. Open the file with Sumatra PDF
4. Switch to another tab, tab switches but the view remains on the CHM file
5. See the crash after few seconds

**Expected behavior**
No crash, switch to another tab view.

**File that reproduces the problem**
[RC DAREDEVILS.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/15385129/RC.DAREDEVILS.zip)

**Comment by Fubaxiusz** [comment]
Here's crash report
https://gist.github.com/Fubaxiusz/c533585b5004dfb3a594cf08b69dfadb

**Comment by kjk** [comment]
Here's how I was able to reproduce that in 3.5.5:
* open 1 file: one .chm and one .pdf
* switch tab to .chm file
* quit the app
* re-open the app so that the files are restored on startup
* .chm tab should be open
* switch to .pdf tab

The good thing is that it's fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/a1daa10dc3776a82c3d43aa208a02abb9c521a02  in latest pre-release https://www.sumatrapdfreader.org/prerelease
