### ISSUE TITLE
TabWidth does not change the tab width

### ISSUE THREAD

**Issue by salavata** [sumatrapdfreader/sumatrapdf#4304]
**SumatraPDF version**
- Version 3.5.2, 64-bit

**Describe the bug**
Changing the TabWidth value does not really change the maximum width of tabs.

**To Reproduce**
1. Open several PDF documents
2. Go to the main menu
3. Click on 'Settings'
4. Click on 'Advanced Options...' (then a text editor launches automatically and opens SumatraPDF-settings.txt)
5. Scroll down to 'TabWidth = 300'
6. Change to 'TabWidth = 900'
7. Save
8. Exit the text editor
9. See error: the widths of all tabs remain unchanged.

**Expected behavior**
All tabs of open documents are expected to widen to fit the document name and a cross, but not wider than the TabWidth value specified (and no single tab is expected to be wider than the space allocated for all tabs).
If the total width of the tabs is greater than the space allocated for them, then "left-right" arrow buttons are expected to appear  without overlapping the cross of a tab.

**File that reproduces the problem**
Any PDF documents.

**Screenshots**
I think they are not needed.

**Additional context**
No other context.

**Comment by GitHubRulesOK** [comment]
Agreed it seems to be a problem in 3.5/3.6 but not in 3.4.6 (? before home tab introduced)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/1b49e585-f74e-4aac-8bf3-52688935e918)

**Comment by salavata** [comment]
3.4.6 was not perfect either. Today I upgraded from 3.4.6 just because the "left-right" arrow buttons overlapped the cross and prevented me from closing the tab. 
3.4.6 tabs also did not shrink in case of small filenames.

**Comment by GitHubRulesOK** [comment]
Tabs dont alter due to text that would be too complex so all apps use one size then reduce them all when more need to fit. 

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/e310f155-55dd-4359-8bfc-6ea493810d35)

SumatraPDF ha**d** one setting to make all smaller or bigger to start with then reduce to just the close button

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/eada64fb-831b-453c-bd9c-833e69180ad3)
