### ISSUE TITLE
How to register SumatraPDF as preview handler for PDF when using the portable zip file?

### ISSUE THREAD

**Issue by bencresty** [sumatrapdfreader/sumatrapdf#4350]
Hi,

First of all thanks a lot for creating this. After using the portable zip for a while with pleasure the only thing left was to set the program as preview handler. To my surprise this works when using the installer (as found here https://github.com/sumatrapdfreader/sumatrapdf/issues/457) , but I'd rather keep using the portable zip instead.

How can we register the software as a preview handler while using the portable zip instead of the installer?

**Comment by GitHubRulesOK** [comment]
Basically you cannot since if you try there would be many problems.

the 2 different EXE are exactly for the reason that a previewer or ifilter (the installer version options) must be installed into the system thus make the app non portable.

either "Portable.exe without previewer" or "Installed with previewer (and/or) iFilter" are the 2 licensed usages
same with 2.5 historic plugin ability it had to be added into system registry
