### ISSUE TITLE
copy/select problems in some languages

### ISSUE THREAD

**Issue by srsh-kh** [sumatrapdfreader/sumatrapdf#4357]
Copying text from Persian (or arabic) language and pasting it results in reversed text. Also, selecting a whole line in these languages are difficult as the selector constantly selects a different portion of the text while I'm trying to select the entire text.

**Comment by GitHubRulesOK** [comment]
Many RTL PDF documents are often not written correctly since most PDF generators dont set or use the RTL fonts correctly. So not a generic issue with SumatraPDF unless it is a problem for the underlying MuPDF reader or a poorly written file.

ther is no way to guess without a specific example however I will say your observations are not uncommon for cursive writing such as Asian Hebrew Arabic Persian etc. especially those with mixed content such as Latin LTR characters e.g 2024.

**Comment by srsh-kh** [comment]
Well. I just tried the pre-release and it seemed to be resolved. But both versions have another problem as well which is when I uncheck the "use tabs" option, whenever I open a new document it will also open another document that I have previously opened and it does it every time. For example I open A.pdf then close it and then open B.pdf and it opens both files simultaneously.

**Comment by srsh-kh** [comment]
Also, still in the pre-release when I try to select a line in languages like Persian it's very difficult or almost impossible to select a line completely and it suddenly jumps to another portion of the text. For example in this document:
https://civil.sadjad.ac.ir/sites/civil.sadjad.ac.ir/files/%DA%AF%D8%B2%D8%A7%D8%B1%D8%B4%20%DA%86%DB%8C%D8%B3%D8%AA.pdf

**Comment by kjk** [comment]
Don't put multiple things into a single issue. One issue for one distinct problem.

The re-opening without the tabs is maybe solved in latest pre-release. If not, open a new issue with a detailed and complete sequence of steps to reproduce the issue. There are many ways to open or close a file, so saying "I closed a file" doesn't provide enough information.
