### ISSUE TITLE
Wrong image color in dark mode

### ISSUE THREAD

**Issue by os9sur** [sumatrapdfreader/sumatrapdf#4380]
**SumatraPDF version**
- 3.6.16429

**Describe the bug**
The color of pictures are inverted

**To Reproduce**
In dark mode

**Screenshots**

![2024-07-18_175940](https://github.com/user-attachments/assets/87682046-2cb5-477c-adbc-cca3ce35ce1e)

**Comment by GitHubRulesOK** [comment]
not a problem inversion of images always works that way and there is no way a PDF can be partly inverted without you edit the whole file which will leed to many other coloured parts also wrong. 

If you even at most basic were to use a black background noe of the darker text would apper in contrast.

Acrobat Reader as a complex editor of PDF contents can make some "on the fly" alterations to a display by re-writing temporarily re-coloured objects in some groups without affecting images but it is limited in many cases.

**Comment by GitHubRulesOK** [comment]
Closing as in effect duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/3061 and many other past comments.

**Comment by kjk** [comment]
It's not related to dark mode but to `invert colors` commands (`i`) which is independent of dark mode.

Unfortunately it's more or less impossible to implement changing colors in PDF just for text and not for images, hence when you use it, images are inverted too.

**Comment by raufoon** [comment]
Even if it's with a naive or memory heavy approach, I suggest implementing an "attempt to keep image colors" option--which should work for many well-behaved pdfs. For example (1) you could invert the images and attempt to place them on top of the existing images and then convert the pages to image and then invert for display [re-inverting the images to their original colors] or (2) you could modify the inverted page image with the extracted un-inverted images.

**Comment by GitHubRulesOK** [comment]
@raufoon that is not impossible (I have done something similar elsewhere as a proof of concept) but it is not as simple as may be thought, since there are many different ways images are defined in a PDF. 

How would you handle images like these https://stackoverflow.com/a/76337148/10802527
https://stackoverflow.com/a/79322375/10802527

They are not that rare as many PDF are built up from discrete sub objects. without a common boundary as a group.

Thus, the time taken to replace them is significant in decompression and re-scaling. Plus, my example replacements mean a whole file had to be slowly re-built and thus in memory space and time a massive resource drain.

Acrobat will usually use greyscale imagery, but they may even disappear as shown here https://superuser.com/a/1866286/1769247 when altering image colours then greyscale is the best option
https://stackoverflow.com/a/78183717/10802527
