### ISSUE TITLE
SumatraPDF 3.5.2 does not uninstall on Windows 10

### ISSUE THREAD

**Issue by bfg01** [sumatrapdfreader/sumatrapdf#4406]
**SumatraPDF version**
- Version 3.5.2

**Describe the bug**
No matter if trying from Settings > Applications or from Control Panel:
first it always prompts UAC for admin rights, even though it was a **default**, user-only installation
then the window "Are you sure to uninstall SumatraPDF"; I hit the uninstall button and then it says it was uninstalled.
But this is NOT true at all. Application is still there intact.

**To Reproduce**
1. Try to uninstall the application, either by:
a. going to Settings > Applications > Select SummatraPDF for uninstall
b. uninstalling from Control Panel

**Expected behavior**
For SumatraPDF to be uninstalled with no traces behind

**File that reproduces the problem**
Not applicable

**Screenshots**
Not applicable

**Additional context**
I had to uninstall it entirely manual way: deleting desktop shortcut, deleting folder inside %localappdata%, deleting Start Menu entries, deleting all Sumatra-related registry entries.
And even so, running CCleaner a couple of times just to be sure.
I did not even try installing it for all users after this.

**Comment by kjk** [comment]
Also in pre-release, after uninstaller copies itself to temp directory, it fails to re-launch itself.

Anti virus? Change in Windows APIs?

**Comment by kjk** [comment]
That was mysterious but figured it out.

Code to parse command-line arguments assumed that first argument is path to it's own executable, as is Windows convention, and skipped first arg.

My code to launch process didn't pass the exe path as first argument.

When I relaunched the un-installer executable from temp directory and passed just `-uninstall` flag, the flag was skipped an nothing happened.

I fixed both the code to launch processes and made cmd-line parsing more robust to only ignore first arg if it's the same as it's own executable.

That's not a perfect fix because it's just arbitrary string passed by the caller so it might not get skipped.

**Comment by bfg01** [comment]
So will there be a next release?

**Comment by kjk** [comment]
This will ship in 3.6

**Comment by bfg01** [comment]
So until next year?

I think this was an important bug to be fixed; it is install/uninstall related.

**Comment by GitHubRulesOK** [comment]
@bgf
when uninstallers dont work as expected the rough users guide says use another version to up or downgrade then uninstall that.

I install many versions each moth for support and rarely have a problem such as you describe EXCEPT the daily auto update can be a problem that is hopefully fixed but I never know until it does not :-)

**Comment by GitHubRulesOK** [comment]
@kjk 
I tried update 16499 to 16506 and it disappeared !! but no return just stays at 16499 !!
![image](https://github.com/user-attachments/assets/98462ea5-2308-4438-8f7b-2411aa4db72d)
