### ISSUE TITLE
Black background with white text - how to get rid of it and where did it cvome from?

### ISSUE THREAD

**Issue by IrishRobbo** [sumatrapdfreader/sumatrapdf#4484]
Look. I just use sumatra right. Suddenly I have a black background and white text and it is awful. Please someone tell me how to get it back to white background and black text.
Otherwise I'll uninstall sumatra and use something else.

**Comment by GitHubRulesOK** [comment]
@IrishRobbo 
latest pre-release has inversion back now to `SHIFTy + I` as any version with it on lowercase `i` is too easy to accidentally brush over but press the other `i` and Irish eyes are a smiling :-)
(greetings from Cork.)

**Comment by kjk** [comment]
Press 'i' to toggle invert colors function

**Comment by 2-5** [comment]
@kjk I was hit by this too. Can you maybe add an `Invert Colors` checkbox menu item in the View menu, so that if you accidentally hit `i` and then desperately try to fix it by looking everywhere, you'll see the menu item?

**Comment by GitHubRulesOK** [comment]
@2-5 since only latest version can be altered you can do that yourself by add a menu item or in prerelease add an icon to the toolbar for example
![image](https://github.com/user-attachments/assets/b9527d8b-e92f-4733-8299-098ae3157c1d)
![image](https://github.com/user-attachments/assets/50c4f59a-f95c-4649-bc51-e2007430ad2c)
```
Shortcuts [
	[
		Cmd = CmdInvertColors
		Key = Shift + I
		ToolbarText = Swap
	]
]
```
