### ISSUE TITLE
Delete : should ask confirmation

### ISSUE THREAD

**Issue by meteorquake** [sumatrapdfreader/sumatrapdf#4493]
I'm sure I can't be the only one that thinks "File - Delete" should prompt to confirm the action, on the principle deletions should always ask. Anyone with a shaky hand has a chance of mis-clicking onto it and deleting their PDF.

David

**Comment by kjk** [comment]
We delete to trash so you can recover the file even if you delete by mistake.

**Comment by meteorquake** [comment]
Not all drives have a recycler though... as an example what happens with network drives? I've just tried it on a drive and it simply deletes it without recovery.

**Comment by H5820121** [comment]
"We delete to trash"
@kjk
But when the file is on a USB flash drive, when deleted it does not go to
the recycle bin, but is completely deleted without any permission.

‫בתאריך יום ו׳, 23 באוג׳ 2024 ב-15:33 מאת ‪Krzysztof Kowalczyk‬‏ <‪
***@***.***‬‏>:‬

**Comment by kjk** [comment]
Then don't use Sumatra to delete files. Sumatra is not a file manager and I'm not going to spend time on adding every possible bell and whistle to non-core functionality.

**Comment by H5820121** [comment]
@kjk
The issue is about those who unintentionally click on this option.
I think it is better to remove the deletion item from the menu, and those
who want to delete should do it through File Explorer or using a keyboard
shortcut in the advanced settings.


‫בתאריך יום ו׳, 23 באוג׳ 2024 ב-16:42 מאת ‪Krzysztof Kowalczyk‬‏ <‪
***@***.***‬‏>:‬

**Comment by kjk** [comment]
It's in the menu because someone asked for it. I can't please everyone.
