### ISSUE TITLE
command line -reuse -instance behavior when another non-specified SumatraPDF.exe program window is located above

### ISSUE THREAD

**Issue by saxyx** [sumatrapdfreader/sumatrapdf#4564]
**SumatraPDF version**
- Version [e.g. 3.6.16779, pre-release]

**Describe the bug**
I like to use two different SumatraPDF at the same time, one `SumatraPDF-prerel-64-3.6.16779.exe` to search forward and backward when compiling tex files, and the other `SumatraPDF-prerel-64-3.6.16779-2.exe` to open some pdf for reference.

However, when the desktop `SumatraPDF-prerel-64-3.6.16779-2` window is above the `SumatraPDF-prerel-64-3.6.16779` window, 
`SumatraPDF-prerel-64-3.6.16779.exe -reuse -instance test.pdf` opens `test.pdf` in `SumatraPDF-prerel-64-3.6.16779-2.exe` window.

**To Reproduce**
1. Open  `D:\SumatraPDF-prerel-64-3.6.16779.exe`  and `D:\SumatraPDF-prerel-64-3.6.16779-2.exe` , such that `SumatraPDF-prerel-64-3.6.16779-2` window is above the `SumatraPDF-prerel-64-3.6.16779` window, 
2. run `D:\SumatraPDF-prerel-64-3.6.16779.exe -reuse -instance D:\test.pdf` in cmd, `test.pdf` opened in `SumatraPDF-prerel-64-3.6.16779-2.exe` window.

**Expected behavior**
When run `D:\SumatraPDF-prerel-64-3.6.16779.exe -reuse -instance D:\test.pdf`, 'test.pdf' will always opened using `D:\SumatraPDF-prerel-64-3.6.16779.exe`

**File that reproduces the problem**
Not applicable

**Screenshots**
Not applicable

**Additional context**
Not applicable

**Comment by GitHubRulesOK** [comment]
the commands as shown are incorrect firstly there should be no need for reuse instance on command line as it is a "preferred" switch in the settings file and does follow a suitable "default" behaviour with tabs when running a LaTeX.synctex file.

Thus for the LaTeX call is not needed when the settings are correctly configured only the forwards searching is needed to find the tab and reuse it `[ForwardSearch("%blah%.pdf","%blah%",%l,0,0,1)]` or `-forward-search blah blah etc` 

Likewise no need for inverse-search as that is also "preferred" as a settings entry.

so firstly try without your 2 wrong switch's as they should be one and you will see that SumatraPDF by design default should find the first instance however many tabs or windows you have.
