### ISSUE TITLE
Register Sumatra PDF as default Preview handler.

### ISSUE THREAD

**Issue by nbrummerstedt** [sumatrapdfreader/sumatrapdf#457]
Upon installation, Sumatra should register af default preview handler for .pdf
This way, sumatra will deliver the preview in Windows Explorer Preview Pane.

Currently, the following alternatives exist:
http://www.windows8pdf.com/pdfpreviewer.html
http://timheuer.com/blog/archive/2008/05/09/foxit-pdf-preview-handler.aspx

**Comment by nbrummerstedt** [comment]
Also, this resource could be helpful.
https://msdn.microsoft.com/en-us/library/windows/desktop/cc144139(v=vs.85).aspx

**Comment by coleberhorst** [comment]
Agree this is something that seems inconsequential but is actually really useful from a user perspective. Especially since most users have tons of documents all in one folder.

**Comment by jpmaterial** [comment]
I concur. I'd prefer to use Sumatra, but I'm currently installing Acrobat Reader because I cannot do without the preview (Windows 10 here too).

**Comment by kjk** [comment]
We already do that. When installing, click "Options" and select "Let Windows show previews of PDF documents"

![](http://i.imgur.com/YgffK1c.png)

**Comment by jpmaterial** [comment]
Great, thanks. Should be default IMO, at least when the user has the preview pane enabled in Windows Explorer.

**Comment by CODE-REaD** [comment]
I was glad to find this answer as I could not discover how to change this setting using SumatraPDF's Options or Advanced Options (I also initially didn't understand that Windows has **_TWO_** ways of associating a file type with a program: _Default Program_ as well as _Default Preview Handler_, this being the latter).

In my case I already had the latest version of SumatraPDF installed, but was able to simply execute `SumatraPDF-3.1.2-64-install.exe` and have it reinstall itself, allowing me to click the Options button [as illustrated above](https://github.com/sumatrapdfreader/sumatrapdf/issues/457#issuecomment-302194352) and select _Let Windows show previews of PDF documents_.  This disabled Acrobat as my previewer and enabled SumatraPDF, apparently by making Registry modifications.

**Comment by GitHubRulesOK** [comment]
@jpmaterial
most users can get this to work by uninstall and reinstall with options selected, however you MUST use the correct version e.g. 64bit install on 64bit windows or 32bit install on 32bit windows (most common reason for failure) ALSO will depend on User Access Control, I have no problem as I am an elevated user, some users need to either  run as administrator or not for windows to allow the changes.

**Comment by jpmaterial** [comment]
This did not work for me. I am local admin, I'm using 64 bit Windows and SumatraPDF and I just un- and reinstalled. Still no preview.

**Comment by GitHubRulesOK** [comment]
@jpmaterial 
I am surprised that after so many attempts you have not got it to work, It is possible that your acrobat installation has had an affect that others have not had. can you confirm the program files folder name is NOT (x86) and from **properties  > details** of the PdfPreview.dll file in that folder what **file version** you have and from the **general** tab the exact Size e.g. something like 241 KB (247,296 bytes)

**Comment by jpmaterial** [comment]
C:\Program Files\SumatraPDF\PdfPreview.dll has 230 KB (235520 bytes). The file version is 3.1.2.0.

**Comment by GitHubRulesOK** [comment]
Ok that seems to be all present and correct, so I just reinstalled exactly the same version as administrator and can NOT see a pdf preview (I could before). That is because on uninstall/reinstall windows resets its default viewer back to edge so now my icons are *a small blue e with grey pdf*. My first task is to get windows 10 to stop interfering with my choice. If I try any of the old methods like run SumatraPDF as administrator or use the internal settings to try to get Sumatra as default handler they don't work as Win10 will keep insisting Edge is king of the viewers. So logged in as admin I have to right click a pdf and using the properties option go to general tab where it says "opens with" then click on **change button** and select SumatraPDF . NOW all my pdf icons change from blue/grey to yellow/black and If preview pane is active I can see the pdf preview again and if there is more than one page scroll though the pages (there are no other controls visible, if there are more controls such as zoom then another previewer must be active).

**Comment by jpmaterial** [comment]
I get the preview in Windows Explorer, my problem is the preview in Outlook.

**Comment by GitHubRulesOK** [comment]
Ok now I understand preview is for system thus 64bit if outlook is 32 bit then it will not work so check if outlook is 32 bit.

 IF so then you can only install 32 bit for outlook or 64bit for windows or upgrade outlook to 64bit

**Comment by dasebasto** [comment]
> We already do that. When installing, click "Options" and select "Let Windows show previews of PDF documents"
> 
> ![](https://camo.githubusercontent.com/ea0cffaa750e6bd267bc4a84ad396d172b7e80ce/687474703a2f2f692e696d6775722e636f6d2f596766664b31632e706e67)

This is when I realized that using auto installers like Ninite is sometimes counter-productive.

The options are off by default, so I had to look this up and reinstall Sumatra manually.

**Comment by musm** [comment]
I also agree that  these should be left true by default

**Comment by acicovic** [comment]
@musm so this is still unchecked by default?

**Comment by GitHubRulesOK** [comment]
From a support point of view the issue here is assumption that without the usual "click here to accept modify your system" that then a user will accept the safe default without reading the more intrusive options.
For a click and run Portable user the registration of preview and associations are unnecessary, 
The effects of the installer command line options should be known to a more skilled administrator.
It is unlikely that writing awordy installation text box would make much difference

On start-up there are two buttons
Options comes first then second is Install, simply use them in Left to Right order !

**Comment by dev4qa** [comment]
Hi
Thank you for a VERY good PDF viewer.  
The performance on large PDF files is lightyears ahead of the competition...and I have tested many different PDF viewers.

Usning Windows 10 64 bit;

Me to have probems with Preview pane in Windows Explorer for  SumatraPDF . 
Windows Exporer preview pane reads something along the lines of "The file you are attempting to open can be harmful to your computer. If you know it is safe open it in the PDF Tool directly". 

So I try add the handler in REGEDIT;

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\PreviewHandlers

To make this work, following instructions in , [https://learn.microsoft.com/en-us/answers/questions/2197108/unable-to-preview-documents-in-explorer-preview-pa](https://learn.microsoft.com/en-us/answers/questions/2197108/unable-to-preview-documents-in-explorer-preview-pa )   , what is the GUID for Sumatra PDF Handler?

Thanks

**Comment by GitHubRulesOK** [comment]
@dev4qa 
Microsoft have AGAIN recently changed pdf handling in Windows.

This is due to the enforcement of "Powered Buy Acrobat" becoming the almost mandatory PDF handler in MS Edge.
The issue with preview is collateral damage as they tigten security of PDF downloads thus the traditional "Mark Of The Web" (ADS WORM) you see when downloading any file is now used by them to raise a warning in previews. It has nothing to do with SumatraPDF which cannot change that.

<img width="1088" height="128" alt="Image" src="https://github.com/user-attachments/assets/b98f06f7-ce3f-44de-86f5-024b240c7113" />

<img width="1088" height="159" alt="Image" src="https://github.com/user-attachments/assets/2e7244ee-f5af-4c69-8838-b5f14c623d3b" />

<img width="1088" height="192" alt="Image" src="https://github.com/user-attachments/assets/cf78f47e-7571-4009-9d0c-1e83aa62740a" />

**Comment by dev4qa** [comment]
@GitHubRulesOK 
Many thanks for the workaround and solution, it worked!
Yes, unfortunalely there are many evil people on internet. 
I kinda understand Microsofts tightened security here.

**Comment by okeeblow** [comment]
I also ran into this when installing SumatraPDF through WinGet (`winget install SumatraPDF.SumatraPDF`) since I prefer to manage software updates that way, all at once on my own schedule, disabling update checks in every separate program.

My solution was to install through WinGet as usual, also download the newest 64-bit installer, run the installer, and select the “search PDF documents” and “show previews of PDF documents” options. I left “Install for all users” deselected, because my all-default-options WinGet installation was already in `%LOCALAPPDATA%\SumatraPDF`. Now that the handlers are registered I can just use WinGet to update as usual and not have to touch another standalone installer.

Thanks for pointing those installer options out!

**Comment by GitHubRulesOK** [comment]
@okeeblow there should be no need for winget it is not the official build unless it is directly downloading from the official page https://www.sumatrapdfreader.org/download-free-pdf-viewer but as for updates SumatraPDF (most of the time) has its own sytem of updating and only needs manual download if that fails. the point about TRYING to enforce Windows to recognise registration of SumatraPDFs own pre-viewers has been altered even in the latest version this week https://github.com/sumatrapdfreader/sumatrapdf/commit/2854c78d63bf14585c6ed054e0a2befb27d5216b
>re-register OpenWithProgids at startup if installed
This restores SumatraPDF in the 'Open with' context menu for .pdf (and other supported formats) in case another app (e.g. Microsoft Edge) has removed the entry after taking over the default handler.    

And there are internal ON/OFF options 

<img width="910" height="390" alt="Image" src="https://github.com/user-attachments/assets/434d0ec3-a421-4816-a363-32e8508a6776" />

<img width="855" height="281" alt="Image" src="https://github.com/user-attachments/assets/bfc320ae-bc44-4669-96b9-f10aacbe0689" />

<img width="851" height="317" alt="Image" src="https://github.com/user-attachments/assets/306be02f-1c0c-4fe7-873b-349ca1e4e075" />

**Comment by Neustradamus** [comment]
@kjk: Latest good is 3.1.2, all recents do not work correctly.
Can you fix it?

**Comment by kjk** [comment]
@Neustradamus just like ifilter, it works for me in latest pre-release

there's even `Ctrl + K` command palette command register/unregister preview and ifilter

**Comment by Neustradamus** [comment]
@kjk: I have tested all versions on Windows 7, the latest good one is 3.1.2 (some versions have not "All users" in installer too).

SumatraPDF 3.6.1 can work on Windows 7 except that the .pdf files can not be by default opened with SumatraPDF.

All times, we need to do, manually, "Open with".
