### ISSUE TITLE
Cannot change TextColor and BackgroundColor with dark theme

### ISSUE THREAD

**Issue by sorsted** [sumatrapdfreader/sumatrapdf#4656]
**SumatraPDF version**
- Version: 3.5.2, 64-bit on Windows 11

**Describe the bug**
Setting TextColor and BackgroundColor (in advanced settings) only seems to have an effect in light mode. The moment the Dark or Darker themes are chosen, the default values seem to be used instead.

**To Reproduce**
Go to advanced settings, and change the default values of TextColor and BackgroundColor, e.g. to
```
FixedPageUI [
	TextColor = #ff0000
	BackgroundColor = #000000
	SelectionColor = #f5fc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
	InvertColors = false
	HideScrollbars = false
]
```
After doing this, change the theme to Dark or Darker, either by changing the line “Theme = Light” or through the menus.

**Expected behavior**
Dark background with red text and a dark theme for the window in general.

**Screenshots**

![image](https://github.com/user-attachments/assets/01729fc5-6635-4f7f-98b0-bc459ac92974)

**Comment by GitHubRulesOK** [comment]
Closing as that specific issue was previously fixed in Pre-Release, howver colour inversion will always produce odd colour effects.

![image](https://github.com/user-attachments/assets/88af6066-b97a-4c65-895e-12382920ba9b)![image](https://github.com/user-attachments/assets/df686ca1-bbea-4790-9ddb-bbede00ef8ef)
