### ISSUE TITLE
 Support for adding notes documents 

### ISSUE THREAD

**Issue by BuZZ-dEE** [sumatrapdfreader/sumatrapdf#49]
It would be great, if it would be possible to add notes to PDF documents.

**Comment by turbodilan** [comment]
Sumatra PDF, need this function for become PERFECT (Now is really the best!).

**Comment by SBot123** [comment]
agree (on my wishlist too)

**Comment by harvcode** [comment]
This feature is absolutely NEEDED for me

I can't stand other pdf readers, I've tried everything and none have the same smooth experience as sumatra, if it only had note support it would be PERFECT.

**Comment by GitHubRulesOK** [comment]
Readers Notes
should be kept in a separate file from the master otherwise you need an editor to modify the pdf etc
There are several ways that can be done but the most effective is to have a companion **.txt** file alongside the master. That can be very easily implemented and has been effectively used for highlights (.smx) and bookmarks (.bkm .vbkm)
a TXT file can be  easily cut and pasted into any other format via the clipboard and for transmittal to others can be zipped up easily (Yes it would be nice if SumatraPDF could write and read cbx or pdx compressed containers which included txt content, however without a standard it would not be well-received by other application users)
Anyway I show how you can currently automate this using MSwrite/WordPad to create a word.docx or openoffice.odt in the forum post
https://forum.sumatrapdfreader.org/t/advanced-tips-add-your-own-notes/2688

**Comment by GitHubRulesOK** [comment]
I gave examples to add external notes in above post

The OP request to add notes to PDF is now addressed by the abillity to add both text comments and free text in current pre-release however note It is still a work in progress
