### ISSUE TITLE
Tabs behavior - request (Sumatra 3.1.1)

### ISSUE THREAD

**Issue by sorrowwind** [sumatrapdfreader/sumatrapdf#496]
Tabs need certain functions.
- Close
- Close all but this tab
- Close All
- Properties
- Open Containing Folder.
  We'll be glad to see those functions in new version.

**Comment by Wikiwide** [comment]
Frankly, I feel like I need to throw all modern Firefox/SeaMonkey/Chrome/etcetera browsers out of the window, and get a window manager which supports tabs and tiling. So that web browsers (and pdf readers, and file explorers) wouldn't need to re-invent the wheel (tab behaviour), and everything would be faster, easier and more consistent. Any recommendations, about such a window manager? Open-source one, of course.

**Comment by GitHubRulesOK** [comment]
This thread has valid ideas however since the OP is duplicated in others requests like #656 I am closing this one
