### ISSUE TITLE
Support 3D PDF with PRC

### ISSUE THREAD

**Issue by Symbian9** [sumatrapdfreader/sumatrapdf#523]
As you know, PDF with U3D is not shown in other than Adobe viewers - http://crunchbang.org/forums/viewtopic.php?id=27441
But what about PDF with PRC? - http://www.pdf3d.com/about-prc/
Opensource code for PRC support - https://en.wikipedia.org/wiki/Asymptote_(vector_graphics_language)

**Comment by GitHubRulesOK** [comment]
There are very few pdf readers that can support 3D since it requires extensive support for many related interactive features. Some very expensive viewers or those that share code with Adobe can have varied results.

The best free viewer from Foxit can support some static media animations but not 3D animations and even with basic spin and zoom cannot handle rendering surface materials. (that is NOT a zebra fish)

![3D](https://user-images.githubusercontent.com/12754913/73125780-a2fd9100-3fa2-11ea-91b8-df44605444a0.png)

**Comment by GitHubRulesOK** [comment]
@kjk 
I personally think this request is in effect way "out of scope" and be tagged as currently shan't fix.

I really would love to see 3D support as I generate PDF's from 3D models on a very regular basis, however I have found they can only reliably be viewed in Acrobat 9 or above. Thus for the past decade have only published models as 2D views.
The old 3D sample shown above can be found here https://github.com/GitHubRulesOK/MyNotes/blob/master/Acrobat%203D%20test%20-%20Laughing%20Porpoise.pdf

The above reference to Asymptote (an editing app) includes in the documentation that it can
"Embed the 3D PRC format in a PDF file and view the resulting PDF file with version 9.0 or later of Adobe Reader."

One reasonable "freemium" viewer to render some models well is the one from the Tracker eXchange Team. However it is much easier for me to shell out of SumatraPDF into Acrobat when I need to view a 3D model

**Comment by kjk** [comment]
Very unlikely to happen.
