### ISSUE TITLE
Putting the same page number twice change the page

### ISSUE THREAD

**Issue by ghost** [sumatrapdfreader/sumatrapdf#531]
If you enter a page number, then the same page number while still being on this page, the page change for the next one instead of staying on the same page.

With 3.1.1 64 bits

**Comment by GitHubRulesOK** [comment]
@kjk 
I cannot duplicate this dead cat bounce in 3.1.164bit portable thus it may have been specific to some installations of 3.1.1?

I can't replicate in the latest version unless I hit enter twice in succession
then it naturally goes to next page

I suggest as this issue is not in current build it be closed.
