### ISSUE TITLE
Cannot delete folder even after closing file

### ISSUE THREAD

**Issue by SumatraPeter** [sumatrapdfreader/sumatrapdf#536]
If I open one or more PDFs, I can then close them, _not_ exit Sumatra and still successfully delete the PDFs. However, if I do the same (open PDFs, close PDFs, _not_ exit Sumatra), I am unable to delete the folder in which the PDFs reside. Windows throws a "Folder in use" error in this case.

Why can I delete closed PDFs without exiting Sumatra, but not the folder as a whole until I exit the program?

[Tested with Sumatra 3.1.1 on Windows 10 32-bit.]

**Comment by kjk** [comment]
What's the evidence that it's Sumatra that causes that and not some other program? You might have an Explorer window with that folder opened or command line prompt or any other program.

**Comment by SumatraPeter** [comment]
@kjk I closed everything else and could still replicate this. Also I am unable to delete the folder but can do so as soon as I exit Sumatra, even if Explorer is open (clearly it is, since I am using it to delete the folder).

Are you saying you could not replicate this?

**Comment by kjk** [comment]
I need definitive proof that it's Sumatra that keeps the directory open even if all files are closed. There are tools that can tell you which process keeps a file/directory open: http://serverfault.com/questions/1966/how-do-you-find-what-process-is-holding-a-file-open-in-windows

**Comment by SumatraPeter** [comment]
@kjk Ok, although it's extremely easy to confirm this bug, here's the proof:

1. After a reboot I have only Firefox, Sumatra, Process Explorer and Paint running. No Explorer window is open. No file is open yet in Sumatra. A search for the path to my test file returns 0 (zero) matches, obviously:

 [![1](http://i.imgur.com/10dDdHu.png)](http://i.imgur.com/10dDdHu.png)

2. I now open my test file (an EPUB) in Sumatra. As you can clearly see, Sumatra opens **two** directory handles and **one** file handle:

 [![2](http://i.imgur.com/7hlIpDm.png)](http://i.imgur.com/7hlIpDm.png)

3. I finally close the file in Sumatra but keep the program running. The source of the problem is now obvious. As you can clearly see, Sumatra closes the file handle but just **one** of the directory handles. The other one is left open and prevents deletion of the directory till Sumatra is closed. This way Sumatra accumulates open directory handles unnecessarily:

 [![3](http://i.imgur.com/maWaXJo.png)](http://i.imgur.com/maWaXJo.png)

I hope that's sufficient proof and you can fix this bug soon. Thanks.

**Comment by kjk** [comment]
Thanks for additional information, that's what I was looking for.

Indeed Sumatra seems to keep the directory open. Unfortunately I can't promise when/if I'll be able to fix it.

**Comment by kjk** [comment]
This is strange, I can't reproduce it on latest win 10 with 3.1.2. I tried pdf/epub on both local drive and network drive. When I open a file I see only one handle to the directory held by Sumatra process and it's gone when I close the file.

Is there anything special about drive d:\ ?
Does it also happen when you use your main drive?

**Comment by SumatraPeter** [comment]
@kjk By "latest win 10" do you mean 1704 i.e. the 'Creators Update'? Which exact build do you have? I don't have 1704 installed yet so I cannot confirm Sumatra's behavior with it. However I just tested 3.1.2 (released 2016-08-14) on Win10 1607 (build 14393.1066) and the issue is still very much present.

Created a new folder C:\Books and copied Test.pdf to it. Double-clicked the file to open it with Sumatra (no previous instance of the program was running). Closed file's tab but kept Sumatra running. Attempted deleting file in Explorer and was successful. Went up one level to C:\ and attempted deleting empty folder C:\Books and got "Folder in use" error.

Can you replicate using these exact steps?

**Comment by kjk** [comment]
Hmm, I don't think version of Windows should matter, but stranger things have happened.

I've tested on Win 10 1703 build 15063.250, 64-bit with Sumatra 3.1.2 64-bit.

I created c:\books directory, put a .pdf file there, opened from explorer with Open With option.
When  file was opened, I checked that there are 2 handles opened with Process Explorer:

![frmerfn](https://cloud.githubusercontent.com/assets/7935/25552537/1ff3dca4-2c51-11e7-8b05-2d4577a9be7b.png)

(it would be only one handle if the file was smaller than 10 MB).

I closed the file, checked that there are no handles to c:\books directory and I was able to delete the directory in Explorer.

So I'm stumped.

Potential explanations.

1. It's possible it depends on Windows version. I'm not ruling anything out, but that's doubtful.

2. Did you enable indexing when installing Sumatra? I've been testing without indexing. It's possible that if it's a new file, there's a window when the directory is held because the file is being indexed. If that's true, then simply waiting a bit should fix it.

It's certainly strange that you see 2 handles opened to the directory when a file is opened. There should be only one. I know it's a lot to ask, but it would help if I knew where in the code those handles are being created.

If you're feeling adventurous and can setup debug tools (https://github.com/sumatrapdfreader/sumatrapdf/wiki/Debugging-Sumatra) it would help if  you ran Sumatra under WinDBG and type `bp kernel32!CreateFileExW` before hitting `g`. This sets a breakpoint at a function in Windows that creates the handle. If the program stops in in WinDBG, type `kb` to get a stack-tracke and paste it into a bug. Looking at the code it should only be called once from `NewWatchedDir` function in Sumatra.

**Comment by kjk** [comment]
I've tested with indexing enabled and that didn't change anything.

**Comment by SumatraPeter** [comment]
@kjk This has been driving me crazy and I've spent the past few days testing all sorts of scenarios. Finally I believe I've managed to narrow it down to something that seems very minor but is clearly causing the issue.

Turns out it's not the version of Win10 after all because I tested both 32 and 64-bit versions of 3.1.2 on 10586.873, 14393.1066 and 15063.250. **The only difference between how you tested and how I did was that I double-clicked the file to open it with Sumatra (which was associated with .PDF, .EPUB etc.), while you right-clicked the file and used the Open With option.**

Strange though it seems, I have confirmed that using Open With allows the folder to be deleted when the file is closed in Sumatra, while double-clicking the file to open it causes an extra dir handle to be opened. Now I leave it to you to look through the code to figure out the reason for this intriguing difference!

**Comment by kjk** [comment]
Thanks @SumatraPeter, I can confirm this happens for me as well.

**Comment by SumatraPeter** [comment]
@kjk Good to know that you were able to replicate the issue finally. I just remembered that quite some time back I had reported [a similar issue with anther app](https://github.com/mbunkus/mkvtoolnix/issues/1518). Perhaps the reason (and thus the solution) is the same in this case?

**Comment by kjk** [comment]
Thanks for the hint @SumatraPeter, you've saved me a bunch of debugging. Should be fixed in latest pre-release 10688 or later (https://www.sumatrapdfreader.org/prerelease.html)

**Comment by SumatraPeter** [comment]
@kjk Thanks a lot; the problem indeed seems to have been fixed.

**Comment by gschenck** [comment]
@kjk Thanks!
