### ISSUE TITLE
Cannot see PDF properties.

### ISSUE THREAD

**Issue by ksrik** [sumatrapdfreader/sumatrapdf#539]
When I open properties box, it shows just a black box.

![sumatrapdf properties error](https://cloud.githubusercontent.com/assets/3216582/15628271/a3871f66-251a-11e6-93d8-3eecd11bbd2c.png)

I am using version 3.1.1.

Regards,
Srikk

**Comment by IvarSnaaijer** [comment]
I have the exact same problem, updated to 3.1.2 64 bit on windows 10 this does not fix the problem.
@ksrik which version / platform do you use ?

**Comment by GitHubRulesOK** [comment]
@IvarSnaaijer
This is apparently a side effect of an incorrect settings file (causes unknown due to solution) 
see https://github.com/sumatrapdfreader/sumatrapdf/issues/1133
The solution is to apparently delete the advanced SumatraPDF-settings.txt file
and let it build a new default copy.

**Comment by IvarSnaaijer** [comment]
Thanks, Fixed it. 
The following setting was changed : 
MainWindowBackground = #80fff200
now set to 
MainWindowBackground = #80000000
and all is well again Tanks !

**Comment by GitHubRulesOK** [comment]
@kjk the common reason for this issue is a bad settings.txt entry. Novice users are not always certain which location the file is stored. Thus to delete and to reset to "factory" settings, it would be useful on the options menu to have a button to "restore to default settings" (with a message - Are you really REALLY certain - Cancel / OK)

**Comment by SumatraPeter** [comment]
@GitHubRulesOK: While I do agree that in general a "restore to default settings" option might be good, I do not agree with your description that "a **_bad_** settings.txt entry" is responsible for this issue, because it seems to indicate that the user is at fault.

Is it mentioned anywhere at all that _MainWindowBackground_ affects the Properties dialog as well? How is any user supposed to know they're making a 'bad' color change (when most likely they're simply trying to create a dark theme)? Moreover, _why_ should any user have to bother about this sort of weird undocumented behavior?

As far as I'm concerned this is a bug that needs fixing. The Properties dialog needs to be independent of all advanced color settings that affect the main document display area.

**Comment by GitHubRulesOK** [comment]
@SumatraPeter I agree it would be best if as you suggest there were paired settings (or alternatively no settings) to avoid this potential mismatch. My suggestion is that when a user finds settings are causing problems then they have a means to restore to initial state without new users having to drill down the user appdata paths

**Comment by kjk** [comment]
In current code the color of properties window is not affected by settings, so this is fixed.
For other issues, let's open separate bugs.
