### ISSUE TITLE
Copy of text returns '???'

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#547]
From: http://forums.fofou.org/sumatrapdf/topic?id=3185156&post=1

Copying text from http://www.msm.cam.ac.uk/phase-trans/2004/z/3750-004.pdf returns '???'. It works in pdf.js.

**Comment by GitHubRulesOK** [comment]
Forum link is now dead so posting file which is an extract from a larger document
[3750-004.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4617568/3750-004.pdf)
This issue seems to be different from #544 and others where characters are interspersed with spaces

In this and similar cases the characters are NOT spaced but words are replaced with ??? ???????????? or sometimes diamonds with ? etc

**Comment by kjk** [comment]
Interestingly, pdfium also can't extract the characters

**Comment by kjk** [comment]
Submitted to mupdf https://bugs.ghostscript.com/show_bug.cgi?id=704163

**Comment by kjk** [comment]
mupdf decided not to fix it
