### ISSUE TITLE
Printing PDF overrides printer and selects Letter rather than default which is A4

### ISSUE THREAD

**Issue by dnkcrook** [sumatrapdfreader/sumatrapdf#553]
When printing to an HP OfficeJet printer that is set by default to A4 Sumatra is overriding this and amending to Letter which is causing the print to come out of the printer the size of a postage stamp. The only option is to amend this each time a print is required. If printing from any other application , i.e. MS Word the printer stays at default of A4

**Comment by GitHubRulesOK** [comment]
If you allow windows to manage printers the default page may change to the previous print option, however SumatraPDF is generally told at print time what the system default page size is to be.

So my default printer is an A5 PDF generator but when I wish to send to my A4 paper printer I need to reset the page size for that driver since SumatraPDF uses the system set default of A5. There is no override setting in SumatraPDF OTHER than scaling=shrink and that causes enough problems as it is :-)

**Comment by GitHubRulesOK** [comment]
Works by design, employing windows "default" printer page size, before a printer is indicated, see #497
one possible cause of a problem with an odd "default" can be as described in #535
