### ISSUE TITLE
Add saving of annotations and cancel highlight

### ISSUE THREAD

**Issue by joshualyl** [sumatrapdfreader/sumatrapdf#561]
Currently SumatraPDF pre-release v3.2.10529 64bit can use 'H' to highlight selection in pdfs, but it fails to save these mark in Document. Additionally, please add a feature that give us a choice of canceling the mark by right clicking via mouse on the highlight marks .

**Comment by zklhp** [comment]
Hi,

I added some lines to make the remove of highlighting possible. I have made a pull request https://github.com/sumatrapdfreader/sumatrapdf/pull/741, and you can find the .exe with this feature at 

https://ci.appveyor.com/project/zklhp/sumatrapdf/build/artifacts

The use of the new feature is simple. With the highlighting selected, press h/H, the highlighting disappears.

I hope this helps.

**Comment by GitHubRulesOK** [comment]
Just an update to cotrrect some of above comments  
Highlight Saving is working as designed (use true or false to determine storage) but now uses the A key (NOT H)

The undo feature mentioned ONLY works in the current session before saving it causes problems if applied to a previous sesions saved smx highlights, does not work with mouse defined areas and cannot remove highlights stored in a saved pdf .

@kjk
The above points including the residual need to "Remove" highlights (both in .smx and .pdf) is generally covered by https://github.com/sumatrapdfreader/sumatrapdf/issues/103 (and https://github.com/sumatrapdfreader/sumatrapdf/issues/323) so I think this issue is effectively redundant.

**Comment by GitHubRulesOK** [comment]
Closing as the above features are now replaced in latest builds by a different method  which does allow for removing all highlighted areas.
