### ISSUE TITLE
problem with latest beta 3.2.10529

### ISSUE THREAD

**Issue by jg-github** [sumatrapdfreader/sumatrapdf#563]
The icons on is version do not appear correctly: Win7x64
[](http://edu-net.net/images/sumatra.jpg)

**Comment by jg-github** [comment]
Whoops, there was supposed to be a link to a screenshot.
http://edu-net.net/images/sumatra.jpg

**Comment by kjk** [comment]
Could you re-test with 10530? If it still shows pink icons, does 3.1.1 work?

I've tested with Win 10 and it works fine (while 3.1.1 had this issue when the icon had to be scaled to match high-dpi monitors). However, it seems that the fix for win 10 might be causing the problem for non-win 10 but I can't test the others.

**Comment by jg-github** [comment]
body p { margin-bottom: 00; margin-top: 0pt; } 


Hi again,

Thanks for your message. 

Here's a link to the results with 10530.
:-( 
http://edu-net.net/images/sumatra_2.jpg

I've also tested it on 3.1.1. It works as it should.

By the way, the monitors I've tested it on are an NEC PA272W and an NEC
2490WUXi2.

I hope this helps. 
-- 
Best regards,
Joe

**Comment by kjk** [comment]
This should be fixed in pre-release 10533 (http://www.sumatrapdfreader.org/prerelease.html)

**Comment by jg-github** [comment]
body p { margin-bottom: 00; margin-top: 0pt; } 


Yes, it's fine now. 

Thank you very much for your ongoing support of this wonderful program.
-- 
Best regards,
Joe
