### ISSUE TITLE
Colours not displaying correctly, gradient should be purple to yellow, shows as purple to white

### ISSUE THREAD

**Issue by JupitermarketingLTD** [sumatrapdfreader/sumatrapdf#566]
Have a PDF file that was generated externally, when opened in Sumatra (latest version and pre-release) there are colours missing from a gradient. displays correctly in adobe acrobat 11.0.15.
File is attached.
[FAR-070-002_v1_HiRes.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/350363/FAR-070-002_v1_HiRes.zip)

**Comment by AakaFosfor** [comment]
Similar issue here. Tested in the latest pre-lease and Adobe Acrobat. See attachment.
[gradientsBug.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/875231/gradientsBug.zip)

**Comment by GitHubRulesOK** [comment]
@kjk this can be closed since:-
OP colour problem is resolved in the latest builds see below in fact the SumatraPDF is much superior to the Acrobat render.
Note the second example above is not the same issue however is well covered by other issues related to improving transparency.
![image](https://user-images.githubusercontent.com/12754913/73544144-70371b00-4430-11ea-9939-96a4bad3f57e.png)

**Comment by kjk** [comment]
Seems to be fixed
