### ISSUE TITLE
I cant create bookmark expediently

### ISSUE THREAD

**Issue by MaesHughes** [sumatrapdfreader/sumatrapdf#57]
May be we can have a shortcut key to this?
I read books everyday by sumatrapdf and often need to jump from one chapter to another to look for sth.
Thx!

**Comment by GitHubRulesOK** [comment]
@kjk old topic that was unfortunately not addressed at the time 

Current suggestion is that Sumatra PDF does not currently edit PDF such as to add bookmarks however this request should be suitably addressed by the favourites feature using Alt F A <enter>.

There are other  enhancement requests to said "favourites" that would effectively make this duplicate/redundant since I am guessing the idea here was similar to adding a memory/recall jump location like say  in a calculator.

**Comment by GitHubRulesOK** [comment]
@MaesHughes I think you will agree the recent improvements in favourites addresses your desire for "expediency" 
Right click allows to easily **add and remove favourite** as placeholders (locations to jump back to) very much like the memory store and recall on a calculator

@kjk above account has no visible activity for 2 years so confirmation may not be forthcoming ? however I personally consider this request has been fulfilled by recent updates

**Comment by SumatraPeter** [comment]
Just to clarify for folks who don't go through code commits, **Ctrl+B** has now been added as a shortcut for adding the current page to favorites. If you want to test, the change should show up in the [daily builds](https://www.sumatrapdfreader.org/dailybuilds.html) soon and the [preview builds](https://www.sumatrapdfreader.org/prerelease.html) after some time.
