### ISSUE TITLE
PDF Rendering Issue (PDF created with MS Word)

### ISSUE THREAD

**Issue by ghost** [sumatrapdfreader/sumatrapdf#587]
I have a PDF file created from MS Word (2016 version in my example) that sumatrapdf shows a faint line between 2 cells in a table. Problem is the table was created with no borders at all. The same PDF file renders well on other PDF readers like Nitro and Adobe.

As you can see below, sumatra incorrectly renders a line; Nitro renders the file as intended.

![su-rendering](https://cloud.githubusercontent.com/assets/21015580/17646602/38ed861a-619f-11e6-871d-755e9a2b70c1.jpg)

![nitro-rendering](https://cloud.githubusercontent.com/assets/21015580/17646606/47a7d5ac-619f-11e6-8926-4e2ab25dec16.jpg)

**Comment by kjk** [comment]
There's nothing I can do without having the PDF file to test.

**Comment by n0tc0der** [comment]
Here's the [test PDF file](https://www.dropbox.com/s/om1gm2l8w3ep5iy/SumatraPDF%20Rendering%20Test.pdf?dl=0) I recreated.

**Comment by SumatraPeter** [comment]
You know what's funny? The dropbox page also loads the PDF inline, and Firefox's pdf.js viewer displays the line between cells too!

**Comment by GitHubRulesOK** [comment]
@kjk this cell division would obviously not appear if it was not there and is more visible in editors and image renderers as a one point / 1 pixel boundary seam between the cells

![image](https://user-images.githubusercontent.com/12754913/73770893-283c2f00-4775-11ea-841a-1a18e78913fb.png)

In theory MuPDF is showing it as a valid seam between cells, however in many viewers such as adobe acrobat it is shown as a seamless joint

I have tagged it MuPDF because it also shows up as a seam in MuPDF-GL and perhaps their library could be "improved" to hide the boundary line.

**Comment by kjk** [comment]
Reported as https://bugs.ghostscript.com/show_bug.cgi?id=702083

**Comment by GitHubRulesOK** [comment]
@kjk 
I see the response is down to needing to toggle Vector AA which is potentially related to other issues, as is Raster text AA causing impressions of "fuzzyness" / grey tones.
I believe that adding AA overide true/false values into settings file would cause ease of use issues and adding many extra options to view menu is not desired, however since a user may need to toggle such "enhancement preferences" easily they could potentially be added as toggles in the "settings" pull down ?

**Comment by SumatraPeter** [comment]
>  interesting its bug https://bugs.ghostscript.com/show_bug.cgi?id=702081 & 702082 & 702083 & 702084 & 702085 seems there is a bug in bug tracker 🙂

Weird! The timestamps differ however... Perhaps kjk submitted multiple times due to some issue at his end?

**Comment by kjk** [comment]
@GitHubRulesOK the duplicate ghostscript bugs are because their website at the time was taking minutes to acknowledge a bug submission so I submitted  a couple because I thought it might be a network issue. I've closed the duplicates.

@SumatraPeter unfortunately that is not a solution. I can either turn off anti-aliasing for every document or none. And I'm sure turning off anti-aliasing will cause problems for every document with vector graphics.

Closing this as I don't see a way to progress.

**Comment by GitHubRulesOK** [comment]
@kjk 
I understand users will not want AA off all of the time, and I do not understand how many places it would require code changes ?
However for **presentations and printing** (especially command line driven uses)
users would probably tolerate a temporary sticky true/false VectorAA preference that could be changed after a select few documents have been rendered, hence my suggestion it be easily GUI accessible but would also need to be externally addressable via settings.txt

**Comment by SumatraPeter** [comment]
@kjk: I think you forgot to mark 702081 as a dupe of 702083 as well.

**Comment by kjk** [comment]
As per https://bugs.ghostscript.com/show_bug.cgi?id=702074 it's unlikely to be fixed.

You can toggle anti-aliasing off (`Ctrl + k`, `toggle anti-alias rendering`) but that will impact rendering of text too.
