### ISSUE TITLE
3.1.2 reset PDF files to Edge

### ISSUE THREAD

**Issue by gemal** [sumatrapdfreader/sumatrapdf#589]
I used "SumatraPDF-3.1.2-64-install.exe"

and Windows 10 said something about a "problem with PDF files registration, so it reset them to Edge"

So now all my PDF are opened with Edge :(

Something is broken in the installer

**Comment by petrasteri** [comment]
I can confirm this behaviour.  Hence, I had to right-click on a PDF to do a "Open with" to change file association back.

**Comment by SumatraPeter** [comment]
Also see https://github.com/sumatrapdfreader/sumatrapdf/issues/604 and https://github.com/sumatrapdfreader/sumatrapdf/issues/615

**Comment by Lady-Luck** [comment]
Almost a year later and this is still a big problem..

**Comment by Lady-Luck** [comment]
With the Fall Update the problem has gotten worse. It can potentially trigger even just from navigating to a folder with pdfs in them.

**Comment by SumatraPeter** [comment]
@Lady-Luck: The procedure I detailed [here](https://github.com/sumatrapdfreader/sumatrapdf/issues/615#issuecomment-330038609) with screenshots in response to your comment still works in the Fall Creators Update. Once I set Sumatra as the default PDF viewer via the Settings app it just sticks, and no amount of folder browsing causes a reset to Edge. I think something's up with your system and since you're just updating the OS in place every time the issue's just persisting or even getting worse. I'd recommend a fresh _clean_ install, but I know how onerous that can be so maybe you can look into an easier solution such as creating a fresh user account.

**Comment by KrasnayaPloshchad** [comment]
What happened if you open Sumatra PDF with administrator rights?

**Comment by GitHubRulesOK** [comment]
1. @kjk now tracked by #1248

**Comment by kjk** [comment]
Consolidate under #1248
