### ISSUE TITLE
Controll on words and characters spaces (words per line)

### ISSUE THREAD

**Issue by HamedFathi** [sumatrapdfreader/sumatrapdf#594]
Hi 

Thanks for your efforts, SumatraPDF is awesome 

but I have a problem with it , I need a feature, setting or any control on space between words and chars.
Now sumatrapdf handles spaces but for me is better lower spaces

anyway, I believe a setting for increase and decrease spaces between chars and words for having more or less words per line will be awesome

**Comment by GitHubRulesOK** [comment]
@kjk this issue seems to be "out of scope"

A PDF is not supposed to be "variable" within the reader, hence we have all the issues that Acrobat does XXX but SumatraPDF does YYY.  However if we are talking E-pub there is an element of user control by their choice of font which will alter "characters per line"

**Comment by kjk** [comment]
Closing as too vague.
