### ISSUE TITLE
strange rendering of plots created with PGFPlots v1.14

### ISSUE THREAD

**Issue by Mo-Gul** [sumatrapdfreader/sumatrapdf#595]
Maybe this is an issue that is related to #566. 

Please have a look at the TeX file and the corresponding result in [PP.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/426396/PP.zip). Opening the PDF in SumatraPDF gives some weird result. Here are the screenshots taken from the views in
- SumatraPDF v3.1.2 64-bit  
  
  ![sumatrapdf](https://cloud.githubusercontent.com/assets/17992976/17800327/99f3b7a8-65e2-11e6-93d3-c16d3cd233cf.PNG)
- Adobe Acrobat XI v11.0.17  
  
  ![adobe acrobat](https://cloud.githubusercontent.com/assets/17992976/17800328/9c023042-65e2-11e6-8541-f23860c7c96c.PNG)

Is there anything (simple) that can be done to improve the view in SumatraPDF?

**Comment by cfeuersaenger** [comment]
The issue surfaced becaused the tex package pgfplots now generates the function definitions within the shading in a different number range.

The old (correctly rendered) behavior was to decode the color data into the range [0,1]. The new behavior is to decode it into the range [0,1000]. The generated PDF is correct (appears to be correct) according to the pdf standard, but SumatraPdf appears to decode it in a wrong way.

In order to track down the issue, experiment with the "/Decode" array and the "domain" argument of the shading functions in Stefan's PP.pdf (of course, the /Bounds needs to be adopted accordingly).

**Comment by GitHubRulesOK** [comment]
As with all pgfplot output it can be highly variable in every PDF reader compare the acrobat block colour output above with the alternative tonal rendering below.
If the output is plain text or basic image it can be saved as suitable for portability between readers, however if it is a hybrid output it is best converted to lossless png/webp before embedding.
Jpg formats are good for photos but not ideal for tonal graduation.
![image](https://user-images.githubusercontent.com/12754913/73542944-c0f94480-442d-11ea-8ca2-835d387d2cc7.png)
[Clipboard01.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4139584/Clipboard01.pdf)

**Comment by kjk** [comment]
Reported as https://bugs.ghostscript.com/show_bug.cgi?id=702076

**Comment by cfeuersaenger** [comment]
You say that 

> As with all pgfplot output it can be highly variable in every PDF reader compare the acrobat block colour output above with the alternative tonal rendering below.

Even if what you say would be true: would it be a fault of pgfplots? A fault in pdf? Or maybe a fault in the reader? 

I as author of pgfplots have put high effort into producing a valid portable pdf output. If it really turns out to be a fault in pgfplots, I would happily fix it on my part. I believe that the PDF is correctly generated. In that case, viewer differences are an issue of the viewer and should be fixed in the viewer.

Aside from that, I would like to stress that I do not agree to your phrase "As with all output of pgfplots". From my experience, 99.9% of the output of pgfplots produces the same results in all viewers, as it ought to be. Exceptions were (for some viewers still are) shadings because both the "function" shading in pdf as well as the geometry poses implementational challenges for the viewer, i.e. has a high risk of introducing bugs.

**Comment by kjk** [comment]
@cfeuersaenger since Adobe Reader / Chrome seems to render it correctly, the fault seems to be in Sumatra / mupdf.

I haven't looked at it in depth so for a definitive answer I would monitor https://bugs.ghostscript.com/show_bug.cgi?id=702076 since mupdf developers are experts on this stuff.

If mupdf fixes this, Sumatra will import the fix. If not, then we wont.

**Comment by cfeuersaenger** [comment]
Sounds great, thank you!

Note that I have contributed fixes to shading issues to libpoppler some time ago, i.e. I have some familiarity with how to implement such things. I might be able to contribute fixes if the mupdf team won't do it.

**Comment by GitHubRulesOK** [comment]
@cfeuersaenger 
I am not a team member just supporter of SumatraPDF
I apologize that my loose wording implied that there is a failing in your appreciated application
My ALL observation was based on a very small subset that causes a different result in the MuPDF engine which is clearly to blame.

**Comment by GitHubRulesOK** [comment]
@kjk 
This is so frustrating, After 4 1/2 years this issue should now be closed as the latest version is fixed to show the above  pgf file correctly, thus https://bugs.ghostscript.com/show_bug.cgi?id=702076 "could" be considered closed.
![image](https://user-images.githubusercontent.com/12754913/104187510-cd449a80-540f-11eb-9f04-faf29a9c2991.png)
However related examples are still not showing well. so if closing this one then need to reopen others such as #1742
