### ISSUE TITLE
open in pdf x-change viewer

### ISSUE THREAD

**Issue by giampi75** [sumatrapdfreader/sumatrapdf#598]
Hello,
in the file menu I have "open in foxit reader" but I don't have "open in pdf x-change viewer", which is installed on my system. Any idea?
Thanks

**Comment by botmtl** [comment]
I am not a sumatra developer but I do try to build it from time to time.  I may be able to help you.  Use this reg file so that sumatra finds "PDFXCview.exe" in the folder pointed to by "InstallPath".  HKEY_CURRENT_USER is also checked. 

**PDFViewer.reg:**

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Tracker Software\PDFViewer]
"InstallPath"="C:\\Program Files\\Tracker Software\\PDF Viewer\\"

**Comment by giampi75** [comment]
Thanks for your answer, but this doesn't work for me

**Comment by botmtl** [comment]
You are not giving enough information for anyone to be of help.

**Comment by GitHubRulesOK** [comment]
To add any ExternalViewer see the general discussion in https://github.com/sumatrapdfreader/sumatrapdf/issues/777 
If you look at the properties of any shortcut to pdf x-change viewer or editor it should be something like
"C:\Program Files\Tracker Software\PDF Viewer\PDFXCview.exe" (It may be different for each variant so could even be like "c:/Program Files (x86)/Tracker Software/PDF Editor/PDFXEdit.exe") but whichever it is you need the full path ending .exe then use that to replace the one in the example entry below and keep the two sets of plain double quotes
ExternalViewers [
```
	[
		CommandLine = "C:\Program Files\Tracker Software\PDF Viewer\PDFXCview.exe" /A page=%p "%1"
		Name = PDF&Xchange for Edits
		Filter = *.pdf
	]
```
]
