### ISSUE TITLE
tell Windows 10 that SumatraPDF can open supported file types

### ISSUE THREAD

**Issue by klonuo** [sumatrapdfreader/sumatrapdf#604]
Title is from 3.1.2 changelog: http://www.sumatrapdfreader.org/news.html

I just updated SumatraPDF and then Windows 10 showed me notification that because of an error it will associate PDF with MS Edge - and it did associate with MS Edge.
Previously all was fine, and Sumatra was my default PDF viewer.

**Comment by petrasteri** [comment]
There must be some situations in which Win10 does not associate PDF with Sumatra.  I have migrated many Win 7/8 to Win10 but I have never got any problem.  FYI: the version of Sumatra is mostly 3.1.1 but some are 3.1, and they are mostly in 64-bit.

**Comment by klonuo** [comment]
I run 3.1.2 64 bit. My previous version was probably 3.1.1.

If not obvious, when I opened Sumatra it asked me if I like to upgrade as there is new version and led me to Sumatra portal to download 3.1.2 installation. I installed and what happened I wrote in initial post.

**Comment by petrasteri** [comment]
Today, I uninstalled 3.1.1 in a computer and then reinstall 3.1.2 and I got this problem.  So I confirm your issue.

**Comment by SumatraPeter** [comment]
Yes, I can confirm that this is definitely still a problem with 3.1.2 (both 32 and 64-bit versions, tested by updating from 3.1.1 on both Win10 1511 and 1607).

The workaround for now is to run the program once as admin and set it as the default PDF viewer. That's the only way the setting 'sticks' and Edge doesn't steal it back.

**Comment by KrasnayaPloshchad** [comment]
This problem is works for me even if I run Sumatra PDF as administrator.

**Comment by TheAdmin27** [comment]
@KrasnayaPloshchad The fix suggested by @SumatraPeter is kind of specific, you can't just run the program as administrator and then click "yes" if it asks you to set it as default. The Key is to run the program as administrator, and then afterwards set Sumatra as default reader manually:
1. Run Sumatra PDF as administrator
-> if a popup asks you if you want to set it as default, press no or close that popup
2. left click on your windows button, press settings
3. Click on "system"
4. Click on "Default Apps"
5. "Choose default Apps for certain filetypes" (sorry, my OS is german and so am i, the translation might be goofy)
6. Set Sumatra PDF as default for .PDF

I might have gone overboard with the details in this one since anyone here should know how to set apps as default in windows 10, but since a lot of people should have this problem there might be one or two who need the explanation as long as it got.

**Comment by GitHubRulesOK** [comment]
@kjk now tracked by #1248

**Comment by kjk** [comment]
Consolidate under #1248
