### ISSUE TITLE
Crashes when printing

### ISSUE THREAD

**Issue by jetzlstorfer** [sumatrapdfreader/sumatrapdf#610]
Sumatra crashes when printing, in fact before the print dialog opens. Regardless of trying with Shortcut or with Menu. Also, the number of open tabs does not matter. 

v3.1.2 64-bit on Win10

**Comment by kjk** [comment]
Unfortunately a number of printer drivers are buggy and there's not much I can do about it. If possible, see if there are newer drivers for the printer.

**Comment by jetinski** [comment]
I don't have any problems when opening and printing the same document with Adobe PDF, thus, I'm not sure if the printer driver is buggy? But thanks for the quick reply!

**Comment by kjk** [comment]
At the same time, sumatra prints on majority of printers. We don't send the exact same data as Adobe does, which might trigger different, buggy paths in the driver. Adobe has resources to tweak their code to work-around bugs in different printers or even get printer manufacturers to fix the bugs that affects Adobe. I don't.

The only realistic scenario for fixing this issue is if someone who has this exact printer and this exact PDF and is capable of figuring out the problem and a work-around sends me a fix.

As it stands, I don't even know which printer it is, which os version, what PDF file triggers the crash etc.

**Comment by ProfBrianChen** [comment]
I have this problem too.  It sucks.

**Comment by GitHubRulesOK** [comment]
Without driver details its impossible to progress this single issue. For new users please check open and closed issues both here and on forum searching for related equipment / solutions.
