### ISSUE TITLE
Make default PDF reader doesn't work

### ISSUE THREAD

**Issue by thany** [sumatrapdfreader/sumatrapdf#615]
Every time Sumatra starts, it asks to become the default app for PDF files. Every time, I click Yes. Every time, it doesn't do anything other than refresh my desktop icons. On top of that the "Don't ask me again" also doesn't work - if that's checked, it still asks every next time.

Edge remains the default PDF reader - it's somehow not able to change that.

Windows 10.0.14393 x64
SumatraPDF 3.1.2 x64

PS. the prerelease version doesn't work at the moment - `A remote procedure call (RPC) protocol error occurred.` when trying to launch the installer - so I'll have to stick with the release version for this bug report.

**Comment by SumatraPeter** [comment]
The workaround for now is to run the program once as admin and set it as the default PDF viewer. That's the only way the setting 'sticks' and Edge doesn't steal it back.

**Comment by thany** [comment]
Can you change it for a future version so that it temporarily requests elevated permissions?

**Comment by SumatraPeter** [comment]
I'm not one of the developers so you'll have to wait for an official reply from them.

The workaround did work for me, but perhaps I should have been more explicit. I launched the program as admin immediately after installing it (after Windows showed me the error notification and set Edge as the default), then explicitly went to Settings > Options and clicked the button to make Sumatra my default PDF viewer. Closed the program and haven't had a problem since with PDF associations.

**Comment by TheAdmin27** [comment]
@SumatraPeter Thank you so much for the "detailed" fix, worked like a charm.

**Comment by SumatraPeter** [comment]
@TheAdmin27: Glad it worked for you! FWIW if you need to, in future just point people to [this document](https://www.sumatrapdfreader.org/docs/Setting-Sumatra-as-default-PDF-reader-b794dcaa2cdd46fb98ccef4323a1398c.html), which is a direct copy-paste of [a post](https://muut.com/sumatrapdf#!/general:problem) I made in the (old) Sumatra forum.

@kjk: I mentioned this on the muut forum but guess you didn't see my post: please fix the minor typo I made in the very last line – it should read _Set SumatraPDF **as** the default app_. Also, after extensive further testing I'd recommend moving the last solution (the _System > Default_ one) up to be the second one users can try. The extra-long second solution can be shifted down to third since it should probably be the very last option users can try if the other two fail for some reason. Last but not least you might also want to fix the italics (between underscores) and bold (between asterisks) text in the [current doc](https://www.sumatrapdfreader.org/docs/Setting-Sumatra-as-default-PDF-reader-b794dcaa2cdd46fb98ccef4323a1398c.html) to make it look like the [older (and better) version(https://www.notion.so/Setting-Sumatra-as-default-PDF-reader-b794dcaa2cdd46fb98ccef4323a1398c).

**Comment by TheAdmin27** [comment]
@SumatraPeter that document is kind of handy, but for me Sumatra PDF had to be running as admin whilst setting it as default via the system default apps (just verified it again on another divice, running it once as admin and closing it before changing the Setting is not enoguh for me).

Do you have any influence/contact to the developers to add that (Run Sumatra PDF as Administrator and minimize it/leave it be) to the last Paragraph in between "If issue is still not resolved" and "Open Settings App"? Having complete instructions on the official page will certainly help some users.

**Comment by SumatraPeter** [comment]
@TheAdmin27: Not quite sure I understand what you're saying. To be perfectly clear, my suggestions (as echoed by the docs) involve either 1) running Sumatra as admin and setting it as the default PDF viewer via `Settings > Options`, _or_ 3) setting it as the default PDF viewer via `Settings app > Apps > Default apps` (during which Sumatra need not be running). If solution 1) doesn't work then 3) definitely does, at least on all the systems I've tried it so far.

Also I have no form of contact with the developer besides posting here and on the forum.

@kjk: Sigh... Since Win10 is a moving target there's yet another change to be made in solution 3), namely, the `Default apps` section is no longer present under `Settings app > System` in the latest Creators Update (Win10 1703), but is now present under `Settings app > Apps`.

\* shakes fist at Microsoft \*

**Comment by TheAdmin27** [comment]
@SumatraPeter For me, 3) worked, but only when Sumatra PDF was running as Administrator while Setting it as Default app for .PDF in Settings > App > Default Apps. If Sumatra PDF was not running as Administrator, the initial Problem  (reset to edge as Default) would occur. This was done both on my custom built PC (Windows 10 Version 1607 Build 14393.1480) and on my Surface (Windows 10 Version 1703 Build 15063.483).

I neither want to be a special snowflake nor spam this thread, but i tested and verified on both devices that Sumatra PDF needs to be currently running as Administrator for solution 3) to work for my devices.

**Comment by SumatraPeter** [comment]
> I neither want to be a special snowflake nor spam this thread, but i tested and verified on both devices that Sumatra PDF needs to be currently running as Administrator for solution 3) to work for my devices.

Hey, you tested on your systems, and I tested on mine and all the ones I administer for family (lot more than two BTW), and it's entirely possible that both our experiences were valid. TBH, it would hardly be a surprise if certain systems behaved differently based on some combination of OS version, patch level, software environment and what not. So even though it makes no sense that an app should be currently running for it to be set as the default via Win10's Settings (and indeed, that wasn't a requirement on any of my systems), we can leave it as one more tip that people can try if all else fails. :)

**Comment by Lady-Luck** [comment]
Latest Windows 10 update has it not showing up in the 'Default app settings' Windows 10 settings app, and if it's not registered there, the OS doesn't like to assign file association when requested.

**Comment by SumatraPeter** [comment]
@Lady-Luck: Works fine here. Which Windows 10 build are you using? Is it an Insider build or a non-Insider stable build?

The following screenshots were taken on Windows 10 version 1703 [latest non-Insider build](https://support.microsoft.com/en-us/help/4018124/windows-10-update-history) 15063.608 (go to `Settings app > System > About` to check your system):

![1](https://user-images.githubusercontent.com/15380332/30520478-6b23ee2c-9bcc-11e7-8e98-e48fc61d55cf.png)

![2](https://user-images.githubusercontent.com/15380332/30520482-702ea902-9bcc-11e7-8c4d-f7aab10556d0.png)

**Comment by kjk** [comment]
This is now tracked by #1248
