### ISSUE TITLE
Printing blank pages

### ISSUE THREAD

**Issue by res87th** [sumatrapdfreader/sumatrapdf#625]
SumatraPDF versions newer 3.0 printing blank pages from text-containing or text-image-mixed PDF files. Image-containing PDF files printing normally. Version 3.0 printing any PDF files normally.

**Comment by kjk** [comment]
Please provide a sample PDF that shows the problem.

**Comment by res87th** [comment]
[PowerShot_SX530_HS_Camera_User_Guide_RU.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/499761/PowerShot_SX530_HS_Camera_User_Guide_RU.pdf)
I tryed to print first page from this file. Text is ciryllic. Printer - HP M2727 PCL6 and HP M1536 PCL6.

**Comment by a875210** [comment]
I also encountered the same problem,Only HP printer appear such circumstance.

**Comment by a875210** [comment]
Is in the case of print multiplay appear such problems

**Comment by achimt** [comment]
I am also running into this problem - with any pdf file that I am trying to print from sumatra that contains text. I am only using hp printers here, from a variety of different Windows operating systems. I can confirm that the problem turned up with versions after 3.0 (and is not fixed in 3.1.2 64-bit).

**Comment by GitHubRulesOK** [comment]
Closing as duplicated by https://github.com/sumatrapdfreader/sumatrapdf/issues/974#
