### ISSUE TITLE
SumatraPDF hangs when opening PDF files

### ISSUE THREAD

**Issue by kitschyboy** [sumatrapdfreader/sumatrapdf#635]
When SumatraPDF opens a PDF file, it hangs just after having opened the file, or tops a few seconds after.
I tryed with 32bit and 64bit versions, and of course I tried with different PDF files.

Attached is the debug result following instructions available on https://github.com/sumatrapdfreader/sumatrapdf/wiki/Debugging-Sumatra, with v3.1.2 32bit.

Thanks in advance for any help.
[sumatraPdf_hang_debug.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/525181/sumatraPdf_hang_debug.txt)

**Comment by kjk** [comment]
From the log it looks like Sumatra is blocked trying to open settings file. Most likely this is caused by one of the programs that I can see loaded their code in sumatra process and are likely to intercept file system calls (McAfee, DropBox, tortoise svn, RocketDock). It's possible un-installing one of them would fix the issue.

**Comment by kitschyboy** [comment]
Thanks for you reply. I would stop everything but McAfee (because it is controlled by IT) and I still have the hangs. Most likely it is an update in McAfee that causes the problem since it SumatraPDF worked without problem before.

**Comment by GitHubRulesOK** [comment]
@kjk 
since this is confined to one known case (at a historic point in time) and no-one has suggested they have similar issue I would suggest this issue be closed since it appears to be due to interference by an aggressive 3rd party app (just like a virus) and is thus outwith SumatraPDF control

**Comment by kjk** [comment]
agreed
