### ISSUE TITLE
ShowStartPage = false still shows stuff

### ISSUE THREAD

**Issue by ghost** [sumatrapdfreader/sumatrapdf#642]
Setting the above flag to false still shows the start page. Or at least a page with info on in.

Should be blank or better explained that ShowStartPage = false still shows you stuff.

**Comment by SumatraPeter** [comment]
With *ShowStartPage = false* it shows the same thing in the main window as the About dialog. Doesn't really bother me.

When you say "should be better explained", do you mean here: http://www.sumatrapdfreader.org/settings3.2.html?

>if true, we show a list of frequently read documents when no document is loaded
ShowStartPage = true

True, it doesn't explicitly say what happens if you set it to false, but is that really such a big issue? Anyway I guess a small note can easily be added by the devs if they feel like it.

**Comment by GitHubRulesOK** [comment]
Appears to be working as designed so closing as without active issues
