### ISSUE TITLE
Printing quality is poor

### ISSUE THREAD

**Issue by alekksander** [sumatrapdfreader/sumatrapdf#644]
Print quality is visibly worse than on other pdf viewers. 
example: 
hair thick lines comes out as dots instead of lines

**Comment by SumatraPeter** [comment]
Have you tried 3.0 with [Print as Image](https://github.com/sumatrapdfreader/sumatrapdf/issues/329) turned off?

**Comment by alekksander** [comment]
Just tried it. Result seems to be the same.

**Comment by gitfve** [comment]
I have same problem:
https://github.com/sumatrapdfreader/sumatrapdf/issues/636

**Comment by GitHubRulesOK** [comment]
@kjk I suggest this be consolidated with #636 and possibly others

For anyone coming to this later the suggestion is to try the latest portable pre-release first to see if there is an improvement in image handling then also try **3.0 portable WITHOUT** Print> Advanced tab compatibility setting of "Print as image" (which is the only default method in the more recent copies including pre-release). So test with that check box empty!

**Comment by wshaver** [comment]
Same issue here using latest 3.2 portable.  You can see the strange dots on my brand new Zebra ZT411 printer. These dots do not appear on-screen. They also don't appear when printing via alternate PDF printers. 

![dots](https://user-images.githubusercontent.com/786554/81875666-a60e9400-9535-11ea-8e03-0d067caa1fcc.jpg)

**Comment by GitHubRulesOK** [comment]
@wshaver 
Thanks for the picture it always says 1000 more than verbal description of "dots" which the OP said was the output for thinnest parts of barcode

semi random output such as yours suggest image is potentially conglomerating pixel clusters into artifacts but no idea why its happening in wave like groups, certainly it looks like it is a by-product of image rather than vector output, did you test 3.0 with image OFF

**Comment by wshaver** [comment]
@GitHubRulesOK  thanks for the quick reply!

I downloaded 3.0 portable binary. The dots moved into a strange pattern. I tried with both PrintAsImage true and false in that version. (Through the command line, and in the UI.) 

Printing the pdf via chrome looks great. Harder to see in the photos but the letters also have less "fuzz" on the edges when printed via chrome.  


Version 3:
![version 3](https://user-images.githubusercontent.com/786554/81876778-52ea1080-9538-11ea-9194-15fa4af14fe1.jpg)

Here's a difference between zoomed in, look at the side of the L in LB and you can see the "fuzz" I'm talking about. 
![version 3 zoomed in](https://user-images.githubusercontent.com/786554/81876863-82008200-9538-11ea-8d37-6c0a45fa46dd.jpg)

Chrome:
![chrome zoomed in](https://user-images.githubusercontent.com/786554/81876870-87f66300-9538-11ea-9e7d-d0366ad5c269.jpg)

**Comment by GitHubRulesOK** [comment]
Thanks for the close-ups my suspicion is that since thermal printers are monochrome i.e. heat ON or OFF and the rendering engine of SumatraPDF is MuPDF (which by default in SumatraPDF is set to Anti-Alias) its attempting to provide grey tone edges (or getting the steps wrong). Unfortunately I can't prove that since MuPDF-GL does not itself allow printing !? so no way to compare any settings. Some users appear to have had better results with their drivers, so possibly the drivers they are using are compensating for the B/W range better.

That still doesent explain the random patterns unless its attempting to add a very pale grey tone (which has been raised in the past, and is still an open issue with Artifex, who produce MuPDF and GhostScript) and in attempting to do so occasionally add 0.00## x X and eventually fire the head

**Comment by wshaver** [comment]
@GitHubRulesOK any way for me to swap out the rendering engine and test? 

I thought I'd add that we have 2 of this same printer, and it does it on both, so it isn't something wrong with the device. We'd been using Datamax printers for years with no issues. They're discontinued, and this Zebra model was the one that supposedly replaces it. It seems much less "industrial" in design, but it has a little light that comes on when you open the hood, so I've got that going for me.

**Comment by GitHubRulesOK** [comment]
If you search on keyword zebra in forum or this github list you should see the alternative suggestions for replacement drivers (seagull seems a word I remember) but I can't vouch for any of them making the difference.
I understand the attraction of using SumatraPDF for printing but have to admit this is one area where as a document viewer it is frequently weak for some other uses.

**Comment by GitHubRulesOK** [comment]
@wshaver 
on checking forum ther is a good discussion at https://forum.sumatrapdfreader.org/t/print-quality-dhl-label/1192

**Comment by wshaver** [comment]
Thanks for the help @GitHubRulesOK 

For others finding this entry I was able to get it to look great following the instructions here:
https://help.postmen.com/hc/en-us/articles/115010761748-Setup-Zebra-thermal-printer-on-Windows
(It was mentioned on the forum linked above.)

**Comment by GitHubRulesOK** [comment]
@kjk 
Overall the issues raised here and elsewhere for small format printers are most commonly resolved by changing the driver for monochrome thermal printers to a specialist one [Bartender Drivers by Seagull™](https://www.seagullscientific.com/support/downloads/drivers)
This suggests that any such similar printing quality "Issue" is resolved outside SumatraPDF and thus this thread be closed ?

**Comment by wshaver** [comment]
The only strange thing here is that some systems (chrome, PDF-XChange Viewer) print perfectly without adjusting settings. Certainly my issue is solved and I can continue using Sumatra. Thanks for your help.

**Comment by GitHubRulesOK** [comment]
Closing as most mono printers will work well when switched to a dedicated thermal printer driver.
