### ISSUE TITLE
Set 'RestoreSession' value from command line

### ISSUE THREAD

**Issue by Hubel** [sumatrapdfreader/sumatrapdf#67]
I use SumatraPDF as help viewer for CHM files from another application.
The help should be opened at a named destination and closed with Escape.

The command I use is:
`SumatraPDF.exe -esc-to-exit -nameddest 3000 chmtest.chm`
(see example file in #65)

By default the previous session is always restored in that scenario resulting in many tabs opened when only one is desired:
![image](https://cloud.githubusercontent.com/assets/10436633/5677973/95462e3a-97ed-11e4-8d3b-a156f5b02e8a.png)

I obtained the correct behavior when I manually changed the value for `RestoreSession` in the setting file from `auto` to `false`.
To control this behavior from my application I would like to set it via command line just like `-esc-to-exit`.

**Comment by zeniko** [comment]
FYI: -esc-to-exit has been deprecated and is scheduled for removal (cf. [command line arguments](https://github.com/sumatrapdfreader/sumatrapdf/wiki/Command-line-arguments#user-content-deprecated-options)).

Since -esc-to-exit and a hypothetical -restore-session permanently change the value in SumatraPDF-settings.txt, what's the reason you don't just manually change it once instead of setting it over and over again?

**Comment by Hubel** [comment]
The settings file can be modified or deleted.
Using the command line, I have more control and know that the actual settings are exactly as I want them.

Therefore I wouldn't want the command line arguments to permanently change the settings.
But in that case I think about rewriting the settings file before starting the viewer.

**Comment by GitHubRulesOK** [comment]
@kjk 
this old issue seems to be addressed by the -appdata option as described in https://github.com/sumatrapdfreader/sumatrapdf/issues/69
I suggest this issues requirements can be addressed (are closed?) by a user customised mix of per session command line settings

**Comment by kjk** [comment]
Closing as per suggestion.
