### ISSUE TITLE
scale down to A5

### ISSUE THREAD

**Issue by xuefer** [sumatrapdfreader/sumatrapdf#679]
http://download.p4c.philips.com/files/h/hx6730_02/hx6730_02_dfu_zhs.pdf
everything is set up to A4 but when printing it scale down to A4 size, printed in the middle/center of A4 paper

print using google chrome works just fine on exactly the same setting and same paper/printer

**Comment by GitHubRulesOK** [comment]
Tested given file it IS A5 pages so if I want to print to A4 I need to tell a print driver to enlarge the pages to FIT PAGE otherwise they print CORRECTLY as described 
e.g. using XPS printer I get three options

SHRINK A5 to printable A4  (NOTE  in this case A5 is placed in the page middle, as described)
FIT to printable = makes A5 larger e.g. A4 (THIS IS WHAT MOST USERS NEED)
Use original (SO the A5  in this case its placed top left corner of the A4) 

Class as NOT a bug (feature required is inform user they need to check thier choice of printer settings)
