### ISSUE TITLE
Print problem on XEROX printer 7835 using ver 3.1.2, downgraded to SumatraPDF ver 3.0 - it works.

### ISSUE THREAD

**Issue by ennist** [sumatrapdfreader/sumatrapdf#685]
Experienced problems with SumatraPDF version 3.1.2 (64 bit) on a XEROX Workcenter 7835 printer.  Printed pages were showing partial lines of printed text (the top part of an entire line of text would be missing). Using a HP Laser printer, however - worked just fine.

I saw a suggestion of using version 3.0 - and I tried that.   That worked.  No print issues!

**Comment by termoco** [comment]
Same issue - Same resolution on multiple machines.

**Comment by mikeri** [comment]
Same issue here as well. This seems to be because Print as Image is always enabled in 3.1+. If you enable Print as Image in 3.0, you'll get the same issue.

Also, if you use the Xerox Class driver the problem does not occur. The problem occurs with official Xerox drivers on many different devices, including 722x, 78xx, 7970 ++.

Any possibility if re enabling the Print as Image option and leaving it on as default, so users can disable it in case of problems? With large documents (small file size and many pages), Print as Image can slow down printing considerably on some printers.

**Comment by bigben386** [comment]
Thanks for the heads up that this does not affect 3.0. We were getting ready to deploy 3.1.2 across our company before we discovered that the prints came out blank on all our Xerox printers. 3.0 has been working fine.

**Comment by AxelFP** [comment]
Same problem here.
3.1.2 gives randomly half lines, 3.0 prints perfectly, 3.0 with print as image gives half lines again.
I'm using a Sharp MX-2610N with a SHARP UD2 PCL6 driver

**Comment by flying-stranger** [comment]
Same problem here.
Xerox 6655.

**Comment by bigben386** [comment]
While 3.0 initially seemed to fix our pdf print problems, we experienced low print quality and layout problems with this version. We had to abandon our plans to switch to Sumatra and went back to Adobe Reader.

**Comment by GitHubRulesOK** [comment]
@kjk dupe / consolidate with https://github.com/sumatrapdfreader/sumatrapdf/issues/919
