### ISSUE TITLE
Handle images better in epub

### ISSUE THREAD

**Issue by whirlwind314** [sumatrapdfreader/sumatrapdf#696]
Hi. Could you please consider an option to scale images for epub reading mode. For particular monitor settings the default scaling maybe too tough to use. Thanks & regards.

P.S. One more thing ... perhaps it has a sense to have a donation page somewhere at your product page (allowing paypal or something else).

**Comment by SumatraPeter** [comment]
First step would be to fix #1120 so that images are displayed at the proper pixel or percentage size specified in an EPUB. After that can look into scaling if required at higher resolutions.

**Comment by GitHubRulesOK** [comment]
@SumatraPeter the epub 3.2 scaling section is a confusion of calculations that aknowledge default 72pt=96dpi as a core value then obscure it for a multitude of readers units eg 1Q=1/4 mm etc.
SumatraPDF old epub1 engine looks likely to be changed soon but would rely on MuPDF epub support which as we know does not support tables and lacks some other epub3 features!!

**Comment by SumatraPeter** [comment]
@GitHubRulesOK: Yup, the update to MuPDF's EPUB engine ought to fix the scaling issue (#1120) at least, as far as we can tell from our test files. Of course we'll have to check with all sorts of EPUBs to see what new issues crop up!

@kjk: 3.2.1 seems too soon due to the amount of work involved, so I guess the EPUB engine switch is planned for 3.3?

**Comment by kjk** [comment]
We've updated epub rendering engine so this might be fixed.

If not, we need a test file that shows the problem.
