### ISSUE TITLE
Too fast scrolling when using touchpad.

### ISSUE THREAD

**Issue by webholik** [sumatrapdfreader/sumatrapdf#725]
So I have a Lenovo B40 laptop with ELAN touchpad (Windows 10) and scrolling works way too fast than what it should. A small movement on the touchpad scrolls multiple pages at a time and I have to keep on reminding myself not to use the touchpad for scrolling which is a hard habit to break. Is there a way to change this behaviour?

**Comment by pdgessler** [comment]
In the menu bar, select View -> Show pages continuously, that should do the trick if I understand correctly.

**Comment by kjk** [comment]
Scrolling speed varies depending on driver and user settings, so changing it so that it fits user A will break user B.

As @pdgessler said, you're most likely not using the right view mode. In non-contiguous mode, you navigate page by page and you can use e.g space to advance and backspace to go backwards. It's not scrolling. For scrolling use contiguous mode.
