### ISSUE TITLE
Printing issues with paper bin in command line

### ISSUE THREAD

**Issue by matgho** [sumatrapdfreader/sumatrapdf#728]
For information :
Two bugs in print.cpp GetPaperSourceByName function
1)  this line :
 // alternatively allow indicating the paper bin directly by number
    if (str::Parse(L"%u%$", name, &count))
    Does not work  it should be :       if (str::Parse( name, L"%u%$",&count))
2) PrinterName length >31 crash the app (using paper bin)
devMode->dmDeviceName  is limited to 31 char ,  function DeviceCapabilities crash 

Cordialy,

**Comment by kjk** [comment]
Good catch, thanks.

I've fixed 1.

I'm not sure I understand 2 or how to fix it. DeviceCapabilities() is a Windows function and Sumatra code never touches devMode->dmDeviceName. I find it hard to believe that DeviceCapabilities() would just crash. Also, why is this related to paper bin.

Or, to say, differently: can you describe the steps needed to cause the crash?

**Comment by matgho** [comment]
Ok for example : -print-settings bin=2 -print-to "printer on the first floor second door" crash
Because printer name >31 and devMode->dmDeviceName can content only 31 chars.
devMode->dmDeviceName return "printer on the first floor second " then can not be use in  DeviceCapabilities because this printer does not exist . 
Thanks.

**Comment by kjk** [comment]
Fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/8c9d42efe305052f5dd4dc73bb93987dab13fe70

The issue was that because the name of printer in devMode can be truncated, we have to use the full, un-truncated name.

Using truncated name would cause DeviceCapabilities() to fail we were handling the failure incorrectly and as a result trying to allocate too much memory, which resulted in a crash.
