### ISSUE TITLE
Option to copy or display hyperlink on pdf

### ISSUE THREAD

**Issue by lzutao** [sumatrapdfreader/sumatrapdf#738]
Everytime I need to know *what page* the hyperlink goes, I need to remember present page and click to this link. Please add an option to display or copy link in the shortcut menu.

Even though, Sumatra PDF is great.

**Comment by GitHubRulesOK** [comment]
@lzutao 
I guess you have already discovered the following, since you have now closed this issue.
however for others looking in the future for an answer, IF the hyperlink is correctly formed you can hover and right click as per this screen shot.
![untitled](https://user-images.githubusercontent.com/12754913/42661236-1ca211c0-861d-11e8-9202-3faa94a37470.png)
What may not be so obvious is that even if a PDF does not have bookmarks, you can save your own Favourites to navigate backwards and forwards to given pages. (look on the left side of the screenshot)   see how I can easily jump back to the index on page 2 or where I also saved a favourite to where I was reading page 10, it does not need to take much time if you use and overwrite short hints like "indx" and  "last"
