### ISSUE TITLE
What is the syntax for adding user-defined keyboard shortcut to trigger external viewers

### ISSUE THREAD

**Issue by llinfeng** [sumatrapdfreader/sumatrapdf#777]
## User case:

According to the documentation for the Advanced setting, as of: http://www.sumatrapdfreader.org/settings3.1.html, the following settings are opening up my external editors fluently. The file in the Sumatra session should also be automatically loaded in the new "Viewer" session. Nice job!
```

ExternalViewers [
	[
		CommandLine = "c:\Program Files (x86)\ABBYY FineReader 12\FineReader.exe"
		Name = "ABBYY"
	]
	[
		CommandLine = "C:\Program Files (x86)\Adobe\Acrobat 11.0\Acrobat\Acrobat.exe"
		Name = "Adobe"
	]
]

```

## More over: menu shortcut are possible through `&`
Doing the following small adjustment to the `Name` shall create a "Menu-shortcut", where ABBYY could not be triggered through pressing `Y` when I have activated the File menu-item.

* The setting: `Name = "ABBY&Y"` ==> Featuring the magical `&`!
* The outcome:
![goodmenushortcut](https://cloud.githubusercontent.com/assets/5890407/24884685/96319f9c-1e18-11e7-93ae-ecc694d06967.png)

## Request: how to trigger these External Viewers through REAL Shortcuts?
I would like to trigger these external Viewers through a keyboard shortcut, especially for the ABBYY Findreader. (This software is reasonably good at OCR, but really lacks command-line support. So, the best way I can think of is to implement a shortcut for triggering it as an external viewer through  Sumatra.

**Comment by kjk** [comment]
Currently there's no way to achieve that. We would have to parse out accelerator key from menu text and register it with the corresponding command id.

**Comment by pxf123** [comment]
I tried to set external editors like you, but it didn't work
I know Sumatra can auto-detect, but I want to add one to have a try. However it failed.
In fact, the first that Sumatra auto-detect can work, the others that I add can't.
Don't know where is wrong ?
```
ExternalViewers [
[
		CommandLine = "‪D:\Adobe Family\Adobe Acrobat Pro DC\Acrobat\Acrobat.exe"
		Name = Acrobat
	]
	[
		CommandLine = "‪C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe"
		Name = dege
	]	
]
```
![sumatra eternal editor problem_2019-03-02_14-54-03](https://user-images.githubusercontent.com/40738817/53678531-4397f200-3cfb-11e9-9d10-faee9545cea0.png)

**Comment by llinfeng** [comment]
@pxf123 You need to wrap the names in quotation marks (双引号/单引号). Here goes the settings that I am using.

```
ExternalViewers [
	[
		CommandLine = "c:\Program Files (x86)\ABBYY FineReader 12\FineReader.exe"
		Name = "ABBY&Y"
	]
	[
		CommandLine = "C:\Program Files (x86)\PDF Annotator\PDFAnnotator.exe"
		Name = "Anno&Tator"
	]
	[
		CommandLine = "C:\Program Files (x86)\Microsoft Office\root\Office16\WINWORD.EXE"
		Name = "&Word"
	]
]
```

**Comment by GitHubRulesOK** [comment]
Your grouping appears wrong as you show three in the menu but only two in your snip from the settings file. 

On the basis you simply did not include the working one

the first example acrobat.exe should work IF the location and filename are correct
that is SumatraPDF shows no errors if you make a mistake in spelling or position
also note from the instructions that there is **usually** a third line
per application that is used to filter the file types (Filter = *.*)

the second dege ? is unlikely to work as that is called like a windows store application 
and for security reasons are exceptionally difficult to address externally
so you need to find a syntax similar to how they are easily opened from a shortcut

**Comment by pxf123** [comment]
@GitHubRulesOK the working one is add by auto-detect and we can ignore the filter if you don't need.
I think the location and filename are correct. **But I add that again**. Amazing, **It works ! ! !**
```
ExternalViewers [
	[
		CommandLine = "D:\Adobe Family\Adobe Acrobat Pro DC\Acrobat\Acrobat.exe"
		Name = Acrobat
	]
	[
		CommandLine = "‪D:\Adobe Family\Adobe Acrobat Pro DC\Acrobat\Acrobat.exe"
		Name = Acrobat
		
	]
]
```
**the first one can work, but the second one don't work. I don't know how different these two are.**
I tried to add internet explore, and it can work. Added firefox too, it can't work.Thanks for your reminder.
### ---------------------------------------------------------
@llinfeng It can work without quotation marks.

**Comment by GitHubRulesOK** [comment]
As far as I know firefox, chrome etc should work with some entries I can open a website or a local pdf in firefox using
		CommandLine = "D:\FirefoxPortable\FirefoxPortable.exe"
		Name = Firefox

But it should also work with the non portable version
Its only Edge that's a known problem because of Microsoft security policies you can search for ways to add a favourite web site (even one with a pdf) but I have not seen current ways to open a file on the system !

Back to your issue I can only think there is some interference from a tab or space character what happens if you cut and paste the working one onto the non working one?

**Comment by pxf123** [comment]
@GitHubRulesOK May it's the problem of coding.
```
"D:\Adobe Family\Adobe Acrobat Pro DC\Acrobat\Acrobat.exe"

"‪D:\Adobe Family\Adobe Acrobat Pro DC\Acrobat\Acrobat.exe"
```
thanks.

**Comment by GitHubRulesOK** [comment]
acrobat reader is often found as
 `AcroRd32.exe`
 if you check in the folder what the exe filename is it should help

**Comment by GitHubRulesOK** [comment]
@kjk I consider this issue could be closed as a user CAN (with valid entries) specify their own "accelerator / shortcut" as Alt F + **something not already used**

**Comment by GitHubRulesOK** [comment]
Just an update that you CAN call Edge via one of many older helper.exe's to add highlights and comments.
However since it circumvents the fact that Edge security removed some of those older methods
I will simply say it is still possible as seen here.
![image](https://user-images.githubusercontent.com/12754913/72491210-43b8b780-3811-11ea-86a0-6abc90533334.png)

**Comment by GitHubRulesOK** [comment]
I am closing this thread as I have had no problem running a dozen ExternalViewer commands when correctly structured. (note the working limit is max of 10 visible)

From the discussions above points to beware of are 

As shown above beware more than command using the same shortcut 
You could use R for reader but it is already assigned to p**R**operties whereas A is not assigned

```
	[
		CommandLine = "C:\Reader 9.0\Reader\AcroRd32.exe" /A page=%p "%1"
		Name = &Acrobat Reader for 3D Animations
		Filter = *.pdf
	]
```

Note the .exe should be a "full absolute path" (no %path% since SumatraPDF will check and only run IF it is valid)
All parameters should generally be as expected by the apps command line and currently only two variables are allowed as shown %p = page number "%1" = full path to current file choose your "&" wisely the example as shown will work ONLY in a .pdf (**filter**) using <kbd>Alt</kbd>+<kbd>F</kbd>+<kbd>A</kbd>

**Comment by GitHubRulesOK** [comment]
**Just an update to the comments above about edge which is now chromium based and easier to access**

The command to open the current html or pdf page in edGe for highlighting / read aloud is now

```
ExternalViewers [
	[
		CommandLine = "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" file://"%1#page=%p"
		Name = Ed&ge
		Filter = *.htm;*.html;*.pdf
	]
]
```
in this case I have set the shortcut to <kbd>Alt</kbd>+<kbd>F</kbd>+<kbd>G</kbd>
