### ISSUE TITLE
Can't open file in "Run as Administrator"

### ISSUE THREAD

**Issue by jiangpeng311** [sumatrapdfreader/sumatrapdf#78]
If *ReuseInstance* is true, running sumatrapdf as administrator, can't open file by double click in explorer.exe.

**Comment by kjk** [comment]
I'm not sure if it's even possible to change. And probably shouldn't.

If you double-click, you simply start a new (non-admin) Sumatra process. With ReuseInstance, it tries to find existing instance and send the file to it.

But since existing instance is running in admin mode, the non-admin instance shouldn't be able to talk to it due to security.
