### ISSUE TITLE
hang on windows 7

### ISSUE THREAD

**Issue by AladW** [sumatrapdfreader/sumatrapdf#802]
When having several djvu and pdf files open in SumatraPDF 3.1.2 (X64), the program will hang sporadically while using ~25% CPU. 

Report from https://github.com/sumatrapdfreader/sumatrapdf/wiki/Debugging-Sumatra#debugging-a-hang using WinDbg (X64, W8.1 SDK) and http://s3.amazonaws.com/kjkpub/sumatrapdf/rel/SumatraPDF-3.1.2.pdb.zip

https://gist.github.com/AladW/2271bc21a9cfbe415df9d7628c9b5c4f

**Comment by GitHubRulesOK** [comment]
@kjk 
legacy report from 3,1.2 any feedback !

**Comment by kjk** [comment]
The attached log https://gist.github.com/AladW/2271bc21a9cfbe415df9d7628c9b5c4f doesn't show any spinning. Sumatra is in windows message loop.

There's not enough information to go on.

**Comment by AladW** [comment]
Might as well tell me how to get "enough information" rather than close 
the bug with some vague reason.

Am 29/02/2020 um 10:11 schrieb Krzysztof Kowalczyk:

**Comment by GitHubRulesOK** [comment]
@AladW 
I can often be wrong but am guessing that the dbg report does not identify a clear cause.
Can I suggest you try a similar group of files with a recent pre-release version since there could potentially better insight into any induced crash situation. However a **hang** may not normally generate a feedback report and it may require you looking closer at other processes that seem to show signs of increased activity such as Anti-virus etc.
Another cause for such interference is location of files e.g. they may not hang when local but can when cloud based ?
