### ISSUE TITLE
stop using GDI+ for printing PDF/XPS documents

### ISSUE THREAD

**Issue by zeniko** [sumatrapdfreader/sumatrapdf#81]
The GDI+ printing code still doesn't get all the edge cases right (see [printing issues in Google Code](https://code.google.com/p/sumatrapdf/issues/list?q=label:Printing) and [github](https://github.com/sumatrapdfreader/sumatrapdf/labels/printing)). The recommendation to users with such issues has so far always been to use "Print as image" instead - and would likely remain so at the current pace of development.

In order to improve the default printing experience (at the cost of higher resource usage), I'd like to remove the GDI+ printing (and no longer needed "Print as image") code instead of dragging it along any further. Any reason not to?

**Comment by kjk** [comment]
Sounds good to me.

**Comment by MikhaelB** [comment]
Hi All!

Printing PDF files on network printers is very slow in "Print as image" mode. Using "gdiplus-device.cpp" ability made printing PDF files on network printers usable for people who print dozens of documents every day.

Because of this I am sure, that printing PDF files in vector mode is really must-have feature in Sumatra PDF Reader!

**Comment by reyaz006** [comment]
Agreed. With "Print as image", network usage is pretty much impossible. I hope alternative mode will get more attention in future.

**Comment by dajo** [comment]
I second that, @reyaz006. Thank you.

**Comment by ChristophWiesmeyr** [comment]
Are there any updates on that? Is it possible to manually switch between the two printing modes? Right now the printing is not only painfully slow but also the printing quality is inferior compared to Adobe.
