### ISSUE TITLE
extra preview handlers don't compile

### ISSUE THREAD

**Issue by ianamk** [sumatrapdfreader/sumatrapdf#810]
the comic and mobile format preview handlers seam to be broken
this happened with the move from the makefile to the project file
in this revision
https://github.com/sumatrapdfreader/sumatrapdf/tree/rel3.1working
all preview handlers compile and work fine (not just cb(x) but epub mobi fb2 etc)
all that is needed for them to compile is a few nmake switches
https://github.com/sumatrapdfreader/sumatrapdf/blob/rel3.1working/makefile.msvc#L270
with the current revision svn 10717 or git 9717
when I add 
```
#define BUILD_CBZ_PREVIEW
#define BUILD_CBR_PREVIEW
```
to \sumatrapdf\src\utils\BuildConfig.h
I get build errors
` LNK2001 unresolved external symbol "class BaseEngine * __cdecl CbxEngine::CreateFromStream(struct IStream *)" (?CreateFromStream@CbxEngine@@YAPAVBaseEngine@@PAUIStream@@@Z) PdfPreview C:\sumatrapdf\vs2015\PdfPreview.obj 1`
I believe some source files are missing from the project

**Comment by kjk** [comment]
Yeah, we changed the build system from makefile.msvc to premake (https://www.sumatrapdfreader.org/docs/Our-build-system-3114db56b1a54b9bb026da6b92d36a80.html) and it's not at parity. You would have to add necessary files to premake5.files.lua.

I have no plans to support this configuration in official build because this kind of configurability doesn't fit well with premake.
