### ISSUE TITLE
Images in CHM file are not displayed

### ISSUE THREAD

**Issue by Hubel** [sumatrapdfreader/sumatrapdf#82]
The supplier of our user manual uses *COSIMA go!* to create CHM files.
After upgrading to a newer version, SumatraPDF cannot display the images correctly which worked fine in the previous version. Now it renders a little cross instead:
![image](https://cloud.githubusercontent.com/assets/10436633/6019952/4b328646-aba6-11e4-9817-16f4e3ef58ac.png)

I cannot tell the difference in the format. Both version use PNG images.
However, the default Windows tool *HTML Help Control* displays both versions of the file correctly.

I'll send the manual CHM file to you via e-mail.

**Comment by zeniko** [comment]
Thanks for the report and the document. The reason your document doesn't display as expected is that it uses malformed URLs for the images: they use the backslash \ as path separator instead of the expected forward slash /. Microsoft HTML Help tolerates such "broken" URLs, as the backslash is the default path separator under Windows. As of the next version, SumatraPDF will tolerate them as well for consistency and should (once again since version 1.9) be able to render such documents as desired.

**Comment by Hubel** [comment]
Tested - working fine. Thanks a lot!
