### ISSUE TITLE
new shortcuts for expand-all / collapse-all needed

### ISSUE THREAD

**Issue by jmfranck** [sumatrapdfreader/sumatrapdf#83]
The numeric keypad shortcuts for expand-all and collapse-all for the bookmarks simply do not work on many newer laptops that  no longer have any numeric keypad support.  For instance, newer Lenovo models have no numeric keypad without an external device.

Previously, someone had posted this as an issue, but was asking for a new button.  This is not needed.  All that's needed is **a new (additional) shortcut that does not require a numeric keypad**.

**Comment by kjk** [comment]
What do other applications do for that?

**Comment by jmfranck** [comment]
Honestly, I have done some searching, and it seems like the expand-all collapse-all shortcuts are not that common or consistent.  But, here it really would be very beneficial, since bookmarks can be so helpful for navigating a large PDF  (unless there is some other way to collapse-all that I'm not aware of).

Cntrl-* or * does seem to pretty routinely offer "expand-all."  Perhaps "-" or Cntrl--?

Of course, a context menu could provide the same functionality, but that seems much harder than just adding a shortcut.

Many thanks for such great software whatever you decide to do!

Date: Wed, 4 Feb 2015 10:53:53 -0800

**Comment by Superbest** [comment]
Bit of a tangent, but I wanted to add: These shortcuts are very poorly documented! I came here intending to submit a feature request, since I looked in all the menus and couldn't find it.

There is a 4 year old feature request regarding this on the old GCode repo: https://code.google.com/p/sumatrapdf/issues/detail?id=1632

zeniko replied:
>We might however consider adding a context menu to items in the bookmark tree for that end.

So why not add it to one of the menus, maybe under "View" after the "Bookmarks" option, since it's something related to bookmarks? We can display the shortcut there as well, and this way non-expert users can easily become aware of the sometimes very useful feature.

In the same issue thread, [it was also noted](https://code.google.com/p/sumatrapdf/issues/detail?id=1632#c4) that the manual is missing these shortcut keys - looks like this is also still not fixed. I was only able to find what the shortcut is by googling and arriving at the old GCode issue thread, where somebody mentioned it.

**Comment by GitHubRulesOK** [comment]
@kjjk whilst you are updating manual page keybindings :-)

it would be worth adding these comments i.e.

"please use the '*' and '/' keys on your numeric keypad for expanding/collapsing all nodes below the current one (these are default shortcuts that also work in trees elsewhere, such as Windows Explorer's folder tree)"
Also whilst in the tree [focus using F6] the right and left arrows will also expand and contract one level at a time.

**Comment by GitHubRulesOK** [comment]
@kjk closed by latest web site and application enhancements
