### ISSUE TITLE
Ø (LATIN CAPITAL LETTER O WITH STROKE) doesn't appear

### ISSUE THREAD

**Issue by mikemorr** [sumatrapdfreader/sumatrapdf#86]
In this PDF: http://www.jazzbooks.com/mm5/download/FREE-nomenclature.pdf
the character Ø (U+00D8, LATIN CAPITAL LETTER O WITH STROKE) doesn't appear in SumatraPDF 3.0 on 64-bit Vista Home Premium. Same issue occurs in Mozilla's pdf.js (see https://github.com/mozilla/pdf.js/issues/5704 ), but not in Adobe Reader. Screenshots from SumatraPDF and Adobe Reader:
![sumatrapdf](https://cloud.githubusercontent.com/assets/2184268/6082855/449254f8-adf2-11e4-9dc5-639ede5f883d.PNG)
![adobereadervista](https://cloud.githubusercontent.com/assets/2184268/6082856/46f4940e-adf2-11e4-8794-c88ad1de1325.PNG)

**Comment by zeniko** [comment]
Thanks for the report and the link to pdf.js' bug tracker. This issue seems to happen due to a confusion about whether the font is a Mac or Windows font (contains a MacRoman cmap but is WinAnsi encoded). I'm not quite sure whether the applied fix is correct, but it works well enough, passes all tests and even fixed a different issue we've been having for quite some time. So version 3.1 should render your document as expected.
