### ISSUE TITLE
Support Fiction Book extensions

### ISSUE THREAD

**Issue by Skif-off** [sumatrapdfreader/sumatrapdf#870]
Now SumatraPDF "knows" extensions `*.fb2`, `*.fb2z`, `*.zfb2`, `*.fb2.zip`.
Can you add `*.fbz` (like `*.fb2.zip`, but short as 8.3 standart)?

**Comment by VictorVG** [comment]
Well, then it makes sense to extend the sentence to:
 
_If the first characters of the container file contain a signature of the format RAR (Rar!), 7-Zip (7z) {if possible} or Zip (PK), when opening such a file, call the appropriate unpacker to determine that this file is an archive and, in the case of a positive response unpack it and after the unpacking process continue processing in accordance with the format._
 
such a solution will allow working with CBR/CBZ, FBZ containers regardless of the packing method.

**Comment by GitHubRulesOK** [comment]
@kjk whilst there are some merits in VictorVGs suggestion it is prone to problems as there are unfortunatly thousands of different file formats/archives based on those "magic" headers.

I suggest the OP request is valid and should be simple to include since .fbz is used as a common 8.3 extension see https://en.wikipedia.org/wiki/FictionBook
