### ISSUE TITLE
SumatraPDF prerelease: bug: incorrect position info (M hotkey) in FixedUI .epub

### ISSUE THREAD

**Issue by nod5** [sumatrapdfreader/sumatrapdf#884]
Tested in SumatraPDF prerelease version , SumatraPDF-prerelease-10740-install.exe from 2017-07-14 Win10

Settings used: advanced settings > EbookUI > UseFixedPageUI = true

**Steps to reproduce:**
1. Open any .epub
2. Press M until the cursor position information is shown in pt
3. Select some text and note the x and y pt values
4. Press H to highlight
5. Press control+S and save with the default filename given in the save dialog.
6. Open file.epub.smx in a text editor and scroll to the last saved highlight (at the bottom of the file).

**Expected effect:** the two first values for "rect = " should be the same (after rounding) as the position pt values from step 3

**Actual effect:** the rect values are higher, in my tests always by a ratio of approximately 1.346364632809646

I discovered this when my [sumatra_highlight_helper](https://github.com/nod5/sumatra_highlight_helper) failed to reliably delete highlights in .epub files.

**Comment by GitHubRulesOK** [comment]
@nod5 
I think you will find this is due to .pub is generally 96 dpi and .pdf is usually counted as 72 dpi
thus with some positional error the figure you want is 4/3 =1.33333333333333333
you could simply look at extensions and allowing for adding others on a peruser basis such a .djvu  or .tiff which may be any dpi provide a pair of variable entries say up to 99 / 99 for scaling current file so user in this case would need to see default of  04 / 03  or 96 / 72 and let AHK do the math

**Comment by GitHubRulesOK** [comment]
@nod5 
I guess on this issue you are by now aware the highlight will be in the "wrong" place when user changes font or font size as .epub is allowed to "reflow" based on font EVEN IF UseFixed=true
thus it is more important they can adjust position on page based on font scalar so may need one for horizontal and one for vertical However you cannot be expected to "roll" highlights from page to page so it would go "pear shaped" from page two onwards. Best you "highlight" your helper cannot work in such cases.

**Comment by nod5** [comment]
@GitHubRulesOK 

> I think you will find this is due to .pub is generally 96 dpi and .pdf is usually counted as 72 dpi
> thus with some positional error the figure you want is 4/3 =1.33333333333333333

Right, I can work around the bug by multiplying the x y pt values from SumatraPDF with 4/3 to get numbers that match those in the .epub.smx  . I've only tried it on a few .epub though. Could some other .epub files require another ratio? Or is the 96 dpi for .epub here rather something hardwired in SumatraPDF?

> highlight will be in the "wrong" place when user changes font or font size ...  your helper cannot work in such cases

Agree. I can warn about that big limitation in the sumatra_highlight_helper readme though. 

Maybe also possible: each highlight added to an .epub.smx could also add a metadata line with the font settings when the highlight was made. A script could then later feasibly restore the correct highlight positions by restoring the original font settings.

**Comment by GitHubRulesOK** [comment]
the 96 is coded in SumatraPDF code based on file type you could look for that value but there is another scalar of 0.8 applied to fonts that  may or may not have a bearing on .epub
Your idea to keep a font name and size is a good one since that should allow for some redress when users grumble it went wrong, as long as you don't overwrite first font details with current font details  :-)

**Comment by GitHubRulesOK** [comment]
I am closing as a legacy issue in SMX files (now depreciated)
