### ISSUE TITLE
Feature Request: Force PortableMode (Low Priority)

### ISSUE THREAD

**Issue by zinthose** [sumatrapdfreader/sumatrapdf#92]
I have am using SumatraPDF within a small utility I created and it works great until I created an installer and there for placing it in the %PROGRAMSFILES% path thus the IsRunningInPortableMode at https://github.com/sumatrapdfreader/sumatrapdf/blob/a74e512e953130a10fd3a4f4e9cd86e24cdd267b/src/AppTools.cpp#L43 is indicating the software is "installed" and no longer portable.  

As a workaround now I am modifying the SumatraPDF-settings.txt in the "%APPDATA%\Sumatra" path but ideally I'd prefer the utility to not interfere with the users defined settings if they have Sumatra previously installed.

Maybe add a command line parameter to allow for forced portable mode or even allow for specifying the SumatraPDF-settings.txt file.

Should be a simple fix.  If I get time, I'll see if I can submit a commit that dose this, but for now.  I wanted to get the issue submitted for tracking at the very l;east.

**Comment by zeniko** [comment]
This will be possible in the next release: you can set the path to the folder where the settings are stored through the -appdata command line flag, so that you could change the shortcut to

"%PROGRAMFILES%\SumatraPDF\SumatraPDF.exe" -appdata "%PROGRAMFILES%\SumatraPDF"

This option was added in issue #69.
