### ISSUE TITLE
Render Fails on device reconnect

### ISSUE THREAD

**Issue by MagikEh** [sumatrapdfreader/sumatrapdf#922]
I have found that when I disconnect my dock from my tablet (the dock being an external USB 3.0 drive keyboard whatchamajigger) the pdf that I had open in Sumatra will remain open but all pages that haven't been seen will fail to render.

1) Open PDF stored on removable media with more than one page in Sumatra
2)Disconnect and reconnect media
3)Attempt to scroll to new (previously unseen) pages in Sumatra.

Testing with a textbook's PDF on an Asus Transformer T100ta

Possible Resolve;
-Downright close pdf's that have been removed from the system file tree
-Rebuild file tree for open documents on affected paths when devices are reconnected

Current workaround:
-Close and re-open the current document.

Attempted Fixes:
-Updated Sumatra to the 3.2.10740pre (Bug was present in v.3.12)
-Change view to/from continuous/single page/book/double/presentation/fullscreen
-Couldn't get it to work with file sizes less than 750 Mb (4 pages). Assuming it has to do with the cache.

**Comment by GitHubRulesOK** [comment]
@kjk 
I know you did some changes related to cutting the branch underfoot,  (and I have caused you many a crash)
but I fail to see how SumatraPDF can decide a file that is in effect temporarily inaccessible due to Internet brownout or swapping out a drive could be allowed for (unless you always close files after a reasonable time-out like say 30 seconds?)

Only the user knows the reason may be they are externally recompiling (rebuild/printing) PDF or its a flaky USB, and in those cases need a longer time-out (like GS/PS infinite wait flag) before closing a non responding missing document.

Recommend closure  as an _expected_ sort of windows system based non-issue?

**Comment by kjk** [comment]
We increased the threshold of PDF size to load the whole file in memory, so this should happen less often.

As to how to handle if it's not fully loaded and the file goes away, current behavior of not rendering a page seems fine to me. Don't see how closing a document is better.
