### ISSUE TITLE
Inverse-search go to specific position or word on line. Feature Request

### ISSUE THREAD

**Issue by skanskan** [sumatrapdfreader/sumatrapdf#928]
Hello.

In addition to the -inverse-search command-line option  %l for the current line in would be great to also have an option to be able to go to a specific position (or word) in that line.

That would be useful when using the inverse-search while compiling latex documents with long lines of text.

**Comment by GitHubRulesOK** [comment]
@kjk 
In part this is dictated by synctex behaviour and **even if** using any hinting enhancements from version 2 or even attempting to re-introduce the experimental %c(olumn) value it would be of infintesimal value since each editor would most likely need a different approach.
Some editors generate a highly precice.synctex file and others don't 
There are some LaTeX editors that use their own methods without synctex for character by character matching and it would be difficult to "please all of the editors all of the time."

I suggest this issue be consolidated **along with #1098** using #841 as the master issue

**Comment by GitHubRulesOK** [comment]
Duplicated by Inverse search: column number is not filled correctly #1098 and consolidated under https://github.com/sumatrapdfreader/sumatrapdf/issues/841
