### ISSUE TITLE
printing problem

### ISSUE THREAD

**Issue by swgith** [sumatrapdfreader/sumatrapdf#932]
Hello,

it's a while I use Sumatra and I'm rather satisfied with it.
Anyway two days ago I'v found couple of problem, printing and they both disappear using Acrobat Reader (that I wouldn't want to use).

1) I try to print multiple pdf files (by selecting them and then right click -> print) on a HP OfficeJet Pro 8720,
no matter what I try to print, it works for two files and on the third printing stop.
Using Acrobat I can print 12 files with no problem (same files of course).

2) trying to print a barcode label on a Dymo LabelWriter 400 I got a problem.
The label is attached here - Etichette_Ordine_OA1013036.pdf
when I open it I see it horizontally but it is printed in the wrong way.
I've tried to change the view but same print.
I've tried to modify the page print on the printer preferences from portrait to landscape but same print.

Printing it with Acrobat give the correct print without changing anything.

Hope you can resolve it.
Thanks
Flaviano
[Etichette_Ordine_OA1013036.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/1503438/Etichette_Ordine_OA1013036.pdf)

**Comment by GitHubRulesOK** [comment]
I am going to exclude issue 1. above since using right click print blind is not recommended. There is little means to control print method or options, as it is Windows that decides where the print goes. So if the files are images Windows would usually use Paint to print them blind. It is possible that if they are PDF then Windows may shove them through SumatraPDF but there would be little or no control.

Dymo Label printing is often an issue so I am consolidating this as a duplicated issue with https://github.com/sumatrapdfreader/sumatrapdf/issues/972#
