### ISSUE TITLE
Documentation outdated for  Customizeing external viewers

### ISSUE THREAD

**Issue by redstoneleo** [sumatrapdfreader/sumatrapdf#958]
https://www.sumatrapdfreader.org/docs/Customize-external-viewers.html
According to the CommandLine argument format specified in the Documentation, I set 
`CommandLine ="C:\Program Files\Foxit Software\Foxit Reader\FoxitReader.exe"  "%1" %p`
but didn't work, after changed to  
`CommandLine ="C:\Program Files\Foxit Software\Foxit Reader\FoxitReader.exe" /A page=%p %1`
 Works !
So maybe the Documentation is outdated, please update !
BTW, a working setting sample as following 
```
ExternalViewers [
 [
 CommandLine ="C:\Program Files\Foxit Software\Foxit Reader\FoxitReader.exe" /A page=%p %1
 Name =Foxit
 Filter = *.pdf
 ]
]
```

**Comment by SumatraPeter** [comment]
The documentation is generic and simply mentions that you can use **%1** for the file path with optionally **%p** for the page if the external viewer sport supports it, so there's absolutely nothing wrong or outdated about it.

Just because Foxit in particular [requires](https://help.foxitsoftware.com/kb/how-to-open-a-file-to-specific-page-via-command-line.php) **/A page=** for **%p** doesn't mean _every_ viewer works the same way.

**Comment by redstoneleo** [comment]
I think it would be better to provide some examples about adding external viewers for sumatrapdf in the documentation .
BTW,  ` /A page= for %p` is not specific to Foxit , but also works for Adobe reader , PDF-XChange Viewer , PDF-XChange Editor.

**Comment by SumatraPeter** [comment]
I guess if Adobe does it that way the others must have simply followed suit, but regardless the point remains that it's not a universal thing and every program is free to do it differently. Remember that we aren't only talking about external PDF programs here, because Sumatra supports a lot of different document and image types and so users have access to any number of external viewers/editors that all behave in different ways.

If you want to provide program-specific examples then why not start a [wiki](https://github.com/sumatrapdfreader/sumatrapdf/wiki) article and do so? Then if the dev wants he can link to the wiki article from the documentation page.
