### ISSUE TITLE
Control Sumatra

### ISSUE THREAD

**Issue by Aphexus** [sumatrapdfreader/sumatrapdf#964]
I really need a good way to control Sumatra. I am having to hack it using WM messages and Send Message to specific windows. I am stuck using 2.5 because 3 changed the interface which changed the hierarchy. It would be very nice if you could add some consistent way to do basic Sumatra control like open files, set and get page changes, home, end, etc.

It should be VERY simple and provide an effective means.

Just respond to WM_USER + X + 1 = Open file(ptr to file name provided), WM_USER + X + 2 = Close file, WM_USER + X + 3 = Goto page y, etc...

This way all I have to do is send the appropriate WM message and argument and it will do as I need regardless of version. This way I am not stuck using versions I have hacked up.

This allows automation of sumatra for many things such as using a remote, midi, or whatever.

**Comment by GitHubRulesOK** [comment]
@Aphexus 
see my "[howto] use cli and dde" on forum it may give you simpler ways to call externally from other apps 
however I think there is no "close" function since it is expected the user will do that, so the "siimplest" command proposed was along the lines of killtask SumatraPDF, 
the other query about current version may be that   -reuse-instance   may vary from user to user setup, if so and THAT causes a problem then that should be reported as an issue

**Comment by kjk** [comment]
This can be done using DDE. I just made DDE understand all commands that sumatra understands (listed in `Commands.h`)
