### ISSUE TITLE
PDF files converted pdf->postscript->pdf using Ghostscript render with misaligned letters in SumatraPDF

### ISSUE THREAD

**Issue by Bunnicula2** [sumatrapdfreader/sumatrapdf#983]
I've come to sanitize every PDF file I receive with Ghostscript (v9.22) like this as it's faster and safer than scanning them for viruses:

    C:\path\to\ghostscript -dNOPAUSE -sDEVICE=ps2write -sOUTPUTFILE=temp.ps file.pdf
    C:\path\to\ghostscript -dNOPAUSE -sDEVICE=pdfwrite -sOUTPUTFILE=sanitized_file.pdf temp.ps
    del temp.ps

The problem is, the output file usually ends up with characters having a somewhat drunken look, being misaligned up and down somewhat, instead of neatly aligned in rows. At first I thought this was a Ghostscript problem, but today I opened one of these files with Acrobat Reader by accident, and it rendered perfectly.

Here's an example (can't vouch for the original file's safety)

[Lantian2017  - I Know Things They Don’t Know.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/1769637/Lantian2017.-.I.Know.Things.They.Don.t.Know.zip)

**Comment by SumatraPeter** [comment]
> At first I thought this was a Ghostscript problem, but today I opened one of these files with Acrobat Reader by accident, and it rendered perfectly.

Strange, especially since the same company's responsible for both muPDF and Ghostscript. Some things to try:

1. The latest Sumatra [pre-release build](http://www.sumatrapdfreader.org/prerelease.html).

2. The latest [muPDF viewer](http://artifex.com/developers-mupdf-download/mupdf-download-resources/) to see if the Ghostscripted PDF looks just as distorted in it. (I'm not sure which version of muPDF Sumatra uses.)

**Comment by GitHubRulesOK** [comment]
select for copy the text in original is conventional font
secect for copy in changed file is garbled (unicode) thus visible output will be different due to changed font metrics especially if height of decenders is affected

**Comment by Bunnicula2** [comment]
It renders exactly the same in Sumatra v3.2.10766 x64
![Sumatra prerelease screenshot](https://user-images.githubusercontent.com/36942931/36921699-354deb40-1e5d-11e8-92e7-5378c2036f28.PNG)

The rendering in MuPDF 1.12.0 is different but also distorted
![MuPDF screenshot](https://user-images.githubusercontent.com/36942931/36922012-56272a2e-1e5e-11e8-8dd2-4b9da5d28743.PNG)

**Comment by GitHubRulesOK** [comment]
I am closing as either bad PDF or a Ghostscript issue (I should have tested earlier that it is the GS > PS conversion at fault) since If we open the PS file it is "wobbly" and text locations are "Out of position"
![image](https://user-images.githubusercontent.com/12754913/126089289-7233fb83-181c-4bc3-a923-63d563b0e823.png)

Out of interest I used Mutool to run a cleaning cycle and whilst the kerning problem  often seen with justification is present the words were not displaced.

![image](https://user-images.githubusercontent.com/12754913/126090458-ecf0b827-cab3-426b-b4a1-b0222be15df2.png)
