### ISSUE TITLE
black-white scan is shown black

### ISSUE THREAD

**Issue by Friendly-User** [sumatrapdfreader/sumatrapdf#991]
I use a MFC device "brother DCP-8110DN" to archive documents. 
If the "source document" doesn't contain any pictures and is printed in black/white only, 
I use the following option: 
300 dpi
black-white
PDF/A

A public and test document you can find here: http://ge.tt/6yIAC1p2

Most of these PDF documents are shown within Sumatra as a black page. 
Sometimes the top (upper part) of the document is white until a black or written part is following. 

Tested "against" Sumatra 3.1.2/64 and PreRelease 10766-64.

Displaying the document in Adobe Reader (e. g. 11.0.23) or PDFXChange-Viewer (2.5) is ok. 
Firefox PDF viewer is showing the file properly, too.

**Comment by Friendly-User** [comment]
[Scan with Brother MFC in black-white mode with 300 dpi.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/1816726/Scan.with.Brother.MFC.in.black-white.mode.with.300.dpi.pdf)

**Comment by GitHubRulesOK** [comment]
Hi

I am afraid your format whilst certainly acceptable to many PDF readers is unlikely to be rendered by SumartraPDF in its current state since it cannot be rendered by either of the latest underlying MuPDF Engines.
Oddly GSview (also developed by Artiflex) CAN view the file

My initial suspicion is it may be a raster decoding problem (I have seen similar decoding black out before), however the resolution of this issue certainly lies with the MuPDF developers rather than SumatraPDF, you could try to open it as an issue at   https://bugs.ghostscript.com/

**Comment by Friendly-User** [comment]
opened Bug at MuPDF / GhostScript

https://bugs.ghostscript.com/show_bug.cgi?id=699123

**Comment by GitHubRulesOK** [comment]
@Friendly-User 
Thanks for your patience, I note MuPDf have not responded to your bug report however a different but fairly similar problem has since arisen and a work around has been found for https://github.com/sumatrapdfreader/sumatrapdf/issues/1005 referenced above which appears to also fix your files

![image](https://user-images.githubusercontent.com/12754913/40089168-368778ee-58a2-11e8-91c6-2215b6e6476c.png)

**Comment by GitHubRulesOK** [comment]
@kjk MuPDF bug report is still open and they state the file works in  GS but not MuPDF thus I suggest this issue be tagged as MuPDF bug  in case they ever bother to address the problem.
