### ISSUE TITLE
Windows Store App Not Launchable via Command Line

### ISSUE THREAD

**Issue by xcjs** [sumatrapdfreader/sumatrapdf#998]
It does look like there's a way to do this, possibly: https://blogs.windows.com/buildingapps/2017/07/05/command-line-activation-universal-windows-apps/

**Comment by SumatraPeter** [comment]
App has ben [reported to the dev](https://forum.sumatrapdfreader.org/t/will-there-be-a-uwp-version-of-this-software/422/3?u=sumatrapeter); let's see what he has to say about it.

**Comment by xcjs** [comment]
@SumatraPeter 

Oh wow, I wasn't aware it wasn't an official port.

**Comment by SumatraPeter** [comment]
Once I figured out what you were referring to I immediately searched MS' app store and it was clear there was nothing official about it (no mention of original dev - just an unknown name, no link to official site etc.) Have seen such scams/thefts a lot - for example don't even remember how many fake VLCs I have come across (esp. before the official app launched) including ones that were paid apps! Easy for unsuspecting users to get fooled though, so I hope this one is taken down ASAP.

BTW I'm curious, what made you prefer the (fake) Store version, especially since you want features of the desktop version such as command line support in it? Are you on Win10S?

**Comment by SumatraPeter** [comment]
I wasn't blaming you or anything. Anyway, thanks for those insights. Yes, a better update mechanism and clean uninstalls are definitely incentives to go with Store versions, but of course WinRT has a long way to go still to catch up with 'legacy' Win32.

As I said above, if someone else can port the program with minimal effort then I sure hope the dev himself will release an official version. Providing a choice of desktop and Store apps will only widen the reach of the program IMO.

BTW, do you suppose it might be better to close this issue for now?

**Comment by kjk** [comment]
Closing for now.
